### ISSUE TITLE
Leviticus 25:30

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#1006]
throughout his descendants' generations

Heb is 

throughout his generations

This seems to be straddling the fence. If the Heb can't be OED literal for some reason, it should just be

... bought it; it will always belong to his descendants

**Comment by TomWarren** [comment]
The ULB of LEV 25:30 now reads:
\v 30 If the house is not redeemed within a full year, then the house in the walled city will become the permanent property of the buyer and his descendants. It  is not to be returned in the year of Jubilee.

Thanks Henry, 

Tom
