### ISSUE TITLE
MRK 7:18-19 ?

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#101]
Mrk 7:18-19 
Jesus said, "Are you also still without understanding? Do you not see that whatever enters into a person from outside cannot defile him, 19because it cannot go into his heart, but it goes into his stomach and then passes out into the toilet."

I believe you need a question mark after "toilet."

**Comment by hharrissWA** [comment]
period replaced with question mark
Thanks Kim!
Harry
