### ISSUE TITLE
JAS 4:1 "yourselves" to "you"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#103]
James 4:1 ULB Where does the quarreling and disputing among yourselves come from?
Could "yourselves" be changed to "you"? It's not reflexive in Greek, and there's nothing in the English that would require a reflexive pronoun.

**Comment by TomWarren** [comment]
Yes, Susan,


Yourselves is not needed. You is simpler.



Change made this morning.


Tom

________________________________
