### ISSUE TITLE
MRK 11:3 ULB '? to ?'

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#104]
if anyone says to you, 'Why are you doing this'?, you should say, 

The question is in the quote, so the quote mark should be before the single quote. 
I don't know if the comma after the quote mark is needed. It's not used in the UDB.

**Comment by TomWarren** [comment]
Right. The question mark should be before the single quotation. The comma is not needed (and it junks up the text). 
Thanks. 

Here is the change: ULB Mark 11:3
\v 3 And if anyone says to you, 'Why are you doing this?' you should say, 'The Lord has need of it and will immediately send it back here.'"
