### ISSUE TITLE
Gal 6:7ULB

### ISSUE THREAD

**Issue by TomWarren** [Door43/ulb-en#105]
A more complex continuity issue.  Sowing or Planting.

Noticed planting and sowing are interchangable. Should we settle on one or the other for continuity?
 Here is the raw searches for sow and plant, I think we should have an algorithm for making decisions between synonyms. Find one and stick with it, unless there is need for change. 

Search "sow" (24 hits in 20 files)
  C:\Users\wthom\Documents\Github\ulb-en\02-EXO\23.usfm (1 hit)
	Line 24: \v 10 For six years you will sow seed on your land and gather in its produce.
  C:\Users\wthom\Documents\Github\ulb-en\18-JOB\04.usfm (1 hit)
	Line 31: \q and sow trouble reap the same.
  C:\Users\wthom\Documents\Github\ulb-en\18-JOB\31.usfm (1 hit)
	Line 36: \v 8 then let me sow and let another eat;
  C:\Users\wthom\Documents\Github\ulb-en\19-PSA\126.usfm (1 hit)
	Line 26: \v 5 Those who sow in tears will reap with shouts of joy.
  C:\Users\wthom\Documents\Github\ulb-en\23-ISA\28.usfm (2 hits)
	Line 106: \v 24 Does a farmer who plows all day to sow, only plow the ground? Does he continually break up and harrow the field?
	Line 110: \v 25 When he has prepared the ground, does he not scatter caraway seed, sow the cumin, 
  C:\Users\wthom\Documents\Github\ulb-en\23-ISA\30.usfm (1 hit)
	Line 108: \v 23 He will give the rain for your seed when you  sow the ground, 
  C:\Users\wthom\Documents\Github\ulb-en\23-ISA\32.usfm (1 hit)
	Line 70: \v 20 you who sow beside all the streams will be blessed, you who who send out your ox and donkey to graze.
  C:\Users\wthom\Documents\Github\ulb-en\24-JER\04.usfm (1 hit)
	Line 13: \q and do not sow among thorns.
  C:\Users\wthom\Documents\Github\ulb-en\24-JER\31.usfm (1 hit)
	Line 99: \v 27 "Look, the days are coming—this is Yahweh's declaration—when I will sow the houses of Israel and Judah with the descendants of man and beast.
  C:\Users\wthom\Documents\Github\ulb-en\24-JER\35.usfm (1 hit)
	Line 17: \v 7 Also, do not build any houses, sow any seeds, or plant any vineyards; this is not for you. For you must live in tents all your days, so that you might live many days in the land where you are staying as foreigners.'
  C:\Users\wthom\Documents\Github\ulb-en\28-HOS\08.usfm (1 hit)
	Line 39: \v 7 For the people sow the wind
  C:\Users\wthom\Documents\Github\ulb-en\33-MIC\06.usfm (1 hit)
	Line 81: \v 15 You will sow but not reap;
  C:\Users\wthom\Documents\Github\ulb-en\41-MAT\06.usfm (1 hit)
	Line 64: \v 26 Look at the birds in the air. They do not sow or reap or gather into barns, but your heavenly Father feeds them. Are you not more valuable than they are?
  C:\Users\wthom\Documents\Github\ulb-en\41-MAT\13.usfm (2 hits)
	Line 8: \v 3 Then Jesus said many things to them in parables. He said, "Behold, a sower went out to sow.
	Line 65: \v 27 The servants of the landowner came and said to him, 'Sir, did you not sow good seed in your field? How does it now have weeds?'
  C:\Users\wthom\Documents\Github\ulb-en\41-MAT\25.usfm (1 hit)
	Line 46: \v 24 Then the servant who had received one talent came and said, 'Master, I know that you are a strict man. You reap where you did not sow, and you harvest where you did not scatter.
  C:\Users\wthom\Documents\Github\ulb-en\42-MRK\04.usfm (1 hit)
	Line 8: \v 3 "Listen, the sower went out to sow.
  C:\Users\wthom\Documents\Github\ulb-en\43-LUK\08.usfm (1 hit)
	Line 11: \v 5 "A sower went out to sow some seeds. As he sowed, some of the seeds fell beside the road and they were trampled underfoot, and the birds of the sky devoured them.
  C:\Users\wthom\Documents\Github\ulb-en\43-LUK\12.usfm (1 hit)
	Line 51: \v 24 Consider the ravens, that they do not sow or reap. They have no storeroom or barn, but God feeds them. How much more valuable you are than the birds!
  C:\Users\wthom\Documents\Github\ulb-en\43-LUK\19.usfm (2 hits)
	Line 46: \v 21 for I was afraid of you, because you are a severe man. You take up that which you did not lay down, and reap that which you did not sow.'
	Line 49: \v 22 The nobleman said to him, 'By your own words I will judge you, you wicked servant. You knew that I am a severe man, taking up that which I did not lay down, and reaping that which I did not sow.
  C:\Users\wthom\Documents\Github\ulb-en\47-1CO\15.usfm (2 hits)
	Line 75: \v 36 You are so ignorant! What you sow will not start to grow unless it dies.
	Line 78: \v 37 And what you sow is not the body that will be, but a bare seed. It may become wheat or something else.
Search "sows" (11 hits in 7 files)
  C:\Users\wthom\Documents\Github\ulb-en\20-PRO\06.usfm (1 hit)
	Line 79: \q and one who sows discord among brothers.
  C:\Users\wthom\Documents\Github\ulb-en\20-PRO\11.usfm (2 hits)
	Line 73: \q but one who sows what is right reaps the wages of truth.
	Line 96: \v 24 There is one who sows seed—he will accumulate even more;
  C:\Users\wthom\Documents\Github\ulb-en\20-PRO\22.usfm (1 hit)
	Line 33: \v 8 He who sows wickedness will reap trouble,
  C:\Users\wthom\Documents\Github\ulb-en\41-MAT\13.usfm (1 hit)
	Line 90: \v 37 Jesus answered and said, "He who sows the good seed is the Son of Man.
  C:\Users\wthom\Documents\Github\ulb-en\42-MRK\04.usfm (2 hits)
	Line 31: \v 14 The sower sows the word.
	Line 55: \v 26 And he said, "The kingdom of God is like a man who sows his seed on the ground.
  C:\Users\wthom\Documents\Github\ulb-en\44-JHN\04.usfm (2 hits)
	Line 70: \v 36 He who is harvesting receives wages and gathers fruit for everlasting life, so that he who sows and he who harvests may rejoice together.
	Line 73: \v 37 For in this is the saying true, 'One sows, and another harvests.'
  C:\Users\wthom\Documents\Github\ulb-en\48-2CO\09.usfm (2 hits)
	Line 16: \v 6 The point is this: the one who sows sparingly will also reap sparingly, and the one who sows for the purpose of a blessing will also reap a blessing.
	Line 16: \v 6 The point is this: the one who sows sparingly will also reap sparingly, and the one who sows for the purpose of a blessing will also reap a blessing.

**Search "plants" (46 hits in 33 files) and that would include the noun variety**
  C:\Users\wthom\Documents\Github\ulb-en\01-GEN\01.usfm (2 hits)
	Line 27: \v 11 God said, "Let the earth sprout vegetation: plants yielding seed and fruit trees bearing fruit whose seed is in the fruit, each according to its own kind." It was so.
	Line 28: \v 12 The earth produced vegetation, plants producing seed after their kind, and trees bearing fruit whose seed was in it, after their kind. God saw that it was good.
  C:\Users\wthom\Documents\Github\ulb-en\01-GEN\03.usfm (1 hit)
	Line 59: \q and you will eat the plants of the field.
  C:\Users\wthom\Documents\Github\ulb-en\01-GEN\09.usfm (1 hit)
	Line 10: \v 3 Every moving thing that lives will be food for you. Just as I gave you the green plants, I now give you everything.
  C:\Users\wthom\Documents\Github\ulb-en\01-GEN\19.usfm (1 hit)
	Line 52: \v 25 He destroyed those cities, and all the plain, and all the inhabitants of the cities, and the plants that grew on the ground.
  C:\Users\wthom\Documents\Github\ulb-en\02-EXO\09.usfm (1 hit)
	Line 45: \v 22 Then Yahweh said to Moses, "Reach out with your hand toward the sky so that there will be hail in all the land of Egypt, on people, on animals, and on all the plants in the fields throughout the land of Egypt."
  C:\Users\wthom\Documents\Github\ulb-en\05-DEU\32.usfm (1 hit)
	Line 12: \q and like the showers on the plants.
  C:\Users\wthom\Documents\Github\ulb-en\11-1KI\04.usfm (1 hit)
	Line 65: \v 33 He described the plants, from the cedar that is in Lebanon to the hyssop that grows out of the wall. He explained also about beasts, birds, creeping things, and fish.
  C:\Users\wthom\Documents\Github\ulb-en\12-2KI\19.usfm (1 hit)
	Line 87: \q They are plants in the field, 
  C:\Users\wthom\Documents\Github\ulb-en\18-JOB\08.usfm (1 hit)
	Line 78: \q other plants will sprout out of the same soil in his place.
  C:\Users\wthom\Documents\Github\ulb-en\18-JOB\40.usfm (2 hits)
	Line 82: \v 21 He lies under the lotus plants
	Line 87: \v 22 The lotus plants cover him with their shade;
  C:\Users\wthom\Documents\Github\ulb-en\19-PSA\037.usfm (1 hit)
	Line 10: \q and wither as the green plants.
  C:\Users\wthom\Documents\Github\ulb-en\19-PSA\104.usfm (1 hit)
	Line 59: \q and plants for man to cultivate
  C:\Users\wthom\Documents\Github\ulb-en\19-PSA\128.usfm (1 hit)
	Line 18: \q your children will be like olive plants
  C:\Users\wthom\Documents\Github\ulb-en\19-PSA\144.usfm (1 hit)
	Line 57: \v 12 May our sons be like plants who grow to full size in their youth
  C:\Users\wthom\Documents\Github\ulb-en\20-PRO\31.usfm (1 hit)
	Line 64: \q with the fruit of her hands she plants a vineyard.
  C:\Users\wthom\Documents\Github\ulb-en\21-ECC\03.usfm (1 hit)
	Line 9: \q1 a time to plant and a time to pull up plants,
  C:\Users\wthom\Documents\Github\ulb-en\22-SNG\01.usfm (1 hit)
	Line 90: \q The lush plants serve as our bed.
  C:\Users\wthom\Documents\Github\ulb-en\22-SNG\04.usfm (1 hit)
	Line 79: \q and of henna and nard plants,
  C:\Users\wthom\Documents\Github\ulb-en\23-ISA\17.usfm (1 hit)
	Line 44: \q1 So you plant pleasant plants, and set out strange slips
  C:\Users\wthom\Documents\Github\ulb-en\23-ISA\37.usfm (1 hit)
	Line 71: \q1 They are plants in the field, green grass,
  C:\Users\wthom\Documents\Github\ulb-en\23-ISA\44.usfm (1 hit)
	Line 69: \q1 He picks for himself trees in the forest. He plants a fir tree and the rain makes it grow.
  C:\Users\wthom\Documents\Github\ulb-en\23-ISA\61.usfm (1 hit)
	Line 53: \v 11 For as the earth produces its sprouting plants, and as the garden makes its planting grow,
  C:\Users\wthom\Documents\Github\ulb-en\24-JER\12.usfm (1 hit)
	Line 17: \v 4 How long will the land go on mourning, and the plants in every field wither because of the wickedness of its inhabitants?
  C:\Users\wthom\Documents\Github\ulb-en\27-DAN\04.usfm (1 hit)
	Line 35: \v 15 Leave the stump of its roots in the earth, bound with a band of iron and bronze, in the middle of the tender grass of the field. Let it be wet with the dew from the heavens. Let it live with the animals among the plants on the ground.
  C:\Users\wthom\Documents\Github\ulb-en\30-AMO\09.usfm (1 hit)
	Line 84: \q and the treader of grapes will overtake him who plants seed.
  C:\Users\wthom\Documents\Github\ulb-en\38-ZEC\10.usfm (1 hit)
	Line 10: \q and plants in the fields for mankind.
  C:\Users\wthom\Documents\Github\ulb-en\41-MAT\13.usfm (4 hits)
	Line 14: \v 7 Other seeds fell among the thorn plants. The thorn plants grew up and choked them.
	Line 14: \v 7 Other seeds fell among the thorn plants. The thorn plants grew up and choked them.
	Line 55: \v 22 He who was sown among the thorn plants, this is he who hears the word, but the cares of the world and the deceitfulness of riches choke the word, and he becomes unfruitful.
	Line 75: \v 32 This seed is indeed the smallest of all other seeds. But when it has grown, it is greater than the garden plants. It becomes a tree, so that the birds of the air come and nest in its branches."
  C:\Users\wthom\Documents\Github\ulb-en\42-MRK\04.usfm (3 hits)
	Line 14: \v 7 Other seeds fell among the thorn plants. The thorn plants grew up and choked them, and they did not produce any grain.
	Line 14: \v 7 Other seeds fell among the thorn plants. The thorn plants grew up and choked them, and they did not produce any grain.
	Line 64: \v 32 Yet, when it is sown, it grows and becomes greater than all the garden plants, and it forms large branches, so that the birds of heaven can make their nests in its shade."
  C:\Users\wthom\Documents\Github\ulb-en\43-LUK\08.usfm (4 hits)
	Line 12: \v 6 Other seeds fell on rocky soil and as soon as they grew into plants, they withered away, because they had no moisture.
	Line 15: \v 7 Still other seeds fell among thorn plants, and the thorn plants grew up together with the seeds and choked them.
	Line 15: \v 7 Still other seeds fell among thorn plants, and the thorn plants grew up together with the seeds and choked them.
	Line 29: \v 14  The seeds that fell among the thorn plants are people who have heard the word, but as they go on their way, they become choked with the cares and riches and pleasures of this life, and so they bring no fruit to maturity.
  C:\Users\wthom\Documents\Github\ulb-en\47-1CO\03.usfm (2 hits)
	Line 14: \v 7 So then, neither he who plants nor he who waters is anything. But it is God who gives the growth.
	Line 16: \v 8 Now he who plants and he who waters are one, and each will receive his own wages according to his own labor.
  C:\Users\wthom\Documents\Github\ulb-en\47-1CO\09.usfm (1 hit)
	Line 16: \v 7 Who serves as a soldier at his own expense? Who plants a vineyard and does not eat its fruit? Or who tends a flock and does not drink milk from it?
  C:\Users\wthom\Documents\Github\ulb-en\49-GAL\06.usfm (3 hits)
	Line 15: \v 7 Do not be deceived. God is not mocked. Whatever a man plants, that is what he will also harvest.
	Line 16: \v 8 For he who plants seed to his own sinful nature will harvest destruction, but he who plants seed to the Spirit, will harvest eternal life from the Spirit.
	Line 16: \v 8 For he who plants seed to his own sinful nature will harvest destruction, but he who plants seed to the Spirit, will harvest eternal life from the Spirit.
  C:\Users\wthom\Documents\Github\ulb-en\59-HEB\06.usfm (1 hit)
	Line 16: \v 7 For the land that drinks in the rain that often comes on it, and that gives birth to the plants useful to those for whom the land was worked—this is the land that receives a blessing from God.

**Comment by hharrissWA** [comment]
Personally, I prefer "plant," because "sow" seems archaic in modern English. "Sow" might be unfamiliar to MTT's who know a little English, or even perhaps a lot of English (?). Of course, maybe MTT's need to learn that "sow" is simply an older English word that means to "plant"? That way they might know what "the parable of the sower" is referencing?  :)  
However, perhaps a greater concern is the average reader across the world who knows a little English and is reading our translations, and who is familiar with "plant" but not with "sow"?  Growing up, I remember not understanding for years that "sow" simply meant "plant."  And yes, I grew up speaking "English."

**Comment by SusanQuigley** [comment]
Sowing is one way of planting—planting by scattering the seed on the ground. People can also plant  by digging a hole and putting the seed or plant in the hole.

**Comment by hharrissWA** [comment]
"Sowing" as "scattering seed" is certainly different from "planting" by "digging a hole and putting the seed in." I wonder how many English speakers/readers across the world will understand that? If they understand that difference, "sow" certainly adds clarity, but if not, it may confuse. If we use "sow," we need to define the word in the Notes and show the difference from "planting." Maybe we have already done that in the Notes or other materials?

**Comment by pjoakes** [comment]
I agree with Susan - the words are not synonymous, and it is important in some cases - such as the parable of the sower - that the reader know that the seed was sown, not planted.

Perry Oakes, Ph.D.
Chief Language Officer
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>

[cid:image002.png@01D116FB.66313BC0]

On Jun 22, 2016, at 9:35 AM, hharrissWA <notifications@github.com<mailto:notifications@github.com>> wrote:


"Sowing" as "scattering seed" is certainly different from "planting" by "digging a hole and putting the seed in." I wonder how many English speakers/readers across the world will understand that? If they understand that difference, "sow" certainly adds clarity, but if not, it may confuse. If we use "sow," we need to define the word in the Notes and show the difference from "planting." Maybe we have already done that in the Notes or other materials?

**Comment by hharrissWA** [comment]
Yes, I agree, that "sowing" the seed that was eaten by the birds because it is on the top of the ground is important to that parable. Since "sow" and "plant" are not synonymous, it seems we need to continue with  both words and perhaps distinguish between their meanings in our materials (if we haven't already done so).

**Comment by SusanQuigley** [comment]
There is a note for ”sow” on  Matthew 13:3-5 Parable of the Sower

There is also a translationWords page for ”sow", but it has a different definition and different distinction between ”plant” and ”sow” than I have.  https://door43.org/en/obe/other/sow


On Jun 22, 2016, at 10:45 AM, hharrissWA <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, I agree, that "sowing" the seed that was eaten by the birds because it is on the top of the ground is important to that parable. Since "sow" and "plant" are not synonymous, it seems we need to continue with both words and perhaps distinguish between their meanings in our materials (if we haven't already done so).

**Comment by hharrissWA** [comment]
I would just suggest adding the distinction you described, Susan, and adding any material that is pertinent?

**Comment by pohlig** [comment]
As long as the passages such as the parable of the sower and the passage that says, "do not sow seed among thorns," retain the verb "sow" (where it really matters, and assuming adequate explanation for MTTs), I do not think that a mix of "plant" and "sow" in the other passages is all that serious a thing, if it is a problem at all. At this stage in phase two, it is very late to reach for formal equivalence when it is not absolutely necessary.

**Comment by hharrissWA** [comment]
I agree with Jim, that as long as we distinguish in our Notes and definitions the difference between "sowing" (scattering seed) and "planting" (placing seed in the ground)--if those are adequate descriptions of the difference in meaning in their given contexts--then retaining both words should not be a problem.
