### ISSUE TITLE
REV 1:12 "gold" vs "golden"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#107]
Rev 1:12  seven golden lamp stands
Rev 1:13 a golden belt

Is there a difference in meaning between "gold" and "golden" in the ULB and UDB?
Sometimes I see "a golden __" and sometimes I see "a gold __."

Someone on team wrote: It's unclear if the lampstands and belt are made out of gold or are gold colored.

**Comment by TomWarren** [comment]
There are 49 "golden" in the ULB (probably from the ASV) and NO use of "gold". 
Another interesting fact.

**Comment by TomWarren** [comment]
29 uses of golden in the UDB.

**Comment by TomWarren** [comment]
Does "golden" mean something made from gold, rather than the gold itself? The absence of "gold" in either version may not mean that things appear to be gold, but I believe it means they were objects made from gold.

**Comment by SusanQuigley** [comment]
The ULB has both gold and golden used as adjectives.

James 2:2: gold rings
Rev 4:4 gold crowns
Rev 5:8 a gold bowl
Rev 8:3 the gold altar
Rev 8:3 a gold incense bowl
Rev 14:14 A gold crown
Rev 15:16 with gold sashes
Rev 15:7 seven gold bowls

Old Testament
”a gold” - 7 times
”one gold” - 12 times
”two gold” - 3 times
(”Gold” occurs 447 times. I didn’t check to see which were nouns and which were adjectives.)

Golden - NT - 8 times, OT 41 times

On Jun 23, 2016, at 5:22 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


There are 49 "golden" in the ULB (probably from the ASV) and NO use of "gold".
Another interesting fact.

**Comment by SusanQuigley** [comment]
I guess the only questionable ones are the sashes, since they are fabric. Was it just gold colored fabric or had they made a fine threads of gold? I thought in the description of the tabernacle or temple there was some kind of gold thread embroidered or woven into something, but I can't find it.

**Comment by TomWarren** [comment]
Residual memory from other translations (when you know it is there, but can't find it). Here are some that sound close.

You were adorned with silver and gold Ezekiel 16:13

The woman was dressed in purple and scarlet and was adorned with gold, precious stones, and pearls. Rev 7:4a

Rev 18:16b
\q3 in purple, and in scarlet, 
\q2 and was adorned with gold, 
\q3 precious jewels, and pearls!"

**Comment by TomWarren** [comment]
I think the fabric had gold thread woven through it. Very precious.

**Comment by SusanQuigley** [comment]
Great. Thank you.

On Jun 24, 2016, at 7:47 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the fabric had gold thread woven through it. Very precious.
