### ISSUE TITLE
REV 2:3 you have gone through much

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#109]
REV 2:3 ULB "you have gone through much"
This is an English figure of speech. Greek has ἐβάστασας which uses the metaphor "carry" or "bear."
Could the ULB be changed to   "you have borne much" or "you have suffered much"?

**Comment by TomWarren** [comment]
Endured seems to fit.
Made the change. 

Thanks,

**Comment by SusanQuigley** [comment]
The clause before that is "I know you have patient endurance."
If "you have gone through much” is changed to ”you have endured much,”
the result will be "I know you have patient endurance, and you have endured much."
That sounds redundant to me.

**Comment by TomWarren** [comment]
Quite right, Susan.

Should be "suffered". That change is made.
Always speed is the enemy of correctness.

Thanks

**Comment by SusanQuigley** [comment]
Thanks for fixing it. :)
