### ISSUE TITLE
REV 2:1 These are the words of 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#110]
REV 2:1 ULB '_These are the words_ of the one who holds the seven stars in his right hand and who walks among the seven golden lampstands _says this_,

Please delete "says this."  
The rest of the letters have "These are the words of", except for 3:1 and 14 which simply have "The words of")

Some of the letters have a colon and some have a period before the quote that follows.

**Comment by TomWarren** [comment]
Got it. Thanks
2:1 removed "says this"
3:1 and 14 have the same Greek expression as the others, and they now read: "These are the words of..."
Good continuity check. Thank you.
