### ISSUE TITLE
Rev 3:7-8, 14

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#112]
To be like the others in Chapter 2 and 3:1, the quote marks should be like this:
 "To the angel    
    'The words of the  one
      "I know

**Comment by TomWarren** [comment]
The multi-level quotations are difficult. These seem to line up correctly. 
Chapters 2 and 3 were reviewed and rendered in a consistent manner.

**Comment by SusanQuigley** [comment]
Thank you.
