### ISSUE TITLE
REV 2:7 To the one...I will permit

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#113]
To the one who conquers I will permit to eat from the tree of life, 
The word "To" at the beginning is not need.
(I will permit the one who conquers...)
OR
To the one who conquers I will give permission to eat from the tree of life,

**Comment by TomWarren** [comment]
The Greek is:
to the one who conquers  I give  to him   to eat   from the tree        of life
τῷ νικῶντι                         δώσω αὐτῷ     φαγεῖν ἐκ     τοῦ ξύλου τῆς ζωῆς

Stylistically, not the smoothest; but to follow the Greek: 

\v 7 If you have an ear, listen to what the Spirit says to the churches. **To the one who conquers—I will allow him to eat from the tree of life, which is in the paradise of God."'"**

**Comment by SusanQuigley** [comment]
Thank you, Tom.
