### ISSUE TITLE
Rev 2:7 ULB - the first and the last

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#114]
the first and the last
Should First and Last be capitalized as they are in 1:17?

**Comment by TomWarren** [comment]
That would be consistent, as nomenclature. 
Will scan to see if it may occur in non-theistic context. Nope, just as name for Christ.
Rev 2:8 is the only other occurrence where it was not in Caps. 
There are 4x the First and the Last in the ULB.
There are 7x in the UDB.
