### ISSUE TITLE
Rev 2:16 without delay

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#115]
ULB I will come to you **without delay**,
UDB I **will not wait** but will come to you **suddenly**

Greek just looks like "I will come to you **quickly/soon/suddenly**.
Maybe we could use an adverb rather than a prepositional phrase with an abstract noun ("without delay")
UDB seems to translate "tachy" twice

**Comment by TomWarren** [comment]
Seems that quickly should serve. It is an adverb from the Greek text. The rest seem to be more commentary on ταχὺ.Noting that the verb is present, not future."Make war" is future. Might want to preserve that distinction.

\v 16 Repent, therefore! If you do not, I come to you quickly, and I will make war against them with the sword that comes out of my mouth.

Comment for me to change it back, and I will do it

**Comment by SusanQuigley** [comment]
**ULB** - Repent, therefore! If you do not, I am coming to you quickly, and I will make war against them with the sword of my mouth.

Thanks for changing "without delay" to "quickly."

As for the "I am coming" after the command and the if clause ("Repent ... If you do not"), the present tense sounds odd in English because we would assume that he won't start coming until after he sees their response. But if you feel it's best to reflect the Greek structure, I won't argue.

**UDB** - Stop doing this and change your direction, or I will not wait but will come to you suddenly

Would you want to tachy to be translated just once?
"Stop doing this and change your direction, or I will come to you suddenly"

**Comment by TomWarren** [comment]
Here is the UDB rendering:
**\v 16 Stop doing this and change your direction, or I will come to you suddenly and I will make war against them with the word of God that comes out of my mouth.**

There you go. That's much better.

**Comment by SusanQuigley** [comment]
Thank you, Tom.
