### ISSUE TITLE
MRK 9:9-10

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#116]
As they were coming down the mountain, he commanded them to tell no one what they had seen, until the Son of Man had risen from the dead ones. 10So they kept the matter to themselves, but they discussed among themselves what "to rise from the dead ones" could mean.

In the Greek, there is not the phrase "the dead one" only the adj nekros. This is a very common figure of speech. Just wanted to point it out and see if there has been discussion on this.

**Comment by SusanQuigley** [comment]
"From the dead ones" made it clear to me that this does not mean "from death." I had always assumed that "from the dead" and "from death" meant exactly the same thing. "From the dead ones" shows me that "the dead" is like "the rich," the poor", "the weak," "the small", referring to categories of people who can be described by those adjectives.

ULB: from the dead ones.
UDB: from the dead

Interesting, the UDB is more literal that the ULB. Maybe they could be switched.

**Comment by TomWarren** [comment]
The rendering "from the dead ones" which is used in the ULB, comes from nekrwn, the term for "dead" with the plural ending, so literally it is "deads" or "dead persons" and we have chosen "dead ones". There has been some discussion about this, it seems to be that Christ was raised from the place (abode) of the those who had died, hence, from the dead ones. 
There is on-going discussion about this, but it follows the Greek, and almost always has some note attached. 
Thanks,

**Comment by TomWarren** [comment]
The term nekrwn is the plural adjective in the Greek text referring to those who are dead: ἐκ νεκρῶν ἀναστῇ. 
There has been discussion about the nominalization of the term.
