### ISSUE TITLE
REV 2:23 ULB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#117]
ULB I am he who searches thoughts and desires.

Instead of "desires," would you want the more literal "hearts" and I'll write a translation note for the metaphor?

**Comment by TomWarren** [comment]
Yes, I changed the ULB from desires to "hearts"

**\v 23 I will strike her children dead, and all the churches will know that I am he who searches thoughts and hearts. I will give to each one of you according to what you have done.**

Thank you.
