### ISSUE TITLE
MRK 9:18 convulsions

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#119]
and it causes him to have convulsions and throws him down; he foams at the mouth, grinds his teeth, and becomes rigid. I asked your disciples to drive it out of him, but they could not."''

The phrase "and it causes him to have convulsions" is literally "it seizes him." The idea is that it "takes over him." The UDB has "attacks him."

**Comment by TomWarren** [comment]
Attacks was changed to "took control of him."

Kim, it is ok to offer suggestions to fix a text problem. We need lots of help! 
Thanks so much.

**Comment by pjoakes** [comment]
Tom,

I think the idea was that the ULB "and it causes him to have convulsions” needed changing, not the UDB "attacks him.” That was OK.

Perry Oakes, Ph.D.
Chief Language Officer
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>

[cid:image002.png@01D116FB.66313BC0]

On Jun 28, 2016, at 11:03 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


Attacks was changed to "took control of him."

Kim, it is ok to offer suggestions to fix a text problem. We need lots of help!
Thanks so much.

**Comment by TomWarren** [comment]
The ULB now reads: 

\s5
\v 17 Someone in the crowd answered him, "Teacher, I brought my son to you. He has a spirit that makes him unable to speak,
\v 18 and it seizes him, it throws him down and he foams at the mouth, grinds his teeth, and becomes rigid. I asked your disciples to drive it out of him, but they could not."

The UDB seems to be ok. Going back to "convulsions" seems more a modern diagnostic that reflecting what the demon was doing to this boy.
