### ISSUE TITLE
REV 3:14  ULB vs UDB arche tes ktisesos

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#121]
The ULB and UDB translate _arche_ with different meanings. Could they be made the same, or could the ULB have a more general meaning that could include the meaning of the UDB?

ULB -  the ruler over the creation of God
UDB -  the one by whom God created all things

Maybe something like "the first of God's creation" in the ULB, and something more specific in the UDB. Then the note could give two possible (specific) meanings, with the one in the UDB being the first one because it is preferred.

**Comment by TomWarren** [comment]
The term ἀρχὴ has a semantic range from "the beginning" to "the ruler." The UDB / ULB split the difference. The UDB, however should be, "the one who made the universe in the beginning." This preserves the Gk ἀρχὴ (beginning) and seems clear.
There are many alternatives, but this is much like many modern versions. In this case the UDB would be an alternative version, displaying the range of options, but true to the range of the term. Care should be used not to either make Christ part of creation, nor of saying Christ made God - who is part of "everything" but outside of the universe, is difficult to distinguish.

**"Write this message to the angel of the group of believers assembled in the city of Laodicea: 'I am saying these things to you. I am the one who guarantees all of God's promises. I am the one who testifies about God reliably and accurately. I am the one who made the universe in the beginning.**

**Comment by TomWarren** [comment]
Jim and I talked and we are going to join the ULB and UDB to contain the same.  This previous rendering could be a good Translation Note. 

I will change the UDB to coincide with the ULB.

**Comment by SusanQuigley** [comment]
Thank you for doing that. I changed the note to fit.
