### ISSUE TITLE
Rev 5:11 200,000,000

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#126]
Greek - the number of them was myriads and myriads and thousands of thousands
ULB - the number of them was 200,000,000
UDB - There were millions of them

The ULB seems quite specific. Could it be more general?

**Comment by TomWarren** [comment]
Another:

\v 11 Then I looked and heard the sound of many angels around the throne and the living creatures and the elders; and the total of them was thousands of thousands.

**Comment by SusanQuigley** [comment]
Beautiful. Thank you.
Susan

On Jul 1, 2016, at 9:48 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


Another:

\v 11 Then I looked and heard the sound of many angels around the throne and the living creatures and the elders; and the total of them was thousands of thousands.

**Comment by TomWarren** [comment]
I included the myriads (ten thousands), some just say millions, it blows the mind even more to try and calculate. I suspect the ULB was taking the two "thousands" and the two "ten thousands" and trying with some logic to get a number. But that really isn't the point. A myriad, can be a number too large to count.

**Comment by SusanQuigley** [comment]
"It blows the mind" - I think that's the point. :)
