### ISSUE TITLE
MRK 10:7&8 Archaic 'shall'

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#128]
7For this reason a man shall leave his father and mother and cleave to his wife,
8and the two shall become one flesh.'

**Comment by TomWarren** [comment]
There is a distinction between will and shall. Shall being a directive that is followed or required. In the law, as in a decree a judge would write,  "you shall make amends" means that is something you must do, or be subject to a penalty. So "shall may not merely be arcane, but it makes a distinction between "may" and "must." It may be a distinction that is being lost in modern English. Here in Mark 10, "will" would serve just as well. But there may be commands that require "shall." "You shall not take the name of Yahweh your God in vain" for example. The UDB had "you must leave" which is the same idea.
