### ISSUE TITLE
Gen 35:22-23

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#13]
The ULB chunk splits the verse. The UDB in Door43 is not able to do that, so it leaves the entire v 22 in the previous chunk: https://door43.org/en/bible/notes/gen/35/21. I don't know if TS will be able to handle this, but I think we decided not to push it. 

I suggest that we consider moving the v 23 marker to its logical location before "Now Jacob had twelve sons." If we don't want to do that, we should probably put this sentence back into the previous chunk.

**Comment by TomWarren** [comment]
Seems like a good solution. Am I able to apply changes to verse numbers? If so, I will do it on Monday.

**Comment by lrsallee** [comment]
Tom,

If you don’t change which verse numbers are in a chunk, but only the amount of text include in the verses, it should automatically update in the notes.

Larry

**Comment by TomWarren** [comment]
This seems to work. This matches exactly the formatting of the ULB. 

\v 21 Jacob, whose new name was Israel, continued traveling with his family, and he set up his tents on the south side of the watchtower at Eder.
\v 22 While they were living in that area, Jacob's son Reuben slept with Bilhah, one of his father's concubines. Someone told Jacob about it, and it made him very angry.

\s5
\p Jacob had twelve sons.
\v 23 The sons of Leah were Reuben, who was Jacob's oldest son, Simeon, Levi, Judah, Issachar, and Zebulon.
\v 24 The sons of Rachel were Joseph and Benjamin.
\v 25 The sons of Rachel's female slave Bilhah were Dan and Naphtali.
\v 22 While Israel was living in that land, Reuben slept with Bilhah his father’s concubine, and Israel heard of it.

**Comment by lrsallee** [comment]
Tom,

The issue here is that I am not sure TS will be able to correctly handle a section break that does not happen at a verse division. That’s why I suggested the option of moving the verse marker to include “Jacob had twelve sons” in both versions. I will Slack Jesse about this to see if it is really a problem.

Larry

**Comment by TomWarren** [comment]
Dear Larry,

Seems to me that there would be just a few cases where a thread of a 
verse would be in the wrong chunk. As long as there is a note. This 
would be a case in which the TN would probably focus more on the 
location of the verse than on the meaning of it.
Hope an easy solution is found.

Thanks,

Tom

**Comment by lrsallee** [comment]
Tom,

The problem is that TN works off the verse range of the ULB. So in this example, everything related to the fragment in v 22 would not appear in any resource except the ULB. Everything else would be missing. As a general principle, we do not split a chunk inside a verse. I want to verify that with Jesse, but I’m pretty sure they asked us never to split a verse like this.

In this instance, I am asking would it really be a problem for us to move the last piece of 22 info 23, where it should be? That would solve the possible issues with TS.

We would also need to make adjustments in the other locations with this problem—either move the verse marker, or the chunk marker.

Larry

**Comment by TomWarren** [comment]
A puzzle. If you make it what it should be, the MTT might get confused. 
Maybe a footnote !

Tom

**Comment by lrsallee** [comment]
Tom,

I would think the MTT would be much more confused by having notes for the last line in chunk 22, but not seeing the text until chunk 23. And then trying to translation the first line in 23, but only having verse markers for 23 in the translation pane.

Larry

**Comment by TomWarren** [comment]
It is a perplexing matter. One solution is just as obtuse as the 
original. Praying for insight and a solution!

Tom
