### ISSUE TITLE
Verses that span chunks

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#130]
We still have a longstanding "itch" with these three chunks that begin with text from the last verse of the previous chunk. I suspect these are going to cause problems with TS display down the road. 

Please see if we can correct these issues. If not, we probably need to have a conversation with the IT and TS people to make sure these will work.

Gen 35:22-23
2Sa 19:8-9
Neh 7:7-8

**Comment by TomWarren** [comment]
The Genesis 35 (ULB) seems to work. If the fragment is to make sense, it needs to carry a verb over the chunk division. Is there some other way to do this?

\v 21 Israel traveled on and pitched his tent beyond Migdal Eder.
\v 22 While Israel was living in that land, Reuben slept with Bilhah his father's concubine, and Israel heard of it.
\p Now Jacob had twelve sons.
CHUNK DIVISION
\s5
\v 23 His sons by Leah were Reuben, Jacob's firstborn, and Simeon, Levi, Judah, Issachar, and Zebulun.
\v 24 His sons by Rachel were Joseph and Benjamin.
\v 25 His sons by Bilhah, Rachel's female servant, were Dan and Naphtali.

2 Sam 19:8 ... has
\v 8 So the king got up and sat in the city gate, and it was told to all the men, "Look, the king is sitting in the gate." Then all the people came before the king.
CHUNK DIVISION
\s5
\p Meanwhile, in Israel every man had fled to his home.

Neh 7:7 ... has 
\v 7 They came with Zerubbabel, Jeshua, Nehemiah, Azariah, Raamiah, Nahamani, Mordecai, Bilshan, Mispereth, Bigvai, Nehum, and Baanah.
CHUNK DIVISION
\s5
\p The number of the men of the people of Israel included the following.

Will apply whatever is needed.

**Comment by lrsallee** [comment]
It looks like someone already fixed Gen 35. That is OK now.

2Sa 19 and Neh 7 are still problems because the chunk starts with a stray piece of the last verse in the previous chunk. 

It seems to me that it would be best to move those chunks into later chunk were they belong. We could add footnotes saying that they are usually in the previous verse, if necessary. I think that would be more helpful to the MTT than letting them dangle on the previous chunk. 

But if we decide not to move the verse division, I think we will need to return these fragments to the previous chunks.

**Comment by TomWarren** [comment]
How about a bridge? and be done with it?

**Comment by lrsallee** [comment]
My understanding is that we can't change chunk divisions at this stage. We can move text around within the chunk, but we can't change the start verse of a chunk or delete a chunk--which is what a verse bridge does.

**Comment by TomWarren** [comment]
What difference would it make if the verse were a little longer?  Doesn't seem like there is any reason, except where the verse number involve, and we are keeping the verse numbers just the same. It's like we found a little piece of verse 8 and added it back in, and no one knew!

**Comment by lrsallee** [comment]
I don't follow. A verse bridge doesn't simply make the verse longer--it combines two or more verses. We can't combine verses that span chunks into a verse bridge. Doing so would change the start verse of the second chunk because it would now start with an earlier or later verse. 

The more I look at 2Sa and Neh, the more I think our only option is to move the stray text to the previous chunks. This will be a bit awkward for the notes writers, but will match other GW versions that we happen to use in addition to the ULB and UDB. If so, the chunks would look like this:

**2Sa:**

\v 8 So the king got up and sat in the city gate, and it was told to all the men, "Look, the king is sitting in the gate." Then all the people came before the king.
\p Meanwhile, in Israel every man had fled to his home.

\s5
\v 9 All the people were arguing with each other throughout all the tribes of Israel saying, "The king rescued us out of the hand of our enemies. He  saved us out of the hand of the Philistines and now he has run out of the country from Absalom.

**Neh**

\v 7 They came with Zerubbabel, Jeshua, Nehemiah, Azariah, Raamiah, Nahamani, Mordecai, Bilshan, Mispereth, Bigvai, Nehum, and Baanah.
\p The number of the men of the people of Israel included the following.

\s5
\v 8 The descendants of Parosh, 2,172.

**Comment by TomWarren** [comment]
I think that is what I was suggesting too. I think we see it the same way.


Just move the section into the verse to which it belongs, and all is well, except for the TranslationNotes, but they can be adjusted, and this assumes there is something in the text that needed a note.


Good job,



________________________________

**Comment by TomWarren** [comment]
You would be keeping the verse together instead of arbitrarily wacking them off as part of a chunk.  That should be ok, except for the Notes, which might not be a problem, let's hope.

**Comment by lrsallee** [comment]
If you put the verses together, we will fix the notes.

**Comment by TomWarren** [comment]
Deal, but you owe me chocolate.

**Comment by lrsallee** [comment]
Wait a minute! How did this become my problem??!!

**Comment by TomWarren** [comment]
First: ULB 

\v 8 So the king got up and sat in the city gate, and it was told to all the men, "Look, the king is sitting in the gate." Then all the people came before the king.
\p Meanwhile, in Israel, every man had fled to his home.

\s5
\v 9 All the people were arguing with each other throughout all the tribes of Israel saying, "The king rescued us out of the hand of our enemies. He  saved us out of the hand of the Philistines and now he has run out of the country from Absalom.

UDB 
2 Sam 19:8-9
\v 8 So the king got up and went and sat at the city gate. And all the people were told, "The king is sitting at the gate!" So they all came and gathered around him.
\p Meanwhile, all of Absalom's men had gone home.

\s5
\p
\v 9 Then all the people throughout the tribes of Israel started to quarrel among themselves. They said to each other, "King David rescued us from the people of Philistia and from our other enemies. But now he has fled from Absalom and left Israel!

ULB Neh 7:7-8
\v 7 They came with Zerubbabel, Jeshua, Nehemiah, Azariah, Raamiah, Nahamani, Mordecai, Bilshan, Mispereth, Bigvai, Nehum, and Baanah.
\p The number of the men of the people of Israel included the following.

\s5
\v 8 The descendants of Parosh, 2,172.

UDB Neh 7:7-8
This was already joined and did not need to be changed.
