### ISSUE TITLE
Rev 1:17 ULB - missing text

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#135]
The whole "First and Last" clause is missing.

**Comment by TomWarren** [comment]
ULB Rev 1:17

Repaired: the First and the Last, 

\v 17 When I saw him, I fell at his feet like a dead man. He placed his right hand on me and said, "Do not be afraid. I am **the First and the Last,**
\v 18 and the one who lives. I was dead, but look, I live forever! And I have the keys of death and of hades.
