### ISSUE TITLE
Rev 8:6 ULB "sound off on them"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#136]
The seven angels who had the seven trumpets got ready to **sound off** on them.

"Sound off" means to express one's opinion loudly or forcefully. 
How about changing "sound off on them" to "sound them"?

**Comment by TomWarren** [comment]
ULB Rev 8:6
"Sound" the trumpets is better than "sound off on them."  

Revised:
**\v 6 The seven angels who had the seven trumpets prepared to sound them.**

**Comment by pohlig** [comment]
Is there another problem here?

**Comment by TomWarren** [comment]
Just making the way trumpets are played consistent. All is well. It can be closed.
