### ISSUE TITLE
Rev 9:1  the key of the shaft leading to shaft

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#137]
It looks like this should either be "a key of the shaft" or "a key leading to the shaft."

**Comment by TomWarren** [comment]
ULB Rev 9:1
Extra phrase was removed:

**\v 1 Then the fifth angel sounded his trumpet. I saw a star from heaven that had fallen to the earth. The star was given the key to the shaft of the bottomless pit.**

Thanks
