### ISSUE TITLE
Jhn 2:20 ULB - misplaced hyphen

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#138]
"forty six-years" should be "forty-six years"

As is, I think it works out to 240 years (40 x 6)

**Comment by destatez** [comment]
I like "new-math"

**Comment by TomWarren** [comment]
Now it reads: ULB John 2:20

\v 20 Then the Jewish authorities said, "This temple was built in forty-six years, and you will raise it up in three days?"
