### ISSUE TITLE
Rev 9:2 a column of smoke went up

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#139]
I don't see anything about a "column" in the Greek.  I wonder if it should just be "smoke went up".

**Comment by TomWarren** [comment]
The Greek is:
καὶ ἀνέβη καπνὸς ἐκ τοῦ φρέατος
and went up smoke from the pit.
No Column there. 

ULB Rev 9:2 now reads:

**\v 2 He opened the shaft of the bottomless pit, and smoke went up out of the shaft like smoke from a huge furnace. The sun and the air turned dark by the smoke pouring out of the shaft.**

Thanks.
