### ISSUE TITLE
2Th 2:1-2 ULB

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#14]
The "are" in the text below does not seem to go with "we request of you"

we request of you, brothers, 
\v 2 that you are not easily shaken in your mind or troubled,

It seems to me that this should be "will not be easily shaken" or you not be easily shaken" or anything that shifts the emphasis to the future result.

**Comment by TomWarren** [comment]
\v 1 Now concerning the coming of our Lord Jesus Christ and our being gathered together to be with him, we ask you, brothers, 
\v 2 that you not be easily disturbed or troubled, either by a spirit, by a message, or by a letter the seems to be coming from us, to the effect that the day of the Lord has already come.
