### ISSUE TITLE
MRK 10 39

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#140]
They said to him, "We are able." Jesus said to them, "The cup that I will drink, you will drink. And the baptism with which I am baptized, you will endure.

Instead of "you will endure," the Greek is literally "you will be baptized." You may wish to consider switching it.

**Comment by TomWarren** [comment]
ULB Mrk 10:39 now reads:

 39They said to him, "We are able." Jesus said to them, "The cup that I will drink, you will drink. And the baptism with which I am baptized, you will be baptized with.
