### ISSUE TITLE
Rev 11:13 Comma needed

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#144]
11:13 ULB  Seven thousand people will be killed in the earthquake* and the survivors will be terrified and ...
I think a comma is needed after the word "earthquake."

**Comment by pohlig** [comment]
Right, fixed.

**Comment by TomWarren** [comment]
ULB Rev 11:13 now reads: 
\v 13 At that hour there will be a major earthquake, and a tenth part of the city will collapse. Seven thousand people will be killed in the earthquake, and the survivors will be terrified and give glory to the God of heaven.

**Comment by aaronfenlason** [comment]
This has been addressed.
