### ISSUE TITLE
Rev 11:16  Almighty One versus ruler over all

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#145]
Greek: pantokrator
ULB: the ruler over all
UDB: the Almighty One

It looks like pantokrator (and perhaps the English "almighty") has at least two senses: "the absolutely powerful one" or "the absolutely sovereign one."  (The tW page for "almighty" has both senses.)

We have a tW page for "almighty." Would you want "the Almighty one" in the ULB and the more specific "the ruler over all" in the UDB?

**Comment by aaronfenlason** [comment]
The text has already been changed. I changed the tN to reflect the change.
