### ISSUE TITLE
MRK 10:52 passive

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#146]
And Jesus said to him, "Go. Your faith has healed you." Immediately he received his sight, and followed him on the road.

This passive is not in the Greek. "he received his sight." It is literally, "he saw again."

**Comment by TomWarren** [comment]
ULB Mrk 10:52 now reads:

\v 52 And Jesus said to him, "Go. Your faith has healed you." Immediately he could see again, and he followed him on the road.

Thanks
