### ISSUE TITLE
Rev 4:5 flashes or bolts 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#147]
4:5  ULB  bolts of lightning - astrapai
8:5 ULB flashes of lightning - astrapai
11:19 ULB flashes of lightning - astrapai
16:18 ULB flashes of lightning - astrapai

Could these all have the same word? They give different images and languages might have different words.  (UDB has "lightning flashed" or "lightning was flashing" for the last 3.)

**Comment by TomWarren** [comment]
ULB Rev 4:4-5 now reads:
\s5
\v 4 Around the throne were twenty-four thrones, and seated on the thrones were twenty-four elders, dressed with white garments, with gold crowns on their heads. 
\v 5 From the throne came flashes of lightning, rumblings, and crashes of thunder. Seven lamps were burning in front of the throne, lamps that were the seven spirits of God.
