### ISSUE TITLE
Rev 2:27 ULB rod or staff

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#148]
2:27 rule them with an iron staff
12:5 rule .. with an iron rod
19:15 rule them with an iron rod

Greek has rhabdo for all of these.
We have separate tW pages for rod and staff. I don't know if they should be combined.
Could the ULB use the same word for all three?

**Comment by aaronfenlason** [comment]
2:27 was already changed to rod.

**Comment by TomWarren** [comment]
That was me. Thanks.
