### ISSUE TITLE
Rev 12:10  Odd em-dash or 'and'

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#149]
Now have come the salvation, the power—
**and** the kingdom of our God,
and the authority of his Christ.

If the em-dash indicates that the next two phrases explain the meaning of "power," then the "and" before "the kingdom" is not needed. Also it might be good to change the first line to "Now have come the salvation **and** the power—"
If the kingdom and authority are two additional things that have come, then I don't think the em-dash is needed.

**Comment by TomWarren** [comment]
ULB Rev 12:10 now reads:
\v 10 Then I heard a loud voice in heaven:
\q "Now have come the salvation, the power,
\q2 the kingdom of our God, 
\q2 and the authority of his Christ. 
\q For the accuser of our brothers has been thrown down,
\q2 the one who accused them before our God day and night.

**Comment by SusanQuigley** [comment]
Thanks, Tom.
