### ISSUE TITLE
Rev 13:10 patient endurance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#154]
ULB: Here is a call for **patient** endurance and faith for those who are holy.
Because the word "patient" is used here, it is listed in the tW list on this page. 
But the word "patient" is not in the Greek, so it seems odd to have it in the tW list. 
Would it be good to delete it from the ULB?

**Comment by TomWarren** [comment]
A common rendering of ὑπομονὴ, is "patient endurance." The rendering is good, and should stay.  

ὑπομονή 
ὑπομονή, ῆς, ἡ    (1) as a basic attitude or frame of mind patience, steadfastness (2C 12.12; probably 2TH 3.5); (2) as steadfast adherence to a course of action in spite of difficulties and testings perseverance, endurance, fortitude (RO 5.3, 4; probably HE 10.36; perhaps 2TH 3.5); (3) with a component of hope and confidence expectation, patient waiting (RV 1.9; perhaps HE 10.36)

**Comment by SusanQuigley** [comment]
Ok. Thanks.
