### ISSUE TITLE
Rev 13:3 a lethal wound that would have caused his death

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#155]
Rev 13:3 ULB a lethal wound that would have caused his death
Greek just has "wound of death." The redundancy in the ULB seems to make it more complicated.

**Comment by TomWarren** [comment]
The ULB now reads: 

\v 3 One of the beast's heads appeared to have a fatal wound; but the wound that should have killed him was healed. And the whole earth marveled as they followed the beast.

Thanks,

Tom
