### ISSUE TITLE
Rev 13:13-14 long sentence

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#156]
This sentence is long. Could it be split up between the two verses?

**Comment by TomWarren** [comment]
Rev 13:13-14 ULB  reads now with shortened sentences:

\v 13 He performed mighty miracles, even making fire come down on the earth from heaven in front of people.
\v 14 He deceived those who lived on the earth by the signs he was permitted to perform. He told them to make an image in honor of the beast who had been wounded by the sword, yet he still lived.

**Comment by SusanQuigley** [comment]
Thank you.
