### ISSUE TITLE
Rev 13:14

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#157]
ULB:  telling them to make an image in honor of the beast who was wounded by the sword, **but still he lived.**

The comma preceding "but still he lived" and the pronoun in that phrase give the impression that that phrase is not part of the relative clause "who was wounded by the sword." Could it be changed to something shorter like one of these?
who was wounded by the sword yet lived.
who lived though he was wounded by the sword.

**Comment by TomWarren** [comment]
THe ULB of Rev 13:14 now reads:

\v 14 and by the signs he was permitted to do, he  deceived those who lived on the earth, telling them to make an image in honor of the beast, who, even though he was wounded by the sword, still lived.

**Comment by SusanQuigley** [comment]
Thank you, Tom. It's not showing up yet on Github and Door43

**Comment by TomWarren** [comment]
Seems there now. Some times it takes a few minutes (don't know why). I reloaded it, and it follows this reading.

**Comment by SusanQuigley** [comment]
Tom, this is odd. I checked the notes page for Rev 13:13-14 to see how I should update the notes based on the changes you made. But those changes still aren't showing up in Door43 or Github. Could you look into it? I want to make sure that the notes fit with the text.

**Comment by TomWarren** [comment]
Just re synced it. SHOULD be there now. Sometimes I have 20 chapters open, and I my be confusing it. Trying to keep open files to a minimum. 
\v 14 and by the signs he was permitted to do, he deceived those who lived on the earth, telling them to make an image in honor of the beast, who, even though he was wounded by the sword, still lived.

**Comment by SusanQuigley** [comment]
Thank you, Tom. It shows up now.
