### ISSUE TITLE
Rev 13:15  Who causes/commands people to be put to death?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#158]
Rev 13:15  Who causes/commands people to be put to death?

ULB -  He was permitted **to give breath** to the image of the beast so that the image might even speak **and to cause** all who refused to worship the beast to be killed. 

UDB: God allowed the second beast to breathe life into that idol in order that **the idol might speak and command** that whoever refused to worship it should be killed. 

It looks like in ULB the second beast does it, and in the UDB the image does it.

**Comment by TomWarren** [comment]
The UDB of Rem 13:15 now reads:
\v 15 God allowed the second beast to breathe life into that idol in order that the idol might speak. And the beast commanded that whoever refused to worship the idol should be killed.

**Comment by SusanQuigley** [comment]
Thank you.
