### ISSUE TITLE
Rev 14:8 ULB the wine of 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#159]
ULB who made all the nations drink the wine of her sexual immorality, the wine that brought much wrath on her.

I see that the ULB follows a suggestion from the UBS Translator's handbook. But I'm finding it more difficult to explain this than a more literal translation would be. (It sounds like God was angry with them because they were drunk or they acted like they were drunk.) This more literal translation would be easier to explain:
who made all the nations drinks he wine of the wrath of her sexual immorality

**drink the wine of wrath** - The angel speaks of them experiencing God's wrath as if they were being made to drink too much wine. AT: "experience God's wrath" or "be punished by God" or "suffer God's punishment as drunks suffer from too much wine"  (See: Metaphor)

**wrath of her sexual immorality** - The reason for God's wrath was her sexual immorality. 

**who made all the nations drink the wine of the wrath of her sexual immorality** - "who led the nations to be sexually immoral and so drink the wine of God's wrath" or "who led the nations to be sexually immoral and to suffer from God's punishment as people suffer when they are drunk"

**Comment by TomWarren** [comment]
ULB Rev 14:8 now reads: 
\v 8 Another angel—a second angel—followed saying, "Fallen, fallen is Babylon the great, who made all the nations drinks the wine of the wrath of her sexual immorality."

Thanks.

**Comment by pohlig** [comment]
I changed "drinks" to "drink." Also, I think it more likely, as some versions do, that the wine of God's wrath refers, not to the immorality of the nations, but instead to God's punishment of their immorality, as in  14:10. So I changed the note to reflect that. The UDB did not need much changing, if any.
