### ISSUE TITLE
Jos 10:37 U:B

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#16]
The word "every" has been deleted before "living creature." It needs to be restored.

New:  They completely destroyed living creature in it,

Old: They completely destroyed every living creature in it,

**Comment by TomWarren** [comment]
Larry,

Repaired:
\v 37 They captured it and attacked with the sword everyone in it, 
including the king and all its surrounding villages. They completely 
destroyed every living creature in it, leaving no survivors, just as 
Joshua had done to Eglon. He completely destroyed it, *and every living 
creature* in it.


Tom
