### ISSUE TITLE
Rev 15:5  "most holy place" and "tent of witness"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#161]
ULB: and the most holy place, in which was the tent of witness, 
UDB: the very holy place in heaven was open, where the sacred tent was.

Both of these make it sound like the tent of witness was in the most holy place. Is that right?
If people look at the tW links, they'll find that the most holy place is in the tabernacle. This could be confusing.

**Comment by TomWarren** [comment]
Yes the tent of testimony (witness)  appears to be part of  the heavenly Temple.  
Yes there is an early tabernacle prior to the Temple of Solomon, and that was to be a reflection of the heavenly Temple. So there is possible confusion even by those who get it right. 
Symbols and iconography. 

The Greek is: 
ὁ  ναὸς  τῆς  σκηνῆς  τοῦ   μαρτυρίου  ἐν  τῷ   οὐρανῷ,
the temple of the tent of witness (testimony) in heaven. So the temple could be the same as the "tent of testimony" or it could be part of the heavenly temple (ἐν  τῷ   οὐρανῷ, in heaven). 
There could be notes on the earthly tent (tabernacle) and the heavenly tabernacle. They have things in common, the ideal being the model for the real early tabernacle (very Platonic), but a good way of thinking about it.

**Comment by SusanQuigley** [comment]
Tom, I've figured out what my difficulty is. The ULB and UDB translate the Greek _naos_  'temple' as "the most holy place." Other versions use the word "temple" for _naos_.   So when the ULB and UDB say that the tent of testimony is in "the most holy place," I thought it was saying that the tent was in the room of the tent. (Illogical)  Could the ULB and UDB translate _naos_ as "temple"?  

Here are my ideas.
**ULB**: and the **temple**, in which was the tent of witness, was open in heaven.
Or better yet
**ULB: ** and the **temple, which is** the tent of witness, was open in heaven.
**ULB: ** and the **temple, which represents** the tent of witness, was open in heaven.

**UDB**:  I saw that the **temple** in heaven was open, where the sacred tent was.
(But I don't know what the relationship was meant by "where the sacred tent was." Was the sacred tent near the _naos_, or in the _naos_?)

**Comment by TomWarren** [comment]
Yes, translating naos, as "most holy place" demands an explanation. Simply translating in both the ULB and UDB as "temple" is much clearer. 
Both UDB and ULB in Revelation translate naos as temple. 
Thank you.

**Comment by SusanQuigley** [comment]
Yoo-hoo! Thank you, Tom.
At this point the ULB reads a little odd. I don't know if you were finished with it or not.
ULB: After these things I looked, and the temple, and in it was the tent of witness in heaven was open.

**Comment by SusanQuigley** [comment]
Thanks for fixing the awkwardness in the ULB.
The UDB still has "the very holy place" rather than "the temple."

**Comment by TomWarren** [comment]
Sorry, I changed them, but didn't sync. the very holy place is now "temple."
Tom

**Comment by SusanQuigley** [comment]
Thank you.
