### ISSUE TITLE
Rev 16:3,4 became (like) blood

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#162]
16:3  it became like the blood of a dead person, 
16:4 they became blood

16:3 egeneto haima hos nekrou. The word "hos" immediately precedes nekrou. 
Would it be better to say "it became blood, like that of a dead person"?
It seems odd to have the seas becoming _like_ blood and the rivers becoming real blood.

**Comment by TomWarren** [comment]
Several changes in UDB Rev 16
Some here: 

\s5
\v 3 Then the second angel poured out upon the ocean what was contained in his bowl. When he poured out his bowl, the water changed its appearance, and it **turned into blood,** but not living blood, but it was like the blood of a dead man, and every creature that lived in the ocean died.

\s5
\v 4 Then the third angel poured out upon the rivers and water springs **what was contained in his bowl.** When he poured out his bowl, the water in the rivers and springs turned into blood.
\v 5 I heard the angel who has power over the waters say to God, "O God, you exist and have always existed. You are the holy one. You are a fair judge of people.
\v 6 The people who rebelled against you murdered your holy people and the prophets. So you are just in punishing them by giving them blood to drink. This is what they deserve."
\v 7 Then I heard someone at the altar answer, "Yes, Lord God, you who are almighty, you punish people rightly and justly."

The same follows through the 7 bowls.

**Comment by SusanQuigley** [comment]
16:3 UDB the water changed its appearance, and it **turned into blood**, but not living blood, but it was like the blood of a dead man,
16:3 ULB  it became **like the blood** of a dead person, 

Thanks for changing both things on the UDB.
Could the ULB also be changed to indicate that the water in the sea actually became blood?
it became blood, like that of a dead person

**Comment by TomWarren** [comment]
\v 3 Then the second angel poured out upon the ocean what was contained in his bowl. When he poured out his bowl, the water changed its appearance, **and it turned into blood,** but not living blood, but it was like the blood of a dead man, and every creature that lived in the ocean died.

There is some apocalyptic language here, what is, is also like something else. I think this is ok. 
Thanks, 

Tom

**Comment by SusanQuigley** [comment]
The scripture you showed above is from the UDB. That looks good to me. 
My concern is with the ULB. The ULB says that the water became **like** blood. I was wondering if the ULB could be changed to say that it became "blood, like that of a dead man." 

My understanding was that the water actually became blood. I'm not sure if you didn't realize I was talking about the ULB, or if you're saying that it only became "like blood."

**Comment by TomWarren** [comment]
Yes, ULB Rev 16:3 now reads:
\v 3 The second angel poured out his bowl into the sea and it became blood, like the blood of a dead person, and every living thing in the sea died.

**Comment by TomWarren** [comment]
Thanks Susan.

**Comment by SusanQuigley** [comment]
Thank you, Tom.
