### ISSUE TITLE
Rev 17:17 ULB power to rule

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#164]
17:17 ULB  their power to rule 

If we need to keep the original figures of speech, it would be good change  "their power to rule" to "their kingdom"

This is metonymy where kingdom represents power to rule as king.

**Comment by TomWarren** [comment]
ULB Rev 17:17
the Gk is :    τὴν  βασιλείαν  αὐτῶν
The meaning is "their kingship" or "their power to rule"  or "their royal power" or "sovereignty" . There is a distinction made between "kingdom" (what he rules over) and "the power they have to rule over a kingdom." 
So this would not be a perfect metonymy with kingdom, but more a description of the means by which those in power rule. 
The ULB is reflects "kingly power".

**Comment by SusanQuigley** [comment]
OK. Thanks for checking it.  I don't see the difference between βασιλείαν here and in other verses in Rev where it is translated as kingdom, but perhaps it has to do with the words in the sentence that are collocated with it?

**Comment by aaronfenlason** [comment]
I think that's the case, Susan, especially in light of v. 12-13.
