### ISSUE TITLE
MRK 12:33 dropped idiom

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#165]
To love him with all the heart and with all the understanding and with all the strength, and to love one's neighbor as oneself, is much more important than all burnt offerings and sacrifices."

Just fyi,
the idiom "much more/more" has been dropped n made explicit into "much more important."

**Comment by TomWarren** [comment]
The Eng can support the Greek text: 

    περισσότερόν ἐστιν πάντων τῶν ὁλοκαυτωμάτων  καὶ  θυσιῶν.

\v 33 To love him with all the heart and with all the understanding and with all the strength, and to love one's neighbor as oneself, is even more than all burnt offerings and sacrifices."

Thanks
