### ISSUE TITLE
Jas 1:6 ULB - "who doubts"

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#168]
This does not appear to be grammatically correct:

"For who doubts is like"

Should be " For whoever doubts" or "For one who doubts" or "For he who doubts" ...

**Comment by TomWarren** [comment]
ULB Jas 1:6 now reads: 
\v 6 But let him ask in faith, without any doubt. For the one who doubts is like a wave in the sea that is moved by the wind and tossed around.
Thanks
