### ISSUE TITLE
Jos 12:03 ULB

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#17]
This verse has "sea of Chinneroth."  I know I have recently seen "Chinnereth." Please check consistency of those two words.

**Comment by TomWarren** [comment]
Dear Larry,

The translation should be Chinnereth (following the Heb and most Eng 
versions).
Checked all OT ULB uses of Chinner* .  There are no occurrences in ULB 
and UDB in the NT of Chinner*.

I updated the TN to match this spelling.

ULB changes: Numbers 34:11; Jos 12:3; and Jos 13:27.  "oth" to "eth"

UDB changes: Jos 11:2; 12:3; and 13:27. "oth" to "eth"

All clear for "Chinnereth".


There you go. Thanks, Larry,

Tom

**Comment by lrsallee** [comment]
Thanks.
