### ISSUE TITLE
Rev 18:15 ULB weeping and loud mourning

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#170]
Rev 18:15 ULB the fear of her torment, weeping and loud mourning.
Rev 18:15 UDB afraid that they will suffer just as the city has. They will weep and mourn

Could ULB be changed to "the fear of her torment, weeping and mourning loudly"
or "the fear of her torment, and they will weep and mourn loudly"? (weeping and mourning loudly would tell what the merchants  do as they stand at a distance.)

In the UDB and Greek, "weeping" and "mourning" are verbs, and the subject is the merchants. 
The ULB has "weeping and loud mourning" as nouns, and the subject is the people of Babylon.

**Comment by aaronfenlason** [comment]
Changed to "weeping and mourning loudly."
