### ISSUE TITLE
67 books?

### ISSUE THREAD

**Issue by Daniel-Hug** [Door43/ulb-en#180]
The file names:
OT: `01-GEN.usfm` - `39-MAL.usfm`
NT: `41-MAT.usfm` - `67-REV.usfm`

The new testament numbers seem to all be incremented by 1, skipping the number 40, and implying 67 books.

**Comment by TomWarren** [comment]
This may also touch on the naming conventions for each book that is in the repo. We need to resolve the names and identification conventions in use.

**Comment by pohlig** [comment]
Can this issue go to Jesse?
