### ISSUE TITLE
MRK 14:27 extra phrase

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#181]
Jesus said to them, "All of you will fall away because of me, for it is written...

Just fyi, the phrase "because of me" isn't in the Greek.

**Comment by aaronfenlason** [comment]
@TomWarren 
This is a text critical issue. The phrase is included in the TR and some other manuscripts, but not in the best witnesses or in modern critical editions of the GNT. Not sure this is something that needs to be removed, or is fine as is.

**Comment by TomWarren** [comment]
It would be well to put a footnote (because it is a well-known verse and could be distressing if someone were familiar with the TR (KJV). The wording of the Mrk 16 section would work.

**Comment by aaronfenlason** [comment]
@TomWarren I'm not familiar with how to write/format footnotes.

**Comment by TomWarren** [comment]
@aaronfenlason  The code is: 
\v X \f + \ft The best ancient copies omit vs. X, "text to be omitted" \f*

See if that works.

**Comment by aaronfenlason** [comment]
That worked. Thanks!
