### ISSUE TITLE
MRK 15:26 capitalize 

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#183]
On a sign they wrote the charge against him, "The king of the Jews."

Capitalize "king"

**Comment by TomWarren** [comment]
The office of king would not be capitalized. It would be as in a phrase like "here comes King David," but not in the phrase, "David was the king of Israel." The same here, Jesus is king, and King Jesus would follow (the latter, of course does not occur). Caps are consistently applied according to these rules. 
This cap in Mk 15:26 is consistent with the conventions we have adopted. Remember this is for translation into other languages, not for those who have Eng as their primary lang. It does look a bit odd to English speakers. The Eng translations differ broadly on this. 
Thanks.

**Comment by aaronfenlason** [comment]
Tom addressed this, so I'm closing it.
