### ISSUE TITLE
MRK 15:42 capitalize?

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#184]
When evening had come, because it was the day of Preparation, that is, the day before the Sabbath

Should "day" in "day of Preparation" be capitalized?

**Comment by aaronfenlason** [comment]
It is capitalized in Luke 23:54, so I capitalized it here (see also Day of Atonement).

**Comment by TomWarren** [comment]
We try to avoid caps when at all possible, because the MTTs will follow our lead (unnecessarily).
