### ISSUE TITLE
GEN 37:14 ?

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#186]
He said to him, "Go now, see whether it is well with your brothers and well with the flock, and bring me word." So Jacob sent him out of the valley of Hebron, and Joseph went to Shechem.

At this point in Gen. Jacob is referred to as Israel. I don't know why "Jacob" is used here. It's not in the Hebrew text; in the Hebrew it's merely specified by the verb. Perhaps the pronoun "he" or "Israel" would be better suited here.

**Comment by TomWarren** [comment]
The first verse of Chapt 37 has "Jacob lived ..."  There is some ambiguity on Israel/Jacob through the "Jacob" history in Genesis. I think most modern translations refer to Jacob here. Sometimes it is good to supply the referent, here "Jacob" going back to 37:1 as the referent, and so it can stand.
