### ISSUE TITLE
PSA 43:5

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#195]
We think that:
5Why are you bowed down, my soul?
Why are you disquieted within me? 
**_HJpe in God_**; for I will yet praise him, 
who is my help and my God. 

Should be:
5Why are you bowed down, my soul?
Why are you disquieted within me? 
**_Hope in God;_** for I will yet praise him, 
who is my help and my God.

**Comment by aaronfenlason** [comment]
Fixed
