### ISSUE TITLE
GEN 40:20 fos dropped

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#196]
It came about on the third day that it was Pharaoh's birthday. He made a feast for all his servants. He paid special attention to the chief cupbearer and the chief baker, more than to all his other servants.

I'm not sure why, but the figure, "lifted up the head" has been dropped from this verse, but it was retain in the previous places where it was mention: 1) Joseph's interpretation of the cup bearer's dream and 2) Joseph's interpretation of the baker's dream. It's been switch out with this "special attention."

**Comment by aaronfenlason** [comment]
@TomWarren 
What do you think about restoring the figure here? A translation note would be sufficient to explain that in this context to "lift up/raise the head" of the chief cupbearer and chief baker is a double entendre in light of 40:13 and 19.

**Comment by TomWarren** [comment]
The FOS "will lift up your head in 13, 19, and 20 is used in a metaphorical and a literal sense (with irony). 
Vs 13,  וַיִּשָּׂ֞א   אֶת־רֹ֣אשׁ  "will lift up your head" means to raise a person to new status and importance.
Vs 19, "will lift , Pharaoh, up your head.
VS 20, the phrase "lift up the head" is used two times, with two different turns of the figure. 
Vs 20, the most, needs the explanation that the chief cupbearer and the chief of the bakers both had their "heads lifted up" but in very different ways. 
The confusion can be removed (to some extent by following the text, which explains it. 
ULB GEN 40:20-22 now reads: 
\v 20 It came about on the third day that it was Pharaoh's birthday. He made a feast for all his servants. He lifted up both the head of the chief of the cupbearers and the head of the chief of the bakers, among his servants, in this way:
\v 21 He restored the chief of the cupbearers to his responsibility, and he put the cup into Pharaoh's hand again;
\v 22 and he hanged the chief of the bakers, just as Joseph had interpreted their dreams to them.

Tom W
