### ISSUE TITLE
EXO 15:24  I, Yahweh your God

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#197]
"If you will listen carefully to my voice, I, Yahweh your God, and do what is right in my eyes—and if you pay attention to my commandments and obey all my laws, I will put on you none of the diseases that I put on the Egyptians; for I am Yahweh, who heals you."

The phrase "I Yahweh your God" does not fit here well.

Suggestions.
"If you will listen carefully to my voice, **to me**, Yahweh your God, and do what is right in my eyes ...
OR
"If you will listen carefully to my voice, and do what is right in my eyes—and if you pay attention to my commandments and obey all my laws, **I, Yahweh your God,** will put on you none of the diseases that I put on the Egyptians; for I am Yahweh, who heals you."

**Comment by TomWarren** [comment]
The difficulty is that the Heb has "his commands" "in his sight" etc in 3rd person, but then it shifts back to 1st person in the last two phrases: 
\v 26 He said, "If you carefully listen to voice of Yahweh your God, and do what is right in his eyes, and if you give ear to his commands and obey all his laws—I will put on you none of the diseases that I put on the Egyptians, for I am Yahweh who heals you."

**Comment by TomWarren** [comment]
The tN have been checked and aligned.

**Comment by SusanQuigley** [comment]
Thanks for fixing it, Tom.

**Comment by SusanQuigley** [comment]
Oops. I just realized  the word "the" is missing where I put the asterisk.
If you carefully listen to * voice of Yahweh your God  (Exo 15:26 ULB)

**Comment by TomWarren** [comment]
The ULB of Exodus 15:25 now reads: 
\v 26 He said, "If you carefully listen to the voice of Yahweh your God, and do what is right in his eyes, and if you give ear to his commands and obey all his laws—I will put on you none of the diseases that I put on the Egyptians, for I am Yahweh who heals you."
