### ISSUE TITLE
EXO 16:32 Is coriander white?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#199]
Exo 16:32 ULB  It was white like coriander seed,
Exo 16:32 UDB It looked like small seeds called coriander, but it was white 

The ULB strongly implies that coriander seed is white. The UDB strongly implies that coriander seed is not white. Could one of them be changed so that they have the same implication? I looked up coriander in wikipedia. The flower is white, but the picture shows that the fruits--which are often called seeds--are brown.

Some more literal versions translate it as 
It was like coriander seed, white: and its taste was like wafers with honey  (The semicolon shows that it is two facts about manna and implies that coriander seed is white.)
It was like coriander seed, white,  and its taste was like wafers with honey (The commas show that it is three facts about manna, and does not strongly imply anything about the color of coriander seed.)

**Comment by SusanQuigley** [comment]
TN says that the use of coriander describes the **size** and **shape** of the manna. 
If so, the manna would be like small, round balls.

Exo 16:14 ULB says "a small round thing as thin as frost on the ground."
Bible Hub glosses say "a small flake-like thing, fine as the frost". 

This is the only use of _chaspas_ "flake-like" in the Bible. 
_Dak_ can be glossed as thin, small, or fine.  
If the coriander is like a ball, maybe _dak_ means "small", not "thin". 

Maybe 16:14 should be something like this, without the idea of "thin"
 "a small round thing like frost on the ground."

**Comment by pjoakes** [comment]
Susan,
The ASV (and ULB) are wrong at this point. They give the wrong impression by saying "a small round thing” as if there were a single object on the ground. There is no clear example of daq meaning “small” to describe an object. It refers to incense, dust (“fine”), and starving cows (“thin”), and here to something like frost. All modern translations go with “fine” or “thin."
Also, mehusmas does not mean “round.” Most modern translations use “flakes” or “flake-like.”

I don’t think anyone can definitively say that the reference to coriander is meant to indicate the shape of the manna. It could - the seed tends to split and would then be small and flake-like. Coriander has a range of color from brown to white, so it could be a reference to color or even taste (being further described as like wafers with honey). It would be good if the Note could leave it open.

Also, the use of “ice” in the UDB is not equivalent to “frost.” That could lead the reader to think of an object. It was not a thick layer of something that looked like ice. It was a thin layer of flakes like frost.

For the ULB, after “behold,” I would suggest: “all over the wilderness was a thin layer of flakes, as thin as frost on the ground."

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Aug 16, 2016, at 1:09 PM, SusanQuigley <notifications@github.com<mailto:notifications@github.com>> wrote:


TN says that the use of coriander describes the size and shape of the manna.
If so, the manna would be like small, round balls.

Exo 16:14 ULB says "a small round thing as thin as frost on the ground."
Bible Hub glosses say "a small flake-like thing, fine as the frost".

This is the only use of chaspas "flake-like" in the Bible.
Dak can be glossed as thin, small, or fine.

If the coriander is like a ball, maybe dak means "small", not "thin".

Maybe 16:14 should be something like this, without the idea of "thin"
"a small round thing like frost on the ground."

**Comment by SusanQuigley** [comment]
Thank you, Perry, for answering my questions concerning the description of manna in Exodus 16:14. I'll copy our posts concerning this verse to a new issue because I introduced issues on two different verses on this thread.

For 16:32 I still have the concern about the difference between the ULB and UDB.
Exo 16:32 ULB It was white **like** coriander seed,
Exo 16:32 UDB It looked like small seeds called coriander, **but** it was white

**Comment by TomWarren** [comment]
The UDB of EXO 16:31 now reads: 
\v 31 The Israelite people called this food 'manna,' which sounds like the Hebrew word that means 'what is it?' It looked white, like the color of coriander seeds, and it tasted like thin wafers made with honey.

The ULB of EXO 16:31 now reads: 
\v 31 The people of Israel called that food "manna." It was white like coriander seed, and its taste was like wafers made with honey.

**Comment by SusanQuigley** [comment]
Thank you.
