### ISSUE TITLE
Exo 16:14 Description of Manna

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#201]
I copied this from what I wrote about Exo 16:32.

TN (for 16:32) says that the use of coriander (seeds) describes the size and shape of the manna. 
If so, the manna would be like small, round balls.

Exo 16:14 ULB says "a small round thing as thin as frost on the ground."
Bible Hub glosses say "a small flake-like thing, fine as the frost".

This is the only use of chaspas "flake-like" in the Bible. 
Dak can be glossed as thin, small, or fine.

If the coriander is like a ball, maybe dak means "small", not "thin".

Maybe 16:14 should be something like this, without the idea of "thin"
"a small round thing like frost on the ground."

**Comment by SusanQuigley** [comment]
I copied this reply of Perry Oakes' reply from the thread on 16:32.

Susan,
The ASV (and ULB) are wrong at this point. They give the wrong impression by saying "a small round thing” as if there were a single object on the ground. There is no clear example of daq meaning “small” to describe an object. It refers to incense, dust (“fine”), and starving cows (“thin”), and here to something like frost. All modern translations go with “fine” or “thin."
Also, mehusmas does not mean “round.” Most modern translations use “flakes” or “flake-like.”

I don’t think anyone can definitively say that the reference to coriander is meant to indicate the shape of the manna. It could - the seed tends to split and would then be small and flake-like. Coriander has a range of color from brown to white, so it could be a reference to color or even taste (being further described as like wafers with honey). It would be good if the Note could leave it open.

Also, the use of “ice” in the UDB is not equivalent to “frost.” That could lead the reader to think of an object. It was not a thick layer of something that looked like ice. It was a thin layer of flakes like frost.

For the ULB, after “behold,” I would suggest: “all over the wilderness was a thin layer of flakes, as thin as frost on the ground."

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>

**Comment by SusanQuigley** [comment]
Tom, did you see Perry's comment concerning the ULB "a small round thing" in 16:14 and his last two paragraphs?

**Comment by TomWarren** [comment]
וְהִנֵּ֞ה is better translated, "there was" instead of "behold."  More of a place marker than an exclamation. 

The ULB of EXO 16:15 now reads: 
\v 14 When the dew was gone, there on the surface of the wilderness were thin flakes like frost on the ground.

The UDB of EXO 16:15 now reads: 
\v 14 When the water dried up, on the ground there was a thin layer of something that looked like small white flakes. It looked like ice laying on the ground.

**Comment by SusanQuigley** [comment]
Thank you.
