### ISSUE TITLE
EXO 18:10 UDB 'hand' ULB 'power'

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#202]
Exo 18:10 UDB and from the **hand** of the Egyptians!
Exo 18:10 ULB and he has set the people free from their **control**.

Maybe the ULB 'control' and UDB 'hand' should be switched.

Hebrew has "hand" three times in this verse to refer to power: the hand of the Egyptians ... the hand of Pharaoh ... the hand of the Egyptians.  
Would it be good for the ULB to have "hand" in these three places?

**Comment by TomWarren** [comment]
The metonymy of hand has been explored through many projects. It would be more consistent to reverse the uses, as suggested. Thanks, 

The UDB of EXO 18:10 now reads: 
\v 10 He said, "Praise Yahweh, who has rescued you from the power of the Egyptian army, and out of the power of the king of the Egyptians (who is called Pharaoh), and has set the Israelites free from the control of the Egyptian people!

The ULB of EXO 18:10 now reads: 
\v 10 Jethro said, "May Yahweh be praised, for he has rescued you from the hand of the Egyptians and from the hand of Pharaoh, and delivered the people from the hand of the Egyptians.

**Comment by SusanQuigley** [comment]
Thank you. Now there's a note dealing with the metonymy.
