### ISSUE TITLE
Exo 18:9  ULB  power or hand?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#203]
Exo 18:9 ULB  in that he had rescued them from the Egyptians' **power**. 
Would you want the metonym "hand" as in Hebrew?

**Comment by pohlig** [comment]
Yes. I'll change the ulb to hand, but make sure the udb understands "power."

**Comment by TomWarren** [comment]
There are a slew of these changes from "hand" to "power" (and the like).

And we should probably leave this open until there is a go-through in the ULB to search "hand" in Heb and replace "power" (and other renderings) with hand. 
@pohlig 
@SusanQuigley
