### ISSUE TITLE
EXO 18:18 ULB  wear out X and Y

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#204]
Exo 18:18 ULB  You will certainly **wear out** yourself and the people who come to you, 

A writer and manager asked for "wear out yourself". I think the following could work:
You will certainly wear **yourself out along with** the people who come to you,

I think the following would be odd because the object of "wear out" is compound:  "yourself" and "the people who come to you":
You will certainly **wear out yourself** and the people who come to you, 

I think the following would be odd because it puts "out" so far away from the verb it belongs to.
You will certainly **wear** yourself and the people who come to you **out**

**Comment by TomWarren** [comment]
ULB of EXO 18:18 now reads: 
\v 18 You will surely wear yourselves out, you and the people who are with you. This burden is too heavy for you. You are not able to do it by yourself.

Thanks.

**Comment by SusanQuigley** [comment]
Even better. Thanks.
