### ISSUE TITLE
Exo 19:10  ULB "dedicate" to "consecrate"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#205]
Exo 19:10 ULB  you must dedicate them to me,
Most versions have 'consecrate' or 'sanctify'. 
The UDB "They must purify themselves" fits with "consecrate" (The KT page for "consecrate" includes "purify'.")
Could the ULB be changed from "dedicate" to "consecrate"?

If this is changed, it would be good to also change it in Exo 19:14

**Comment by TomWarren** [comment]
The word וְקִדַּשְׁתָּ֥ם here "to consecrate" "to make holy" "to set apart for special use" etc, (5 or more), and this was one of the subsidiary uses of וְקִדַּשׁ and it seems to match the context. The tN could be created about this, and I think there is something about "holy" in the introduction, in Translation Words, and other places.  
This is ok, by that reading and the project we did for continuity some time ago. But you are right, it is the same "word" just many nuances.
