### ISSUE TITLE
Exo 23:14 ULB empty handed

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#208]
Exo 23:14 ULB empty handed

Should this have a hyphen as it is in 34:20?

**Comment by TomWarren** [comment]
The ULB of EXO 23:15 now reads: 
\v 15 You are to observe the Festival of Unleavened Bread. As I commanded you, you will eat unleavened bread for seven days. At that time, you will appear before me in the month of Abib, which is fixed for this purpose. It was in this month that you came out from Egypt. But you must not appear before me empty-handed.

**Comment by SusanQuigley** [comment]
Sorry, Tom. I just  noticed that "empty handed" in the UDB also needs a hyphen.

**Comment by TomWarren** [comment]
The UDB at EXO 23:15 now reads: 
\v 15 The first one is the Festival of Bread with no Yeast. Celebrate it in the month of Abib, which is the month in which you left Egypt. Celebrate it in the way that I commanded you; eat the bread for seven days. Always bring an offering when you come to worship me. Do not come empty-handed.
