### ISSUE TITLE
EXO 34:31 ULB came up to him

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#210]
EXO 34:31 ULB Aaron and all the leaders of the community **came up** to him

Could "came up to him" be changed to "came to him" or "went to him" so that the word "up" does not lead MTTs to think that they went partway up the mountain? The Hebrew verb is shub.

**Comment by TomWarren** [comment]
This was changed by another hand: "came to him" is in the ULB EXO 34:31.

**Comment by SusanQuigley** [comment]
Hi Tom. Your changes to the ULB in verses 31 and 32 aren't showing up yet in Door43.
