### ISSUE TITLE
EXO 34:32 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#211]
EXO 34:31 ULB all the people of Israel came up to Moses

Could "came up to Moses" be changed to one of these so that the word "up" does not lead MTTs to think that they went partway up the mountain? The Hebrew verb is nagash "came near".

"came/went to Moses" 
"came/went close to Moses"
"approached Moses.

(I wrote a similar request for 34:32, but the Hebrew verb was different there.)

**Comment by TomWarren** [comment]
This was changed by another hand. The ULB of EXO 34:32 now reads: "came near"
