### ISSUE TITLE
PSA 2:1 "are" vs "do"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#213]
Psalm 2:1 ULB Why **are** the nations in rebellion,
and the peoples conspire in vain?

The second clause needs the verb "do".  The verb "are" in the first clause cannot be the understood  verb for the second clause.

Why **are** the nations in rebellion,
and why **do** the peoples conspire in vain?
OR
Why **do** the nations rebel
and the peoples conspire in vain?

**Comment by TomWarren** [comment]
The ULB is following the Hebrew text.  I added the "why do" in the second phrase to make it more understandable. 
The ULB at PSA 2:1 now reads: 
\v 1 Why are the nations in turmoil,
\q and why do the peoples make plots that will fail?
