### ISSUE TITLE
PSA 2:2 ULB Messiah vs anointed 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#214]
PSA 2:2 ULB against Yahweh and against his **Messiah**, 
PSA 2:2 UDB against Yahweh and against his **anointed one**

Hebrew simply has "his anointed," not "his Messiah."
Since this does not necessarily refer to the Messiah, could it be just "anointed one"?

**Comment by pjoakes** [comment]
“Messiah” and “anointed one” are the same in Hebrew.

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>



On Aug 23, 2016, at 8:34 AM, SusanQuigley <notifications@github.com<mailto:notifications@github.com>> wrote:


PSA 2:2 ULB against Yahweh and against his Messiah,
PSA 2:2 UDB against Yahweh and against his anointed one

Hebrew simply has "his anointed," not "his Messiah."
Since this does not necessarily refer to the Messiah, could it be just "anointed one"?

**Comment by SusanQuigley** [comment]
Oops. I misunderstood the UBS-TN  note. I thought it was saying that the Hebrew word for Messiah was derived from the Hebrew word for "anointed one." But it was talking about the English word Messiah.

Even so, capitalizing Messiah seems to indicate that it refers to God's final anointed one, not the king of that time that this psalm was originally written for.

**Comment by TomWarren** [comment]
The rule we use is that a title like "King" would be used in a name like "King David" but that in the phrase, "David was the king of Israel"  king would be LC. It seems there is some vagueness about "anointed one" whether it is a description or a title. If a title, then "Anointed One" when referring to Christ. To follow the lead of the ULB, it would be well to capitalize "Anointed One" in Ps 2:2 for continuity. 

Some data: 
The ULB uses "anointed one" for Messiah 17x and only in the OT 
The ULB does not  use "messiah"  
The ULB does not use  "Anointed One"
The ULB uses "Messiah" only 2x in the Gospels MRK 12:37; and JHN 4:25.
The ULB uses "Christ" only in the NT  306x

The UDB has Messiah in the NT 53x  none in the OT. 
The UDB does not use "messiah" 

The UDB uses "anointed one" only once in Ps 2:2
\v 2 The kings of the nations on earth prepare to revolt;
\q2 the rulers plot together to fight against Yahweh and against his **anointed one.** (changed below)

The UDB uses "Christ" 532x (only in the NT)

For continuity, it would seem that "anointed one" should be capitalized to be comparable to the ULB (to avoid confusion). It may be well to have tN about it.

The UDB PSA 2:2 now reads: 
\v 2 The kings of the nations on earth prepare to revolt;
\q2 the rulers plot together to fight against Yahweh and against his Anointed One.

Thanks.
