### ISSUE TITLE
PSA 2:9 UDB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#215]
PSA 2:9 UDB  you will smash * like a potter's jar.

I think this needs the word "them" where I put the asterisk.

**Comment by TomWarren** [comment]
This was gone-through a bit. 

The ULB now reads: 
\v 9 You will break them with an iron rod;
\q like a jar of a potter, you will smash them to pieces."

The UDB now reads: 
\v 9 You will strike them down with an iron rod;
\q2 like the potter crashes his pot into pieces when he throws it on the ground,
\q2 that is how you will break them up into small pieces.

**Comment by SusanQuigley** [comment]
Tom, these changes aren't showing up on Door43 yet.

**Comment by TomWarren** [comment]
There is a delay (that is not attributable to my failing to SYNC! thank you.  I will look .

**Comment by TomWarren** [comment]
That was odd. They were on my history of having been sync'ed, but they 
didn't appear on Door43, but they showed on my Github history. I added 
unnecessary spaces, saved and synced it again. There they are now.

They are on Door43 now.

Don't know why.


Tom

**Comment by SusanQuigley** [comment]
Odd. Thanks for checking into it.
