### ISSUE TITLE
PSA 2:12 ULB vs UDB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#216]
ULB - Give true allegiance to his son 
UDB - Bow down humbly before his son!
Hebrew - Kiss the son

The Hebrew and UDB use a symbolic action,
The ULB presents the command without a symbolic action.
Could the ULB be translated with a symbolic action?

Then I would write a note like this:
**Kiss his son** - People would show their king that they were loyal to him by kissing him, perhaps on the feet.  AT: "Show his son that you are truly loyal to him" or "Bow down humbly before his son" (See: Symbolic Action)

**Comment by TomWarren** [comment]
Taking the Hebrew as it is (and following many modern versions), there are some who clearly mark "the son" as referring to Messiah (the Son), however in keeping with our rules for caps, it seems best to leave it without adding the additional suggestion of the Son of God. Others may draw that conclusions, but the text is as it is. 
Avoiding the figure of "kiss the son" seems unwise. Just present the text, and then add a note to it.  The UDB has an interpretative rendering.

The ULB of PSA 2:12 now reads: 
\v 12 Kiss the son or he will be angry with you, 
\q2 and you will die in the way when his anger burns for just a moment.
\q How blessed are all those who seek refuge in him.

Thanks.

**Comment by SusanQuigley** [comment]
Thanks, Tom.
