### ISSUE TITLE
PSA 5:9 ULB sepulchre spelling, or tomb

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#217]
PSA 5:9 ULB sepulchre
Could this be changed to American spelling sepulcher?
Also in 2 Chronicles 16:14

Or maybe change "sepulchre" to "tomb" as it was in 2 Kings 9:28.
"Tomb" is used 26 times in the ULB-OT.
Sepulchre is used only twice.

**Comment by TomWarren** [comment]
Tomb is good for continuity and sepulchre /sepulcher is too elite.

Changes ULB 2KI 9:28 to read: 
\v 14 They buried him in his own tomb, which he had dug out for himself in the city of David. They laid him on a bier that was filled with sweet odors and various kinds of spices prepared by skilled perfumers. Then they made a very great fire in his honor.

Changes ULB PSA 5:9 to 
\v 9 For there is no truth in their mouth;
\q their inward being is wicked;
\q their throat is an open tomb;
\q they flatter with their tongue.
