### ISSUE TITLE
PSA 9:5 rebuke vs battle cry

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#218]
Psalm 9:5 
ULB You terrified the nations with your battle cry;
UDB You rebuked the people of other nations,

Rebuke and battle cry are very different.
Also, "terrified" is in the ULB but not the UDB.

**Comment by TomWarren** [comment]
The vocab "name" (changed from "memory") and the phrase "forever and ever" now more closely follow the Heb. 
The ULB "terrified" seems to be following the NET. The Heb גער seems to be "rebuke" (as most other modern versions).

ULB PSA 9:5 now reads:  
\v 5 You rebuked the nations; 
\q you have destroyed the wicked;
\q you have blotted out their name forever and ever.

Thanks.

**Comment by SusanQuigley** [comment]
Tom, the change shows up for the first two lines, but not for the third ("memory" to "name").

**Comment by TomWarren** [comment]
Sorry, didn't commit the final change. It is there now, I trust.
