### ISSUE TITLE
PSA 9:8 fairly vs justly

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#219]
Psalm 9:8a
ULB He judges the world **fairly**
UDB He will judge all the people in the world **justly**.

The word "fairly" in 9:8a ULB seems weak, and we have no translationWords page for it.
Could it be changed to "righteously" (sedeq) or "justly"?

Psalm 9:8b
ULB He makes **just** decisions for the nations.
UDB he will judge the people of all nations **fairly**.
If we want to avoid two instances of  "justly/just" in this verse, maybe "just" in the ULB here could be changed to "fair".

**Comment by TomWarren** [comment]
Note the future aspect here.
The ULB PSA 9:8 now reads: 
\v 8 He will judge the world with righteousness,
\q and he will execute judgment for the nations with fairness.

The UDB now reads: 
\v 8 He will judge all the people in the world justly;
\q2 he will be fair when he judges the people of every nation.
Thanks.
