### ISSUE TITLE
EXO 25:25 Span versus Handbreadth

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#22]
The ASV has "span" 5 times and "handbreadth" 7 times.
The ULB has "span" 9 times and "handbreadth" twice.
Should ULB be the same as the ASV?
A span is about 23 cm (tip of thumb to tip of small finger with fingers spread out).
A handbreadth is about 8 cm (the breadth of the hand without the thumb).
I have not looked at the UDB translations.

**Comment by destatez** [comment]
From previous KT work, there are 6 handbreadths to a cubit and 2 spans to a cubit {Eerdmans Dictionary of the Bible} which means there are 3 handbreadths to a span. This was not the only source of data, though. The handbreadth was the measure across four fingers held together.

**Comment by TomWarren** [comment]
Yes, Susan, and thanks.

It seems that "handbreadth" is clearer and that it would be clearer not 
to use the more archaic "span."
I will edit the spans to handbreadths, for continuity, and will check 
the TNs. If span is a KT it would not be needed, then. There are 9 
"spans" that could read, with more clarity, handbreadth.

Thanks,

Tom

**Comment by TomWarren** [comment]
Just read your note more carefully.
I lept too quickly.

Let me check the source text (Heb) and be more informed before I edit 
wildly.

Tom

**Comment by SusanQuigley** [comment]
Tom, "handbreadth" and "span" do not mean the same thing. The handbreadth is about twice as big as a span.I think you would need to check the Hebrew in all of these verses to see if they all used the same word. Ok. I see your second note. Thanks.

**Comment by TomWarren** [comment]
Dear Susan,

I realized just that point before I carried on.  I am searching the Heb 
now, and will not edit precipitously.

Thanks.
Tom

**Comment by destatez** [comment]
Tom, Susan

  I should have put my whole KT analysis in my earlier comments, which had the Hebrew Strong's IDs.
  Sorry.

Dave

**Comment by TomWarren** [comment]
FYI,

Here is the Heb word study:

זֶ֥רֶת  is "span"
EXO 28:16  2x
EXO 39:9  2x
1SA 17:4
ISA 40:12
EZK 43:13

טֹפַח is "handbreadth
EXO 25:25
EXO 37:12
EZK 40:5
EZK 40:43
EZK 43:13

Tom

**Comment by SusanQuigley** [comment]
Cool. Thanks for checking that, Tom. Would you be able to go through and make the changes in the ULB? (and possibly UDB if the numbers aren't quite right there)?

**Comment by TomWarren** [comment]
Yes all the changes have been made and checked. 
Thanks,
Tom

**Comment by TomWarren** [comment]
There are no occurrences of "span" or "handbreadth" in the UDB.

**Comment by SusanQuigley** [comment]
Thank you, Tom. 😀

**Comment by SusanQuigley** [comment]
Tom,

My concern was not that ”span" or ”handbreadth" might be in the UDB. My concern was that the translator of the UDB might have based the metric measurement for the UDB on the wrong unit (span or handbreadth.) But if the translator simply copied the number from another version that uses the metric system, then there shouldn’t be a problem.

Susan


On Apr 13, 2016, at 10:42 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


There are no occurrences of "span" or "handbreadth" in the UDB.

**Comment by TomWarren** [comment]
Right.

I will look at the UDB on those verses to see if these terms were 
rendered consistently, so as not to confuse the MTTs.

Thanks

**Comment by TomWarren** [comment]
Dear Susan,

Thanks for your good suggestion. Here is my research using ParaTExt and the results and a record of the resolution.

This is the resolution.

Here is the Heb word study:

זֶ֥רֶת  is "span" 23 centimeters
EXO 28:16  2x  ULB span 2x;  UDB reads 23 centimeters (x2)
EXO 39:9  2x ULB span 2x; UDB reads 23 centimeters
1SA 17:4  ULB span; UDB reads three meters, which is almost exactly six cubits and a span.
ISA 40:12 ULB span; UDB had palm of his hand changed to span of his hand (to make it 23 cm)
EZK 43:13 ULB span; UDB had eight centimeters, changed to 23 centimeters.

טֹפַח is "handbreadth" which is 8 cm
EXO 25:25 ULB handbreadth; UDB had 8 centimeters. No change
EXO 37:12 ULB handbreadth; UDB had 7.5 centimeters, changed to 8 centimeters. ULB and UDB changed.
EZK 40:5 ULB had handwidth changed to handbreadth for continuity, TN corrected; UDB had 3.2 meters (the whole measurement of which the handbreadth is a part), which is about 6 "long" cubits, a "long" cubit is a cubit plus a handbreadth (from the ULB). So the UDB seems accurate (perhaps a little long). Changed ULB, UDB is ok.
EZK 40:43 ULB had span changed to handbreadth for continuity, TN no correction needed; UDB has 8 centimeters. ULB CHANGED, UDB ok.
EZK 43:13 ULB had span changed to handbreadth for continuity. TN no correction needed; the UDB is taking a measurement from the ULB of "a cubit and a handbreath, which comes to about 54cm,  which the UDB reads as a half meter. ULB changed, UDB ok.

Tom

**Comment by SusanQuigley** [comment]
Dear Tom,

That’s a lot of work. Thank you for doing that.

Isaiah 40:12 is interesting. It’s hard to imagine how someone would measure water in "the span of his hand." I wonder if ”palm of his hand” would be better here since this span here isn’t being used to measure length.

Susan

On Apr 13, 2016, at 11:57 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Susan,

Thanks for your good suggestion. Here is my research using ParaTExt and the results and a record of the resolution.

This is the resolution.

Here is the Heb word study:

זֶ֥רֶת is "span" 23 centimeters
EXO 28:16 2x ULB span 2x; UDB reads 23 centimeters (x2)
EXO 39:9 2x ULB span 2x; UDB reads 23 centimeters
1SA 17:4 ULB span; UDB reads three meters, which is almost exactly six cubits and a span.
ISA 40:12 ULB span; UDB had palm of his hand changed to span of his hand (to make it 23 cm)
EZK 43:13 ULB span; UDB had eight centimeters, changed to 23 centimeters.

טֹפַח is "handbreadth" which is 8 cm
EXO 25:25 ULB handbreadth; UDB had 8 centimeters. No change
EXO 37:12 ULB handbreadth; UDB had 7.5 centimeters, changed to 8 centimeters. ULB and UDB changed.
EZK 40:5 ULB had handwidth changed to handbreadth for continuity, TN corrected; UDB had 3.2 meters (the whole measurement of which the handbreadth is a part), which is about 6 "long" cubits, a "long" cubit is a cubit plus a handbreadth (from the ULB). So the UDB seems accurate (perhaps a little long). Changed ULB, UDB is ok.
EZK 40:43 ULB had span changed to handbreadth for continuity, TN no correction needed; UDB has 8 centimeters. ULB CHANGED, UDB ok.
EZK 43:13 ULB had span changed to handbreadth for continuity. TN no correction needed; the UDB is taking a measurement from the ULB of "a cubit and a handbreath, which comes to about 54cm, which the UDB reads as a half meter. ULB changed, UDB ok.

Tom

**Comment by TomWarren** [comment]
Guess it would depend on how he was using his hand to measure. Reverting 
to palm seems going back down the hill. The renderings are consistent, 
and perhaps a note would take care of it.

Having aligned the entire corpus on this term, perhaps a note.

Tom

**Comment by SusanQuigley** [comment]
Tom, I just realized, if the word ”span” is used in Isaiah 40:12, it would be in the ULB, not the UDB. The ULB has ”hollow of his hand”.

Susan
On Apr 13, 2016, at 12:13 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:

Guess it would depend on how he was using his hand to measure. Reverting
to palm seems going back down the hill. The renderings are consistent,
and perhaps a note would take care of it.

Having aligned the entire corpus on this term, perhaps a note.

Tom

**Comment by TomWarren** [comment]
The hollow in Isa 40:12 is

שֹׁעַל
[שֹׁעַל]


	_n.[m.]_ *hollow hand, handful -- 1.* /hollow hand/. *2.* /handful/.

HTML clipboard
Changed "span" in UDB to "palm" of his hand.
Continuity: span is 23 cm measurement  from tip of little finger to 
thumb. And has specific measurement uses throughout. Here it should not 
be used to render shal.

Hollow is the equivalent to our "palm."


Tom

**Comment by TomWarren** [comment]
The hollow in Isa 40:12 is

שֹׁעַל
[שֹׁעַל]

	n.[m.] hollow hand, handful -- 1. hollow hand. 2. handful.

Changed "span" in UDB to "palm" of his hand.
Continuity: span is 23 cm measurement  from tip of little finger to thumb. And has specific measurement uses throughout. Here it should not be used to render shal.

Hollow is the equivalent to our "palm."


Tom

**Comment by SusanQuigley** [comment]
Thanks, Tom.
Susan

On Apr 13, 2016, at 12:35 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


The hollow in Isa 40:12 is

שֹׁעַל
[שֹׁעַל]

n.[m.] hollow hand, handful -- 1. hollow hand. 2. handful.


Changed "span" in UDB to "palm" of his hand.
Continuity: span is 23 cm measurement from tip of little finger to thumb. And has specific measurement uses throughout. Here it should not be used to render shal.

Hollow is the equivalent to our "palm."

Tom
