### ISSUE TITLE
PSA 10:15 ULB  make him accountable

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#221]
PSA 10:15 ULB
make him accountable for his evil deeds

Could the ULB be changed to this?
make him **account** for his evil deeds

**Comment by TomWarren** [comment]
The verse has been reworked: 

The ULB of PSA 10:15 how reads: 

\v 15 Break the arm of the wicked and evil man.
\q Make him account for his evil deeds, 
\q which he thought you would not discover.
