### ISSUE TITLE
PSA 52:7 ULB confirmed himself

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#222]
PSA 52:7 ULB
**confirmed himself in his wickedness**
The word "confirmed" doesn't mean anything to me here. Could it be changed to something like "strengthened"? Then I could write a note like this.

**strengthened himself in his wickedness** -  Possible meanings are 1) strength represents protection, or 2) strength represents determination.  AT:  1) "he protected himself by doing wicked things" or 2) "he became more determined to do wicked things" (See: metonymy)

**Comment by TomWarren** [comment]
ULB PSA 52:7 Now reads:
\v 7 "See, this is a man who did not make God his refuge,
\q but he trusted in the abundance of his wealth,
\q and he was strong when he destroyed others."

This is very different from the ULB here. 
The UDB now reads: 
\v 7 "Look what happened to the man who would not ask God to protect him;
\q2 he trusted that his great wealth would save him;
\q2 he trusted in the money that he got by wickedly taking it from others!"
\q2 he grew more powerful by wickedly hurting other people."

The ULB is very close to the Heb. The alternative would be "he sought refuge when he was destroyed". Which is a minority reading. 
The ULB above is in keeping with the majority. The triplet (3 parallel statements pointing in the same direction) give support to this reading.
Thanks

**Comment by SusanQuigley** [comment]
OK. Thanks.
