### ISSUE TITLE
PSA 53:4 ULB  but vs and

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#224]
53:4 ULB Do they not know anything, those who commit iniquity,
those who eat up my people as they eat bread
**but** who do not call on God?

The word "but" in the ULB seems to imply that there is some expectation that people who commit iniquity and eat up people as they eat bread should call upon God. That seems strange.
Could "but" be changed to "and"?

**Comment by TomWarren** [comment]
UDB PSA 53:4 now reads: 
\v 4 Will all these evil people never learn what God will do to them?
\q1 They hurt Yahweh's people with terrible violence, while they are enjoying the very food that God  provided for them,
\q2 and still, they never pray to Yahweh.

ULB PSA 53:4 now reads: 
\v 4 Do those who commit iniquity, not know anything—
\q those who devour my people as if they were eating bread
\q and who do not call on God?

**Comment by SusanQuigley** [comment]
Thanks for changing "but" to "and" in the ULB.
You made some good changes to the  UDB after you posted this.
