### ISSUE TITLE
PSA 55:9  ULB Confuse their languages

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#225]
ULB: Confuse their languages
This sounds like it had something to do with people speaking different languages.
But it really had to do with them being able to communicate and make plans against the writer.
Could "languages" be changed to "language" or "tongues"?

**Comment by TomWarren** [comment]
UDB PSA 55:9 now reads: 
\v 9 Lord, confuse my enemies and cause their plans to fail.
\q2 I saw them hurting others by their violence and causing riots throughout the city.

**Comment by SusanQuigley** [comment]
Thanks, Tom. It hasn't shown up yet, but I've fixed the notes.

**Comment by TomWarren** [comment]
There are times when Sync is slow.  All seems there in UDB and ULB.
Thanks.
