### ISSUE TITLE
PSA 55:10-11 ULB  the city - her vs it

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#226]
PSA 55:10-11
Day and night they go about on **her** walls;
iniquity and mischief are in the middle of **her**.
Wickedness is in the middle of **it**;
oppression and deceit do not leave **its** streets.

It would be good to have consistency in the pronouns used to refer to the city. Other than the pronouns, this psalm does not treat the city as a woman, so it would probably be good to use "its" and "it".

**Comment by TomWarren** [comment]
Changes made, now the UDB and ULB rboth refer to the city as:  "its" and "it".

**Comment by SusanQuigley** [comment]
Thank you.
