### ISSUE TITLE
PSA 55:19  ULB "remain" as metonym for "rule"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#227]
PSA 55:19 ULB
God, he who remains from ancient times 

Since this refers to God ruling, could "remains" be changed to "sits"? It's easy to tell how "sits" represents ruling, (sits on his throne), but "remains" just sounds like he lives.

**Comment by TomWarren** [comment]
ULB PSA 55:19 now reads: 
\v 19 God, the one who ruled from eternity, 
\q will hear them and humiliate them.
 \qs Selah\qs*
\q They never change,
\q and they do not fear God.

Note: Ruled from eternity seems better than he sits from antiquity. The implication is of a king sitting on a throne, ruling. "Humiliate" may be "answers" The two words are identical in Heb (apart from the pointing. Either could fit, but "humiliate" or some akin is in the modern versions most of the time.

**Comment by SusanQuigley** [comment]
Thanks for the changes to "rule" and "humiliate".
I had tried to write a  note for "respond" that would include the idea of afflicting or humbling, but it was a goofy note. Your changing "respond" to "humiliate" in the ULB makes it easier.

 ULB God, the one who **ruled** from eternity, 
Could "ruled" be "rules" or "has ruled" to show that he still rules?

**Comment by TomWarren** [comment]
Yes, Susan, that is a good suggestion. 
ULB PSA 55:19 now reads: 
\v 19 God, the one who rules from eternity, 
\q will hear them and humiliate them.
\qs Selah\qs*
\q They never change,
\q and they do not fear God.
