### ISSUE TITLE
ISA 5:10 "four hectares" or "ten acres"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#23]
ISA 5:10 ULB says "four hectares." Hebrew has ten _simde_ or 'acres'. 
This is the only use of hectare in the ULB.  Could it be changed to "ten acres"?

On the tA pages for Biblical Measures of Volume and Distance, we said that the ULB uses the original measures. I tried not to imply that the ULB uses the Hebrew or Greek words, but that the basic measure is the same. We don't have a page for area. Hmmm. Maybe it doesn't matter. What do you think?

**Comment by TomWarren** [comment]
I agree. Hectare is a very rare term,

Here is the rendering in the ULB:
\v 10 For a ten-acre vineyard will yield only one bath, and one homer of 
seed will yield only an ephah.

The UDB:

*10*The vines on ten acres of land will not produce enough grapes to 
make twenty-two liters of wine,

    and ten baskets of seed will produce only one basket of grain."


    There you go,

    Tom

**Comment by SusanQuigley** [comment]
That’s beautiful. Thanks.
Susan

On Apr 14, 2016, at 4:53 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:

I agree. Hectare is a very rare term,

Here is the rendering in the ULB:
\v 10 For a ten-acre vineyard will yield only one bath, and one homer of
seed will yield only an ephah.

The UDB:

*10*The vines on ten acres of land will not produce enough grapes to
make twenty-two liters of wine,

and ten baskets of seed will produce only one basket of grain."


There you go,

Tom
