### ISSUE TITLE
PSA 56:11 status of a clause following an em-dash

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#230]
In God, whose word I praise—
in Yahweh, whose word I praise—
11 In God I have put my trust; I will not be afraid;
what can mere man do to me?

It looks like the beginning of verse 11 is a continuation of the sentence started in verse 10.   I think the first word of verse 11 should start with a lower case letter.

**Comment by TomWarren** [comment]
The ULB PSA 56:11 now reads: 
\v 10 In God—whose word I praise,
\q in Yahweh—whose word I praise,
\v 11 in God I trust,
\q I will not be afraid.
\q What can anyone do to me?

**Comment by SusanQuigley** [comment]
Thanks for fixing that-- and for getting rid of the semi-colon after "I will not be afraid."
