### ISSUE TITLE
PSA 57:3 ULB swallow me up

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#231]
PSA 57:3 ULB   the man who wishes to **swallow me up'**

Could you fix this as you did for 56:2a?

**Comment by TomWarren** [comment]
ULB PSA 57:3 now reads: 

\v 3 He will send help from heaven and save me,
\q he is angry with those who crush me. 
\qs Selah\qs*
\q God will send me his loving kindness and his faithfulness.

**Comment by SusanQuigley** [comment]
Thanks for fixing "swallow me up."
As for chesed, there was a decision earlier on to translate it  in the ULB as "covenant faithfulness" or "covenant loyalty" and we have an translationWords page for it. Would you want to go back to that?
https://door43.org/en/obe/kt/covenantfaith

**Comment by TomWarren** [comment]
It is such a rich theological word that I would not want to see us always translate it in one way. Sometimes it is grace, or kindness, or mercy, or covenantal loyalty, or loving kindness. It is a bit like "grace" in the NT. 
I don't think it is one size fits all.

**Comment by SusanQuigley** [comment]
OK. Thanks. I'll change the link in translationWords list on the chunk.

**Comment by TomWarren** [comment]
Do you have to cover every rendering of these key verbs? Maybe it would be good to alert the MTT that this is a rich theological term and could be translated in several ways.

**Comment by SusanQuigley** [comment]
We don't write notes talking about the Hebrew or Greek words. Instead we make links to the pages for the (English) translationWords that show up in the ULB, or we write notes about them.

Perhaps the TranslationWords page for covenant "faithfulness, covenant loyalty" could also have "loving kindness" in the title and description. I'll ask Andrew to do this.

If the words "grace" or "mercy" are used in the ULB, there will be links to the pages for "grace" and "mercy". Trying to link them to the page for "loving kindness" whenever chesed is used would require the translationWords team to always check the Hebrew whenever those English words are used to know which page to link them to.
