### ISSUE TITLE
PSA 37:7

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#232]
There is a conflict on this verse:

7Be still before Yahweh and wait patiently for him. <<<<<<< HEAD

Do not be angry if someone succeeds in what he does, 

when he makes evil plots. ======= 

Do not be distressed about the one who succeeds in what he does, 

or when he carries out his evil plans. >>>>>>> origin/master

**Comment by TomWarren** [comment]
The ULB of PSA 37:7 now reads; 

\v 7 Be still before Yahweh and wait patiently for him.
\q Do not be angry if someone succeeds in what he does,
\q when he makes evil plots.

Thanks

**Comment by TomWarren** [comment]
I am curious that this didn't show up on my GitHub desktop, as they often do when a "over-write" on a verse is done (like two people at the same time). 
Curious.

**Comment by ChrisJarka** [comment]
What do you think about asking David to run a script looking for <<<HEAD?

**Comment by TomWarren** [comment]
In NotePad++ I searched "case sensitive" the word: **HEAD** and the ULB and UDB were clean.

This kind of error shows up when I SYNC. But not this time.
