### ISSUE TITLE
PS 103:20-22 comma

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#235]
20Give praise to Yahweh you angels
...
21Give praise to Yahweh all his angel armies,
...
22Give praise to Yahweh all his creatures

Should commas be added before "you angels," "all his angel armies," and "all his creatures" because of the direct address??

**Comment by TomWarren** [comment]
ULB PSA 103:20-22 now reads: 
\v 20 Give praise to Yahweh, you his angels, 
\q you mighty ones who are strong and do his word,
\q and obey the sound of his word.
\q
\v 21 Give praise to Yahweh, all his angel armies,
\q you are his servants who carry out his will.
\q
\v 22 Give praise to Yahweh, all his creatures,
\q in all the places where he reigns.
\q I will give praise to Yahweh with all my life.

Thanks.
