### ISSUE TITLE
Mat 5:25 ULB

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#24]
"Or your accuser may hand you over to the judge, and the judge hands you over to the officer, and you be thrown into prison."

The opening of this sentence was changed from "Lest perhaps..." but the following verbs were not adjusted. They fit with the old opening, but seem strange now--particularly the last clause.

**Comment by TomWarren** [comment]
\v 25 Agree with your accuser quickly while you are with him on the way to court. Or your accuser may hand you over to the judge. And the judge would hand you over to the officer. And you would be thrown into prison.
\v 26 Truly I say to you, you will never come out from there until you have paid the last bit of money you owe.

Thanks Larry
