### ISSUE TITLE
PSA 58:3  estranged?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#240]
ULB
The wicked are **estranged** from the womb;
they go astray as soon as they are born, speaking lies.

UDB 
Wicked people do wrong things and tell lies from the time that they are born.

What does the first line of the ULB mean? If I think of the normal meaning of the English word "estranged", it would mean that even from the womb the wicked are alienated from God--no longer in a close relationship with him. But the UDB doesn't explicitly say anything about relationship with God. It seems to treat the two phrases as meaning the same thing - simply that they've gone astray into sin.

Should I write a note saying that it means that they are alienated from God, or that the two phrases mean the same thing? If they mean the same thing, could  "They are estranged" be changed to something like "They turn away" or "they go the wrong way"?

**Comment by TomWarren** [comment]
ULB PSA 58:3 now reads:
\v 3 The wicked go astray even when they were in the womb;
\q they go astray from birth, speaking lies.
