### ISSUE TITLE
Psalm 59:14-15 ULB vs UDB tense and mood

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#241]
**ULB** - This sounds like "Let our enemies return. It doesn't matter. They probably won't succeed anyway." 
14 At evening let them return; let them howl like dogs
and go around the city.
15 They will wander up and down for food
and will wait all night if they are not satisfied.

**UDB** - This sounds like a complaint or concern about the enemies threatening them habitually.
My enemies return each evening,
snarling like vicious dogs as they prowl around this city.
15They roam around, searching for food;
and if they do not find enough, they growl like dogs.

Could one of these be changed so that they have the same tense and mood?

**Comment by TomWarren** [comment]
The Two are much closer now: 
UDB: 
\v 14 My enemies return each evening,
\q2 snarling like vicious dogs as they prowl around this city.
\q1
\v 15 They roam around, searching for food;
\q1 and if they do not find enough, they growl like dogs.

ULB: 
\v 14 At evening let them return; let them howl like dogs
\q and go around the city.
\q
\v 15 They wander about looking for food
\q and they growl like a dog if they are not satisfied.

Hope that helped (from the other Github).

TW

**Comment by SusanQuigley** [comment]
Thanks for fixing the differences in images.
I'm still concerned about the ULB saying Let this happen and the UDB saying It is happening.

ULB: At evening **let them** return; **let them**howl like dogs
and go around the city.
UDB: **My enemies return** each evening,
snarling like vicious dogs as they prowl around this city.

What would you think about making that part of them the same?

**Comment by TomWarren** [comment]
I changed the ULB to be closer to the HEB: 
\v 14 At evening they return, 
\q howling like dogs going around the city.
\q
\v 15 They wander about looking for food
\q and they growl like a dog if they are not satisfied.

The UDB: 
\v 14 They return each evening,
\q2 snarling like vicious dogs as they prowl around this city.
\q1
\v 15 They roam around, searching for food;
\q1 and if they do not find enough, they growl like dogs.

That seems to be a match.  TW

**Comment by SusanQuigley** [comment]
Thank you, Tom. That looks good.
