### ISSUE TITLE
PS 105:18-19 punctuation 

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#242]
18His feet were bound by shackles;
iron chains were put on him.
19until the time that his prediction came true.
The word of Yahweh proved him to be right.

Something needs to be done to the end of 18 or beginning of 19 to fix the punctuation or low-cap letter.

**Comment by TomWarren** [comment]
ULB 105:18-19 now reads: 
\v 18 His feet were bound by shackles;
\q on his neck was put an iron collar,
\q
\v 19 until the time his words came true,
\q and the word of Yahweh tested him.

Think we're ok. 
TW
