### ISSUE TITLE
PSA 59:15 ULB vs UDB growl or wait

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#243]
**ULB**
They will wander up and down for food
and **will wait all night** if they are not satisfied.

**UDB**
They roam around, searching for food;
and if they do not find enough, **they growl like dogs**.

What they will do if they are not satisfied is different in the ULB and UDB.

**Comment by TomWarren** [comment]
The UDB if fine. 
The ULB PSA 59:15 now reads: 
\v 15 They wander about looking for food
\q and they growl like a dog if they are not satisfied.

Have no idea where the previous ULB trans came from. The Heb is clear.

Thanks.
