### ISSUE TITLE
PSA 59:16 ULB missing "in the morning"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#245]
PSA 59:16 ULB
But I will sing about your strength;
for you have been my high tower
and a refuge in the day of my distress.

This seems to be missing "I will sing aloud in the morning" after the first line.

**Comment by TomWarren** [comment]
ULB PSA 59:16 now reads: 

\v 16 But I will sing about your strength,
\q and in the morning I will sing about your steadfast love!
\q For you have been my high tower
\q and a refuge in the day of my distress.

Thanks.

**Comment by SusanQuigley** [comment]
Thank for fixing it.
