### ISSUE TITLE
PSA 60:9 ULB and UDB Who is saying verse 9?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#247]
8 Moab is my washbasin;
over Edom I will throw my shoe;
I will shout in triumph because of Philistia.
9 Who will bring me into the strong city?
Who will lead me to Edom?"

Of the versions that use quote marks in the psalms, I don't see any that put the end quote at the end of verse 9  (as the ULB and UDB do), which would indicate that God is still the speaker. They put the end quote at the end of verse 8, which would indicate that the speaker of verse 9 is the psalmist.

Would you want to move the end quote to the end of v8 in the ULB and UDB?

**Comment by TomWarren** [comment]
The quote ends at the end of Vs 8, and the writer of the Psalm again asks for help. 
Most modern translation agree with that. 
VS 8 is clearly Yahweh speaking. Vs 9 shifts back to the author. 

There you go.
