### ISSUE TITLE
PS 106:30 lost passive

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#248]
Then Phinehas rose to intervene,
and the plague subsided.

So "subsided" is the passive verb "stayed" in the Hebrew. So I know this is a bit petty, but a passive implies an outside agent, which is lost when switched to active.

**Comment by TomWarren** [comment]
It's ok Kim. We are trying to be close to the Heb in the ULB. We use the passive where it occurs (except when it is opaque to the reader (to help the MTTs). But the UDB would be the place to name the agency and unpack the figures of speech. 
This can stand.
