### ISSUE TITLE
PSA 132:8 ULB Missing text?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#249]
Psalm 132:8 
**ULB** Arise, Yahweh; come to your resting place.
**UDB**: Yahweh, come to the place where you live eternally,
to the place where your sacred chest is,
to the place that shows that you are very powerful.

ULB doesn't seem to have the idea of "to the ark of your strength."

**Comment by TomWarren** [comment]
Good catch!
ULB PSA 132:8 now reads: 
\v 8 Arise, Yahweh, to your resting place,
\q you and the ark of your strength!

Note, I took out the second verb ("go") because it was inferred. But the verb "Arise" is the main verb.

**Comment by SusanQuigley** [comment]
I don't understand how the phrase "you and the ark of your strength" fit in the sentence.
What you wrote above looks like it's asking for Yahweh and the ark of his strength to go to his resting place. Is that what you intended?

**Comment by TomWarren** [comment]
This is the Heb text has, with many other versions. 
It can be unpacked it he UDB>

**Comment by TomWarren** [comment]
Arise  to your resting place ....  you and the ark of your strength. 
Ark of your strength would be in UDB something like, you and the symbol of your great power.

**Comment by SusanQuigley** [comment]
Thanks, Tom. Here are my tNs.
**you and the ark of your strength** - Possible meanings are 1) "come to the ark of your strength" or 2) "come, and make the ark of your strength come." (See: Ellipsis)
**the ark of your strength** - "the ark that shows your great power"
