### ISSUE TITLE
Mat 13:15 ULB

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#25]
The following archaic phrase was recently updated in Mat 5:25, but not in 13:15.

"lest they should perhaps..."

**Comment by TomWarren** [comment]
Worked this out: 
\v 25 Agree with your accuser quickly while you are with him on the way to court. Or your accuser may hand you over to the judge, and the judge would hand you over to the officer, and you would be thrown into prison.

**Comment by TomWarren** [comment]
Final on Matt 13:15
15For this people’s heart has become dull,
and their ears are heavy of hearing,
and their eyes they have closed,
so they would not see with their eyes,
and hear with their ears,
and understand with their hearts,
and should turn again,
and I would heal them.'
