### ISSUE TITLE
PSA 132:14-18 ULB Quote marks needed?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#250]
PSA 132:14-18 ULB Should all of this be in quotes since it has changed from the psalmist speaking to God speaking?

**Comment by TomWarren** [comment]
Yes. I will look .... Quotes go from 14 alone in quotes, then 13-16 in quotes, ending after 16.
I did work through the entire PS a bit. You may want to review it quickly. 
TW
v 11 Yahweh swore a sure oath to David,
\q a sure oath that he will not revoke:
\q "I will place one of your descendants on your throne.
\q
\v 12 If your sons keep my covenant
\q and the laws that I will teach them,
\q their children also will sit on your throne forevermore."
 
\s5
\q
\v 13 Certainly Yahweh has chosen Zion,
\q he has desired her for his seat.
\q
\v 14 "This is my resting place forever.
\q I will live here, for I desire her.
 
\s5
\q
\v 15 I will abundantly bless her with provisions.
\q I will satisfy her poor with bread.
\q
\v 16 I will clothe her priests with salvation,
\q her faithful ones will shout aloud for joy.
 
\s5
\q
\v 17 There I will make a horn to sprout for David
\q and set up a lamp for my anointed one.
\q
\v 18 I will clothe his enemies with shame,
\q but on him his crown will shine."

**Comment by SusanQuigley** [comment]
That looks clear. Thanks.
