### ISSUE TITLE
PSA 133:3 ULB Missing "is"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#251]
It * like the dew of Hermon,
I think this needs "is" where I put the asterisk.

**Comment by TomWarren** [comment]
I edited PSA 133 to bring it closer to the Heb source. 

ULB PSA 133 now reads: 
\d A song of ascents, of David.
\b
\q
\v 1 Behold, how good and how pleasant it is
\q for brothers to live together!
 
\s5
\q
\v 2 It is like fine oil on the head
\q pouring down on the beard—
\q Aaron's beard,
\q and then it pours down on the collar of his robes.
\q
\v 3 It is like the dew of Hermon
\q which falls on the mountains of Zion.
\q For there Yahweh commanded the blessing—
\q life forevermore.

**Comment by SusanQuigley** [comment]
Thank you, Tom.
