### ISSUE TITLE
PSA 127:2 food or sleep?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#252]
ULB - for Yahweh gives his beloved **sleep**.
UDB - because Yahweh gives **food** to those whom he loves.

I think it would be good either for these to be the same or for the UDB to include the idea of food along with sleep.

because Yahweh gives food to those he loves so that they can sleep.

**Comment by pohlig** [comment]
Fixed 
ULB to: for Yahweh provides for his beloved as they sleep.

UDB to:  because Yahweh gives food to those whom he loves even while they sleep.

**Comment by SusanQuigley** [comment]
Thank you, Jim.
