### ISSUE TITLE
PSA 135:12 ULB Random number

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#253]
Psalm 135:12 uLB  There's a number 2 in the middle of verse 12 that doesn't belong.

**Comment by TomWarren** [comment]
Just checked the ULB. No wandering 2.

**Comment by SusanQuigley** [comment]
Tom, thanks for checking this. Jim just fixed the UDB -- He got rid of the 2 and corrected the translation of inheritance so that it does not talk about the Israelite people passing it on. Would you be able to change it back to what Jim just did?

**Comment by TomWarren** [comment]
That was odd. Jim and I had a conflict that I had to resolve in GitHub, and part of one and part of another were mixed together. I think it is ok now. 
Thanks.

**Comment by SusanQuigley** [comment]
Thank you. It looks good now.

**Comment by TomWarren** [comment]
THE UDB of PSA 135:12 now reads: 

\v 12 Yahweh gave us their land,
\q2 and so the land would belong to us forever.

**Comment by SusanQuigley** [comment]
Oops. There was more.
\v 12 Yahweh gave us their land,
\q2 and so the land would belong to us, his people Israel, forever.

**Comment by pohlig** [comment]
see current version.

**Comment by SusanQuigley** [comment]
Thank you.

**Comment by TomWarren** [comment]
We are going to fall over each other, if not careful.

**Comment by TomWarren** [comment]
It is continuing on. Jim and I were working on top of each other and Github (on my side) was quite confused. 
Sorry to ask, but is this correct:

\q2 and so the land would belong to us, his people Israel, forever.

**Comment by SusanQuigley** [comment]
Jim and I did not discuss whether this was to tell God's purpose in giving it or the result of his giving it.

**Comment by pohlig** [comment]
It should be purpose: "so that the land would belong...."

**Comment by TomWarren** [comment]
Done and final. Jim will address the purpose or result issues. I just learned a stack!

**Comment by TomWarren** [comment]
I did have a question about whether actions of Yahweh much be with purpose or result. Is that not a binary trap that precludes the possibility that there was both and purpose and a result in view.  God isn't the same as we are.  
Just a thought running amok.
