### ISSUE TITLE
PSA 65:12 "It drops" versus "full of flocks"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#255]
ULB It drops onto the pastures in the wilderness,
UDB The pastures are full of flocks of sheep and goats;

I'm having trouble making the connection between the two translations.
Is it that the translations come from two different texts/interpretations, or is that the pastures being full of flocks is a result or proof of "fatness" dropping onto them?

**Comment by TomWarren** [comment]
UDB of PSA 95:12 now reads: 
\v 12 The pastures in the wilderness glisten with the morning dew, 
\q2 it is as though the hills are singing joyful songs.

ULB of PSA 95:12 now reads: 
\v 12 The pastures in the wilderness drip with dew,
\q and the hills are clothed with joy.

Hope that helps. TW

**Comment by SusanQuigley** [comment]
That helps. Thank you.
It just doesn't show up yet in Door43.

**Comment by TomWarren** [comment]
The SYNC feature is going slow this morning. 
Should be there now.  I see it in Wiki.

**Comment by SusanQuigley** [comment]
I see it now, too. Thank you.
