### ISSUE TITLE
NUM 3:25 extra phrases?

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#256]
"The family of Gershon must care for the tabernacle curtains under the outer coverings of the tent of meeting. They must care for the tent, the tent-like covering, and the curtain for the entrance to the tent of meeting."

So I may be dull and be missing something, but the verse seemed a bit confusing so I checked some Eng. translations and the Hebrew... I don't know where the phrase " for the tabernacle curtains under the outer coverings of the tent of meeting" comes from. Should it be there?

**Comment by TomWarren** [comment]
ULB NUM 3:25 now reads: 
\v 25 The family of Gershon must care for the tent of meeting including the tabernacle. They must care for the tent, its covering, and the curtain used as the entrance of the tent of meeting.

This is simpler and follows the HEB.
