### ISSUE TITLE
NUM 3:51 buy-back

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#257]
Moses gave the buy-back money to Aaron and to his sons. Moses did everything he was told to do by Yahweh's word, as Yahweh had commanded him.

So in the discussion section for this page there's a note from Tom saying that he was changing "buy-back" to "redemption" but I don't see it reflected in the text. Just FYI.

**Comment by TomWarren** [comment]
ULB NUM 3:51 now reads: 
\v 51 Moses gave the redemption money to Aaron and to his sons. Moses did everything he was told to do by Yahweh's word, as Yahweh had commanded him.

Don't know why it didn't take before. But thanks very much, Kim, for catching that. 
Should be there now.  TW
