### ISSUE TITLE
NUM 13:30 ULB Confusing sentence.

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#259]
Num 13:30 ULB Then Caleb tried to encourage the people gathered around Moses. 

It's easy to read this sentence wrong and think there is an error. 
Could the relationship between "gathered around Moses" and "he people" be expressed more clearly in the ULB? Here are some ideas.

Then Caleb tried to encourage the people who were gathered around Moses. 
Then Caleb tried to encourage the people who had gathered around Moses.

**Comment by TomWarren** [comment]
ULB NUM 13:30 now reads: 
\v 30 Then Caleb silenced the people who were before Moses and said, "Let us go up and take possession of the land, for we are certainly able to conquer it."

The main verb is "silenced" is הסה, and it needs to be kept. All modern versions have it.

**Comment by SusanQuigley** [comment]
Thanks for fixing both the relative clause and the verb.
