### ISSUE TITLE
NUM 13:30 discouraged or crying loudly?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#260]
ULB Then Caleb tried to encourage the people gathered around Moses. 
UDB When they said that, the people were afraid and started to cry out very loudly. But Caleb told the people who were standing near Moses to be quiet. 

These give different images of the people's behavior and how Caleb responded to them.

**Comment by TomWarren** [comment]
The UDB at NUM 13:30 has been edited to align with the ULB: 
\v 30 Caleb told the people who were standing near Moses to be quiet. Then he said, "We should go there and take the land, because we are certainly able to conquer it!"

As noted, the verb is "be quiet" or the like. 
Hope that helps. 

TW

**Comment by SusanQuigley** [comment]
Thanks for fixing both texts.
