### ISSUE TITLE
NUM 14:35 ULB "consumed" metaphor

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#263]
ULB They will be consumed in this wilderness. Here they will die.

It looks like the Hebrew has "they will end"  and the  ULB has introduced a metaphor with "they will be consumed."

I wrote the note like this because I didn't want to treat it as a figure of speech. But if "consumed" is kept, and if I should treat it as a metaphor, please let me know.
**They will be consumed** - "They will be destroyed" or "they will end"

**Comment by TomWarren** [comment]
The Heb is תמם, to come to an end, or be completely cut off. 
The ULB of NUM 14:35 now reads: 
\v 35 I, Yahweh, have spoken. I will certainly do this to all this evil community that is gathered together against me. They will be completely cut off, and here they will die.'"

**Comment by SusanQuigley** [comment]
I think that's another metaphor.

**Comment by TomWarren** [comment]
This rendering is very close to the Heb. Let the metaphors live.

**Comment by pohlig** [comment]
The Heb. verb tmm is more or less 'come to an end.' Although be cut off signals the same idea on a pragmatic level, it's a different figure of speech for sure. Why can't we just have "come to an end"?

**Comment by pohlig** [comment]
It's question of not needlessly substituting one Hebrew metaphor for another.
