### ISSUE TITLE
NUM 4:31 vs 3:36

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#264]
Both of these verses describe the framing of the tabernacle and detail it's various parts. 4:31 calls the framing "framing" whereas 3:36 uses "boards." It may be good to settle on one since these verses has nearly identical lists. The Hebrew קַרְשֵׁי֙ is the same word in both places.

**Comment by TomWarren** [comment]
The ULB of NUM 3:36-37 now reads: 
\v 36 The descendants of Merari must care for the **framing** of the tabernacle, the crossbars, posts, bases, all the hardware, and everything related to them, including 
\v 37 the pillars and posts of the courtyard that surround the tabernacle, with their sockets, pegs, and ropes.

The ULB of NUM 4:31-32 reads (without changes): 
\v 31 This is their responsibility and their work in all their service for the tent of meeting. They must care for the **framing** of the tabernacle, its crossbars, posts, and sockets,
\v 32 along with the posts of the court around the tabernacle, their sockets, pegs, and their ropes, with all their hardware. List by name the articles they must carry.

The UDB of NUM 3:36-37 read (without changes):  
\v 36 The work of the men of those two clans was to take care of the **frames** that held up the tent, the crossbars, the pillars, and the bases. They also did all the work that was connected with those items.
\v 37 Their work was also to take care of the posts that held up the curtains that formed the walls of the courtyard, and all the bases, tent pegs, and ropes that fastened those curtains.

The UDB of NUM 4:31-32 reads (without changes):
\v 31 Their work will be to carry the **frames** that hold up the sacred tent, the crossbars, the posts that hold up the curtains, and the bases.
\v 32 They must also carry the posts for the curtains that form the walls of the courtyard and the bases for the posts, the tent pegs, and the ropes to fasten the curtains. Tell each man what things he must carry.
