### ISSUE TITLE
MRK 4:8

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#265]
The field noticed this wrong word in Mark 4:8
Other seed **_feel_** into good soil and it produced grain while growing up and increasing

And thought that this would be better. ;)
Other seed **_fell_** into good soil and it produced grain while growing up and increasing

**Comment by TomWarren** [comment]
Thanks, the ULB of MRK 4:8 now reads: 
\v 8 Other seed fell into good soil and it produced grain while growing up and increasing, and some brought forth thirty times as much, and some sixty, and some a hundred."
