### ISSUE TITLE
NUM 16:5 bring up

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#268]
ULB He will **bring up** to himself the man he chooses. Yahweh will **bring him up** to himself.

ULB seems to introduce a metaphor , where going **near** to God is spoken of as going **up** to God. Could the word "up" be deleted?

**Comment by TomWarren** [comment]
The ULB NUM 16:5 now reads:
\v 5 He spoke to Korah and to all those with him, "In the morning Yahweh will make known who belongs to him and who is dedicated to him. He will bring that person near to him. The one he chooses he will bring near to himself. 

This is close to the Heb source. TW

**Comment by SusanQuigley** [comment]
That's great. Thank you.
