### ISSUE TITLE
Num 16:3, 7 Two English metaphors for one Hebrew idiom

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#269]
16:3 ULB You take too much on yourselves
16:7 ULB You have gone too far

Could these be translated the same way? Moses accuses Korah and friends of the same thing that they accused Moses and Aaron of -- presuming to take on more authority than they should.

Maybe something like "you do too much." That way it doesn't introduce the English metaphors, "take on' or "go too far."

**Comment by TomWarren** [comment]
"You have gone too far" in 16:3 and 16:7 now.
TW

**Comment by SusanQuigley** [comment]
Thank you

**Comment by TomWarren** [comment]
I did change some phrase about "dedicated" to "set apart" and leaving out "holy" which is not implied.

**Comment by SusanQuigley** [comment]
OK. Thanks. I'll check the notes.

**Comment by SusanQuigley** [comment]
NUM 16:7
UDB Yahweh has chosen to be his holy servant
You wrote above that "holy" is not implied. Would you want to remove it from the UDB?

**Comment by TomWarren** [comment]
No, the UDB can stand. The root in Heb is the word from which "holy" is derived, so there is no harm in having it in the UDB. 
Thanks,

**Comment by SusanQuigley** [comment]
Ok. Thanks.
