### ISSUE TITLE
Neh 9:5-6

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#27]
\v 5 Then the Levites, Jeshua, and Kadmiel, Bani, Hashabneiah, Sherebiah, Hodiah, Shebaniah, and Pethahiah said, "**Stand up and give praise to Yahweh** your God forever and ever. **May they bless** your glorious name, and may it be exalted above every blessing and praise.
\v 6 **You are Yahweh**. You alone. You have made heaven, the highest  heavens, with all their angels arrayed for war, and the earth and everything on it, and the seas and all that is in them. You give life to them all, and the angel armies of heaven  worship you.

This long quotation that extends beyond the chunk seems awkward to me. It begins with a short statement to the Israelites to "Stand up and give praise..." But then it continues on in an address to Yahweh, with no indication of a break. It seems like the first exhortation to the people should close, and that a second prayer to Yahweh should start with fresh quotes.

**Comment by TomWarren** [comment]
Separated with closed quotes the call to prayer (verse 5)  and the prayer itself (that begins at verse 6)
Here is the revised text:
\v 5 Then the Levites, Jeshua, and Kadmiel, Bani, Hashabneiah, Sherebiah, Hodiah, Shebaniah, and Pethahiah said, "Stand up and give praise to Yahweh your God forever and ever. May they bless your glorious name, and may it be exalted above every blessing and praise."
\v 6 "You are Yahweh. You alone. You have made heaven, the highest  heavens, with all their angels arrayed for war, and the earth and everything on it, and the seas and all that is in them. You give life to them all, and the angel armies of heaven  worship you.

\s5
\v 7 You are Yahweh, the God who chose Abram, and brought him out of Ur of the Chaldees, and gave him the name Abraham.

**Comment by lrsallee** [comment]
Tom,

Could you take a second look at this? It seems to me that the audience switch occurs in the middle of verse 5, with “May they bless…

Would this be better divided as:


\v 5 Then the Levites, Jeshua, and Kadmiel, Bani, Hashabneiah, Sherebiah, Hodiah, Shebaniah, and Pethahiah said, "Stand up and give praise to Yahweh your God forever and ever." "May they bless your glorious name, and may it be exalted above every blessing and praise.
\v 6 You are Yahweh. You alone. You have made heaven, the highest heavens, with all their angels arrayed for war, and the earth and everything on it, and the seas and all that is in them. You give life to them all, and the angel armies of heaven worship you.

\s5
\v 7 You are Yahweh, the God who chose Abram, and brought him out of Ur of the Chaldees, and gave him the name Abraham.

Larry

**Comment by TomWarren** [comment]
Ah.  See it now.

Thanks.  Will change it.

Tom

**Comment by lrsallee** [comment]
Appreciate it.
