### ISSUE TITLE
NUM 16:16 ULB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#270]
ULB: Tomorrow you and all your company must go before Yahweh, you, they, and Aaron.

 There should probably be some other form of punctuation after Yahweh - a colon or dash, perhaps?

**Comment by TomWarren** [comment]
The ULB of NUM 16:16 now reads: 
\v 16 Then Moses said to Korah, "Tomorrow you and all your company must go before Yahweh— you, they, and Aaron.

**Comment by SusanQuigley** [comment]
Thank you. It looks like there is no space before the dash and a space after the dash. I expect it should probably be the same on both sides.

**Comment by TomWarren** [comment]
Quite right. It was at a word-wrap. 
Thanks. 
TW
