### ISSUE TITLE
\p markers not displaying as expected

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#271]
There is a \p marker before verse 5 of Joel 1 ULB. As you can see from the pic the paragraph is not rendered. Could it be because there is no \m to 'bring the margin back to left aligned?' 
Or is it a conflict of interest/priority with having a \p and \q next to each other?

This is happening throughout Joel and other poetic books. (specifics can be provided)
![paragraph error](https://cloud.githubusercontent.com/assets/9850185/19078605/c19b7e66-8a1e-11e6-905d-79c79ecbfe91.png)

**Comment by jag3773** [comment]
Seen on bible.unfoldingword.org.

**Comment by jag3773** [comment]
@pohlig Is going to test this in paratext.

**Comment by lrsallee** [comment]
I believe \q overwrites \p. From my browsing of the USFM sheet, it looks like we should use \b to insert spaces to separate paragraphs, rather than \p.
