### ISSUE TITLE
odd icon on uW site

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#272]
Hosea 1:1 ULB has an icon - pop-up and "we" do not know why?

Here is what the USFM is in GitHub - 
\s5
\c 1
\p
\v 1 This is the word of Yahweh that came to Hosea son of Beeri in the days of Uzziah, Jotham, Ahaz and Hezekiah, kings of Judah, and in the days of 

![pop up window](https://cloud.githubusercontent.com/assets/9850185/19079062/4c72237c-8a20-11e6-9293-1d61ae2fac60.png)

This happens twice in Hosea (chap 1 and 12) and scattered in OT

**Comment by jag3773** [comment]
Seen on bible.unfoldingword.org.
