### ISSUE TITLE
Numbers 16:37 ULB "they" to "he"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#273]
ULB:  Speak to Eleazar ... and tell him to take the censers ... Then **they** must scatter the embers. 

I think "they" should be "he." The Hebrew text in BART (Numbers 17:2) has a masculine singular subject for "scatter."

**Comment by TomWarren** [comment]
Yep. The ULB of NUM 16:37 now reads: 
\v 37 "Speak to Eleazar son of Aaron the priest and let him take up the censers out of the flames, for the censers are set apart to me. Then let him scatter the burning coals at a distance.
