### ISSUE TITLE
Num 17:2 ULB Delete "chosen"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#275]
ULB one from each leader **chosen** from each tribe.

I don't see "chosen" in other versions or the Hebrew. 
I don't want to have a note dealing with passive form and have to tell who chose the leaders.
Could "chosen" be deleted from the ULB?

This also comes up in 17:6 with 
one staff from each leader, selected from each of the ancestral tribes

Is chosen/selected implied information made explicit in the ULB?

**Comment by TomWarren** [comment]
Try this. The ULB of NUM 17:2 now reads; 
\v 2 "Speak to the people of Israel and get staffs from them, one for each ancestral tribe, twelve staffs. Write each man's name on his staff.

**Comment by SusanQuigley** [comment]
Thank you. I don't need a note for that now.
