### ISSUE TITLE
Num 17:9 ULB  "rod" to "staff"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#276]
Moses brought out all the **staffs** from before Yahweh to all the people of Israel. Each man found his **rod** and took it.

The ULB has been using the word "staff" in this chapter. Could "rod" be changed to "staff"? (It's the same Hebrew word for both sentences.)

**Comment by TomWarren** [comment]
ULB NUM 17:9 now reads: 
\v 9 Moses brought out all the staffs from before Yahweh to all the people of Israel, and each man took his staff.
