### ISSUE TITLE
Num 18:8 ULB  "the" needed

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#277]
NUM 18:8 ULB the holy offerings that * people of Israel give to me.

These needs the word "the" where I put the asterisk.

**Comment by TomWarren** [comment]
ULB NUM 18:8 now reads: 
\v 8 Then Yahweh said to Aaron, "Look, I have given you the duty of handling the offerings raised up to me, and all the holy offerings that **the** people of Israel give to me. I have given these offerings to you and your sons as your ongoing share.
