### ISSUE TITLE
NUM 18:10 ULB vs UDB  "holy offerings" vs "sacred place"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#279]
ULB: These offerings are very holy; every male must eat it, for they are holy to you.
UDB: You must eat those offerings in a sacred place, near the sacred tent. You and all of the other males in your clan may eat it, but you must consider those offerings to be holy to me.

It looks like UDB and ULB come from different interpretations of haqqodashim at the beginning of the verse. ULB doesn't say anything about a sacred place. UDB expands on sacred place by explaining that it refers to the sacred tent.

**Comment by TomWarren** [comment]
The UDB has been changed to Read: NUM 18:10
\v 10 You are to eat it as a most holy offering. Every male in your clan may eat it. But you must have respect for those offerings because they are holy to you.

**Comment by SusanQuigley** [comment]
Thanks for fixing this.
