### ISSUE TITLE
Lev 14:8 ULB

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#28]
"The person who is to being cleansed"

This needs to be changed to one of the following:

- The person who is being cleansed
- The person who is to be cleansed

**Comment by TomWarren** [comment]
Changed to:
\v 8 The person who is being cleansed will wash his clothes, shave off all his hair, and bathe himself in water,  and then he will be clean. After that he must come into the camp, but he will live outside his tent for seven days.
