### ISSUE TITLE
NUM 18:19 ULB  Comma needed?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#280]
ULB: I have given them to you, to your sons* and to your daughters, as an ongoing share.

Should there be a comma after the word "sons"? The suffixes for "you" and "your" are singular.

**Comment by TomWarren** [comment]
The ULB of NUM 18:19 now reads: 
\v 19 All the holy offerings that the people of Israel present to Yahweh, I have given to you, and to your sons and to your daughters with you, as a continual share. It is an everlasting covenant of salt, a binding covenant forever, before Yahweh for both you and your descendants with you."
\v 20 Yahweh said to Aaron, "You will have no inheritance in the people's land, nor will you have any share of property among the people. I am your share and inheritance among the people of Israel.

This is a case where the which is plural (people of Israel, considered as a whole) but the pronoun is singular,(you, your, masc sing), This is a common issue in the way Heb handles classes/ groups as though they were an individual. The sing is used but in Heb it has a plural referent .  All through this section the singular (you, your) refers to the plural noun (the children of Israel).

**Comment by SusanQuigley** [comment]
Thank you. That's clearer.
