### ISSUE TITLE
NUM 7:37+ mingled vs mixed

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#282]
"His sacrifice was one silver platter weighing 130 shekels and one silver bowl weighing seventy shekels, by the standard weight of the sanctuary shekel. Both of these objects were full of fine flour mingled with oil for a grain offering"

The above verse is repeated about 12 times. In the previous 4 cases the same Hebrew word is translated as "mixed," but in vs. 37, 49, 55, 60, 66, 72, and 78 it's translated as "mingled." 

Since the passages are the same, it may be good to use the same wording.

**Comment by TomWarren** [comment]
Mixed replaced mingled. in NUM 7. (a simpler word than mingled).
