### ISSUE TITLE
MAT 5:44 and other verses don't have a \ft tag in their footnote

### ISSUE THREAD

**Issue by richmahn** [Door43/ulb-en#283]
Some books don't have a \ft after the \f + for the 'f'ootnote 't'ext:

41-MAT.usfm: \f + The best ancient copies omit \fqa "Bless those who curse you, do good to those who hate you."\f*
41-MAT.usfm: \f + The best ancient copies omit \fqa "For yours is the kingdom and the power and the glory forever. Amen"\f*
41-MAT.usfm: \v 21 \f + The best ancient copies omit v. 21. \fqa But this kind of demon does not go out except with prayer and fasting."\f*
41-MAT.usfm: \v 11 \f + The best ancient copies omit the phrase that appears as v. 11. \fqa For the Son of Man came to save that which was lost.\f*
41-MAT.usfm: \f + The best ancient copies omit \fqa "Many are called, but few are chosen." \f*
48-2CO.usfm: \f + Some translations combine verse 13 with verse 12 and number verse 14 as verse 13.\f*

**Comment by TomWarren** [comment]
Fixed MAT 5:44
\f + \ft The best ancient copies omit \fqa "Bless those who curse you, do good to those who hate you."\f*
Mat 6:13: 
\f + \ft The best ancient copies omit \fqa "For yours is the kingdom and the power and the glory forever. Amen"\f*
MAT 17:21 
\v 21 \f + \ft The best ancient copies omit v. 21. \fqa But this kind of demon does not go out except with prayer and fasting."\f*
MAT 18:11
\v 11 \f + \ft The best ancient copies omit the phrase that appears as v. 11. \fqa For the Son of Man came to save that which was lost.\f*
MAT 20:16
\f + \ft The best ancient copies omit \fqa "Many are called, but few are chosen." \f*
2CO 13:13
\f + \ft Some translations combine verse 13 with verse 12 and number verse 14 as verse 13.\f*
