### ISSUE TITLE
Num 18:28-29 ULB presented offering

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#286]
The noun phrase "presented offering" is used in the ULB only six times -  in Num 18:24, 26, 27, 28 (twice) and 29.
It sounds like a technical term, but we don't have a tW page for it and I don't know what it means. 
I wonder if it is translated some other way elsewhere in the ULB.

**Comment by TomWarren** [comment]
Contribution is the way it is translated in almost every other place. 
I have changed "presented offering" to "contribution" and adjusted the contexts. 
Thanks.

**Comment by SusanQuigley** [comment]
Great. Thank you.
