### ISSUE TITLE
NUM 18:30 ULB "by the Levites" to "to the Levites"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#287]
ULB: then **it must be considered by the Levites like** the produce from the threshing floor and the winepress. 
UDB:  **I will consider that those gifts  are as though** they came from your own grain and wine

The UDB fits with other versions. Could ULB be changed to something like this to fit with them?
then **it will be reckoned to the Levites as** the produce from the threshing floor and the winepress. 
or
then then **it will be counted to the Levites as** the produce from the threshing floor and the winepress.

**Comment by TomWarren** [comment]
ULB NUM 18:30 now reads: 
\v 30 Therefore you must say to them, 'When you present the best of it, then it must be credited to the Levites as the product from the threshing floor and the winepress.
