### ISSUE TITLE
Lev 23:1-2 ULB  Missing the word "these"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#288]
The appointed festivals for Yahweh, which you must proclaim as holy assemblies, *  are my regular festivals.

Is the word "these" missing? It's in the Hebrew, and what follows is a description of the feasts and what they must do. So it sounds like this sentence is meant to introduce them. So could the word "this" be added where I put the asterisk?

**Comment by TomWarren** [comment]
The ULB for LEV 23:2 now reads: 
\v 2 "Speak to the people of Israel, and say to them, 'These are the appointed festivals for Yahweh, which you must proclaim as holy assemblies, are my regular festivals.

**Comment by SusanQuigley** [comment]
**These are** the appointed festivals for Yahweh, which you must proclaim as holy assemblies, **are my regular festivals**.

This doesn't work with "are" twice. Maybe one of these will work.
These are the appointed festivals for Yahweh, which you must proclaim as holy assemblies. **They** are my regular festivals.
or 
**These appointed festivals for Yahweh**, which you must proclaim as holy assemblies, are my regular festivals.

**Comment by TomWarren** [comment]
Left out a bit:
\v 2 "Speak to the people of Israel, and say to them, 'These are the appointed festivals for Yahweh, which you must proclaim as holy assemblies; they are my regular festivals.

**Comment by SusanQuigley** [comment]
Thank you.
