### ISSUE TITLE
NUM 18:24 ULB Extra "it"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#289]
ULB For the tithes of the people of Israel, which they offer **it** as a contribution to me

The word "it" can be deleted. 

Thanks for changing "presented offering" to "contribution." I've gone back to the chunk to remove the note for "presented offering" and I saw this unnecessary "it"  in the ULB.

**Comment by TomWarren** [comment]
YEP. 
The ULB of NUM 18:24 now reads: 
\v 24 For the tithes of the people of Israel, which they offer as a contribution to me—it is these that I have given to the Levites as their inheritance. That is why I said to them, 'They must have no inheritance among the people of Israel.'"
