### ISSUE TITLE
Sng 2:7 and 5:8 ULB

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#29]
"Daughters of Jerusalem, swear to me..." 

Our TN sends MTT's back from 5:8 to 2:7 to compare the translation. However, the ULB now treats this similar phrase very differently. Do you want to make the text consistent, or should we remove the TN?

**Comment by TomWarren** [comment]
"I want you to promise, daughters of Jerusalem,"  appears to be a clearer rendering of both 2:7 and 5:8.
The TN have been amended, and the reference in 5:8 rightly reflects 2:7, since the Heb is the same in each.
Thanks.
