### ISSUE TITLE
Lev 23:27 ULB  Change comma to semicolon?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#290]
ULB It must be an assembly that is set apart to Yahweh**,** you must humble yourselves and present an offering to Yahweh by fire.

Could the comma after "Yahweh" be changed to a semicolon or period?

**Comment by TomWarren** [comment]
ULB LEV 23:27 now reads:
\v 27 "Now the tenth day of this seventh month is the Day of Atonement. It is to  be a holy assembly, and you must humble yourselves and present to Yahweh an offering by fire.

There was an addition that was confusing. This now is closer to the Heb text. Thanks.
