### ISSUE TITLE
Lev 23:32 ULB Missing "must"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#291]
ULB This day must be to you a Sabbath of solemn rest, and you * humble yourselves the ninth day of the month. 

It looks like this needs the word "must" before  "humble yourselves"

**Comment by TomWarren** [comment]
There were three "evenings" in this section. The former ULB left one out. 
ULB LEV 23:32 now reads: 
\v 32 This day must be to you a Sabbath of solemn rest, and you must humble yourselves the ninth day of the month at the evening. From evening to evening you are to observe your Sabbath."

**Comment by SusanQuigley** [comment]
Thank you.
