### ISSUE TITLE
Lev 25:31 ULB round around

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#294]
ULB: But the houses of the villages that have no wall **round around** them 

Please delete "round."

**Comment by TomWarren** [comment]
The ULB of LEV 25:31 now reads: 
\v 31 But the houses of the villages that have no wall around them will be considered as the field of the land. They may be redeemed, and they must be returned during the jubilee.

TW

**Comment by SusanQuigley** [comment]
Thank you.
