### ISSUE TITLE
Lev 26:23 "teaching" to "discipline"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#295]
ULB: If in a all this you still do not accept my **teaching**

The word "teaching" seems week. It could imply any of God's teaching. But here it refers to his discipline because they were sinning. Could it be changed to something like this?

If in all this you still do not accept my **discipline**

**Comment by TomWarren** [comment]
ULB LEV 26:23-24  now reads:
\v 23 If in spite of these things you still do not accept my correction and you continue to walk in opposition to me, 
\v 24 and because of this I will also walk in opposition to you, and I myself will punish you seven times because of your sins.

**Comment by SusanQuigley** [comment]
Thank you.
