### ISSUE TITLE
Lev 26:36 ULB Paragraph break needed

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#296]
ULB Lev 26:36
As for those of you who are left in your enemies' lands,

I think this needs a paragraph break before v. 36.  (he verses before this talk about the land of Israel being abandoned and having a Sabbath rest. Verse 36 goes on to talk about those who go into exile.

**Comment by TomWarren** [comment]
The Section now has a paragraph break, that shows up in the WIKI.
Thanks,
TW
