### ISSUE TITLE
NUM 30:10 confusing

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#297]
"And if a woman in her husband's family makes a vow—if she binds herself by a promise with an oath,"

This wording is confusing. It leads me to think it is refers to another woman in the woman's husband's family, even though this is not the case.

**Comment by TomWarren** [comment]
ULB of NUM 30:10-11 now read:
\v 10 And if a woman made a vow in her husband's house or obligates herself by taking an oath,
\v 11 and her husband hears of it but he says nothing to her and he does oppose her, then all her vows must stand and the obligations she made must remain in force.
