### ISSUE TITLE
LEV 21:3

### ISSUE THREAD

**Issue by drew-curley** [Door43/ulb-en#298]
The phrase "in his house" seems to imply that the pronoun references the brother instead of the father. The context appears to favor the latter. Additionally, the phrase "for her he" could use a comma for clarity "For her, he".

**Comment by TomWarren** [comment]
THE ULB of LEV 21:2-3 now reads: 
\v 2 except for his closest relatives—his mother, his father, his son, his daughter, his brother, 
\v 3 or his virgin sister who has no husband—he may make himself unclean for her.
