### ISSUE TITLE
Num 15:2-3 Change period to em-dash?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#299]
ULB: When you go into the land where you will live, which Yahweh will give to you— **3**and you are to prepare an offering by fire to him, either a burnt offering, or a sacrifice for a vow or a freewill offering, or an offering at your feasts, to produce a sweet aroma for Yahweh from the herd or the flock.
**4** Then the one bringing the sacrifice must offer to Yahweh a grain offering of a tenth of an ephah of fine flour mixed with one-fourth of a hin of oil. 

The sentence starting with "When" does not finish until the end of verse four. Could you change the period at the end of verse 3 to an em-dash, and change verse 4 "Then" to "then"?

**Comment by TomWarren** [comment]
There was some reworking on these verses. Here is how ULB NUM 15:1-5 now reads:  

 \v 1 Then Yahweh spoke to Moses. He said,
\v 2 "Speak to the people of Israel and say to them, 'When you go into the land where you will live, which Yahweh will give to you,
\v 3 you are to prepare an offering by fire to him, either a burnt offering, or a sacrifice for a vow, or a freewill offering, or an offering at your feasts, to produce a sweet aroma for Yahweh from the herd or the flock.
 
\s5
\v 4 You are to prepare a sacrifice and offer to Yahweh a grain offering of a tenth of an ephah of fine flour mixed with one-fourth of a hin of oil.
\v 5 You must also offer with the burnt offering, or for the sacrifice, one-fourth of a hin of wine for the drink offering for each lamb.

**Comment by SusanQuigley** [comment]
The revision above does not make it clear that the grain offering was to accompany the "offering by fire". Could it be made it clear in verse 4?

4. When you present one of these offerings, you must also offer to Yahweh a grain offering of ...

**Comment by TomWarren** [comment]
I reworked the comments. Hope that is clear. 
TW

**Comment by SusanQuigley** [comment]
Ok. I think I understand. 
4. You must offer to Yahweh a burnt offering as well as a grain offering
The phrase "a burnt offering" in verse 4 refers to the offerings in verse 3.
