### ISSUE TITLE
ACT 1.3 Missing Phrase in ACT 1.3 Issue #1 from uW/ulb-en

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#3]
"After his suffering he presented himself alive to them by many convincing proofs, appearing to them during forty days and speaking about the kingdom of God." --NRSV89
 "the ones to whom he appeared alive after his suffering. For forty days he kept appearing to them, saying things about the kingdom of God." ULB

The phrase by many convincing proofs is missing in ULB

----------

TomWarren  commented 24 days ago  

The phrase "with (or by) many convincing proofs" was added. 
 \v 3 After his suffering, he presented himself alive to them with many convincing proofs. For forty days he appeared to them, and he spoke about the kingdom of God.
 Thank you for showing us this. Really appreciated.

**Comment by TomWarren** [comment]
This was corrected about two weeks ago, on the rec of someone from India 
in Github. I made the corrections, as it is here:

\v 3After his suffering, he presented himself alive to them with many 
convincing proofs. Forforty daysheappearedtothem,and he spoke aboutthe 
kingdom of God.
