### ISSUE TITLE
Zec 3:7 ULB

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#30]
Kara's ELL check caught the use of "adjudicate" in this verse. That term is a bit complex for non-native speakers. Can it be changed to "judge" or "act as judge" or "be a judge" something simpler?

**Comment by TomWarren** [comment]
Looked at Zec 3:7. Changed to:
\q 'If you will walk in my ways, and if you will keep my commandments, 
\q then you will govern my house and guard my courts,  
\q for I will allow you to go and come among these who stand before me.
