### ISSUE TITLE
LEV 21:20

### ISSUE THREAD

**Issue by drew-curley** [Door43/ulb-en#300]
I believe the word "dwarfed" in the phrase "a dwarfed man" should be in the form "dwarf". I think dwarfed is the past participle of the verb and not the adjectival form of the noun dwarf (e.g. a dwarf star, a dwarf giant, a dwarf hamster).

**Comment by pohlig** [comment]
I guess you're right. I checked. I changed the ULB to "no hunchback or
dwarf." The UDB already uses "dwarf."
Jim

**Comment by TomWarren** [comment]
J.R.R. Tolkien had an objection to dwarves (pl of dwarf), and called them dwarfs according to his own rules. 
TW

**Comment by SusanQuigley** [comment]
It would probably be good to avoid the English nouns "dwarf" and "hunchback."  At best we can  call them dated, but some would find them offensive (and some might even find them misleading, bringing up images of beings that are not quite human).

Any man who has a bodily defect must not approach Yahweh, such as a blind man, a lame man, one who is disfigured or deformed, 19a man with a crippled hand or foot, 20 **a man who has a hunchback or is abnormally short**, or a man with a defect in his eyes, or with a disease, sore,

**Comment by drew-curley** [comment]
The same could be said about hunchback

**Comment by SusanQuigley** [comment]
Exactly. For describing the condition a person has, I think it's ok. But not for referring to the person himself. That's why I suggested "a man who has a hunchback". But this would probably be clearer:  "a man who has a hump on his back"

**Comment by TomWarren** [comment]
I think the text has several separate conditions in view, not conflating them into one individual, "one who has a hump, one who is abnormally think, one who has a diseased eye, etc ...

**Comment by TomWarren** [comment]
Here is a go at it. The ULB for LEV 21:18-21 now reads: 
\v 18 Any man who has a bodily defect must not approach Yahweh, such as one who is blind or one who is unable to walk, or one who is disfigured or deformed,
\v 19 or one with a crippled hand or foot,
\v 20 or one who has a hump in his back or is abnormally thin or short, or one who has a defect in his eyes, or has a disease, a sore or scabs, or a man whose testicles have been crushed.
\v 21 No man among the descendants of Aaron the priest with a bodily defect may come near to perform the offerings made by fire for Yahweh. Such a man has a bodily defect and he must not come near to offer the bread of his God.

There it is. TW

**Comment by SusanQuigley** [comment]
Looks good to me.

**Comment by TomWarren** [comment]
The UDB of LEV 21:20 now reads:
\v 20 no man who is a hunchback or an abnormally short person, no man whose eyes are defective, no man who has a skin disease or whose private parts have been damaged.
