### ISSUE TITLE
Lev 27:15 ULB  Delete "and"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#301]
But if the owner who set apart his home **and** later wishes to redeem it, he must add a fifth of its value to its redemption price, and it will belong to him.

The word "and" after "who set apart his home" does not fit in the sentence.

**Comment by TomWarren** [comment]
The ULB of LEV 27:15 now reads:
\v 15 But if the owner who set apart his home wishes to redeem it, he must add a fifth of its value to its redemption price, and it will belong to him.

**Comment by SusanQuigley** [comment]
Thank you.
