### ISSUE TITLE
Lev 27:28 ULB "sets apart" to "permanently sets apart"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#302]
ULB: However, nothing a man **sets apart** from anything he has, whether human or animal, or his family land, may be sold or redeemed. Everything that is devoted is holy to Yahweh.

This seemed to contract what was taught in the previous  verses until I learned that this "sets apart" referred to permanently setting something apart. The earlier verses used the verb _qadash_.
This uses the noun _herem_ and and the verb _harim_. 

So, could "sets apart" be changed to "permanently sets apart" or "permanently devotes"?

**Comment by TomWarren** [comment]
The ULB of LEV 27:28 now reads: 
\v 28 But nothing that a man devotes to Yahweh, from all that he has, whether human or animal, or his family land, may be sold or redeemed. Everything that is devoted is very holy to Yahweh.

There חֵרֶם harem, devoted to (and one of the meanings is "devote to destruction" but here "devoted to"); and then קֹדֶשׁ holy.

**Comment by SusanQuigley** [comment]
Thank you.
