### ISSUE TITLE
Lev 27:32 one tenth

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#303]
32 As for all the tithe of the herd or the flock, whatever passes under the shepherd's rod, **one tenth** must be set apart to Yahweh.

The phrase "one tenth" in the ULB gives the impression that it could be any tenth of all the flock (as in 10% in general). But most versions translate it as "every tenth animal"  meaning that they would keep counting off 1-10  and mark every 10th animal as belonging to the Lord. (They were not to exchange any animals for any of the tenth animals counted.)

Could it be changed to "every tenth" or "every tenth animal"?

**Comment by TomWarren** [comment]
The ULB now reads: 
\v 32 And as for all the tithe of the herd or the flock, whatever passes under the shepherd's rod, every tenth animal must be set apart to Yahweh. 
Thanks.
