### ISSUE TITLE
JDG 18:19 vs 17:10

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#305]
...Put your hand on your mouth and come with us, and be to us a father and priest....

The phrase above "father and priest"  spoken by the Danites in 18:19 repeats what Micah asked the Levite to be in 17:10. The word for "father" can be translated adviser or father, but either way it needs to be consistent in these two places as they are a real parallel.

**Comment by TomWarren** [comment]
ULB JDG 17:10 now reads:
\v 10 Micah said to him, "Stay with me, and be to me a father and a priest. I will give you ten pieces of silver a year, a suit of clothes, and your food." So the Levite went into his house.
ULB JDG 18:19 now reads: 
\v 19 They said to him, "Be quiet! Put your hand on your mouth and come with us, and be to us a father and a priest. Is it better for you to be priest for the house of one man, or to be priest for a tribe and a clan in Israel?"
