### ISSUE TITLE
Jos 9:4 "wine skins" to "wineskins"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#310]
ULB:  They also took old **wine skins** 

In the rest of the ULB OT and NT, "wineskins" is one word.

**Comment by TomWarren** [comment]
Did a check with search, and found this is the only one "wine skins".
\v 4 they acted with a cunning plan. They went as messengers. They took worn-out sacks and put them on their donkeys. They also took old wineskins that were worn, torn, and had been repaired.
