### ISSUE TITLE
1SA 27:8  Quotes in footnote

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#313]
1SA 27:8  Quotes in footnote
[1] Instead of "_the Girzites_, found in the Hebrew text, some modern versions have _the Gizrites_, which is found in the margin of the Hebrew text.

Either the _Girzites_ and the _Gizrites_ should both have quote marks around them, or neither of them should.

**Comment by TomWarren** [comment]
The quotes should make it clear what is being addressed. So the FN at 1SA 27:8 now reads:
\f + \ft \fq Instead of "the Girzites," \fqb found in the Hebrew text, some modern versions have \fqa "the Gizrites," \fqb which is found in the margin of the Hebrew text. \f*

**Comment by SusanQuigley** [comment]
Thank you.
