### ISSUE TITLE
2 SA 14:14 mismatch?

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#314]
Hey, it doesn't seem like the ULB and UDB jive too well on this verse. 

ULB v14b
But God does not take away life; instead, he finds a way to bring back one whom he has driven away from himself.

UDB v14b
Even God does not cause people who have died to become alive again. So Amnon cannot become alive again. But God creates ways for those who have been exiled to be able to return to their homes.

ULB has God not taking away life, while the UDB has God not causing the dead to come back.

**Comment by TomWarren** [comment]
Thanks for the good work. Hope this is closer between the two.
The ULB of 2SA 14:14 now reads: 
\v 14 For we all must die, and we are like water spilled on the ground, which cannot be gathered up again. But God will not take away life; instead, he finds a way for those who were driven away to be restored. 

The UDB of 2SA 14:14 now reads: 
\v 14 All of us will die. We are like water that cannot be picked up after it is spilled on the ground. God does not take life away, but instead, God creates ways for those who have been exiled to return and be restored to their people and to their homes.
