### ISSUE TITLE
JOS 6:25 ULB "lived" to "lives"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#315]
JOS 6:25 ULB She **lived** in Israel to this day

Hebrew, the UDB, and other translation have this in the present tense. The past tense in the ULB is odd because it leads to either wondering what "this day" is, or to thinking that "this day" Rahab (or her descendants) must have stopped living in Israel. (UBS-TH, TEV, and UDB treat "Rahab" as a metonym for Rahab's descendants.)

Could the ULB have "lives" instead of "lived"?

**Comment by TomWarren** [comment]
ULB JOS 6:25 now reads: 
\v 25 But Joshua allowed Rahab the prostitute, her father's household, and all that were with her to live. She **lives** in Israel to this day because she hid the men whom Joshua sent to spy on Jericho.

**Comment by SusanQuigley** [comment]
Thank you!
