### ISSUE TITLE
MAT 21:15 ULB delete 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#316]
MAT 21: 15 ULB But when the chief priests and the scribes saw the marvelous things that he did, and when they heard the children shouting in the temple and saying, "Hosanna to the son of David," **and** they became very angry. 

Please delete "and" before "they became very angry."

**Comment by TomWarren** [comment]
The ULB of MAT 21:15 now reads:
\v 15 But when the chief priests and the scribes saw the marvelous things that he did, and when they heard the children shouting in the temple and saying, "Hosanna to the son of David," they became very angry.
