### ISSUE TITLE
Jos 7:8 ULB ! or ?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#318]
ULB Lord, what can I say, after Israel has turned their backs before their enemies! 

This really sounds like a rhetorical question. Could it have "?" instead of "!"?

**Comment by TomWarren** [comment]
It seems like a rhetorical question to me as well. The exclamation point is overused in the ULB. I removed about 500 of the little guys from Ezekiel. 
ULB of JOS 7:8 now reads: 
\v 8 Lord, what can I say, after Israel has turned their backs before their enemies?

**Comment by SusanQuigley** [comment]
Thank you  :)
