### ISSUE TITLE
Jos 7:14 The tribe that Yahweh selects by lot

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#319]
ULB The tribe that Yahweh selects **by lot**

"By lot" is not in the Hebrew. Would it be better to have this in the UDB instead of in the ULB?

**Comment by TomWarren** [comment]
The ULB of JOS 7:14 now reads: 
\v 14 In the morning, you must present yourselves by your tribes. The tribe that Yahweh selects will come near by their clans. The clan that Yahweh selects must come near by each household. The household that Yahweh selects must come near one by one.

**Comment by SusanQuigley** [comment]
Thank you moving "by lot" to the UDB, and for changing "takes" to "selects."
In JOS 7:15 could "the one who is "caught" be changed to "the one who is selected."
It's the same Hebrew word, and presumably it refers to the same kind of event.

**Comment by TomWarren** [comment]
The ULB of JOS 7:15 now reads:
 \v 15 It will happen that the one who is selected and who has the things that were set apart for destruction, he will be burned, he and all he has, because he has broken the covenant of Yahweh and because he has done a disgraceful thing in Israel.'"

**Comment by TomWarren** [comment]
Thanks. 
I am trying to be more broad in my review (looking before and after to establish context and continuity), but the time it takes works against my best intentions. Appreciate your help.

**Comment by SusanQuigley** [comment]
:)
