### ISSUE TITLE
ISA 11:1 ULB "root" to "stump"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#320]
ULB A shoot will sprout from the **root** of Jesse,
a branch out of his root will bear fruit

Could the word "root" in the first clause be changed to "stump"?
Hebrew has _geza_ 'stump' in the first clause and _shoresh_ 'root' in the second.

What's nice about the word "**stump**" is that people can infer that the tree had been cut down.

**Comment by TomWarren** [comment]
Yes. 
ULB ISA 11:1 now reads: 
\v 1 A shoot will sprout from the stump of Jesse, and a branch out of his root will bear fruit.
Good work.

**Comment by SusanQuigley** [comment]
Thank you!
