### ISSUE TITLE
ISA 13:8  ULB sorrows?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#322]
ULB  **pangs and sorrows will seize them**

The ULB word "sorrows" sounds like something emotional. The Hebrew word is _khebel_. Other translations use words that indicate terrible physical pain. Could 'sorrows' be changed to something like "anguish," "agony," or "writhing"?

**Comment by TomWarren** [comment]
The ULB of ISA 13:8 now reads:
\v 8 They will be terrified; pain and agony will seize them, like a woman in labor.
