### ISSUE TITLE
ISA 22:16

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#325]
ULB 'What do you have here, and who are you, that you have hewn out a grave?
Hewing out a grave on the heights, carving out a resting place for yourself in the rock!'" 

The way this is punctuated, I don't think "Hewing out ... in the rock!" is a complete sentence.

**Comment by TomWarren** [comment]
The ULB of USA 22:15-16 now reads: 
\v 15 The Lord, Yahweh of hosts, says this, "Go to this administrator, to Shebna, who is over the house, and say,
\q1
\v 16 'What are you doing here and who gave you permission to cut out a tomb for yourself,
\q1 hewing out a grave on the heights and carving out a resting place in the rock?'"
