### ISSUE TITLE
ISA 24:20

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#328]
ULB will sway to and fro like a hammock

UDB it will shake like a hammock in a windstorm

Here "hammock" is the same Hebrew word used in Isa 1:8. There the ULB translates it as "shed" which seems to be the typical way of translating it. I suggest changing "hammock" to "shed" or "hut" or "tent" or some kind of temporary dwelling place.

**Comment by TomWarren** [comment]
The ULB now reads: 
\v 20 The earth will stagger like a drunken man and it will sway back and forth like a hut.
\q1 Its sin will be heavy on it and it will fall and never rise again.

Thanks very much.
