### ISSUE TITLE
ISA 25:4-5

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#329]
ULB when the blast of the ruthless is like a storm against a wall.
5As the heat in a drought,
you will subdue the noise of strangers; 

UDB they are like a storm beating against a wall,
5and like the very strong heat in the desert.
But you cause the roaring of people in foreign nations to cease. 

The ULB has "as the heat in a drought" modifying what comes next in verse 5. But, the UDB has "like a very strong heat in the desert" modifying the last part of verse 4.

It looks like most modern versions follow the UDB. Do you want to change the text so the ULB and UDB agree? Then I will write a note saying either way is possible.

**Comment by TomWarren** [comment]
The last verb in ULB ISA 25:5 is יַעֲנֶֽה׃, it is most difficult. The idea of reply or answer seemed to fit best.

The ULB now reads:
\v 4 For you have been a place of safety for the one who is poor, 
\q1 a shelter for the one who is needy in his distress—
\q1 a shelter from the storm and a shade from the heat.
\q1 When the breath of the ruthless was like a storm against a wall,
\q1
\v 5 and like  heat in a dry land,
\q1 you subdued the noise of foreigners,
\q1 as the heat is subdued by the shade of a cloud, 
\q1 so the song of the ruthless ones is answered.

The UDB now reads: 
\v 4 Yahweh, you are like a strong tower where poor people can find refuge,
\q2 a place where needy people can go when they are distressed.
\q1 You are like a place where people can find refuge in a storm
\q2 and where they can stay in the shade, out of the hot sun.
\q1 People oppress us and show us no mercy,
\q2 they are like a storm beating against a wall,
\q2
\v 5 and like the very strong heat in the dry land.
\q1 But you cause the noisy cries of people from foreign nations to be quiet.
\q2 Like the air cools when a cloud comes overhead,
\q2 you stop merciless people from singing songs about how great they are.
