### ISSUE TITLE
ISA 14:16  "space comma" to "comma space"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#331]
ULB  They will **say ,'Is** this the man 

There is a space before the comma. It should be after the comma.

**Comment by TomWarren** [comment]
The ULB of ISA 14:16-17 now reads:
\v 16 Those who see you will gaze at you and they will pay attention to you. 
\q1 They will say, 'Is this the man who made the earth tremble, who shook kingdoms,
\q1
\v 17 who made the world like a wilderness, who overthrew its cities and did not let his prisoners go home?'

**Comment by SusanQuigley** [comment]
Tom, the page still needs the space after the comma.

**Comment by TomWarren** [comment]
Done. It was changed, and then I copied what I pasted, and then I was cut what I copied, ... and then, well....

**Comment by SusanQuigley** [comment]
😀
