### ISSUE TITLE
ISA 14:29 "because" to "that"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#333]
ULB: Do not rejoice, Philistia, **because** the rod that struck you is broken.

This sounds like the reason they should not rejoice is that the rod that struck them is broken.

Could the word "because" be changed to "that?

**Comment by TomWarren** [comment]
First portion of ULB ISA 14:29 now reads: 

\v 29 Do not rejoice, all you people of Philistia, 
\q1 that the rod that struck you is broken,
\q2 and that their king is dead.
