### ISSUE TITLE
ISA 14:28  What will the poor do?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#334]
ULB: The firstborn of the poor will eat,
UDB: Those of my people who are very poor will take care of their flocks of sheep,

What will the poor do?

**Comment by TomWarren** [comment]
The ULB of ISA 14:30 has been changed and now reads: 
\v 30 The firstborn of the poor will graze their sheep in my pastures, and the needy will lie down in safety.

The UDB of ISA 14:30 is not changed:
\v 30 Those of my people who are very poor will take care of their flocks of sheep,
\q2 and the needy people will lie down safely, 

Hope that helps.

**Comment by SusanQuigley** [comment]
That does. Thank you.
