### ISSUE TITLE
Luk 7:6  that you to come

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#335]
ULB because I am not worthy **that** you **to** come under my roof.

Please either change "that" to "for" or delete "to."

**Comment by TomWarren** [comment]
The ULB of LUK 7:6  now reads:
\v 6 So Jesus continued on his way with them. But when he was not far from the house, the centurion sent friends to say to him, "Lord, do not trouble yourself, because I am **not worthy for you to come** under my roof.
