### ISSUE TITLE
Isa 26:18 reword UDB

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#336]
UDB We have not rescued anyone people from being conquered by their enemies

I don't think "anyone people" is correct. May need to reword.

**Comment by TomWarren** [comment]
The UDB of ISA 26:18 now reads:
\v 18 We were pregnant and had severe pain,
\q2 but nothing good resulted from it.
\q1 We have not rescued any people or kept their enemies from conquering them, 
\q2 and those in the world who were our enemies did not fall in battle.
