### ISSUE TITLE
Isa 26:19 "dew" or "light"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#337]
ULB for your dew is the dew of herbs

UDB His light will be like dew that falls on you

The ULB and UDB are translating the Hebrew differently. We may need to change one so that they agree. From what I found "light" is the more common translation rather than "herbs."

**Comment by TomWarren** [comment]
The ULB of ISA 26:19 now reads: 
\v 19 Your dead will live; their dead bodies will arise. Awake and sing for joy, you who live in the dust;
\q1 for your dew is the dew of light, and the earth will give birth to the dead.

The UDB is not changed.
