### ISSUE TITLE
Isa 26:19 "drop prey" or "give birth"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#338]
ULB for your dew is the dew of herbs, and the earth will drop the dead, its prey. 

I don't see any other English version that translates it like this. Most go with some idea about the earth giving birth to the dead.

**Comment by TomWarren** [comment]
The ULB now reads: 
\v 19 Your dead will live; their dead bodies will arise. Awake and sing for joy, you who live in the dust;
\q1 for your dew is the dew of light, and the earth will give birth to the dead.
