### ISSUE TITLE
LUK 7:14 - sofa?

### ISSUE THREAD

**Issue by losto** [Door43/ulb-en#34]
Then he came forward and touched the funeral **couch**, and those carrying it stood still. He said, "Young man, I say to you, arise.”   - Luke 7:14  ULB

Here at ES-419 GL Mast I saw this translated into **sofá**, I don't think that is quite what the original author was thinking.

I would propose the use of “coffin” or something more like that.

**Comment by TomWarren** [comment]
The body of the boy was being carried to be buried. Often, the bodies were carried on the shoulders of those carrying him. The "bier" was an open frame used to carry the body to the grave. You might simply state that the body was carried to the grave on a wooden frame. There may be confusion about sofa or couch, when it is just a wooden frame used to carry the body. Hope that helps..

**Comment by losto** [comment]
Thank you for the extra information.  Can that ULB be updated as well?

**Comment by TomWarren** [comment]
The ULB has been changed: the wooden frame on which they carried the body. And an additional line in the Translation Notes was added.
