### ISSUE TITLE
isa 27:9 "turn away" or "take away"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#340]
ULB for this will be the full fruit of turning away from his sin

The ULB translates the Hebrew word SUR as "turn away from." But, the word is in the Hiphil which seems to have the idea of "take away" or "remove." Most English versions go with something like "remove." I think this subtle change is important because it puts the emphasis on God removing their sin which results in them destroying the altars. I think this lines up better with passages like Jer 31:31-34 and Ezek 36:24-27 where the people truly obey God because he has given them a new heart.

I thought I would send this to you for consideration.

**Comment by TomWarren** [comment]
THe ULB of ISA 27:9 now reads, with some changes here and there ...
\v 9 So in this way, the iniquity of Jacob will be atoned for, for this will be the full fruit **the removal** of his sin:
\q1 when he will make all the altar stones as chalk and crushed to pieces,
\q1 and no Asherah poles or incense altars will remain standing.
