### ISSUE TITLE
Isa 27:12 Merism?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#341]
ULB from the flowing stream of the Euphrates River, to the brook of Egypt,

UDB He will bring them back to Israel, one by one, from the land between the Euphrates River in the northeast and the brook at the border of Egypt in the southwest

The way the Hebrew is worded it would seem Euphrates River and brook of Egypt would be a merism meaning all the land between these two rivers, such as the UDB indicates.

But, looking at a Bible map I think it is too exact to say "between" these two rivers since that would leave out a good chunk of Assyria, Babylon, and Egypt, and that is where the exiles would be. I'm not sure what is a better way to word this, but I thought I would bring it to your attention.

**Comment by TomWarren** [comment]
Don't think this statement would be necessarily comprehensive in terms of the areas from which people of Israel would be gathered. Scripture often makes one statement but does not eliminate another statement  that might complement the former. This statement of "threshing" would define one segment of that work of gathering the people, and it would not be exclusive of gathering his people from another area. It can stand with the tweaking of the ULB that I effected, to be a bit to the Heb sense. 

The ULB of ISA 27:12 now reads:
v 12 It will come about on that day
\q1 that Yahweh will thresh from the Euphrates River to the Wadi of Egypt
\q1 and you, the people of Israel, will be gathered together one by one.
