### ISSUE TITLE
Isa 28:2 "cast down to the earth"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#344]
ULB he **will strike** the earth with his hand. 

I don't see any other versions that translate it this way. It seems the idea of the Hebrew is that he [the enemy king] will **throw it** [the garland crown] to the earth with his hand.

**Comment by TomWarren** [comment]
I went through it pretty carefully, and here are the renderings. 
The ULB of ISA 28:1-2 now reads:
\v 1 Woe to the proud garland crown that is worn by each of the drunkards of Ephraim, and to the fading flower of its glorious beauty,
\q1 the garland that is set on the head of the lush valley of those who are overcome with wine!
\q1
\v 2 Behold, the Lord sends one who is mighty and strong; like a storm of hail and a destructive windstorm,
\q1 like a driving rain and overflowing waters;
\q1 and he will throw down each crown to the ground.
(**each crown** is added for clarity)

**Comment by jhutchins25** [comment]
Looks good. One correction:

"he will thrown" should be "he will throw"

**Comment by TomWarren** [comment]
Thanks. Here is the fix:
\v 2 Behold, the Lord sends one who is mighty and strong; like a storm of hail and a destructive windstorm,
\q1 like a driving rain and overflowing waters;
\q1 and he **will throw** each garland crown down to the ground.
