### ISSUE TITLE
Isa 16:7 ULB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#348]
ULB: You mourn for the raisin cakes of Kir Hareseth **that was completely devastated**.
UDB: They will all mourn, because **there will be no more raisin cakes** in the city of Kir Hareseth.

In the ULB, the **city** is devastated. In the UDB "devastated" is not stated explicitly, but it says that there will be no more **raisin cakes**.
The subject of nakaim 'stricken' is plural, so would it be the raisin cakes?

Could the ULB be changed to something like one of these?
You mourn, for the raisin cakes of Kir Hareseth were destroyed. 
You mourn for the raisin cakes of Kir Hareseth, because they were destroyed.
You mourn for the raisin cakes of Kir Hareseth, because there are none.

**Comment by TomWarren** [comment]
The ULB of ISA 16:7 now reads:
\v 7 So Moab wails for Moab—they all wail!
\q1 It will wail for what has happened to the raisin cakes of Kir Hareseth—you will groan for the people who were destroyed.

The UDB of ISA 16:7 now reads:
\v 7 Some day all the people in Moab will weep.
\q2 They will all mourn,
\q1 because there will be no more raisin cakes in the city of Kir Hareseth.
\q2 But more than the cakes, they mourn for the people who lived there, who were all killed.

**Comment by SusanQuigley** [comment]
Hi Tom. I'm wondering how  "groan for the people who were destroyed" comes in with "wail for what has happened to the raisin cakes". I understand that the word ashisha is rare and scholars don't know whether it means "men" or "raisin cakes." But it seems like it would have to mean one or the other--not both.

**Comment by TomWarren** [comment]
There is a phrase in HEB "they will grieve over stricken people" that is not rendered in some translations. I think is is rendered in the NIV. It is the comparison that the "cakes" were destroyed, but that was a harbinger of further destruction, that of the people. 
Hope that helps. TW

**Comment by SusanQuigley** [comment]
Yes, NIV has "Lament and grieve for the men ‡ of Kir Hareseth" along with this note: 
16:7 Or “ raisin cakes, ” a wordplay.
I'm not sure why it says that it's a wordplay. Do you think that they are saying that the Hebrew word is intended to bring up both meanings? 

This is the note Jim had written for "raisin cakes".
**raisin cakes** - This rare word in Hebrew is translated in different ways by some modern versions, as "men" or "farmers."

This is what SIL-TN said:
The Hebrew word meaning “men” is similar to the word meaning raisin cakes, so NIV has taken “men” as the correct reading. But there is no need to make this change.



**raisin cakes** - This rare word in Hebrew is translated in different ways by some modern versions, as "men" or "farmers."

**Comment by TomWarren** [comment]
This is a place where two issues were compared, the cakes and the people. Some try (I think unnecessarily) to try and see word-play, but it seems to be a poetic way of describing the destruction of the city where the "cakes" were made, and then the realization that the people there were also destroyed. 
To keep the meaning as applying to the cakes alone would mean cutting out the final phrase ("grieving over the stricken people"). It seems straightforward to me, but I am simple in these matters.

**Comment by TomWarren** [comment]
The ULB of ISA 16:7 (with thanks to Aaron Fenlason for help), now reads:
\v 7 So Moab wails for Moab—they all wail! Mourn, you who are utterly destroyed, for the raisin cakes of Kir Haraseth.

Hope that helps, Susan.
