### ISSUE TITLE
ISA 33:15

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#353]
He who walks righteously and speaks honestly; he who despises the gain of oppression,
who refuses to take a bribe, who does not plot violent crime,
and does not look on evil.

This is one really long subject, not a compete English sentence. Most English translations use this "--" to connect it to verse 16.

**Comment by TomWarren** [comment]
The ULB of ISA 33:15-16 now read:
\v 15 He who walks righteously and speaks honestly; he who despises the gain of oppression,
\q1 who refuses to take a bribe, who does not plot violent crime,
\q1 and does not look on evil—
\q1
\v 16 he will make his home on the heights;
\q1 his place of defense will be the fortresses of rocks; his food and water will be in steady supply.
