### ISSUE TITLE
Isa 30:10 "straighforward"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#355]
ULB Do not prophesy straightforward truth to us

I think it is unnecessary to introduce an idiomatic word like "straightforward" here. 

It would be much more "straighforward" to translate it as "Do not prophesy to us what is true"

**Comment by TomWarren** [comment]
The ULB of ISA 30:10-11 now reads:
\v 10 They say to the seers, "Do not see;"
\q1 and to the prophets, "Do not prophesy the truth to us;
\q1 speak flattering words to us, prophesy illusions.
\v 11 Turn aside from the way, stray off the path;
\q1 cause the Holy One of Israel to cease speaking before our face."
