### ISSUE TITLE
ISA 35:1-2 clausal breaks

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#357]
The wilderness and the Arabah will be glad; and the desert will rejoice and blossom
like the rose.
2It will blossom abundantly and rejoice with joy and singing;

In the UDB the phrase "like a rose" is connected to verse 2, whereas here, it is connected to the last clause of verse 1. English verses are inconsistent here as well, but it might be best to make our versions consistent.

**Comment by TomWarren** [comment]
This seems to make more sense than the alternative. 
The UDB  of ISA 35:1-2 now reads: 
\v 1 The wilderness and the Arabah will be glad; and the desert will rejoice and blossom.
\q1 Like the rose,
\q1
\v 2 it will blossom abundantly and rejoice with joy and singing;
\q1 the glory of Lebanon will be given to it, the
splendor of Carmel and Sharon;
\q1 they will see the glory of Yahweh, the splendor of our God.

Thanks,
