### ISSUE TITLE
MRK 11:32 ULB  "They" to "they"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#363]
Mark 11:32 ULB  But if we say, 'From men,' ... " They feared the people
It looks like "They" should be "they" since the preceding phrase does not end with a period.

This would be like Matthew 9:6. 
But that you may know that the Son of Man has authority on earth to forgive sins, ... " he said to the paralytic, "Get up, pick up your mat, and go to your house."

**Comment by TomWarren** [comment]
The ULB of MRK 11:32 now reads:
\v 32 But if we say, 'From men,' .... " (They were afraid of the people, for everyone was convinced that John was a prophet.)
