### ISSUE TITLE
Isa 6:4 foundations of the thresholds

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#364]
ULB The doors and the thresholds shook

UDB it caused the doorposts of the temple

The UDB does not contain the idea of the foundation of the threshold. It looks like most versions mention something about the foundation.

**Comment by TomWarren** [comment]
The ULB of ISA 6:4 was changed to read: 
\v 4 The foundations of the thresholds shook at the voices of those who were crying out, and the house was filled with smoke.
The UDB of ISA 6:4 was changed to read:
\v 4 When they spoke, the sound of their cries caused the foundation beneath the doorposts of the temple to shake, and the temple was filled with smoke.
