### ISSUE TITLE
Mrk 3:5 ULB  their hardness of hearts

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#365]
grieved by their hardness of hearts

Please change "hearts" to "heart"

**Comment by TomWarren** [comment]
The ULB of MRK 3:5 now reads:
\v 5 He looked around at them with anger, and he was grieved by their hardness of **heart**, and he said to the man, "Stretch out your hand." He stretched it out, and his hand was restored.

Thanks,
TW
