### ISSUE TITLE
MRK 8:33 ULB You do are not setting your mind

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#366]
MRK 8:33 ULB You do are not setting your mind

I think the word "do" was left in by mistake.

**Comment by TomWarren** [comment]
The ULB of MRK 8:33 now reads:
\v 33 But Jesus turned and looked at his disciples and then he rebuked Peter and said, "Get behind me, Satan! You are not setting your mind on the things of God, but on the things of people."
