### ISSUE TITLE
LUK 8:10 ULB others they

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#368]
LUK 8:10 ULB  but **the others they** are taught in parables, 

It would be good to either delete "they" or put a comma between "the others" and "they."

**Comment by TomWarren** [comment]
The ULB of LUK 8:10 now reads:
\v 10 He said, "The knowledge of the secrets of the kingdom of God has been given to you, but for others I speak in parables, so that 'seeing they may not see, and hearing they may not understand.'

Thanks.
