### ISSUE TITLE
Luk 8:10 ULB so that 'that seeing

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#369]
Luk 8:10 ULB: so **that 'that** seeing they may not see, and hearing they may not understand.'

Should the second "that" be deleted?

**Comment by TomWarren** [comment]
Saw that correction, too, 
\v 10 He said, "The knowledge of the secrets of the kingdom of God has been given to you, but for others I speak in parables, **so that 'seeing t**hey may not see, and hearing they may not understand.'
