### ISSUE TITLE
Pro 1:5

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#370]
UDB and those who already have insight will gain more ways to teach people how they should live

I don't see any other version that translates this as the wise learning more ways to teach other. It seems to be parallel with the first part of verse five and mean that people who are wise should learn from proverbs to become even more wise themselves.

**Comment by TomWarren** [comment]
The UDB of PRO 1:5-6 now read: 
\v 5 so the wise may listen to these sayings and increase in their learning,
\q2 and those who already have insight will gain more ways to live according to the lessons of wisdom.
\q1
\v 6 They seek to understand the lessons of the proverbs and the meaning of the parables.
\q2 These are the words of the wise and their difficult riddles.
