### ISSUE TITLE
Luk 9:16 ULB He taking

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#374]
**He taking** the five loaves and the two fish, he looked up to heaven, he blessed them and broke them into pieces, and he gave them to the disciples to set before the crowd. 

Could you change "He taking" to "Taking"?
Could "he" before "blessed" be deleted or changed to "and"?

**Comment by TomWarren** [comment]
The ULB of LUK 9:16 now reads:
\v 16 Taking the five loaves and the two fish, he looked up to heaven, he blessed them and broke them into pieces, and he gave them to the disciples to set before the crowd.

Thanks
