### ISSUE TITLE
Pro 1:17 Move verse?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#375]
ULB 15My son, do not walk down that road with them;
do not let your foot touch where they walk;
16their feet run to evil
and they hurry to shed blood.
17For it is useless to spread the net to trap a bird
while the bird is watching. 

(Chunk break)

18These men lie in wait to kill themselves—
they set a trap for themselves.
19So are the ways of everyone who gains riches by injustice;
unjust gain takes away the lives of those who hold on to it. 

Verses 17-18 are a comparison of the wisdom of birds and the foolishness of the sinners. I think it is confusing to separate the comparison over two chunks. Would it be worthwhile to move verse 17 to the next chunk?

**Comment by TomWarren** [comment]
John, I spoke with Larry Sallee, just to be certain, and the news is that the chunks are not moveable at this point. There would be many disruptions through the text if changes were made to the chunks, and we have many sections that would logically fit together in an different arrangement. 
For now, we have the chunks that we have. 
Thanks for thinking through the text.
