### ISSUE TITLE
Pro 1:22

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#376]
ULB How long, you who have no wisdom, will you love what you do not understand?

I'm not sure if this gets the correct idea across. I don't think this means they love what they don't understand, but rather they love that they don't understand, that is, they love being simple or ignorant. They do not want to learn wisdom.

**Comment by TomWarren** [comment]
THe ULB now reads at PRO 1:22:
\v 22 "How long, you simple ones, will you love being simple?
\q How long, you mockers, will you delight in mockery,
\q and how long, you fools, will you hate knowledge?

I checked the appearance of this term for "simple"  (HEB פֶּתִי) and applied it throughout Proverbs, in similar texts
