### ISSUE TITLE
City/city of David ULB

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#38]
I am finding many instances of both "city" and "City" in the ULB.

**Comment by hharrissWA** [comment]
Thanks Larry. I will check this out and the previous email you sent, too.


Harry


C. Harry Harriss

Associate Editor, Unfolding Word Bible

Translation Consultant (in training)

Wycliffe Associates and Wycliffe India

harry_harriss@wycliffeassociates.org<mailto:harry_harriss@wycliffeassociates.org>

662-890-5637 home



________________________________

**Comment by lrsallee** [comment]
Thanks, Harry. I didn’t look at many places in the UDB, but you probably need to make sure it also matches whichever you choose.

Larry

**Comment by hharrissWA** [comment]
Ok. Do you suggest a search of the entire OT for "city" for this? I can do that, but I am wondering how large of an issue this might be before searching it out.


Thanks,

Harry


C. Harry Harriss

Associate Editor, Unfolding Word Bible

Translation Consultant (in training)

Wycliffe Associates and Wycliffe India

harry_harriss@wycliffeassociates.org<mailto:harry_harriss@wycliffeassociates.org>

662-890-5637 home



________________________________

**Comment by TomWarren** [comment]
Harry, Just do a search for "City of God" and all of them will come up. There are less than 10 that need to be fixed. There are only 32 in total. Not too bad. 
Thanks. 

Tom

**Comment by hharrissWA** [comment]
Ok, will do.

Thanks!

H


C. Harry Harriss

Associate Editor, Unfolding Word Bible

Translation Consultant (in training)

Wycliffe Associates and Wycliffe India

harry_harriss@wycliffeassociates.org<mailto:harry_harriss@wycliffeassociates.org>

662-890-5637 home



________________________________

**Comment by SusanQuigley** [comment]
Hi Harry,

You might want to check "city of David" in the ULB. I see both "city of David” and ”City of David.” I don’t know if this is intentional.

Susan

On Apr 25, 2016, at 9:52 AM, hharrissWA <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok, will do.

Thanks!

H


C. Harry Harriss

Associate Editor, Unfolding Word Bible

Translation Consultant (in training)

Wycliffe Associates and Wycliffe India

harry_harriss@wycliffeassociates.org<mailto:harry_harriss@wycliffeassociates.org><mailto:harry_harriss@wycliffeassociates.org>

662-890-5637 home



________________________________

**Comment by lrsallee** [comment]
Susan,

Actually, I create the same issue this AM in GitHub, and Harry is already working it.

Harry, Tom referred to “city of God”. The issue I made was for “city of David”. Looks like they both might need attention.

Larry

**Comment by hharrissWA** [comment]
It seems all "City" instances have been changed to "city" now--at least in relation to uses of "city of David" and "city of God." If there are other instances of "City" where it should be "city," please inform, of course. I  don't see others right now, but there may some obscure usages which do not come to mind (at least my mind). To search the word "city" by itself would be a time consuming task, it seems.
Thanks, Harry H.

**Comment by TomWarren** [comment]
My "city of God' was a brain flip, but it turns out that it needs some attention (at least a quick scan). Thanks to all for helping with continuity issues. 
Tom
