### ISSUE TITLE
Gal 3:1 ULB typo

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#381]
Gal 3:1 ULB Jesus CHrist 

The "h" in "CHrist" is upper case.

**Comment by TomWarren** [comment]
Gal 3:1 ULB now reads;
\v 1 Foolish Galatians! Who has put a spell on you? Before your eyes Jesus Christ was vividly portrayed as crucified?

**Comment by SusanQuigley** [comment]
Gal 3:1 ULB Before your eyes Jesus Christ was vividly portrayed as crucified?

Oops. I just saw that there is a question mark at the end. It should be period or exclamation point.

**Comment by TomWarren** [comment]
\v 1 Foolish Galatians! Who has put a spell on you? Before your eyes Jesus Christ was vividly portrayed as crucified.

Always somethin'
