### ISSUE TITLE
Gal 3:1 ULB  Location of footnote

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#382]
Foolish Galatians! Who has put a spell on you? Before your eyes Jesus Christ was vividly portrayed as crucified?[1] 

[1]Some older versions add, _so that you should not obey the truth_?

Should the foot note come right after "Who has put a spell on you?"

**Comment by TomWarren** [comment]
The footnote is removed. There is no credible textual family that includes this suggestion.
