### ISSUE TITLE
Luk 17:20  ULB vs UDB with signs

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#385]
ULB: The kingdom of God is not coming **with signs** that may be observed.
UDB: That is not something people will be able to see with their eyes.

The ULB makes explicit the information about the signs. 
Would it be good to have this in the UDB (instead)?

**Comment by TomWarren** [comment]
The ULB of LUK 17:20 now reads:
\v 20 Being asked by the Pharisees when the kingdom of God would come, Jesus answered them and said, "The kingdom of God does not come by careful observing.

The last phrase follows the GRK, μετὰ  παρατηρήσεως,. Many modern translations add, "signs to be observed" but as noted, that would be an addition.

**Comment by SusanQuigley** [comment]
The kingdom of God does not come **by** careful observing.

Would it be good to change "**by**" to "**with**"? It's not that people thought that observing would **cause** the kingdom to come; rather they thought that  while the kingdom comes, they would be able to observe it coming. The observing would **accompany** the coming.

**Comment by TomWarren** [comment]
The Greek seems to favor your view. "with" is μετά  used with the genitive, as here.
So the ULB of LUK 17:20 now reads:
\v 20 Being asked by the Pharisees when the kingdom of God would come, Jesus answered them and said, "The kingdom of God does not come with careful observing.
Thanks.
