### ISSUE TITLE
Isa 18:4-7  Quote marks

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#387]
At this point the ULB and UDB have quote marks around what Yahweh says in verse 4. Would we want to extend the quote in both versions through verse 6?

This is based on the "he" of "he will cut off the sprigs with pruning hooks, and he will cut down and take away the spreading branches" referring to the farmer. Yahweh tells a parable in 4-6 and refers to the farmer in it as "he."

**Comment by TomWarren** [comment]
The quotes in the UDB and ULB run from vs 4 to the end of vs 6.
This is the ULB of ISA 18:4-6

\v 4 This is what Yahweh said to me, "I will quietly observe from my home,
\q1 like the simmering heat in sunshine, like a cloud of mist in the heat of harvest.
\q1
\v 5 Before the harvest, when the blossoming is over, and the flower is ripening into a grape,
\q1 he will cut off the sprigs with pruning hooks, and he will cut down and take away the spreading branches.
\s5
\q1
\v 6 They will be left together for the birds of the mountains and for the animals of the earth.
\q1 The birds will summer on them, and all the animals of the earth will winter on them."
