### ISSUE TITLE
Isa 52:5 add quotations

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#389]
ULB 5 Now what do I have here—this is Yahweh's declaration—seeing that my people are taken away for nothing? Those who rule over them mock—this is Yahweh's declaration—and my name is slandered continually all day long.

Do you think this would make more sense to MTT's if we remove the dashes and add quotation marks?

5 Now what do I have here," this is Yahweh's declaration, "seeing that my people are taken away for nothing? Those who rule over them mock," this is Yahweh's declaration, "and my name is slandered continually all day long.

**Comment by TomWarren** [comment]
The phrase "this is Yahweh's declaration" is included within the quotation, and not as a comment by the prophet.
