### ISSUE TITLE
Isa 52:5 ULB/UDB disagreement

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#390]
ULB  Those who rule over them mock

UDB And my people's own rulers wail and lament

There is a footnote on the chunk saying either translation is possible, but should we make the ULB and UDB agree instead of each one having a different translation?

**Comment by TomWarren** [comment]
The two translations should say the same thing, only with different approaches to the text.
The UDB of ISA 52:5 has been changed to read:
\v 5 But now think about what is happening:
\q1 My people are being forced to be slaves again, this time by the people of Babylonia.
\q2 And my people's own rulers boast and make fun of them,
\q1 and the other people groups in the world despise it whenever my name is spoken.

**Comment by jhutchins25** [comment]
It seems if you interpret "those who rule over them" to mean the Israelites rulers, then we would need to say they were "wailing" instead of "mocking." I think the meaning is the Israelite rulers are in Babylon crying about their situation rather than they are making fun of their people or God's name. I suggest one of these two options may work better:

ULB Those who rule over them mock
UDB The rulers of Babylon mock
or
ULB Those who rule over them wail
UDB my people's own rulers wail

**Comment by TomWarren** [comment]
ULB \v 5 Now what do I have here—this is Yahweh's declaration—seeing that my people are taken away for nothing? Those who rule over them **mock**—this is Yahweh's declaration—and my name is slandered continually all day long.

UDB \v 5 But now think about what is happening:
\q1 My people are being forced to be slaves again, this time by the people of Babylonia.
\q2 And the rulers of Babylon boast and make fun of them (as I, Yahweh, have said they would do),
\q1 and the other people groups in the world despise the mention of my name.

That should work. Thanks.

**Comment by TomWarren** [comment]
I fixed the quotation marks in the UDB, changing from double to single.
