### ISSUE TITLE
Isa 52:13 successful or wisely

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#391]
ULB Look, my servant will be successful;

UDB My servant will act wisely and do all that Yahweh wants him to do

After I hit create new issue I noticed that the UDB also says "and do all that Yahweh wants him to do." Originally I was just comparing "will act wisely" with "will be successful," which I wasn't sure if they were exact synonyms. But, since there doesn't seem to be a cancel button you can take a look at them and decide if ULB or UDB should be changed.

**Comment by TomWarren** [comment]
The verb is יַשְׂכִּ֖יל and may (meaning 6 in BDB) have the view of "have success, but here it appears to many scholars to be "to be wise" or "to act with wisdom", perhaps there is a connection between having wisdom and being successful. Success, here, seems less likely than wisdom.

The ULB of ISA 52:13 now reads:\v 13 Look, my servant will act wisely;
\q1 he will be high and lifted up, and he will be exalted.
