### ISSUE TITLE
Isa 52:5 "for nothing"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#392]
Sorry to keep bringing up this verse. I keep noticing little things.

ULB my people are taken away for nothing

I don't see the idea of "for nothing" reflected in the UDB. It seems "for nothing" means God sold the people for nothing as in 52:3. Or it means the Babylonians took them away unjustly, without cause.

**Comment by TomWarren** [comment]
Thanks! No keep 'em coming! 
It is so hard to broaden out the editing focus when working on a small part of the whole.

The UDB at ISA 52:5 now reads:
\v 5 But now think about what is happening:
\q1 My people are being forced to be slaves again, this time by the people of Babylonia. **They have taken my people away, but they never declared any just reason for taking them captive.**
\q2 And the rulers of Babylon boast and make fun of them (as I, Yahweh, have said they would do),
\q1 and the other people groups in the world despise the mention of my name.
\q1

Give that a look. 
TW
