### ISSUE TITLE
Isa 54:6 quotation mark

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#395]
ULB like a woman married young and rejected, says your God. 

Verse 7 in the ULB opens with a quotation mark. Either a quotation marks needs to be put after "rejected" in verse 6 or the one in verse 7 needs to be removed. 

I suggest adding the quotation after "rejected" because in 54:1 the phrase "says Yahweh" is not included as part of the quotation.

**Comment by TomWarren** [comment]
The suggestion is good. The ULB of ISA 54:6 now reads:
\v 6 For Yahweh has called you back as a wife abandoned and grieved in spirit,
\q1 like a woman married young and rejected," says your God.

==== and then a new quotation block begins with the next chunk, (vs 7), and that works.  
So currently the quotations begin Vs 1 end Vs 2, begin quotation at Vs 2  ending Vs 6 and begin Vs 7, and  ending Vs 17 (end of chapter) ======
