### ISSUE TITLE
PRO 17:1

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#396]
It is better to have quiet with a dry morsel of bread
than a house full feasting with strife.

This reads that the house is full (of people), and those inside are feasting with strife. This should read that the house if full of feasting.

Suggestion: "than a house full of feasting with strife"

**Comment by TomWarren** [comment]
Thanks very much, Kim,
 The ULB of PRO 17:1 now reads:
\v 1 It is better to have quiet with a dry morsel of bread
\q than a house full of feasting with strife.
