### ISSUE TITLE
Lev 21:3 ULB missing phrase?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#397]
ULB or his virgin sister who has no husband

The Hebrew has the phrase הַקְּרֹובָ֣ה אֵלָ֔יו (near him or dependent on him)

The UDB says "has been living in your house"

Since the phrase is reflected in the UDB should it be added to the ULB?

**Comment by TomWarren** [comment]
Yes, and thank you. 
The ULB of LEV 21:3 now reads:
\v 3 or his virgin sister who is dependent on him, since she has no husband—for her he may make himself unclean.
