### ISSUE TITLE
Lev 22:24

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#398]
This chunk got sent back to p2edit. The proofreader asked if this chunk had been sent to you previously. In February Kim P said: Hey Tom, please change “testicles” in to “reproductive organs”. It's in the UDB 2X and the ULB 1X here. Thanks! 

Then Bram added: Same comments as here: Leviticus 21:18-21. 

I didn't know if it wasn't sent to you or if the decision had been made to not change the text.

**Comment by TomWarren** [comment]
There was an alert that we should not use specific terminology about reproductive organs, but the reason for that was a fear of internet service providers in closed countries, would not allow the text in. This proved not to be a barrier after all, and the instruction for the ULB/UDB was rescinded. Obviously, care should be taken when dealing with these private parts, but this section in LEV is dealing with this specific issue.
This section in LEV 22 is descriptive of the specific injury, and it can stand.
