### ISSUE TITLE
Pro 26:7-10 ULB Backward similes?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#400]
Pro 26:7-10  The ULB  seems to have translated these similes backwards.  The chapter is about fools, but the ULB switched around the "topic" and the "image" of the simile by saying that various things are like fools.

7 The legs of a paralytic hanging down
are like a proverb in the mouth of fools. 
8 Tying a stone in a sling
is the same as giving honor to a fool. 
9 A thornbush that goes up into the hand of a drunk
is like a proverb in the mouth of fools. 
10 An archer who wounds everybody
is like the one who hires a fool or just anyone who passes by. 

Could these be changed to something like this?
7 The legs of a paralytic hang down
and so do proverbs in the mouth of fools.
8. Like tying a stone in a sling
so is giving honor to a fool.
9. As a thornbush that goes up into the hand of a drunk is
so is a proverb in the mouth of fools.
10. Like an archer who wounds everybody, 
so is one who hires a fool or just anyone who passes by.

**Comment by TomWarren** [comment]
The ULB of PRO 26:7-10 now reads:
\s5
\q
\v 7 The legs of a paralytic hang down,
\q and so does a proverb in the mouth of fools.
\q
\v 8 Tying a stone in a sling
\q is the same as giving honor to a fool.
\s5
\q
\v 9 A thorn that goes into the hand of a drunkard
\q is like a proverb in the mouth of fools.
\q
\v 10 An archer who wounds all those around him
\q is like one who hires a fool or hires anyone who passes by.

Thanks, 
TW

**Comment by SusanQuigley** [comment]
I mean, could these be reworded so that fools (or doing these things for fools) are like the image.

**Comment by TomWarren** [comment]
Try this for PRO 26:7
\v 7 Like the legs of a paralytic which hang down
\q is a proverb in the mouth of fools.

Thanks, 
TW

**Comment by SusanQuigley** [comment]
This is great. Could you do this with the others?

**Comment by TomWarren** [comment]
Sure:
\v 7 Like the legs of a paralytic which hang down
\q is a proverb in the mouth of fools.
\q
\v 8 Like tying a stone in a sling
\q is giving honor to a fool.
\s5
\q
\v 9 Like thorn that goes into the hand of a drunkard
\q is a proverb in the mouth of fools.
\q
\v 10 Like an archer who wounds all those around him
\q is one who hires a fool or hires anyone who passes by.

**Comment by SusanQuigley** [comment]
Thank you. This looks good.
