### ISSUE TITLE
Pro 26:5 ULB Introduced metaphor

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#403]
Pro 26:5 ULB and join in on his folly

The ULB introduces the metaphor "join in." This is not part of the Hebrew.
Would you want to change it to "according to his folly" ?

**Comment by TomWarren** [comment]
The ULB of PRO 26:5 now reads: 
\v 4 Do not answer a fool according to his folly,
\q or you will become like him.
