### ISSUE TITLE
Num 19:18 missing phrase?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#408]
ULB and on the one who touched the bone, **the killed person, the dead person**, or the grave.

UDB  on any person who touched a human bone or **who touched a person who died**, or who touched a grave

Did the UDB purposefully reduce "killed person, the dead person" to just "person who died" or is the UDB missing the phrase about "the killed person"?

**Comment by TomWarren** [comment]
The ULB of NUM 19:18 now reads: 
\v 18 Someone who is clean must then take hyssop, dip it in the water, and sprinkle it on the tent, on all the containers inside the tent, on the persons who were there, and on anyone who touched the bone, the one who was killed, the one who died, or the grave.

The UDB of NUM 19:18 now reads: 
\v 18 Then someone who has not become unacceptable to me must take a stalk of a plant named hyssop and dip it into the water. Then that person must sprinkle some of the water on the tent where that person died, on the things that are in the tent, and on the people who were in the tent. **He must also sprinkle some of that water on any person who touched a human bone or who touched a person who had been killed, or who touched a person who died of natural causes, or who touched a grave.**
