### ISSUE TITLE
Heb 1:5 ULB Two Question marks?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#411]
For to which of the angels did God ever say,
"You are my son,
today I have become your father"? 
"I will be a father to him,
and he will be a son to me"?

The use of two question marks seems odd. Could both quotes be within the same question?
For to which of the angels did God ever say,
"You are my son,
today I have become your father**,**"
**or** "I will be a father to him,
and he will be a son to me"?

Or could "And again" be put back in before the second quote to show that this quote also is within a question even though the question has been elided?

For to which of the angels did God ever say,
"You are my son,
today I have become your father"? 
**And again,** "I will be a father to him,
and he will be a son to me"?

If the second suggestion is used I would add notes like this:
**And again** - This introduces another quote in a similar question. AT: "And about which of the angels did God ever say" (See: Ellipsis)

**And again, "I will be a father ... will be a son to me"?** - This question emphasizes that God does not refer to any of the angels as his son. AT: "And God never said about any of his angels, 'I will be a father ... will be a son to me.'" (See: Rhetorical Question)

**Comment by SusanQuigley** [comment]
"I will be a father to him,
and he will be a son to me"?

This looks odd, but I added these two notes, and it may be adequate.
**"I will be ... to me"?** - The first part of this question is understood from the earlier question. AT: "And about which of the angels did God ever say, 'I will be ... to me"? (See: Ellipsis)
**"I will be ... to me"?** - This question emphasizes that God does not call any angel his son. AT: "And God never about any angel, "I will be ... to me.'" (See: Rhetorical Question)

**Comment by TomWarren** [comment]
Here is my rendering of ULB HEB 1:5-6: 

\v 5 For to which of the angels did God ever say,
\q "You are my son,
\q today I have become your father" and again,
\b
\q "I will be a father to him,
\q and he will be a son to me"?

\s5
\p
\v 6 But again, when God brings the firstborn into the world, he says, 
\q "All God's angels must worship him."
\v 7 About the angels he says,
\q "He is the one who makes his angels spirits,
\q and his servants flames of fire."
