### ISSUE TITLE
Deu 11:4 punctuation

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#412]
ULB Neither did they see what he did to the army of Egypt, to their horses, or to their **chariots; how** he made the water of the Sea of Reeds overwhelm them as they pursued after you, and how Yahweh has destroyed them until **today;**

A proofreader sent this to me saying these semicolons are problematic. He suggest either changing both to dashes or changing the first semicolon to a colon.

I looked at other English versions. Some have the punctuation exactly as it is in the ULB. Some change both semicolons to commas, and some change the first semicolon to a comma and the second to a period or exclamation mark.

Do you think having two semicolons causes a problem?

**Comment by TomWarren** [comment]
This could be commas. The text now reads:
\v 4 Neither did they see what he did to the army of Egypt, to their horses, or to their chariots, how he made the water of the Sea of Reeds overwhelm them as they pursued after you, and how Yahweh has destroyed them until today,
\v 5 or what he did for you in the wilderness until you came to this place.
