### ISSUE TITLE
Gal 3:14 ULB  Extra "that"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#413]
Gal 3:14 ULB the blessing **that** of Abraham might come to the Gentiles in Christ Jesus, 

It looks like "that" should be deleted after "blessing."

**Comment by TomWarren** [comment]
The ULB of GAL 3:14 now reads:
\v 14 so that the blessing of Abraham might come to the Gentiles in Christ Jesus, so that by faith we might receive the promise of the Spirit.

Thanks,
