### ISSUE TITLE
Deu 11:13 Punctuation

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#415]
ULB It will happen, if you will listen diligently to my commandments that I command you **today to** love Yahweh **your God, and** to serve him with all your heart and with all your soul, 14 that

Commas may not be in the best places. A proofreader suggests this:

It will happen, if you will listen diligently to my commandments that I command you **today, to** love Yahweh **your God and** to serve him with all your heart and with all your soul, that

**Comment by TomWarren** [comment]
The ULB of DEU 11:13 now reads:
\v 13 It will happen, if you will listen diligently to my commandments that I command you today, to love Yahweh your God and to serve him with all your heart and with all your soul,
