### ISSUE TITLE
Pro 27: 9 ULB  the sweetness of a friend is better than his advice

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#416]
Perfume and incense make the heart rejoice,
but the sweetness of a friend is better than his advice.

I realize that the second line in Hebrew is very hard to understand, but I don't see any other versions that translate it like this. And what the ULB says seems to be contrary to what verse 6.
Could the second line be changed to something like one of these?

and so does the sweetness of a friend's advice
or 
and the sweetness of a friend is from his advice

A similar change would be needed in the UDB.

**Comment by hmw3** [comment]
I think you're right that the ULB needs to be changed to match versions. I like your second version and will install it forthwith.

**Comment by SusanQuigley** [comment]
Does "comes" introduce a metaphor that is not in the Hebrew? It seems like "comes" here represents "results" or "is recognized by." That's why I used the weaker word "is."

**Comment by hmw3** [comment]
The Hebrew would be literally "[is] from"; there's no overt verb in the clause, and the _min_ on the next verb indicates some sort of source. It doesn't (in English) require physical motion, and in fact a sentence like "Her value to me comes from her loyalty" would be awkward if we swapped "is" in for "comes." I would rate this like "table leg": no metaphor.

**Comment by SusanQuigley** [comment]
That makes sense. Thanks.
