### ISSUE TITLE
Pro 27:4 ULB  "suffered" to "experienced"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#417]
ULB Have you **suffered** so many things for nothing
UDB All the things you **experienced** after you believed in Christ—**whether good things or bad things**

Since the Greek word translated in the ULB as "suffered" could refer either to suffering or to experiencing good things, and since translations vary on whether it was good things or bad, could the ULB use the more generic "experienced"? Then we can have a note saying that Paul was referring either to good or to bad experience.

Also could "whether good things or bad things" be deleted from the UDB? Paul could have been referring to one kind of thing--not necessarily both.

**Comment by TomWarren** [comment]
This reference is to Galatians 3:4. 
The verb seems to be a pregnant verb of Paul, suffering/ experiencing difficulty. In the NT it is not referring to "good things" that are experienced, but the challenging or difficult experiences that they have gone through. The context of the verse -- "if indeed for nothing?" would point to a serious event, suffering would fit. 
More importantly, the lexicography of this term finds that it is only used once in the literature (LXX and patristics) in terms of a positive experience, and it is not used in a purely positive sense in the Biblical text,. There is  a singular **neutral** meaning translated generally as "experience" in Mt 17:15. In all other LXX and NT references it is rendered "to suffer." 

The UDB of GAL 3:4 now reads:
\v 4 All the difficult things you have experienced after you believed in Christ would have been of no value at all if you had not been trusting in him.

**Comment by SusanQuigley** [comment]
Tom, thanks for the explanation. I'll fix the note. 
The change you made to the UDB does not show up yet.
