### ISSUE TITLE
Lev 27:19 Typo

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#421]
ULB If the man who set apart the field wishes to redeem it, then he must add a fifth to the valuation, and it **will be become** his again

Remove either "be" or "become"

**Comment by TomWarren** [comment]
Yes. The ULB of LEV 27:19 now read:
\v 19 If the man who set apart the field wishes to redeem it, then he must add a fifth to the valuation, and it will belong to him.
