### ISSUE TITLE
Pro 27:13 ULB puts up money?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#422]
ULB:  Take a garment if its owner
puts up money as security for a stranger's debt;

The ULB adds the idea of money to this. But that doesn't make sense. If someone has put up money, then that money should pay the debt. There would be no need for the garment. Taking the garment would be to guarantee that the person will pay the loan in order to get the garment back.

How about something like this?
Take the garment of anyone who offers it as security for a stranger's debt

This also occurs in Pro 20:16.

**Comment by TomWarren** [comment]
ULB PRO 27:13 now reads:
\v 13 Take a garment of one who has put up security for a stranger,
\q and hold it in pledge when he puts up security for an immoral woman.

UDB of PRO 27:14 now reads:
\v 13 Take a man's garment as security when he is guaranteeing a loan for a stranger.
\q2 Hold the garment in pledge to protect yourself when he puts up security for an adulteress.

ULB PRO 20:16 now reads:
\v 16 Take a garment of one who has put up security for a stranger,
\q and hold it in pledge when put up security for an immoral woman.

UDB of PRO 20:16 now reads:
\v 16 If you guarantee a loan for a stranger, take his expensive coat, so you can sell it if he does not pay.
\q2 And if he makes a pledge for a immoral woman, hold his coat as a guarantee so you will not lose your money.

**Comment by SusanQuigley** [comment]
20:16b ULB Typo
 and hold it in pledge **when put up** security for an immoral woman.
The bolded phrase should be "when he puts up."

Content Issue:
It looks like in 27:13, the ULB and UDB mean the same thing.
But in 20:16 the ULB and UDB mean different things.
In 20:16 the ULB has the lender taking the garment of the one who guarantees the loan,
and the UDB has the one who guarantees the loan taking the garment of the borrower.

Could the UDB be the same in both verses?

**Comment by TomWarren** [comment]
There is some ambiguity in the UDB about who does what. Your note is helpful, Susan Q. 

The UDB of PRO 20:16 now reads:
\v 16 Take the expensive coat of the person who guarantees a loan for a stranger, so it can be sold if the debt is not paid back.
\q2 And if he makes a pledge for a immoral woman, hold his coat as a guarantee for the loan he makes.

**Comment by SusanQuigley** [comment]
20:16b UDB
And if he makes a pledge for **a immoral woman**, hold his coat as a guarantee for the loan he makes.
Please change the bold phrase to "**an** immoral woman"

20:16 ULB
and hold it in pledge **when put up security** for an immoral woman.
Please make the bold phrase "when **he** put**s** up security"

**Comment by TomWarren** [comment]
Thanks, 
The UDB of PRO 20:16 now reads:
\q2 And if he makes a pledge for an immoral woman, hold his coat as a guarantee for the loan he makes.
