### ISSUE TITLE
Num 31:14, 48 hundreds and thousands

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#423]
31:14 - ULB the officers of the army, the commanders of **thousands** and the captains of **hundreds**

UDB the army officers and the men who were commanders of **a thousand men** and those who were commanders of **a hundred men**

ULB and UDB do not agree.

The ULB says these men commanded many more than a thousand men or many more than a hundred men. But the UDB says they commanded a thousand or a hundred men. 

The Hebrew has plurals for thousand and hundred.

If you change the text here, the UDB has the same issue in 31:48.

**Comment by TomWarren** [comment]
Yes, the UDB of NUM 31:14 now reads:
\v 14 But Moses was angry with some of the men who had returned from the battle. He was angry with the army officers, those men who were commanders over thousands of men and those who were commanders over hundreds of men.

UDB of NUM 31:48 now reads:
\v 48 Then the army officers, those who were commanders over thousands of men and those who were commanders over hundreds of men, they came to Moses.
