### ISSUE TITLE
Gal 4:27  "is" to "are"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#425]
ULB: Cry out and shout for joy, you who **is** not suffering the pains of childbirth.

Suggested change: Cry out and shout for joy, you who **are** not suffering the pains of childbirth.

Could the verb "is" be changed to fit with "you"?

**Comment by TomWarren** [comment]
Yes, the ULB of GAL 4:27 now reads:
\v 27 For it is written,
\q "Rejoice, you barren one who does not give birth.
\q Cry out and shout for joy, you who **are** not suffering the pains of childbirth.
\q Because the children of the abandoned woman are more numerous than the woman who has a husband."
