### ISSUE TITLE
Pro 20:26 Metaphor?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#428]
ULB A wise king winnows the wicked
and he turns a threshing wheel over them. 

UDB A king who is wise will separate the wicked from among his people;
    then he will drive a threshing cart over their bodies to kill them.

Everywhere I have read describes "turns a threshing wheel over them" as a metaphor meaning he separates the wicked and destroys or punishes them. The UDB treats it as if it were literal.

Do you want to change the UDB to reflect the metaphor?

**Comment by TomWarren** [comment]
Yes, the UDB should unpack the metaphor. The UDB at PRO 20:26 now reads:
\v 26 A king who is wise will separate the wicked from among his people;
\q2 then he will severely punish those wicked people.
