### ISSUE TITLE
Hos 9:6 silver become like a wilderness

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#429]
UDB All your wealth in silver will become like the wilderness, 

To me this sounds a little odd. From what I found it is the places where they stored their silver that would become like a wilderness rather than the treasure itself.

**Comment by TomWarren** [comment]
This may be closer: 
The UDB of HOS 9:6 now reads:
\v 6 Look! If you escape and the Assyrians do not kill you,
\q2 the army of Egypt will capture you.
\q2 You will die there, and the people in the city of Memphis will bury you.
**\q1 All your wealth in silver will be covered up 
\q1 and lost when the desert plants grow into your homes and take them over.**
