### ISSUE TITLE
Php 1:20 ULB  Move second "that"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#432]
It is according to my eager expectation and certain hope that I will not be at all ashamed. But with all boldness, now as always, **that** Christ will be exalted in my body, whether by life or by death.

Could the word "that" before "Christ" either be deleted or be moved to follow the word "But"?

I think Paul had two expectations: 1) that he would not be ashamed and 2) that his boldness would result in Christ being exalted in his body. 

It is according to my eager expectation and certain hope that I will not be at all ashamed, **but that** with all boldness, now as always, Christ will be exalted in my body, whether by life or by death.

**Comment by TomWarren** [comment]
The ULB of PHP 1:20 now reads:
\v 20 It is according to my eager expectation and certain hope that I will not be at all ashamed, and yet with all boldness, now as always, Christ will be exalted in my body, whether by life or by death.
