### ISSUE TITLE
Jos 4:5 typo

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#433]
UDB a stone on his sholder

Misspelled "shoulder"

**Comment by TomWarren** [comment]
Misspelling in UDB JOS 4:5 now reads:
\v 5 and said to them, "Go into the middle of the Jordan riverbed, to the place where the priests are standing and holding the sacred chest that Yahweh, your God, gave you. Each of you must pick up a large stone, one for each tribe, each one carrying a stone on his **shoulder**—twelve stones for the twelve tribes of the people of Israel.
