### ISSUE TITLE
Eph 1:10 ULB Christ's work was a plan

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#435]
**Christ's work was a plan for the fullness of time,** to bring all things together, all things in heaven and on earth, under one head, even Christ.

I don't understand the first phrase. I'm guessing that "plan" is a translation of _oikonomian_. 

Suggestions:
For God had planned that in the fullness of time, he would bring all things in heaven and on earth together, under one head, even Christ.
or
God did this for his plan for the fullness of time to bring all things in heaven and on earth together, under one head, even Christ.

**Comment by TomWarren** [comment]
This seemed to be a case where cutting the sentence made it less understandable. 
The ULB of EPH 1:9-10 now reads:

\v 9 God made known to us the hidden purpose of his will, according to what pleased him, and which he demonstrated in Christ,
\v 10 with a view to a plan for the fullness of time, to bring all things together, all things in heaven and on earth, under one head, even Christ.

**Comment by SusanQuigley** [comment]
Does "with a view to a plan" mean that he did verse 9 because he was thinking about a plan?

**Comment by TomWarren** [comment]
"With a view" to a plan is rendering the phrase at the beginning of vs 10 : εἰς  οἰκονομίαν, this follows the use of eis, "unto" a bit more expansively.  God had hidden purposes, those purposes were in his will, and therefore they pleased him, and he demonstrated them (his purposes within his will) in Christ (in this manner) with a view to a broader plan for the fullness of time, to bring everything together in heaven and earth under one head, Christ.

This is very difficult reading and very deep theology. Hope this helps. 
TW

**Comment by SusanQuigley** [comment]
Thanks. What you wrote here is easier to understand. I'll try to update the notes to fit.

**Comment by SusanQuigley** [comment]
Have you made the change to the ULB yet? It's not showing up for me.

**Comment by TomWarren** [comment]
Sync should show.

**Comment by SusanQuigley** [comment]
It does. Thank you.
