### ISSUE TITLE
DEU 11:27-28 incomplete sentences

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#438]
ULB 27The blessing, if you will listen to the commandments of Yahweh your God that I command you today. 28And the curse, if you will not listen to the commandments of Yahweh your God, but turn aside out of the way that I command you today, to go after other gods that you have not known.

Verses 27 and 28 are not complete sentences. Perhaps they should be rewritten or have their punctuation (including the period at the end of v. 26) changed. Are commas needed after "blessing" and "curse"?

**Comment by TomWarren** [comment]
The ULB of DEU 11:26-28 reads as follows:

\v 26 Look, I set before you today a blessing and a curse:
\v 27 the blessing, if you obey the commandments of Yahweh your God that I command you today,
\v 28 and the curse, if you do not obey the commandments of Yahweh your God, but turn aside from the way that I command you today, to go after other gods that you have not known.


Note:  the rendering of "listen" seemed to risk confusion to the MTT. The instruction is that they would do what Yahweh commands, therefore, "obey" is best, and follows almost all modern versions.  This is a long sentence, but there are too many gymnastic moves in shortening it into three parts. It does chunk nicely. 

Thanks, 
TW
