### ISSUE TITLE
Eph 4:20  ULB vs UDB?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#439]
ULB: But this is not how you came to know Christ.
UDB: But when you learned about Christ you did not learn to live like that.

Should I understand the ULB as having the same meaning as the UDB, or is the ULB about coming into relationship with Christ?

Most versions use "learned", and the object of learned is "that" or "this", referring to the behavior of the Gentiles (in v. 19).

Could the ULB be something like this?
But that is not what you learned about Christ.

**Comment by TomWarren** [comment]
VS 20 is about the change that is effected in the lives of those who came to know Christ, and the break with sinful actions and desires. The central idea is "coming to know Christ."  The highlighted verse is where I made changes.

The UDB of EPH 4:19-21 now reads:

\v 19 They have chosen to do shameful things their bodies desire without stopping. They commit all kinds of immoral acts and are obsessed with them more and more, and they are greedy for anything they desire.

\s5
\p
**\v 20 When you came to know Christ, you put off those shameful and immoral actions and the greedy desires you once had.** 
\v 21 Now that you have heard about Jesus and he has taught you, you know that his way is the true way to live.

Thanks,
TW
