### ISSUE TITLE
Luk 1:79 UDB

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#44]
UDB changes from taking about the "Savior, who is like the rising sun" in v 78 to "His message" in v 79. I liked he shortened sentence, but think v 79 should start with "He..." to indicate that it is the Savior who will shine on them. This also fits better with "He" in the second sentence of v 79.

**Comment by hharrissWA** [comment]
Changed "His message will shine on people" to "He will shine on people..."
Perhaps a Note is needed for this figure of speech, too, if something is not already there?  :)
