### ISSUE TITLE
Eph 4:24 ULB  statement or command?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#441]
ULB: So now you put on the new man that is created in the image of God
UDB: You must start living like new persons.

Should I understand the ULB to be a statement or a command?
If it's a command, could the word "you" be deleted?

**Comment by TomWarren** [comment]
Seems to be a statement about what happens when you were taught about Christ. This is ULB EPH 4:24 as it now reads:
\v 24 and to put on the new man that is created in the image of God—in true righteousness and holiness.
