### ISSUE TITLE
2KI 22:15 God sent Huldah?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#443]
UDB Yahweh told Huldah to go back and tell the king who sent her

From what I can tell , this is not correct. God gave the message to Huldah. She then told the king's servants to speak the message to the king rather than going herself.

What is in the UDB now does not agree with the ULB or the UDB in 22:20

**Comment by TomWarren** [comment]
This chapter had many issues. The UDB of 2KI 22:15 now reads:
\v 15 She then told them what Yahweh the God whom the Israelites worship says, 
"Yahweh has a message for the king who sent you to me, and this is what Yahweh says:
\v 16 'Listen to this carefully. I am going to bring a disaster on Jerusalem and all the people who live here, which is what was written in the scroll that the king has read.

Thanks,
TW
