### ISSUE TITLE
2ki 22:16 missing word?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#444]
ULB See, I am about to bring disaster to this place and to its **inhabitants, all the words** of the book that the king of Judah has read

I believe this is correct according to the literal Hebrew, but it is  confusing. It is not clear how "all the words ..." relates to the previous clause. 

Some English versions say "according to all the words" or "fulfilling all the words."

Do you think this should be in the ULB or should I just write a note?

**Comment by TomWarren** [comment]
Seems like the ULB at 2KI 22:16 should be:
\v 16 "This is what Yahweh says: 'See, I will bring disaster to this place and to its inhabitants, according to everything written in the book that the king of Judah has read.

כָּל־דִּבְרֵ֣י has the sense of "according to all things/ words/ message / saying / utterance , etc" here "according to everything written."
