### ISSUE TITLE
Pro 26:23 ULB Backwards simile?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#445]
The glaze overlaying an earthen vessel
is like burning lips and an evil heart.

I expect that the topic in this simile is the burning lips and heart. Could this be reworded like one of these?
As glaze covers an earthen vessel,
so are burning lips with an evil heart.
or
As are glaze and an earthen vessel,
so are burning lips and an evil heart.
or 
Burning lips and an evil heart
are like glaze covering an earthen vessel.

**Comment by TomWarren** [comment]
The ULB of PRO 26:23 now reads:

\v 23 Like the glaze overlaying an earthen vessel
\q so are burning lips and an evil heart.

Thanks, 
TW
