### ISSUE TITLE
2KI 22:20 change "nor"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#446]
ULB See, I will gather you to your ancestors; you will be gathered to your grave **in peace, nor will** your eyes see

I don't believe this "nor" is correct grammatically since a negative does not precede it in the sentence. Should be "in peace, and your eyes will not see"

**Comment by TomWarren** [comment]
There were some unnecessary complications in the former ULB rendering. 
The ULB of 2KI 22:20 now reads:
\v 20 See, I will gather you to your ancestors, and you will be gathered to your grave in peace. Your eyes will not see all the disaster that I will bring upon this place.'"'" So the men took this message back to the king.
