### ISSUE TITLE
Deu 8:14 "become" or "becomes"?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#448]
ULB that then your heart **become** lifted up

This seems to make sense in an old English kind of way, but would it be better to say "that then your heart **becomes** lifted up" or "so that your heart **does not become** lifted up"

**Comment by TomWarren** [comment]
This was covered in the previous ISSUE. 
Thanks, 

The ULB of DEU 8:13-14 now reads:
\v 13 And be careful when your herds and flocks multiply and when your silver and gold increase, and all that you have is multiplied,
\v 14 then your heart becomes be lifted up and you forget Yahweh your God, who brought you out of the land of Egypt, out of the house of bondage.
