### ISSUE TITLE
Matt 24:15

### ISSUE THREAD

**Issue by pjoakes** [Door43/ulb-en#451]
Since the parenthetical comment is not part of Jesus' quoted speech, it seems there should be a close quote before it and an open quote after it. 
Also, shouldn't there be a note at each chunk of Matt 24 & 25 that says Jesus continues talking?

**Comment by SusanQuigley** [comment]
I'll add the connecting statements.

I would like to see the quote marks in the ULB of Mat 24:15 and 16 say:
Therefore, when you see the abomination of desolation, which was spoken of by Daniel the prophet, standing in the holy place**"** (let the reader understand), 16 **"**let those who are in Judea flee to the mountains,

**Comment by TomWarren** [comment]
The quotation marks have been added to MAT 24:15 and 16, and they now read:
\v 15 Therefore, when you see the abomination of desolation, which was spoken of by Daniel the prophet, standing in the holy place" (let the reader understand),
\v 16 "let those who are in Judea flee to the mountains,

This parenthetical expression only occurs in MAT 24:15, and MRK 13:14 (but there are no quotation marks in the latter). 

Thanks. 
Tom
