### ISSUE TITLE
Josh 22:7

### ISSUE THREAD

**Issue by pjoakes** [Door43/ulb-en#452]
Now to one-half of the tribe of Manasseh, Moses had given **them** an inheritance in Bashan, but to the other half, Joshua gave an inheritance beside their brothers in the land west of the Jordan. 

Delete "them."

**Comment by TomWarren** [comment]
THe ULB of JOS 22:7 now reads:
\v 7 Now to one-half of the tribe of Manasseh Moses had given an inheritance in Bashan, but to the other half Joshua gave an inheritance beside their brothers in the land west of the Jordan. Joshua sent them away to their tents; he blessed them
