### ISSUE TITLE
2KI 3:25 awkward wording

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#453]
"They stopped up all the springs of water and chopped down all the good trees, except in Kir Hareseth only, where they left the rocks in place."

This sentence is awkward. The "except" clause doesn't seem to have the right transition. Perhaps something like:

"They stopped up all the springs of water and chopped down all the good trees. They only left the rocks of Kir Hareseth in place."

**Comment by TomWarren** [comment]
The ULB of 2KI 3:25 was reworked. It now reads:
\v 25 They destroyed the cities, and on every good piece of land every man threw a rock until it was covered up. They stopped up every spring of water and chopped down all the good trees. Only Kir Hareseth was left with its rocks in place. But the soldiers armed with slings surrounded and attacked it.
