### ISSUE TITLE
JOS 2.24

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#456]
This verse is missing the closing quote mark.

24And they said to Joshua, "Truly Yahweh has given this land to us. All the inhabitants of the land are melting away because of us. 3 1Joshua got up early in the morning, and they set out from Shittim.

**Comment by TomWarren** [comment]
The ULB of JOS 2:24 now reads:
\v 24 And they said to Joshua, "Truly Yahweh has given this land to us. All the inhabitants of the land are melting away because of us."

with the closing quote. 

Thanks.
