### ISSUE TITLE
JOS 4:8

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#457]
This sentence seems to be a bit confusing. What do you think? Maybe break it into two sentences?

The people of Israel did just as Joshua commanded, and they picked up twelve stones from the middle of the Jordan, as Yahweh said to Joshua, they were set up in the same number as the tribes of the people of Israel.

**Comment by TomWarren** [comment]
The ULB of JOS 4:8 now reads:
\v 8 The people of Israel did just as Joshua commanded, and they picked up twelve stones from the middle of the Jordan, as Yahweh said to Joshua. They set the stones up according to the number of the tribes of the people of Israel. They carried the stones with them, over to the place where they camped and they set them down there.
