### ISSUE TITLE
JDG 18:17 Remove extra "and"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#458]
ULB they took the carved figure, the ephod, **and** the household gods, and the cast metal figure

Do not need the "and" before "the household gods"

**Comment by TomWarren** [comment]
The ULB of JDG 18:17 now reads:
\v 17 The five men who had gone to scout out the land went there and they took the carved figure, the **ephod, the household gods**, and the cast metal figure, while the priest stood by the opening of the gate with the six hundred men armed with weapons of war.

Thank you, 
TW
