### ISSUE TITLE
JDG 18:7 awkward wording

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#459]
Thank you so much for submitting a suggested change. We ask that you title the issue starting with the 3 letter code of the book followed by the chapter number colon then verse number(s).

ULB and they saw the people who were there were living in safety

This is a little awkward. Suggest: "and they saw that the people who were there were living in safety" or "and they saw how the people there were living in safety" or "they saw the people there living in safety"

**Comment by TomWarren** [comment]
The ULB of JDG 18:7 now reads:

\v 7 Then the five men left and came to Laish, and they saw that the people were living in safety, in the same way the Sidonians lived undisturbed and secure. There was no one who conquered them or who oppressed them in any way in the land. They lived far away from the Sidonians and had no dealings with anyone.

I may a few translation changes. Hope this is better.
Thanks, 

TW



Thanks, 
TW
