### ISSUE TITLE
JOS 20:9 Sentence Fragment

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#46]
So that this person would not die by the hand of the one who wanted to avenge the blood that was shed, until the accused person would first stand before the assembly.

This is a sentence fragment. Maybe change "So that" to "In this way" or "So,"

**Comment by hharrissWA** [comment]
fixed

**Comment by SusanQuigley** [comment]
Thank you, Harry.
On Apr 29, 2016, at 1:11 PM, hharrissWA <notifications@github.com<mailto:notifications@github.com>> wrote:


fixed
