### ISSUE TITLE
Jos 6:13 Reword

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#460]
ULB The seven priests carrying the seven trumpets of rams' horns in front of the ark of Yahweh, **and walking steadily, they gave blasts on the trumpets**

This last part of the sentence does not fit quite right with the first part. Suggestion: "The seven priests, who were carrying the seven trumpets of rams' horns in front of the ark of Yahweh, walked steadily and gave blasts on the trumpets"

**Comment by TomWarren** [comment]
\v 13 The seven priests, who were carrying the seven trumpets of rams' horns in front of the ark of Yahweh, walked steadily and gave blasts on the trumpets. Armed soldiers were walking in front of them. But when the rear guard walked after the ark of Yahweh, then the trumpets gave out continual blasts.

The ULB follows your suggestion.
Thanks. 

TW
