### ISSUE TITLE
JAS 1:4  Delete "in"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#461]
JAS 1:4 so that you may lack **in** nothing.

Could "in" be deleted? It would either be "so that you may **be lacking in** nothing" or "so that you may **lack nothing**."

**Comment by SusanQuigley** [comment]
Oh maybe I misunderstood.
I thought that "so that you may lack in nothing" meant "so that you may have all you need."
But the UDB says "so that you may follow Christ in every way."
Does "lack nothing" mean "have all you need" and "lack in nothing" mean "be all you should be"?

**Comment by TomWarren** [comment]
A clearer rendering is: "not lacking anything."
The ULB of JAS 1:4 now reads:
\v 4 Let endurance complete its work, so that you may become fully developed and complete, and not lacking anything.

**Comment by TomWarren** [comment]
The AT could be "lacking in nothing" (but it is more obtuse.

Thanks,
TW

**Comment by SusanQuigley** [comment]
Thanks for fixing both versions.

**Comment by TomWarren** [comment]
I didn't touch the UDB. If it is good, I can't take credit. It seems to align with the ULB. 

TW
