### ISSUE TITLE
1SA 12:8 Change period to comma

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#462]
ULB When Jacob came to Egypt, and your ancestors cried out to Yahweh. Yahweh sent Moses

Change period after "Yahweh" to a comma.

**Comment by TomWarren** [comment]
The ULB of 1SA 12:8 now reads:
\v 8 When Jacob came to Egypt, and your ancestors cried out to Yahweh, then Yahweh sent Moses and Aaron, who led your ancestors out of Egypt and they settled in this place.
