### ISSUE TITLE
1Ki 16:11 ULB awkward wording

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#464]
He left alive not a single male child, neither of his relatives nor of his friends

The first phrase is awkward. 

He did not leave alive a single male child, neither of his relatives nor of his friends
OR
He did not leave a single male child alive, neither of his relatives nor of his friends

Also, I don't know if "child" is needed. UDB  does not use it.

**Comment by TomWarren** [comment]
The ULB of 1KI 16:11 now reads:

\v 11 When Zimri began to reign and was seated on his throne, he killed all the family of Baasha. He did not leave alive a single male belonging to Baasha's relatives or friends.

Thank you, 

TW
