### ISSUE TITLE
MRK 15.28

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#466]
From the Swahili GL Translation Project:

The team working on the Swahili GL translation of Mark 15.28 found these errors (or at least they sure look like errors) in the [foot]note imbedded in the ULB text (not the translation Notes):

1. The verse note refers to Luke 22.3. The correct reference is Luke 22.37 

\v 28 \f + \ft The best ancient copies omit verse 28 (see Luke 22:3), vs 28, \fqa And the scripture was fulfilled that says, 'He was counted with the lawless ones.' \f*

2. The [foot]note is missing half of the questionable verse. The rest of the verse needs to be added to the [foot]note.

I don't know what they mean about the 2nd point. Could it be that they thought that the quote from the verse in Luke? Maybe the reference to Luke is confusing?

**Comment by TomWarren** [comment]
The reference within the footnote was correction from LUK 22:3 to read now: 
LUK 22:37. 

The omitted verse is "vs 28, \fqa And the scripture was fulfilled that says, 'He was counted with the lawless ones.' \f*  

The order of the material was rearranged to make it more clear:

**The best ancient copies omit MRK 15:28, And the scripture was fulfilled that says, 'He was counted with the lawless ones.' (compare LUK 22:37)**

Hope that helps.
TW

**Comment by ChrisJarka** [comment]
Yes, that does seem much clearer. Thank you.
