### ISSUE TITLE
1SA 5:7 "god" or "God"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#467]
UDB The **god of the Israelites** is punishing us and our god Dagon. So we cannot allow the sacred chest of the **God of the Israelites** to remain here!"

When the Philistines are talking should "God of the Israelites" be capitalized or not? In 1 Sa 5:8 when the Philistines speak, "God of Israelites" is capitalized.

**Comment by TomWarren** [comment]
It is a bit of a reach to put "God of Israel" on the lips of the Philistines, yet for the reality of the situation, and for more simplicity for the MTT, it should be "God of Israel." 

The UDB of 1SA 5:7 now reads: 

\v 7 The people of Ashdod realized why this was happening, and they cried out, "The God of the Israelites is punishing us and our god Dagon. So we cannot allow the sacred chest of the God of the Israelites to remain here!"

I checked the ULB and it consistently uses "God of Israel" even on the lips of idolaters.  It is a bit of an accommodation, but a small one. 

Thanks, 

Tom
