### ISSUE TITLE
2ki 15:10  ULB vs UDB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#468]
ULB  attacked him **in front of the people**,
UDB  killed him **in the city of Ibleam**

ULB translates qaval 'am.
UDB translates bə ivle'am.

Would you want them to be the same?

**Comment by TomWarren** [comment]
The ULB was changed to read 2KI 15:10:
\v 10 Shallum son of Jabesh conspired against Zechariah, attacked him in Ibleam, and killed him. Then he became king in his place.
;
There was a note in ParaTExt:
Remark: 1. An old exegetical tradition of the Pharisees interprets this expression as "before the people". 2. Some of the Septuagint witnesses give a transcription of the MT, while others read here the name of the town, "Ibleam". 3. One half of the Committee gave the MT the rating C, while the other half preferred the Septuagint variant, "Ibleam", with the rating D. Translators may choose either reading.

There is a 50/50 split. In such cases we usually (and properly) follow the MT, but usually with a footnote. 
I will forward this to Jim Pohlig for the footnote.

Thanks.
TW
