### ISSUE TITLE
"Savior/savior"

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#47]
I am seeing an inconsistent capitalization of "Savior/savior" especially in the ULB NT. May be elsewhere. Both ways referring to Christ.

Also, we have both "God our Savior" and "God our savior"

**Comment by hharrissWA** [comment]
Which way should it be? Has a decision been made about whether it should be capitalized or not?

**Comment by lrsallee** [comment]
Harry,

I don’t know. That’s a decision for Jim or Tom.

Larry

**Comment by hharrissWA** [comment]
Ok, that's what I figured, but wanted to see if it had already been clearly determined.

Thanks Larry,

Harry


C. Harry Harriss

Associate Editor, Unfolding Word Bible

Translation Consultant (in training)

Wycliffe Associates and Wycliffe India

harry_harriss@wycliffeassociates.org<mailto:harry_harriss@wycliffeassociates.org>

662-890-5637 home



________________________________

**Comment by TomWarren** [comment]
Like king, as a title, Our Savior Jesus Christ would work. But Jesus is our savior. Like King David, he was the king of Israel. When it becomes a title, caps, when it describes his work, lower case savior.

**Comment by lrsallee** [comment]
Tom,

I’ve seen several places where that isn’t consistently followed. I’ll let you and Harry sort out who checks into that.

Larry

**Comment by BramvandenHeuvel** [comment]
Larry, thanks for the update. Capitals were assigned to me, so one of these days I'll make a sweep through the ULB NT.
