### ISSUE TITLE
2ki 15:17  ULB "began the reign of"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#470]
ULB: began the reign of Menahem son of Gadi over Israel

Could this be changed to this?
Menahem son of Gadi began to reign over Israel

Please see my next comment about 2 Kings 15:1 "began his reign"

**Comment by TomWarren** [comment]
The ULB of 2KI 15:17 now reads;
\v 17 In the thirty-ninth year of Azariah king of Judah, Menahem son of Gadi began to reign over Israel; he reigned ten years in Samaria.

Thanks.

**Comment by SusanQuigley** [comment]
Tom, thanks for making all these changes.
