### ISSUE TITLE
15:1 ULB began his reign

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#471]
ULB: Azariah son of Amaziah king of Judah **began his reign**.

2 Kings has "began to reign" 29 times.
This is the only time it has "began his reign".
Could 15:1 have "began **to** reign" instead so that it matches the rest?

**Comment by TomWarren** [comment]
The ULB of 2KI 15:1 now reads:

\v 1 In the twenty-seventh year of Jeroboam king of Israel, Azariah son of Amaziah king of Judah began to reign.
