### ISSUE TITLE
1SA 6:19 UDB and ULB very large number in the MT

### ISSUE THREAD

**Issue by TomWarren** [Door43/ulb-en#472]
The MT has 50,070 with almost unanimous concurrence from all extant manuscripts.  Some very late and weak MSS have 70. 
Our ULB and UDB have 70.

The NET alone (from a brief survey) has 50,070, and almost all modern versions have simply "70". 

The NAB, NIV, NRSV, NLT reject the MT and follow the weak and late witnesses. 
The MT and the ancient versions would support the larger (and to some, the impossibly large) number of 50,070. 
If the current versions are followed, it should have a note that the ancient MSS have a strong witness for the larger number.

This is the NET note on 1SA 6:19:
l 6:19 12 Textual Criticism The number 50,070 is surprisingly large, although it finds almost unanimous textual support in the MT and in the ancient versions. Only a few medieval Hebrew mss lack “50,000,” reading simply “70” instead. However, there does not seem to be sufficient external evidence to warrant reading 70 rather than 50,070, although that is done by a number of recent translations (e.g., NAB, NIV, NRSV, NLT). The present translation (reluctantly) follows the MT and the ancient versions here.
m 6:20 13 Translator's Note Heb “he” or “it”; the referent here (the ark) has been specified in the translation for clarity (cf. also NIV, CEV, NLT). Others, however, take the referent to be the LORD himself.

**Comment by SusanQuigley** [comment]
It should be 1 Samuel 6:19.

**Comment by TomWarren** [comment]
Sorry to have popped up a curve. 
ULB 1SA 6:19 is the target. 
I changed the title of this ISSUE to help.

**Comment by TomWarren** [comment]
I added a footnote to ULB 1SA 6:19:
\v 19 Yahweh attacked some of the men of Beth Shemesh because they had looked into the ark of Yahweh. He killed 50,070 men.\f + \ft Some later copies have: \fqa ... seventy men. \fqb \f* The people mourned, because Yahweh had given the people a great blow.

The USFM has:
ULB:

19 Yahweh attacked some of the men of Beth Shemesh because they had looked into the ark of Yahweh. He killed 50,070 men.[1] The people mourned, because Yahweh had given the people a great blow. 20The men of Beth Shemesh said, "Who is able to stand before Yahweh, this holy God? To whom will the ark go up from us?"
[1]Some later copies have: ... seventy men.
