### ISSUE TITLE
MAT 24.51

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#473]
Matthew 24:51 has “weeping and gnashing of teeth” 24.51

Matthew  8:12, 13.42, 13.50, 22.13, & 25.30 uses “weeping and grinding of teeth”   

I’m wondering about consistency.

 tR

**Comment by TomWarren** [comment]
The pattern, "grinding" is the accepted rendering of the quaint, "gnashing." 
The ULB of MAT 24:51 now reads:
\v 51 His master will cut him in pieces and make his fate the same as that of the hypocrites, where there will be weeping and grinding of teeth.
