### ISSUE TITLE
MAT 25.26

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#474]
It now has:

\v 26 But his master answered and said him,

Should it be?
\v 26 But his master answered and said **_to_** him,

tR

**Comment by TomWarren** [comment]
The ULB of MAT 25:26 now reads:
\v 26 But his master answered and said to him, 'You wicked and lazy servant, you knew that I reap where I have not sowed and harvest where I have not scattered.

Thanks, 
TW
