### ISSUE TITLE
1SA 23:19 Different spelling

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#475]
ULB and UDB have two different spellings.

ULB Hachilah

UDB Hakilah

**Comment by TomWarren** [comment]
See also: 
ULB has 1SA 23:19, and 26:1; 3, 
UDB has 1SA 23:19, 26:1, 3, 4.

The preferred spelling follows the ULB, Hachilah.
The UDB of 1SA 23:19 now reads: 

\v 19 Some people from Ziph went to Saul when he was at Gibeah, and they told him, "David and his men are hiding in our land! They are hiding in places at Horesh on the hill of Hachilah, south of a place named Jeshimon.

Thanks, 
TW
