### ISSUE TITLE
1Sa 25:2-3 Missing phrase in UDB and possible reordering of UDB

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#476]
I noticed that the UDB does not refer to Nabal being in Carmel shearing his sheep as mentioned at the end of verse 2 in the ULB.

But, I also wanted to bring up an extremely long note that a reviewer wrote about reordering the ULB sentences. The note says this:

> Some translators may need to put these ideas in a different order. AT: "There was a man whose name was Nabal, a descendant of the house of Caleb, who was very wealthy. He lived in Maon, but his possessions were in Carmel: he had three thousand sheep and one thousand goats. The man was harsh and evil in his dealings. The name of his wife was Abigail. The woman was intelligent and beautiful in appearance. Now he was shearing his sheep in Carmel." 

If you like this reordering, could we change the UDB to be closer to what the note has so we can delete the note?

**Comment by TomWarren** [comment]
The UDB of 1SA 25:2-3 now reads:
\v 2 In the town of Maon there was a very rich man. This man kept his property and livestock in a town nearby that is called Carmel. He had much property and livestock and he owned three thousand sheep and one thousand goats. Carmel is where he sheared his sheep.
\v 3 His name was Nabal; he was a descendant of Caleb. His wife Abigail was a wise and beautiful woman, but Nabal was very cruel and treated people very unkindly.

Perhaps the note can be removed. Your call.

Thanks,
TW
