### ISSUE TITLE
2KI 9:37 need a verb here

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#477]
and the body of Jezebel shall be like dung the fields in the land at Jezreel,..."

Perhaps: "like dung in the fields" or "like dung scattered in the fields"

**Comment by TomWarren** [comment]
The ULB of 2KI 9;37 now reads:

\v 37 and the body of Jezebel will be like dung on the surface of the fields in the land at Jezreel, so that no one will be able to say, "This is Jezebel."'"

Hope that helps, and thanks very much!


TW
