### ISSUE TITLE
2ki 15:25 ULB delete "the"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#479]
2ki 15:25 ULB a captain serving **the** Pekahiah

Please delete "the"

**Comment by TomWarren** [comment]
Some sorting out for clarity in this narrative. 
The ULB of 2KI 15:25 now reads:

\v 25 Pekahiah had an officer named Pekah son of Remaliah, who conspired against him, and along with fifty men of Gilead, Pekah killed Pekahiah as well as Argob and Arieh in Samaria, in the citadel of the king's palace. Pekah killed Pekahiah and became king in his place.

A twisted tale.

**Comment by SusanQuigley** [comment]
That is much easier to read, but now the ULB and UDB do not match.

In the UDB, Argob and Arieh helped kill the king.
In the new ULB it looks like Argob and Arieh were killed.

The ULB was ambiguous about this before, so I had the following translation note:
**with Argob and Arieh** - Possible meanings are that 1) Argob and Arieh were part of Pekah's group that killed Pekahiah, or 2) Pekah also killed Argob and Arieh.

**Comment by TomWarren** [comment]
Just didn't get around to the UDB ....
The UDB of 2KI 15:25 now reads:

\v 25 Then one of Pekahiah's army commanders whose name was Pekah son of Remaliah, planned with fifty men, from the region of Gilead to kill Pekahiah and two of his assistants, Argob and Arieh. They assassinated the king in a fortified place in the king's palace in Samaria. Then Pekah became the king.

**Comment by SusanQuigley** [comment]
OK. Thank you.

**Comment by TomWarren** [comment]
I read through and stream-lined it a bit.  See bold. 

\v 25 Pekahiah had an officer named Pekah son of Remaliah, who conspired against him. Along with fifty men of Gilead, Pekah killed Pekahiah as well as Argob and Arieh in Samaria, in the citadel of the king's palace. Pekah killed Pekahiah and became king in his place.

**Comment by SusanQuigley** [comment]
That's even easier. Thanks.
