### ISSUE TITLE
2ki 15:23 ULB began the reign

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#480]
ULB began the reign of Jotham son of Azariah, king of Judah.

Could this be changed to this?
Jotham son of Azariah, king of Judah began to reign

**Comment by TomWarren** [comment]
Yes. The ULB of 2KI 15:23 now reads:
\v 32 In the second year of Pekah son of Remaliah, king of Israel, Jothan son of Azariah, king of Judah, began to reign.

Thanks,

TW
