### ISSUE TITLE
1Sa 22:3 ULB/UDB spelling discrepancy

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#482]
ULB Mizpeh

UDB Mizpah

These are spelled differently.

**Comment by TomWarren** [comment]
Also:
Jos 13:26 changed to Mizpah
Jos 18:26 changes to Mizpah
1SA 22:3 changed to Mizpah
(the standard that we were told to follow was the spelling of the NIV).

Your Issue:
The ULB of 1SA 22:3 now reads:
\v 3 Then David went from there to **Mizpah** in Moab. He said to the king of Moab, "Please let my father and my mother go out with you until I know what God will do for me."

And further on: 

The UDB at JOS 13:26 was changed: 
\v 26 Their land extended from Heshbon to Ramath **Mizpah** and Betonim, all the way to Mahanaim and to the region of Debir.

Should be all of them.

Thanks,

TW

**Comment by TomWarren** [comment]
I resent the link to this issue to Perry and Jim.
