### ISSUE TITLE
Ezr 6:5 ULB  "the temple in Babylon"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#483]
Ezr 6:5 ULB: that Nebuchadnezzar brought from the temple in Jerusalem to **the temple in** Babylon

The Hebrew does have anything about **a temple** in Babylon.
Could "to the temple in Babylon" be changed to "to Babylon" ?

**Comment by TomWarren** [comment]
The ULB  of EZR 6:5 was reworded, it now reads:

\v 5 Now bring back the gold and silver objects belonging to the house of God, which Nebuchadnezzar brought to Babylon from the temple in Jerusalem and  send them back to the temple in Jerusalem. You are to put them in the house of God.'

Thanks, 
TW
