### ISSUE TITLE
2sa 23:7 UDB punctuation

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#484]
UDB Someone who wants to get rid of thornbushes does **not grab them.**
but he uses an iron shovel or a spear to dig them out 

I think the period after "them" should be a comma.

**Comment by TomWarren** [comment]
Comma is it. 
The UDB of 2SA 23:7 now reads:
\v 7 Someone who wants to get rid of thornbushes does not grab them,
\q2 but he uses an iron shovel or a spear to dig them out
\q2 and then he burns them completely."

Thanks,
TW
