### ISSUE TITLE
2ki 6:6-9 "warning" or "warnings"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#486]
In this passage, Elisha sends warnings to the king of Israel about where he should go to avoid the king of Aram. 

It is clear in verse 10 that Elisha sent more than one warning. But, in verse 10 and 11 it has the singular "that warning" and "this warning." 

The Hebrew is singular, but would these make more since as plural "those warnings" and "these warnings"

**Comment by TomWarren** [comment]
The ULB of 2KI 6:10-11 now reads:
\v 10 The king of Israel send a message to the place about which the man of God had spoken and warned him. More than once or twice, when the king went there, he was on his guard.
\v 11 The king of Aram was enraged about these warnings, and he called his servants and said to them, "Will you not tell me who among us is for the king of Israel?"

Hope that is clear and close to the HEB text. 
Thanks,
TW

**Comment by jhutchins25** [comment]
Hello Tom,

"The king of Israel send"

Should this be "The king of Israel sent" or "The king of Israel would send"

**Comment by TomWarren** [comment]
\v 10 The king of Israel sent a message to the place about which the man of God had spoken and warned him. More than once or twice, when the king went there, he was on his guard.

**Comment by jhutchins25** [comment]
Thanks. I didn't know if you would get my email if I replied to this
message. That is why I sent it to you in outlook as well.

John
