### ISSUE TITLE
NEH 3:14 typo?

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#487]
Malchijah son of Rechab, the ruler of the district of Beth Hakkerem, repaired the Dung Gate. He built it and set its doors, its bolts and its bars.

Is a comma needed after bolts?

**Comment by TomWarren** [comment]
For clarity the comma helps.
THe ULB of NEH 3:14 now reads:
\v 14 Malchijah son of Rechab, the ruler of the district of Beth Hakkerem, repaired the Dung Gate. He built it and set its doors, its bolts, and its bars.

Thanks, Kim,

Tom
