### ISSUE TITLE
NEH 3:19 awkward verb construct

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#488]
"Next to him repaired Ezer son of Jeshua, the ruler of Mizpah, who repaired another section opposite the ascent to the armory, at the corner of the wall."

The active verb-subject construction is awkward and will definitely be for our MTT friends. Perhaps:

"Next to him, Ezer son of Jeshua, the ruler of Mizpah,  repaired another section opposite the ascent to the armory, at the corner of the wall."

**Comment by TomWarren** [comment]
It was a tangle, 
The ULB of NEH 3:19 now reads:
\v 19 Next to him, Ezer son of Jeshua, the ruler of Mizpah, repaired another section that faced the ascent to the armory at the corner of the wall.

Thanks, Kim, 

Tom
