### ISSUE TITLE
NEH 3:26-27 tower

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#489]
"... on the east of the projecting tower. 27After him the Tekoites repaired another section, opposite the great tower that stands out, as far as the wall of Ophel."

Here the same phrase in the Hebrew is translated two different ways: "projecting" and "that stands out." Both of these "tower" references likely refer to the same tower. The only difference is the second occurrence adds the adj. "great." Perhaps these phrases can be made the same, that is, with the second being modified by "great."

**Comment by TomWarren** [comment]
The ULB of NEH 3:26-27 now reads;
\v 26 Now the temple servants living in Ophel repaired to the point opposite the Water Gate on the east and the projecting tower.
\v 27 After him the Tekoites repaired another section that was opposite the great projecting tower as far as the wall of Ophel.
