### ISSUE TITLE
Ezr 6: 12  Missing phrase? 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#491]
ULB: any king and people who **violates** this house of God in Jerusalem
UDB: any king or any nation that **tries to change this decree or tries to destroy** that temple in Jerusalem

Hebrew has two verbs: lehashnayah "change" and lehabbalah "destroy"
ULB is either missing the first, or it conflates the two verbs into one.
UDB and other versions make explicit that the object of "change" is the king's decree. 
Would you want that in the ULB?

**Comment by TomWarren** [comment]
The ULB of EZR 6:12 now reads:
\v 12 May the God who has caused his name to dwell there overthrow any king or people who lifts a hand to change this decree, or to destroy this house of God in Jerusalem. I, Darius, am ordering this. Let it be done with diligence!"

Thanks. 

Tom

**Comment by SusanQuigley** [comment]
Nice. Even better than I asked for! Thank you.
