### ISSUE TITLE
REV 14.2 & 18.22 tr

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#494]
Rev 14.2 states:

2 I heard a voice from heaven sounding like a roar of many waters and loud thunder. The sound I heard was also like **_harpists_** playing their harps.

Rev 18.22 states:

22 The sound of **_harpers_**, musicians,
flute players, and trumpeters 
will not be heard anymore in you. 

The reader thinks that maybe both should be harpist and harpists.

**Comment by TomWarren** [comment]
Harpists is the more accepted descriptor, and so it used here. 

The ULB of REV 18:22 now reads:
\v 22 The sound made by harpists, musicians,
\q3 flute players, and trumpeters
\q2 will not be heard anymore in you.
\q No craftsman of any kind
\q2 will be found in you.
\q No sound of a mill
\q2 will be heard anymore in you.

Thanks, 

Tom Warren
