### ISSUE TITLE
1TI 4.9 tr

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#495]
1TI 1:15 reads:
This message is reliable and worthy of all acceptance, that Christ Jesus came into the world to save sinners. I am the worst of these.

1TI 4.9 reads:
This message is trustworthy and worth full acceptance.

The readers wonder if 1TI 4.9 should read:
trustworthy and worthy of acceptance

**Comment by TomWarren** [comment]
The ULB of 1TI 4:9 now reads:
\v 9 This message is trustworthy and worthy of full acceptance.

The adj ἄξιος· means "worthy." 

Thanks,

Tom
