### ISSUE TITLE
GAL 2:17 tr

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#496]
17But if, while we **_seek to be justify_** in Christ, we too, were found to be sinners, does Christ then promote sin? Absolutely not!

Should it read?
17But if, while we **_seek to be justified_** in Christ, we too, were found to be sinners, does Christ then promote sin? Absolutely not!

**Comment by TomWarren** [comment]
Yes, 
The ULB of GAL 2:17 now reads:
\v 17 But if, while we seek to be justified in Christ, we too, were found to be sinners, does Christ then promote sin? Absolutely not!

Thanks, 

Tom
