### ISSUE TITLE
MAT 23.25 tr

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#497]
25 Woe to you, scribes and Pharisees, hypocrites! For you clean the outside of the cup and of the plate, but **_inside they are full_** of greed and self-indulgence. 26 You blind Pharisee! Clean first the inside of the cup and of the plate, so that the outside may become clean also.

The reader is asking if instead of the "they" it should be "you".

**Comment by TomWarren** [comment]
The ULB is correct. The GRK has the 3rd person plural for the verb in the second phrase.  The GRK is γέμουσιν, "they are full of".

It may be that there is a misunderstanding. The phrase refers to the cups and dishes, and by extension the Pharisees.  They cleaned the outside of things, but they didn't clean the inside of them. 

A bit of a paraphrase, "You clean the outside of the cups and dishes, as you Pharisees love to do, but inside the cup and dishes they are full of greed and self-indulgence, just like you."

Thanks, 

Tom Warren
