### ISSUE TITLE
Mat 19:4 ULB em-dash?

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#5]
Since this verse ends with a rhetorical question, and the next verse is a new sentence in a new chunk, it seems like this verse should end with a question mark and not with an em-dash.

**Comment by TomWarren** [comment]
I put a period and closed the quote on Mt 19:4. And corrected some "level 2" quotes (') that should have been "level 1" (").

**Comment by lrsallee** [comment]
Thanks.
