### ISSUE TITLE
Ezr 7:14 ULB  Restrictive or Non-Restrictive Relative clause?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#506]
I, the king, and my seven counselors, send you all out to inquire concerning Judah and Jerusalem according to **God's law that you understand**,

The phrase "that you understand" sounds like a restrictive relative clause -- with the implication that Ezra does not need to be concerned with the parts of God's law that he does not understand. 

Could it be changed to this?
I, the king, and my seven counselors, send you all out to inquire concerning Judah and Jerusalem according to **God's law, which you understand**,

**Comment by TomWarren** [comment]
There is an issue with the "in your hand" and the many ways that is translated. Here it appears that Ezra is carrying a portion of the Law with him, "in his hand." 

The ULB of EZR 7:14-15 now reads:
\v 14 I, the king, and my seven counselors, send you all out to inquire concerning Judah and Jerusalem according to God's law, which is in your hand.
\v 15 You are to bring the silver and gold that they have freely offered to the God of Israel, whose dwelling is in Jerusalem.

This section changed passive into active, which would normally be consigned to the UDB. 

Tom
