### ISSUE TITLE
PHP 2:1 tr

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#513]
1 **_I suppose_** then that there is encouragement in Christ. **_I suppose_** that there is comfort from his love. **_I suppose_** that there is fellowship of the Spirit. **_I suppose_** that there are tender mercies and compassions. 

The readers are uncomfortable with the use of 'I suppose'. They quote the phrases used in the NIV, ESV, &NASB as being: **if any** comfort from his love, **if any** common sharing in the Spirit, **if any** tenderness ...

**Comment by TomWarren** [comment]
That was an odd "translation."
The ULB of PHP 2:1-2 now reads: 
\v 1 If there is any encouragement in Christ, if there is any comfort from his love, if there is any fellowship of the Spirit, if there are any tender mercies and compassions,
\v 2 then make my joy full by thinking alike, having the same love, being united in spirit, and having the same purpose.
