### ISSUE TITLE
PHP 2:8 tr

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#514]
8He humbled himself and became obedient **_until death_**, the death of the cross. 

The readers interpret the words 'until death' to mean until the point of death and not through his death. They suggested using the word "unto" instead of "until".

Where the following versions have:
NIV - becoming obedient to death-- even death on a cross!
ESV - becoming obedient to the point of death, even death 
NASB -  by becoming obedient to the point of death, even

**Comment by TomWarren** [comment]
The ULB of PHP 2:8 now reads:
\v 8 He humbled himself and became obedient to the point of death,
\q even death of a cross!
