### ISSUE TITLE
Ezk 45:14  ULB "kor" to "cor"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#516]
Ezk 45:14 ULB The regulation offering of oil will be a tenth of a bath for every **kor** (which is ten baths)

Please change "kor" to "cor" to match the other verses that use this word.

ULB spellings of kor/cor.

1ki 4:22 Solomon's provision for one day was thirty **cors** of fine flour and sixty **cors** of meal,
1ki 5:11 Solomon gave Hiram twenty thousand **measures** of wheat for food to his household and twenty **measures** of pure oil.
2ch 2:10 twenty thousand **cors** of ground wheat, twenty thousand **cors** of barley
2ch 27:5 ten thousand **measures** of wheat, ten thousand **measures** of barley
Ezr 7:22 up to one hundred silver talents, one hundred **cors** of grain,
Ezk 45: 14 The regulation offering of oil will be a tenth of a bath for every **kor** (which is ten baths)

**Comment by TomWarren** [comment]
Kor was changed to cor where it occurs.
EZE 45:14 ULB
\v 14 The regulation offering of oil will be a tenth of a bath for every cor (which is ten baths), or for every homer, since a homer is also ten 

Thanks,

Tom
