### ISSUE TITLE
Ezra 7:27; 8:15

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#517]
"Ezra said" in these verses is not in the Heb. The lengthy direct quotes that follow are not needed. It would be better to delete "Ezra said" and have a note that Ezra spoke of himself as if he were someone else in the earlier part of the book and is now speaking autobiographically. He goes to speaking of himself in third person in chapter 10.

**Comment by TomWarren** [comment]
This may have been an attempt to carry the quotation across the chunk. But that isn't necessary. 
The two chunks at EZR 7:25-28 now read:
\s5
\v 25 Ezra, with the wisdom that God has given you, you must appoint judges and discerning men to serve all the people in the Province Beyond the River, and to serve anyone who knows the law of your God. You must also teach those who do not know the law.
\v 26 Punish anyone who does not fully obey God's law or the king's law, whether by death, banishment, confiscation of their goods, or imprisonment.

\s5
\p
\v 27 Praise Yahweh, our ancestors' God, who placed all this into the king's heart to glorify Yahweh's house in Jerusalem,
\v 28 and who extended covenant faithfulness to me before the king, his counselors, and all his powerful officials. I have been strengthened by the hand of Yahweh my God, and I gathered leaders from Israel to go with me."


Thanks,

TW

**Comment by hmw3** [comment]
How about 8:15?

**Comment by TomWarren** [comment]
I worked through the quotation marks to make them consistent. People love changing quotation marks!

The ULB of EZR 8:15 now reads: without the  "I said" .....

\v 15 I gathered the travelers at the canal that goes to Ahava, and we camped there three days. I examined the people and priests, but could not find any descendants of Levi there.

Thanks, Henry


TW
