### ISSUE TITLE
Ezr 8:3 ULB  Missing words?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#518]
Of the descendants of Shecaniah, descendants of Parosh: Zechariah. With him were listed 150 males.

It looks like some words may be missing. I don't know what it means.

**Comment by TomWarren** [comment]
Tried to clean up some confusing use of the colon ... and ... the wording of the geneaology.

The ULB of EZR 8:3 now reads:
\v 3 Of the descendants of Shecaniah, who was from the descendants of Parosh; and Zechariah, and with him there were 150 males registered in the record of his genealogy.

a mess...

TW

**Comment by SusanQuigley** [comment]
Tom, thanks for fixing this.  
**Typo**: The end of v 3 has both "there were" and "were."
and Zechariah, and with him **there were** 150 males **were** listed in the record of his genealogy.

**Question**: I'm trying to write the notes for this. Is this how I should understand "of" and "for" and the colon? 

The leader of the descendants of Phinehas was Gershom.
The leader of the descendants of Ithamar was Daniel.
The leaders of the descendants of David were Hatush and Zechariah.
Hatush was a descendant of Shecaniah who was a descendant of Parosh. 
With Zechariah there were 150 males were listed in the record of his genealogy.

**Comment by TomWarren** [comment]
Got rid of the extra **were**.
I think your reading of the genealogy is right. They are a puzzle for MTTs. 

Thanks,

Tom

**Comment by SusanQuigley** [comment]
Ok. Thanks, Tom.
