### ISSUE TITLE
8:16 ULB vs UDB Elnathan?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#519]
ULB: So I sent for Eliezer, Ariel, Shemaiah, **Elnathan**, Jarib, and **Elnathan** and Nathan, Zechariah, and Meshullam—who were leaders—and for Joarib and **El Nathan**—who were teachers.

UDB: So I summoned Eliezer, Ariel, Shemaiah, **El Nathan**, Jarib, Nathan, Zechariah, and Meshullam, who were all leaders of the people. I also summoned Joiarib and another **El Nathan**, who were teachers.

ULB has two men named Elnathan, and one named El Nathan.
UDB has two men named El Nathan.

Should the ULB and UDB have the same number and the same spellings?
Should I include a note that the listing of two leaders by that name may have been an accidental repetition in an early text?

**Comment by TomWarren** [comment]
All modern versions have "Elnathan" it means Gift of God (El God, nathan, gift). The UBS Handbook notes that there are three people mentioned as Elnathan, and they suggest that they were three different individuals having the same name. 

ULB at EZR 8:16 now reads:
\v 16 So I sent for Eliezer, Ariel, Shemaiah, Elnathan, Jarib, and Elnathan and Nathan, Zechariah, and Meshullam—who were leaders—and for Joarib and Elnathan—who were teachers.

The UDB of EZR 8:16 now reads:
\v 16 So I summoned Eliezer, Ariel, Shemaiah, Elnathan, Jarib, another Elnathan, Nathan, Zechariah, and Meshullam, who were all leaders of the people. I also summoned Joiarib and one more man named Elnathan, who were teachers.

Thanks, 

Tom
