### ISSUE TITLE
Ezr 8:33 ULB Comma or period needed

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#524]
Then on the fourth day the silver, gold, and objects were weighed out in our God's house into the hand of Meremoth son of Uriah the priest***** and with him were Eleazar son of Phinehas, Jozabad son of Jeshua, and Noadiah son of Binnui the Levite. 

Could there be a comma or period where I put the asterisk?

**Comment by TomWarren** [comment]
The ULB of EZR 8:33 now reads: 
\v 33 Then on the fourth day the silver, gold, and objects were weighed out in our God's house into the hand of Meremoth son of Uriah the priest, and with him were Eleazar son of Phinehas, Jozabad son of Jeshua, and Noadiah son of Binnui the Levite.

Thanks,
Tom
