### ISSUE TITLE
HEB 8:5  tr

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#526]
v 5 They serve a copy and shadow of the heavenly things. It is just as Moses was warned by God when he was about to construct the tabernacle: "See," God said, "that you make everything according to the pattern that was shown to you on the mountain."

verse 5 seems to be missing a verb. 
v 5 They serve **_as_** a copy and shadow of the heavenly things.

**Comment by pjoakes** [comment]
Interrupting the quote after the first word makes it difficult to read: "See," God said, "that you make everything..." Better would be: God said, "See that you make everything..."

**Comment by TomWarren** [comment]
The ULB of HEB 8:5 now reads: 

\v 5 They serve **as** copy and shadow of the heavenly things. It is just as Moses was warned by God when he was about to construct the tabernacle: **God said, "See** that you make everything according to the pattern that was shown to you on the mountain."
