### ISSUE TITLE
Est 5:11 ULB Missing phrase?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#527]
Eat 5:11 ULB:  Haman recounted to them the splendor of his riches and the number of his many sons,  * how he had advanced above all the officials and the servants of the king.

This does not say anything about the **king** promoting him. This clause would go where I put the asterisk.

**Comment by TomWarren** [comment]
That was an omission. Thanks for seeing it. 
The  ULB of EST 5:11 now reads:
\v 11 Haman recounted to them the splendor of his riches, the number of his many sons, all the promotions with which the king honored him, and how he had advanced above all the officials and the servants of the king.

Blessings on you, 
Tom

**Comment by SusanQuigley** [comment]
Looks great. Thank you.
