### ISSUE TITLE
1SA 15:27 Change "Saul" to "Samuel"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#529]
UDB As Samuel turned to leave, Saul tried to stop him by grabbing **the edge of Saul's robe**, and it tore.

I believe this should be "the edge of Samuel's robe"

**Comment by TomWarren** [comment]
The UDB of 1SAM 15:27 now reads:
\v 27 As Samuel turned to leave, Saul tried to stop him by grabbing the edge of Samuel's robe, and it tore.

Thanks, John,
Tom
