### ISSUE TITLE
Gal 6:8 ULB

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#53]
This is odd phrasing in English. How do we "harvest out from"?????

"will harvest corruption out from his flesh"

It should simply be "will harvest corruption from his flesh". Someone tried too hard to add extra meaning to "εκ"

**Comment by TomWarren** [comment]
\v 8 For he who sows seed to his own sinful nature will gather a harvest of destruction. But he who sows seed to the Spirit, from the Spirit will gather a harvest of eternal life.
