### ISSUE TITLE
Est 9:17 ULB  add "and"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#531]
Est 9:17 ULB: On the thirteenth day of the month of Adar, * on the fourteenth day,
Could the word "and" be added where I put the asterisk?

Actually, there's more to this. I'll write below.

**Comment by SusanQuigley** [comment]
On the thirteenth day of the month of Adar, on the fourteenth day, they rested and made that a day of feasting and gladness.

Without a phrase like "This happened" at the beginning, it looks like both days were the day of feasting and gladness. Could it be changed to something like this. 

**This happened on** the thirteenth day of the month of **Adar. On** the fourteenth day, they rested and made that a day of feasting and gladness.

**Comment by TomWarren** [comment]
ULB of EST 9:17 now reads:
\v 17 This happened on the thirteenth day of the month of Adar, and on the fourteenth day they rested and made that a day of feasting and gladness.

Thanks Susan, 

Tom

**Comment by SusanQuigley** [comment]
Thanks, Tom. Glad to see you back. Hope you're feeling better.
