### ISSUE TITLE
Est 9:22 ULB from mourning into a holiday

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#532]
their sorrow was turned to joy, and **from mourning into a holiday.**

Could "from mourning into a holiday" be changed to either of these?
 "their mourning to celebrating" 
 "their day of mourning to a holiday"

**Comment by TomWarren** [comment]
The HEB "a day of good" is rendered "a day of celebration" possibly meaning more than a day, more a "time of celebration." 

The ULB of EST 9:22 now reads:
\v 22 These were the days when the Jews got relief from their enemies, and the month when their sorrow turned to joy, and mourning into a day of celebration. They were to make them days of feasting and gladness, and of sending gifts of food to one another, and gifts to the poor.

Bit a a repeat of the previous, but ok.

Thanks,

Tom
