### ISSUE TITLE
LUK 12:30-31 tr

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#536]
\v 30 For all the nations of the world look for **_these things,_** and your Father knows that you need **_these things._**
\v 31 But seek his kingdom, and **_these things_** will be added to you.

The reader questions the triple usage of 'these things' thinking that it is redundant.

**Comment by TomWarren** [comment]
Edited τούτων to read "them" referring to "these things" in Vs 30. This relieved some of the pedantic nature of the reading.
The ULB of LUK 12:30-31 now reads:
.
\v 30 For all the nations of the world look for **these things**, and your Father knows that you need **them**.

\s5
\v 31 But seek his kingdom, and **these things** will be added to you.
