### ISSUE TITLE
HEB 12:27 tr

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#543]
27 These words, "One more time," mean the removal of those things that can be shaken, that is, of the things that have been created, so that **_the things that cannot shaken will remain._**

Perhaps it should read ? - **_the things that cannot be shaken will remain._**

**Comment by TomWarren** [comment]
Yep. The ULB of HEB 12:27 now reads:
\v 27 These words, "One more time," mean the removal of those things that can be shaken, that is, of the things that have been created, so that the things that cannot be shaken will remain.

Thanks, 

Tom
