### ISSUE TITLE
dan 5:15 One group or two groups?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#544]
ULB And now the men known for wisdom and those who claim to speak with the dead

UDB The men who are known for their wisdom and who speak with the dead

The way I read this, the ULB sounds like two separate groups (the wise men and the men who speak with the dead) and the UDB sounds like one group (the wise men who speak to the dead)

From my research, I'm not sure whether it is one or two groups. But, based on your decision the comma in the ULB will need to be moved.

ULB And now the men known for wisdom and those who claim to speak with **the dead, have** been brought in before me

If it is two separate groups you can take out the comma so that the subject is not separated from the verb.

If is it one group it can be worded like this:

And now the men known for wisdom, who claim to speak with the dead, have been brought in before me

**Comment by TomWarren** [comment]
The UDB of DAN 5:15 now reads: 
\v 15 There were men who are known for their wisdom and others who speak with the dead, and they tried to read the writing on this wall and to tell me what it means, but they could not do it.

Probably two groups. I translated Dan. Seemed like I should agree with myself. 
Tom
