### ISSUE TITLE
Job 12:9 ULB given them life

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#545]
ULB: Which animal among all these does not know
that the hand of Yahweh has done this—**given them life**—

UDB: All of them certainly know that it is Yahweh who has **made them** by his hands.

The ULB adds the phrase "given them life." Would you like the ULB to leave open the possibility of other interpretations? The NET Bible notes say that "this" in "the hand of Yahweh has done this" probably refers to the things that have already been discussed - how God rules the world in wisdom and inflicts suffering.

**Comment by TomWarren** [comment]
The ULB was too speculative. It was returned to follow the Heb text.
VS 10 was also problematic and was edited. 

The ULB of JOB 12:9-10 now reads: 
\v 9 Which animal among all these does not know
\q that the hand of Yahweh has done this?
\q
\v 10 In his hand is the life of every living thing
\q and the breath of all mankind.

**Comment by SusanQuigley** [comment]
Now that you've made the ULB less speculative about the meaning of "this", would you like to make the UDB less speculative? Maybe the UDB could be simply this:

All of them certainly know that it is Yahweh who has **done this**.

**Comment by TomWarren** [comment]
Good fit.
The UDB of JOB 12:9 now reads:

\v 9 All of them certainly know that it is Yahweh who has done this.

Thanks,

Tom
