### ISSUE TITLE
Job 12:20 ULB "trustworthy" to "trusted"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#547]
He removes the speech of people who are **trustworthy**

Could "trustworthy" be changed to "trusted"? Just because people trust them does not make them worthy of trust. I expect that is the reason that God silences them.

**Comment by TomWarren** [comment]
The ULB of JOB 12:20 now reads: 
\v 20 He removes the speech of those who had been trusted
\q and takes away the understanding of the elders.

Thanks,
Tom
