### ISSUE TITLE
Job 13:9 ULB misrepresent him 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#548]
ULB: Or like someone deceives someone else, would you really **misrepresent him** in court?
UDB but do not think that you can lie about him in court and say that you are defending him!

Other versions say "deceive him"
Hebrew has the same verb in both clauses: hathal.

**Comment by TomWarren** [comment]
The ULB in JOB 13:9-10 seems to be off the rails. I have gone through these two verses:
\v 9 Would it really be good for you when he searches you out? 
\q Could you deceive him as you might deceive men?
\q
\v 10 He would surely reprove you
\q if in secret you showed partiality.

Thanks,
Tom

**Comment by SusanQuigley** [comment]
The ULB is fine as you did it now. But I don't think v 10 was far off. It simply made it explicit that God was the one they were showing partiality to.  I think this interpretation comes from verses 7-8.

**Comment by TomWarren** [comment]
Just seemed more of a UDBism, to me. But that is the heart of the two versions.

**Comment by SusanQuigley** [comment]
That makes sense about it being a UDBism.
