### ISSUE TITLE
Job 19:5  "convince everyone that I am disgraced"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#549]
ULB:  If indeed you will boast against me
and **convince everyone that I am disgraced,**

UDB: If you truly think that you are better than I am,
and if you argue that I must be guilty because I am suffering,

Could the second line of the ULB be changed to something like this? 
"use my disgrace as an argument against me" 
"claim that my disgrace is proof against me" 

This would fit with the sense in the UDB and other versions.

**Comment by TomWarren** [comment]
The ULB now reads: 
\v 5 If indeed you will exalt yourselves above me
\q and use my humiliation against me, 
\q
\v 6 then you should know that God has done wrong to me
\q and has caught me in his net.

The UDB seems closer to the text in this section, than the ULB. 

Tom Warren

**Comment by SusanQuigley** [comment]
Tom, this makes one sentence cross chunks. There is a chunk for 19:3-6 and 19:6-8. Do you want it to do that.
