### ISSUE TITLE
Luk 4:18-19

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#55]
The first lines of the ULB are capitalized even mid-sentence.

18"The Spirit of the Lord is upon me,
Because he anointed me to preach good news to the poor.
He has sent me to proclaim freedom to the captives,
And recovery of sight to the blind,
To set free those who are oppressed,
19To proclaim the favorable year of the Lord."

There is one line of the UDB capitalized mid-sentence:

captives will go free,
And will tell thos

**Comment by hharrissWA** [comment]
How does this look, Larry, for the ULB?
18"The Spirit of the Lord is upon me,
    because he anointed me to preach good news to the poor.
He has sent me to proclaim freedom to the captives,
   and recovery of sight to the blind,
   to set free those who are oppressed,
19to proclaim the favorable year of the Lord."

**Comment by hharrissWA** [comment]
I placed some indentation in there too which did not copy here. Check out the published ULB page.
Harry

**Comment by lrsallee** [comment]
Harry,

I don’t know what your current policy is on indentation of OT citations, but it does not appear to match Luk 3:4-6.

Also, 4:11 still needs to start on a new line.

Larry

**Comment by hharrissWA** [comment]
Ok, I believe I'm getting there with these Luke 4 passages. I haven't done this sort of thing yet in Github, but I believe I'm about to figure it out. They seem to be ok now?
https://door43.org/en/ulb/ep/43-luk.usfm

**Comment by lrsallee** [comment]
Harry,

That looks right  to me. Thanks.

Larry

**Comment by hharrissWA** [comment]
Great, Larry, thanks!  I will close this out.
