### ISSUE TITLE
Job 14:21 ULB "come to honor"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#550]
ULB His sons **may come to honor**

Could "come to honor" be changed to something like one of these?
"may achieve honor" 
"may receive honor"

In Hebrew it's simply yiḵ·bə·ḏū  
John H was explaining that it's probably translated like this to avoid the English passive (be honored) because it's not passive in Hebrew.
But translating it as "come to honor" introduces an English idiom.

**Comment by TomWarren** [comment]
The ULB of JOB 14:21 now reads:
\v 21 If his sons are honored, he does not know it;
\q and if they are brought low, he does not see it.

This is a bit simpler, but clearer to the point. 
Tom
