### ISSUE TITLE
Job 19:7 ULB  I call out to say that I have been done wrong

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#551]
ULB:  I call out to say that **I have been done wrong**
UDB: I cry out, 'People are murdering me!'

The UDB and other versions have "cry" or "cry out" and indicate that he cries out while the wrong is being done. The cry is urgent.

Could the ULB have the same urgency?

**Comment by TomWarren** [comment]
FYI: The Heb חָמָס  is "Hamas" as in the terror group. 

The ULB of JOB 19:7 now reads: 
\v 7 See, I cry out, "Violence!" but I get no answer.
\q I call out for help, but there is no justice.

The UDB is fine. 

Thanks, 
Tom
