### ISSUE TITLE
Job 19 17 ULB  "my pleas" vs UDB "me"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#552]
ULB:  my **pleas** are loathsome to my own brothers and sisters.
UDB:  my brothers detest me.

Could "my pleas" be taken out of the ULB so it will be like UDB and others?
I am loathsome to my own brothers and sisters.

 NET Bible Note indicates that these come from two different interpretations of the word _wehannoti_. One treats it as based on the root khanan  "be gracious" and means "although I entreated" or "my supplication." (ULB: my pleas).
The other says it comes from another root meaning "be offensive/loathsome" (UDB: detest).

**Comment by TomWarren** [comment]
The HEB is very indicative: 
\v 17 My breath is offensive to my wife;
\q I am even disgusting to those who were born from my mother's womb.

This preserves the Hebraism and it is understandable. A NOTE may help to clean it up .  The HEB doesn't seem that difficult. חנן khanan (you note) is the root for "grace"  and is one of the terms that point to two poles (like baruk, bless, and it means curse) meaning both grace, and loathsomeness, depending on the context. Context usually settles the issue, as here. 

The UDB seems fine.

Thanks,
