### ISSUE TITLE
LUK 18:18-23 tr

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#553]
The man in this passage is referred to twice as a **_ruler_**. But then in verse 23, he is referred to as the **_rich_** man. Some people in translation might wonder if this is a different person. I think it would be better to say in verse 23 "_But when he heard these things_" as some other translations handle it.

18 **_A certain ruler asked_** him, saying, "Good teacher, what must I do to inherit eternal life?"
\v 19 Jesus said to him, "Why do you call me good? No one is good, except God alone.
\v 20 You know the commandments—do not commit adultery, do not kill, do not steal, do not testify falsely, honor your father and mother."
\v 21 **_The ruler said,_** "All these things I have obeyed from the time I was a youth."

\s5
\v 22 When Jesus heard that, he said to him, "One thing you still lack. You must sell all that you have and distribute it to the poor, and you will have treasure in heaven—and come, follow me."
\v 23 But when **_the rich man heard_** these things, he became extremely sad, for he was very rich.

**Comment by TomWarren** [comment]
The ULB of LUK 18:18-23 
\v 18 A certain **ruler** asked him, saying, "Good teacher, what must I do to inherit eternal life?"
\v 19 Jesus said to him, "Why do you call me good? No one is good, except God alone.
\v 20 You know the commandments—do not commit adultery, do not kill, do not steal, do not testify falsely, honor your father and mother."
\v 21 The **ruler** said, "All these things I have obeyed from the time I was a youth."

\s5
\v 22 When Jesus heard that, he said to him, "One thing you still lack. You must sell all that you have and distribute it to the poor, and you will have treasure in heaven—and come, follow me."
\v 23 But when the **ruler** heard these things, he became extremely sad, for he was very rich.
