### ISSUE TITLE
LUK 24:28, 29 tr

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#554]
48 You are witnesses of these things.
49 See, I am **_sending upon you what my_** Father promised. But remain in the city until you are clothed with power from on high."

Suggestion is to remove the word "upon"  so verse 49 reads, "See, I am **_sending you what my_** Father promised."

**Comment by TomWarren** [comment]
The ULB of LUK 24:28, 29 now reads: 
\v 49 See, I am sending you what my Father promised. But remain in the city until you are clothed with power from on high."

Thanks,
Tom
