### ISSUE TITLE
Job 20:3 ULB "puts me to shame"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#556]
ULB: I have heard from you a rebuke **that puts me to shame,**
UDB: By saying these things you have insulted me,

Could ULB "that puts me to shame" be changed to something that does not imply that Zophar agrees with Job's rebuke? Maybe:
"that insults me"
"that dishonors me"

**Comment by TomWarren** [comment]
The ULB of JOB 20:3 now reads:
\v 3 I hear a rebuke that insults me,
\q2 and a spirit from my understanding answers me.

The UDB would stand.

The Heb is followed, and it is difficult. 
A note about "a spirit from my understanding" could explain, "my understanding was inspired to replay" or "my understanding gives me an answer" or something like that.

**Comment by SusanQuigley** [comment]
Tom, thanks for the help with "a spirit from my understanding"
