### ISSUE TITLE
Job 10:3b ULB vs UDB a spirit ... answers me

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#557]
ULB: but a spirit that is beyond my understanding answers me.
UDB: but something more than I can explain shows me how I can reply to you. 

I'm not sure if these two mean the same thing. 
Does "the spirit that is beyond my understanding" mean the same as 
"something more than I can explain"?
Should I understand it to refer to a spirit being, or to an attitude or emotion of Zophar's?

Is "about how I can reply to you" in the UDB  implied info made explicit?

**Comment by TomWarren** [comment]
This is difficult. The וְ֝ר֗וּחַ (spirit) (of my understanding) מִֽבִּינָתִ֥י is problematic. 
Simply following it, is often the best course, and I eschew fantastic imagination trying to glue some meaning into something that is just beyond our understanding. 
The UDB has been changed a bit:

The UDB is: 
\v 3 By saying these things you have insulted me,
\q2 but something within my understanding suggests to me how I may reply to you.

The ULB is:
\v 3 I hear a rebuke that dishonors me,
\q but a spirit from my understanding answers me.

Seems like something from within Zophar, and not an animation of a spirit or from idols, or the like. Just that there was some influence from his understanding ("spirit of my understanding"). It is an odd way to speak of understanding, but here it is.
