### ISSUE TITLE
Pro 13:8 ULB/UDB agreement?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#558]
ULB but a poor person **will not listen to rebuke**

UDB no poor person **would have to think about that kind of danger**

Would you take a look at these and tell me what you think? Do you think these two meanings agree? A lot of English versions use "threat" rather than "rebuke" because they take the meaning to be that no one would threaten a poor person since they have nothing to give as a ransom unlike the rich person.

**Comment by TomWarren** [comment]
The UDB of PRO 13:8 has been changed to read:
\v 8 A rich person may have to use his wealth to buy back his life from a criminal who holds him as a hostage,
\q2 but a poor person does not listen even when he is threatened.

The ULB of this section has also been edited:
The ULB of PRO 13:8 now reads:
\v 8 The ransom of a rich man's life is his wealth,
\q but a poor person does not hear a threat.

The ULB is closer to the Heb now. 

Thanks, 
Tom
