### ISSUE TITLE
Job 20:22b ULB vs UDB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#559]
ULB:  the hand of everyone who is in poverty will come on him.
UDB:  Misery will strike them and crush them.

Note in discussion section from John Hutchins:
I wasn't sure the best way to handle this since the ULB seems to follow the literal Hebrew and the UDB follows the Septuagint.

**Comment by TomWarren** [comment]
The goal is that the ULB and UDB say the same thing. The ATs can be different, but there should be essential agreement ULB to UDB. 

The ULB now reads:
\v 22 In the abundance of his wealth he will fall into trouble;
\q the hand of everyone who is in poverty will come against him.

The UDB now reads: 
\v 22 When they are still very wealthy,
\q2 they will suddenly experience trouble.
\q2 The full power of everyone who lives in misery will crush them.

Thanks,

TW
