### ISSUE TITLE
"non-Israelite" vs "non-Jewish" in UDB

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#56]
"non-Israelite" is used in the UDB 5x in OT and 5x in NT for "Gentile."  However, "non-Jewish" is used 52x in the NT. Looks to me like you switched to "non-Jewish" and have a few "non-Israelite" strays.

**Comment by TomWarren** [comment]
Will settle this today. Thanks.

**Comment by TomWarren** [comment]
This has been settled, finally. Promises are hard to keep. Changed 5x from non-Israelite to non-Jewish.
