### ISSUE TITLE
Job 21:3 ULB  Archaic word?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#560]
**Suffer** me, and I also will speak.

Could "Suffer me" be changed to something like these?
"Put up with me"
"Bear with me'
"Be patient with me"

**Comment by pohlig** [comment]
Good catch. I've changed the ULB to "Put up with me." I see the udb has "Be
patient with me," which I think is good.
Jim

**Comment by SusanQuigley** [comment]
Thank you.
