### ISSUE TITLE
Job 27:2-3 UDB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#561]
27:2-3 "**As** God lives, * has taken away my justice,
the Almighty, who made my life bitter,
**as** long as my life is yet in me
and breath from God is in my nostrils.

Does the first line need the word "who" where I put the asterisk?
Also, we have two verses starting with "as", but nothing to finish up the sentence.
Other versions have verse 4 as the end of the sentence.
Maybe this just needs a comma at the end rather than a period.

The UDB adds "I will say this" to verse 3, but I don't know what "this" refers to.

**Comment by TomWarren** [comment]
Yes, the ULB of JOB 27:2 now reads:
\v 2 "As God **lives, who** has taken away my justice,
\q the Almighty, who made my life bitter,

Thanks,

TW
