### ISSUE TITLE
1th 2:11-12 ULB "we exhorted and encouraged you" ?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#565]
1th 2:11-12 ULB: In the same way you know how that we dealt with each one of you as a father deals with his own children, _12_so you should walk in a manner that is worthy of God, who calls you into his own kingdom and glory.

There is a note for "we exhorted and encouraged you." This phrase is no  longer in the ULB. Is this intentional?

**Comment by TomWarren** [comment]
The phrase was missing from the ULB. The breaks with "and" follow the Greek order. 
The ULB of 1TH 2:12 now reads:
\v 12 we were begging you and encouraging and urging you to walk in a manner that is worthy of God, who calls you into his own kingdom and glory.

Thanks,
TW
