### ISSUE TITLE
1th 2:11 ULB  "how" or "that"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#566]
1th 2:11 ULB: In the same way you know **how that** we dealt with each one of you as a father deals with his own children, 

It looks like either "how" or "that" should be deleted.

**Comment by TomWarren** [comment]
The ULB of 1TH 2:11 was corrected to read:
\v 11 In the same way you know **how** we dealt with each one of you as a father deals with his own children, 

Thanks,
TW
