### ISSUE TITLE
Dan 8:9-12 little horn="him" or "it"?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#567]
The UDB at one time described the horn as a man. So all of the pronouns said "he" or "him." At some point, the reference to the horn being a man was taken out, but all the pronouns are masculine in 8:9-12. Do you want to change them to "it" as in the ULB?

**Comment by TomWarren** [comment]
The masc sing pronouns referring to "horn" have been replaced with "it" etc. for continuity.

Look in situ.
