### ISSUE TITLE
Dan 8:11 ULB/UDB disagreement

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#568]
ULB It became great, even as great as the divine commander of the army

UDB He defied God, the commander of the army of heaven

To me, these do not mean the same thing. ULB says he became as great as God. UDB says he defied God.

**Comment by TomWarren** [comment]
Noting that the NET has a note on DAN 8:11 that the "Prince of the army" may be a reference to God.
However, the UDB and ULB should say the same ...
So the UDB has been changed to read:

\v 11 It set itself up to be as great as the commander of the army of heaven, and it took away the daily offerings of sacrifices from him, and it also defiled the place of his temple.

Perhaps an AT here regarding the Prince (commander) of the army of heaven, "It defied God who commanded the army of heaven".

The ULB was changed to read:
\v 11 It made itself to be as great as the commander of the army. It took away from him the regular burnt offering, and the place of his sanctuary was polluted.

The capitalization of Prince (in the former ULB), "Commander" here,  seems to imply too much. 
In either case the commander could be acting at God's direction, and if it is God who is implied, that could still be reasoned from the account.
