### ISSUE TITLE
Dan 8:21 "king" or "kingdom"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#569]
ULB **the kings** of Media and Persia
UDB **the kingdoms** of Media and Persia

ULB The male goat is the **king** of Greece
UDB The goat that you saw represents the **kingdom** of Greece

It is explained in the notes that this could be "king" or "kingdom." Do you want the ULB and UDB to say the same thing here?

**Comment by pjoakes** [comment]
I think this is a good place for them to differ slightly, to show something of the range of meaning.

**Comment by TomWarren** [comment]
Then the UDB and ULB are good. 
Thanks.
