### ISSUE TITLE
Luk 4:31 UDB

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#57]
The UDB adds that the disciples went with Jesus. 

"One day he went with his disciples down to Capernaum..."

This is not in the text, and does not appear necessary because the disciples nowhere appear in the events that happen there. It begs for a note, but there does not appear to be any way to explain the presence of "with his disciples." It would be easier for us if it was removed.

**Comment by hharrissWA** [comment]
Correct, I do not see the disciples present in Luke 3 or 4. Jesus does not call His first disciples until later in chapter 5. I have removed the reference, "with his disciples."
