### ISSUE TITLE
2 Ki 13:25 Joash or Jehoash?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#570]
ULB  Joash attacked him three times

If I understand the comments in the discussion correctly, "Josah" is supposed to be changed to "Jehoash."

**Comment by TomWarren** [comment]
There were two Joash's and some translations mix them. The NIV is helpful. 

The ULB of 2KI 13:35 now reads:
\v 25 Jehoash son of Jehoahaz took back from Ben Hadad son of Hazael the cities that had been taken from Jehoahaz his father by war. **Jehoash** attacked him three times, and he recovered those cities of Israel.

Joash was changed to Jehoash in the bolded.
