### ISSUE TITLE
2 Ki 10:25 missing "as"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#572]
ULB So then as soon Jehu finished

Need "as" between "soon Jehu"

**Comment by TomWarren** [comment]
The ULB of 2KI 10:25 added the word "as" to the text. It now reads:
\v 25 So then as soon **as** Jehu finished offering the burnt offering, he said to the guard and to the captains, "Go in and kill them. Let no one come out." So they killed them with the edge of the sword, and the guard and the captains threw them out and went into the inner room of the house of Baal.
