### ISSUE TITLE
Job 29:6 ULB archaic "awash"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#573]
Job 29:6 ULB when my way was **awash** in cream

Could the word "awash" be updated to something like "flowing"?
"when my path was flowing with cream"

(I think we would want to keep the metaphor. It's just that the word "awash" isn't used much.)

**Comment by TomWarren** [comment]
Sounds like an Italian Restaurant. 
The ULB of JOB 29:6 now reads: 
\v 6 when my way was covered with cream,
\q and the rock poured out for me streams of oil!

Thanks, Susan, 
Tom
