### ISSUE TITLE
Pro 25:20 "soda" or "wound"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#575]
ULB like vinegar poured upon **carbonate of soda**

UDB pouring vinegar into **a wound**

It looks like ULB is based on the Hebrew and the UDB is based on the LXX.

**Comment by TomWarren** [comment]
The UDB of PRO 25:20 now reads: 
\v 20 Singing a song to someone who is feeling sad,
\q2 it is as unhelpful as taking off a coat on a very cold day,
\q2 or pouring vinegar into soda, making it bubble.

A bit expansive, but it aligns with the ULB. Wonder where the LXX got that?

Tom
