### ISSUE TITLE
Mat 12:26 ULB "Because of this?"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#576]
ULB: And if I drive out demons by Beelzebul, by whom do your sons drive them out? Because of this? For this reason they will be your judges.

It looks like "Because of this?" is some kind of leftover that needs to be deleted. 
Either that, or "? For this reason" needs to be deleted.

And if I drive out demons by Beelzebul, by whom do your sons drive them out? For this reason they will be your judges.
or 
And if I drive out demons by Beelzebul, by whom do your sons drive them out? Because of this they will be your judges.

**Comment by TomWarren** [comment]
Yep. The ULB of MAT 12:27 now reads: 
\v 27 And if I drive out demons by Beelzebul, by whom do your sons drive them out? For this reason they will be your judges.

Thanks,

Tom

**Comment by TomWarren** [comment]
One of the few initial "And"s left in the NT. It needed to stay.
