### ISSUE TITLE
Job 29:20 ULB  Missing final quote mark

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#579]
Job 26:18- 21 
ULB Then I said, 'I will die in my nest;
I will multiply my days like the grains of sand.
19My roots are spread out to the waters,
and dew lies all night on my branches.
20The honor in me is always fresh,
and the bow of my strength is always new in my hand.*
21To me men listened; they waited for me;
they stayed silent to hear my advice.

ULB does not have a final quote mark. I would suggest  putting it at the end of verse 20. When Job is quoting himself, he speaks in the present tense. Then he goes back to the past tense in v21 as he talks about what his situation was like before tragedy struck.

The UDB ends the quote at the end of v 18. I'll write another issue about  that on the UDB side.

**Comment by TomWarren** [comment]
The ULB of JOB 29:21 now reads:
\v 21 To me men listened; they waited for me;
\q they stayed silent to hear my advice." _**[note the final closing quotation]**_

**Comment by SusanQuigley** [comment]
Tom, I only included v 21 here to show how it reverted to past tense which indicates that it was not part of the quote.  Could the final quote mark be moved to the end of 20 where I put the asterisk?

**Comment by TomWarren** [comment]
Sure ... 
The ULB of JOB 29:20-21 now reads:
\v 20 The honor in me is always fresh,
\q and the bow of my strength is always new in my hand."
\q
\v 21 To me men listened; they waited for me;
\q they stayed silent to hear my advice.

Thanks.

**Comment by SusanQuigley** [comment]
Thanks, Tom.
Please change that double quote mark to a single quote mark.

**Comment by TomWarren** [comment]
\v 18 Then I said, 'I will die in my nest;
\q I will multiply my days like the grains of sand.
\q
\v 19 My roots are spread out to the waters,
\q and dew lies all night on my branches.

\s5
\q
\v 20 The honor in me is always fresh,
\q and the bow of my strength is always new in my hand.'

Single quote. See it. 

Thanks,
Tom
