### ISSUE TITLE
Job 29:25 ULB "at a funeral"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#580]
ULB: I selected their way and sat as their chief;
I lived like a king in his army,
like one who comforts mourners **at a funeral**.

UDB: I was their leader, and I decided what things would be good for them to do;
I was among them like a king who is among his troops;
I was like someone who comforts others who are mourning."

Could "at a funeral" be deleted from the ULB?

The phrase "at a funeral" is not in the Hebrew, and I do not think that it is implied in the context. 
NICOT indicates that these three lines tell about Job's leadership in different situations: leading people as a chief in peaceful times, leading as a king in stressful times, comforting his people in times of sorrow. I would not want to make these times explicit, but the reference to a funeral limits the image of the kind of sad situations people face and the kind of comfort he gave.

**Comment by TomWarren** [comment]
Yes, you are right! 
I did work on this translation a bit and punctuation. Hope this helps. 
The ULB of JOB 29:25 now reads:
\v 25 I selected their way and sat as their chief,
\q I lived like a king with his army,
\q I was like one who comforts mourners.

Thanks Susan, 

TOm

**Comment by SusanQuigley** [comment]
Great. Thank you for also changing that "in his army" to "with his army".
