### ISSUE TITLE
Job 30:8  ULB "descendants of fools"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#582]
ULB : They were **descendants** of fools, indeed, of worthless men;
they were driven out of the land by whips. 

UDB: They were people without good sense,
whose names no one knows;
they were driven out from the land where they were born.

Could "descendants" in the ULB be changed to "sons"?

According to UBS-TH and UDB, this is not saying that their ancestors were fools and worthless men, but that that these men themselves were fools and worthless men. Here "sons of" expresses what these people were like, not that they were descendants of such people.

**Comment by TomWarren** [comment]
Yep. A little tweaking with the request. 
The ULB of JOB 30:8 now reads: 
\v 8 They were the sons of fools, indeed, sons of nameless people!
\q They were driven out of the land with whips.

Hope that covers it. Thanks.

Tom

**Comment by TomWarren** [comment]
Always a bit strange when the UDB gets it.

**Comment by SusanQuigley** [comment]
Looks good. Thanks.

**Comment by SusanQuigley** [comment]
:)
