### ISSUE TITLE
Ezr 10:28 Name variant

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#583]
Name spelled differently in ULB and UDB.

ULB Jehochanan

UDB Jehohanan, 

It is also spelled "Jehohanan" in ULB and UDB in Ezra 10:6 (assuming that is the same person)

**Comment by TomWarren** [comment]
Both names are spelled "Jehohanan" following the NIV. Yes, there is some on-going discussion about the spelling of proper names. If they are consistently rendered, then any changes can be made expeditiously. 
Thanks John, 
Tom
