### ISSUE TITLE
Job 30:11b ULB "lose self-control"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#584]
Job 30:11b ULB: and so these people **lose all self-control in front of me.**

This gives the impression that these people are simple or foolish and lack control.
Could it be changed to show that the people have done this intentionally? In the past they would have controlled their behavior out of respect for Job, but now they disrespect him and throw off any such control.

Suggestions for  ULB: 
and so these people no longer restrain themselves before me
and so these people have thrown off all restraint in my presence
and so these people refuse to control themselves in my presence

**Comment by TomWarren** [comment]
Note: Bot  30:10 and 30:11 have in the HEB, מִפָּנַ֥י "before my face," and I have rendered this term in very similar ways in the rework. 
The word translated "restraint" is the word for "halter" (HEB רֶסֶן) as in the bridle that controls a horse, etc., FYI.

The ULB of JOB 30:10-11 now read:
\v 10 They abhor me and stand far off from me;
\q they do not refrain from spitting **_in my face._**
\q
\v 11 For God has unstrung the string to my bow and afflicted me,
\q and they cast off restraint **_before my face._**
