### ISSUE TITLE
EZK 21:25 hanging indent

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#586]
I'm not sure why this chunk is formatted with a hanging indent... Better check it out.

**Comment by TomWarren** [comment]
Reformatted this section. GitHub does render the USFM. Check it at:
https://door43.org/en/bible/notes/ezk/21/25

The ULB of EZK 21:25-27 now reads:
\v 25 As for you, profane and wicked ruler of Israel, whose day of punishment has come, and whose time of committing iniquity has ended,
\q
\v 26 the Lord Yahweh says this to you: Remove the turban and take off the crown! Things will no longer be the same! Exalt the lowly and humble the exalted!
\q
\v 27 I will make everything a ruin! A ruin! A ruin! The crown will exist no longer, not until the one comes who has a right to it. Then I will give it to him.

Thanks Kim,

Tom
