### ISSUE TITLE
2 Ki 17:36 change word order

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#587]
ULB and it is to him that **will you** sacrifice

Should be "you will"

**Comment by TomWarren** [comment]
Yep. The ULB of 2KI 17:36 now reads: 
\v 36 But Yahweh, who brought you up from the land of Egypt with great power and a raised arm, is the one you must honor; it is to him that you will prostrate yourselves, and it is to him **_that you will_** sacrifice.

Thanks John, 
Tom
