### ISSUE TITLE
Job 31:23 ULB Typo

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#588]
ULB For I dreaded destruction from God;
because of the thought of his majesty,
I could do have done those things. 

Should the last line be one of these?
I could not do those things.
I could not do any of those things.
I could do none of those things.

**Comment by TomWarren** [comment]
The Heb is pretty straightforward.

The ULB of JOB 31:23 now reads:
\v 23 For I dreaded destruction from God,
\q and I could not face his majesty.

The Notes may not match the text. 

Thanks,
Tom
