### ISSUE TITLE
2 Ki 16:5-6 Country confusion

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#589]
ULB 5Then Rezin, king **of Aram** and Pekah son of Remaliah, king of Israel, came up to Jerusalem to attack. They besieged Ahaz, but they could not conquer him. 6At that time, Rezin king **of Aram** recovered Elath **for Aram** and drove the men of Judah out of Elath. Then **the Arameans** came to Elath where they have lived to this day.

UDB 5While he was the king of Judah, King Rezin **of Assyria** and King Pekah of Israel came with their armies and attacked Jerusalem. They surrounded the city, but they could not conquer it. 6At that time the army of the king **of Edom** drove out the people of Judah who were living in the city of Elath. Some of the people **from Edom** started to live there, and they are still living there.

I put in bold where the ULB and UDB do not agree on the location. It seems the ULB and UDB translate differently because some of the ancient manuscripts differ.

I did not look through the chapter to see if this mixture of names is widespread.

**Comment by TomWarren** [comment]
Yep. A twisted tale. Hope this is better. 
The UDB of 2KI 16:5-6 now reads:
\v 5 Then King Rezin of Aram, came along with his army, and at that time Pekah (who was the son of King Remaliah of Israel) also came along with his army, and together their armies came up to attack Jerusalem, but King Ahaz led a fight to defend the city. The armies surrounded the city, but they could not conquer it.
\v 6 It was at that time that the army that was commanded by King Rezin of Aram drove out the people of Judah who were living in the city of Elath, and the city came under the control of the Arameans. This was the time when some people from Aram began to live in Elath, and they are still living there.

Thanks John,

Tom
