### ISSUE TITLE
JOB 6:25a 

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#590]
ULB How painful are truthful words! 

UDB When people speak what is true, that truth will not hurt the person who hears it,

There are two possible opposite meanings for this verse.  They have been addressed in a note already, but it's probably best for the ULB and UDB to take the same interpretation.

**Comment by TomWarren** [comment]
The UDB of JOB 6:25 now reads: 
\v 25 When people speak what is true, it can be painful for the listener to hear honest words.
\q2 But what have all your arguments proven about me?

Thanks Kim, 
Tom
