### ISSUE TITLE
Neh 11:6 UDB missing part of text

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#591]
UDB There were 468 men who were descendants of Perez. 

This does not mention that the men lived in Jerusalem or that they were "outstanding" as in the ULB.

**Comment by TomWarren** [comment]
Yep. The UDB of NEH 11:6 now reads:
\v 6 There were 468 men who were descendants of Perez who lived in the city of Jerusalem. These men were very brave and skilled in combat.

Thanks,
Tom
