### ISSUE TITLE
Est 1:2 "fortress" or "palace"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#592]
A reviewer linked several chunks back to this one telling MTT's to translate the word "palace" the same way they did in 1:2. But, the word "palace" does not appear here. It says "fortress." I'm not sure if the text was changed at some point, but in researching this I noticed that the Hebrew word "birah" is translated as "fortress" only twice (1:2 and 9:6) in the ULB. Everywhere else it is translated as "palace." 

It looks like most English versions translate it as  "fortress" or "citadel."

Before I change the notes I wanted to see if you wanted to change 1:2 and 9:6 to palace, or all the others to fortress, or just leave them as is.

**Comment by TomWarren** [comment]
I worked through the terms for Susa (fortress, city). and they are consistent now. Mostly the "fortress of Susa" except when referred to as a city (like EST 8:15),

Hope that is more consistent. 

Tom
