### ISSUE TITLE
Est 5:8 Incomplete sentence

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#593]
ULB My petition and my request is this, 8if I have found favor in the eyes of the king and if it pleases the king to grant my petition and to honor my request. Let the king and Haman

If I am reading this right verse 8 has an incomplete sentence. Possibly should be " to honor my request, let the king and Haman"

It may also help the flow of the sentence to use a colon after "my request is this"

**Comment by TomWarren** [comment]
Yep, a fragment. 
THe ULB of EST 5:8 now reads: 
\v 7 Esther answered, "My petition and my request is this,
\v 8 if I have found favor in the eyes of the king and if it pleases the king to grant my petition and to honor my request, let the king and Haman come to the feast that I will prepare for you tomorrow and I will answer the king's question."

Thanks John, 

Tom
