### ISSUE TITLE
Ezr 2:2 awkward phrase

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#595]
ULB This is the record **of the men of people** of Israel

This is correct by the literal Hebrew, but  little awkward in English. Maybe just adding "the" would smooth it out some: "of the men of the people of Israel"

**Comment by TomWarren** [comment]
THe ULB of EZR 2;2 now reads: 
\p This is the record of the men of the people of Israel.

Thanks,
Tom
