### ISSUE TITLE
Est 6:3 missing word.

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#596]
UDB "What was done to honor Mordecai **for what did?"** 

Should be "for what he did"

Also, while you are there, the proofreader also has this suggestion for the ULB.

ULB 6:3b
Then the king's young men, his servants said, "Nothing was done for him."

A comma is needed after "servants." The words "his servants" are in apposition to the words "the king's young men."

**Comment by TomWarren** [comment]
The UDB of EST 6:3 now reads: 
\v 3 The king asked, "What was done to honor Mordecai for what he did for the king?" The young men serving the king answered, "Nothing has been done for him."
The ULB of EST 6:3 now reads:
\v 3 The king asked, "What was done to give honor or recognition to Mordecai for doing this?" Then the king's young men who served him said, "Nothing was done for him."
This rendering of the ULB seemed simpler.

Tom
