### ISSUE TITLE
Est 6:13 missing quotation mark

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#597]
ULB said to him, "If Mordecai, before whom you have begun to fall, is Jewish, you will not overcome him, but you will certainly fall before him. 

Missing closing quotation mark after "him."

**Comment by TomWarren** [comment]
THe ULB of EST 6:13 now reads:
\v 13 Haman told Zeresh his wife and all his friends everything that happened to him. Then his men who were known for their wisdom, and Zeresh his wife, said to him, "If Mordecai, before whom you have begun to fall, is Jewish, you will not overcome him, but you will certainly fall before him."

Thanks
TW
