### ISSUE TITLE
Est 7:5 missing word?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#598]
ULB  5**Then King Ahasuerus and said to Esther** the queen

There is a mistake in the ULB. There is either a missing verb after "King Ahasuerus" or the "and" should not be there.

**Comment by TomWarren** [comment]
Yep, extra "and." But really a missing phrase ...
The ULB of EST 7:5 now reads:
\v 5 Then King Ahasuerus said to Esther the queen, "Who is he? Where is this person  who has filled his heart to do such a thing?"

There was a missing phrase "where is this person"

Thanks, 
Tom
