### ISSUE TITLE
Est 9:30, 32 two issues in UDB

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#599]
UDB  

30 These letters confirmed were sent to all the Jews - Looks like a stray "confirmed" was inserted into this sentence.

32 the Purim featival - "festival" misspelled

**Comment by TomWarren** [comment]
Some reworking here:
The UDB of EST 9:30-32 now reads:
\v 30 These letters were sent to all the Jews in the 127 provinces of the kingdom of Ahasuerus—words of peace and truth—
\v 31 to establish these days of Purim at their appointed times, as Mordecai the Jew and Queen Esther had established, just as the Jews had established for themselves and their descendants, matters that included their times of fasting and lamenting. 
\v 32 The command of Esther confirmed these regulations that explained how they should celebrate the Purim festival. The instructions about the feast and the account of these events were written down in the book of history.

Thanks,
Tom
