### ISSUE TITLE
1Sa 13:1

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#60]
For some reason, there are ellipses in both the ULB and UDB.

**Comment by TomWarren** [comment]
Saul's age was not supplied in the Heb text. The ESV has the ... just as we have it. Some translations supply "30 years old" others have [30 years old]. The Heb lacks the number (or it was lost in transcription over time. The UBS note:  The MT literally says “Saul was a son of a year in his reigning and two years he reigned over Israel.”

**Comment by TomWarren** [comment]
Either a note to explain the difficulty, or a footnote to deal with the textual lapse.

**Comment by lrsallee** [comment]
Tom,

OK, I see the issue. I am still a little surprised, since many versions give some help, that the UDB does not have any suggestion that we could refer to in a note. I’d like to pull in Jim for advice on how to work the texts, notes, and footnotes together to be a help to the MTT.

Larry

**Comment by TomWarren** [comment]
Yep. Jim needs to jump in on this one.

Thanks,

Tom

**Comment by TomWarren** [comment]
@Wysackyprof  Jim this issues has been floating around. 
Could you take a look?

**Comment by aaronfenlason** [comment]
@TomWarren 
Both the ULB and the UDB now read "[thirty] years old ... [forty] years."
Is this safe to close?

**Comment by pohlig** [comment]
I like it the way Tom has fixed it; he's gotten the best of a bad bargain.
