### ISSUE TITLE
Act 19:14 ULB  missing word

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#600]
ULB The Jewish high priest, whose name * Sceva, had seven sons who were doing this.

This is missing the word "was" where I put the asterisk.

**Comment by TomWarren** [comment]
Yep. The ULB of ACT 19:14 now reads:
\v 14 The Jewish high priest, whose name was Sceva, had seven sons who were doing this.

Thanks Susan, 
Tom
