### ISSUE TITLE
EXO 28:37 ULB Typo

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#601]
he must always bear any guilt that might attach to the offering of the holy gifts that the Israelites set **is** apart to Yahweh.

set is apart - It looks like the word "is" should be deleted

**Comment by TomWarren** [comment]
Yep. 
The ULB of EXO 28:38 now reads: 
\v 38 It must be on Aaron's forehead; he must always bear any guilt that might attach to the offering of the holy gifts that the Israelites _**set apart**_ to Yahweh. The turban must be always on his forehead so that Yahweh may accept their gifts.
