### ISSUE TITLE
RMS 8:28

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#602]
28 We know that for those who love God, he works all things together for good, for those who are called according to his purpose.
\f + \ft Some older versions read, \fqa All things work together for good. \f*

When the above verse is printed - it is hard to tell exactly what is altered. At first read, I thought the entire verse was replaced with the 6 words - "All things work together for good." 
But, upon further discussion - we think that the footnote means that the alternate is: We know that for those who love God, _all things work together for good,_ for those who are called according to his purpose.

Perhaps the footnote can be more explicit?

**Comment by pohlig** [comment]
Fixed. It now reads,
Instead of he works all things together for good , some older versions read, all things work together for good.
