### ISSUE TITLE
JON 2:4

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#603]
This is from a UBN team member:
I was looking at Jonah 2:4 and noticed something that appears contradictory that I wanted to bring to your attention to consider.  

The ULB says "yet I will again look toward your holy temple" a statement of hope.  

The UDB says: "I will never see your holy temple in Jerusalem again!", a statement of hopelessness which contradicts the ULB.

**Comment by TomWarren** [comment]
There were some variations on the translation here, but the majority and the HEB text seems straightforward:
The UDB of JON 2:4 now reads:

\v 4 Then I thought, 'You have banished me, and I will never be able to enter your presence again. But in spite of what you do to me, one day I will again see your holy temple in Jerusalem!'

Thanks,
Tom
