### ISSUE TITLE
Eze 29:7 ULB shattered legs and shaking hips

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#604]
Note from Adam Van Goor. 

ULB 7 “you shattered their legs” the word “legs is not in the Hebrew; the UDB translates this more accurately.

ULB 7 “made their hip to shake” I am not sure that the connotation of this phrase in modern English is the one we want.

Note from Susan. Could the ULB be changed so that it talks about only the hip(s) rather than the  hip and legs?
you wrenched their hips so they could not stand
you made their hips unsteady when they stand

**Comment by TomWarren** [comment]
The UDB  of EZE 29:7 reads (with no change):
\v 7 And when they leaned on that pole, it splintered and tore open their shoulders. When they leaned on you, you were like a pole that broke, and as a result you wrenched their hips and made it impossible for them to stand.'

The ULB of EZE 29:7 now reads: 
\v 7 When they took hold of you in their hand, you broke and tore open their shoulder;
\q and when they leaned on you, you shattered and caused their legs to be unsteady.

The UDB is familiar to me. 
Hope this helps with the ULB. 

Thanks, 
Tom

**Comment by SusanQuigley** [comment]
I realize it's a metaphor, but would you want the ULB and UDB to refer to the same body parts?
In the ULB, are "broke" and "shattered" intransitive, describing what happened to the pole?

**Comment by TomWarren** [comment]
The UDB of EZK 20:7 now reads: 
\v 7 And when they leaned on that pole, it broke and tore open their shoulders. When they leaned on you, you were like a pole that broke in their hand, and as a result you caused their legs to be wrenched and that made it impossible for them to stand.'

The ULB of EZK 20:7 now reads:
\v 7 When they took hold of you in their hand, you broke and tore open their shoulder;
\q and when they leaned on you, you were broken, and you caused their legs to be unsteady.

Try that one. 
Thanks,
Tom

**Comment by SusanQuigley** [comment]
That works. Thank you.
