### ISSUE TITLE
Neh 12:41-42 priests with trumpets

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#605]
ULB 41Then the priests took their place: Eliakim, Maaseiah, Miniamin, Micaiah, Elioenai, Zechariah, and Hananiah, **with the trumpets,** 42Maaseiah, Shemaiah, Eleazar, Uzzi, Jehohanan, Malchijah, Elam, and Ezer. The singers made themselves heard with Jezrahiah as director.

UDB 41My group included these priests **who were all blowing trumpets**: Eliakim, Maaseiah, Miniamin, Micaiah, Elioenai, Zechariah, Hananiah, 42another Maaseiah, Shemaiah, Eleazar, Uzzi, Jehohanan, Malchijah, Elam, and Ezer. The singers, whose leader was Jezrahiah, sang loudly.

A proofreader asked me about the text of the ULB and who exactly were "with the trumpets." I can't find much info on it. The UBS handbook says only the first seven priests were with trumpets, and the other eight may have been musicians or singers, but it is not clear.

The UDB says all 15 priests had trumpets. I'm not sure either way. Do you have more info on this?

**Comment by TomWarren** [comment]
There appears to be a group of priests who were set apart (seven in all) by having trumpets, suggesting these were the ones who carried and played their trumpets.
Then the next group from the second priest named Maaseiah, through Ezer (perhaps part of the preceding group, but that seems unlikely to insert the "with the trumpets" in the middle of the group.
Then the final as the group of singers (we know they were priests who sang), which I am suggesting is associated with the singers, and so they appear to be the either a third group, or my suggestion is that the singers were made from the group from the second Maaseiah through Ezer, with Jezrahiah as their leader. 
The VAV ("**and** also Maaseiah ...") seems to lean us toward taking the last group as the same as the singers, and it has been translated that way. 

The ULB of NEH 12:41-42 now reads: 
\v 41 Then the priests took their place: Eliakim, Maaseiah, Miniamin, Micaiah, Elioenai, Zechariah, and Hananiah, with the trumpets,
\v 42 and also Maaseiah, Shemaiah, Eleazar, Uzzi, Jehohanan, Malchijah, Elam, and Ezer, and the singers made themselves heard and Jezrahiah was their leader.

A note might explain there are others possibilities, but I think this is the most likely. 
Thanks,

Tom
