### ISSUE TITLE
Ezk 31:16 him or it

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#608]
ULB 16 I brought shuddering to the nations at the sound of his downfall, when I threw him down to Sheol with those who went down into the pit.

This chapter is a long allegory about a cedar tree. Here the pronoun changes to "his" and "him." I think this could be confusing. Could we change it to "its" and "it"?

**Comment by TomWarren** [comment]
Certainly Vs 17 had it right, so Vs 16 should join in. 
The ULB of EZK 31:16 now reads:
\v 16 I brought shuddering to the nations at the sound of **_its_** downfall, when I threw **_it_** down to Sheol with those who went down into the pit. So I comforted all the trees of Eden in the lowest parts of the earth. These had been the choicest and best trees of Lebanon; the trees that drank the waters.

Thanks John, 

Tom
