### ISSUE TITLE
2 KI 11:21

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#610]
ULB Jehoash

UDB Joash

Should ULB have "Joash"?

**Comment by TomWarren** [comment]
Check the ref. it did say 2KI 21:21 but I think it was 2KI 11:21 (if not let me know).  I changed the ref at the title of this Issue (for clarity)
We are following the NIV for help on these name conventions. 
The ULB of 2KI 11:21 now reads: 
\v 21 Joash was seven years old when he began to reign.

Thanks,

Tom

**Comment by jhutchins25** [comment]
Yes, it is 11:21.

Thanks.
