### ISSUE TITLE
Eze 29:13 ULB Missing "the"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#611]
Eze 29:13 ULB:  I will gather Egypt from * peoples among whom they were scattered. 

Should this have "the" before the word "peoples"?

**Comment by TomWarren** [comment]
The ULB of EZK 29:13 now reads:
\v 13 For the Lord Yahweh says this: At the end of forty years I will gather Egypt from **the** peoples among whom they were scattered.

Thanks Susan, 

Tom
