### ISSUE TITLE
ACT 10:19

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#614]
While Peter was still thinking about the vision, the Spirit said to him, "See, three men are looking for you.

\f + \ft Some ancient copies have, \fqa two men are looking for you \fqa* or \fqa some men are looking for you \fqa*. \f*

We are wondering if the word 'see' is also included.  So will the first alternate version be:

While Peter was still thinking about the vision, the Spirit said to him, "See, two men are looking for you.
or
While Peter was still thinking about the vision, the Spirit said to him, "Two men are looking for you.

then for the second alternative version:

While Peter was still thinking about the vision, the Spirit said to him, "See, some men are looking for you.
or
While Peter was still thinking about the vision, the Spirit said to him, "Some men are looking for you.

**Comment by TomWarren** [comment]
Behold, the GRK is Ἰδοὺ, Idou, and it is used throughout Acts. 
 C:\Users\wthom_000\Desktop\GitHub\ulb-en\45-ACT\08.usfm (1 hit)
	Line 58: \v 27 He arose and went. **Behold**, there was a man from Ethiopia, a eunuch of great authority under Candace, queen of the Ethiopians. He was in charge of all her treasure. He had come to Jerusalem to worship.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\45-ACT\10.usfm (1 hit)
	Line 35: \v 17 Now while Peter was very confused about what the vision that he had seen could mean, **behold**, the men who were sent by Cornelius stood before the gate, after they had asked their way to the house.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\45-ACT\11.usfm (1 hit)
	Line 22: \v 11 **Behold**, right away there were three men standing in front of the house where we were; they had been sent from Caesarea to me.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\45-ACT\12.usfm (1 hit)
	Line 20: \v 7 **Behold**, an angel of the Lord suddenly appeared by him, and a light shone in the prison cell. He struck Peter on the side and woke him and said, "Get up quickly," and his chains fell off his hands.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\45-ACT\16.usfm (1 hit)
	Line 6: \v 1 Paul also came to Derbe and to Lystra; and **behold**, a certain disciple named Timothy was there, the son of a Jewish woman who believed; his father was a Greek.

For continuity, 
The ULB of ACT 10:19 now reads: 

\v 19 While Peter was still thinking about the vision, the Spirit said to him, "Behold, three men are looking for you.

There may be others who want to address the NOTES issue.

Thanks,

Tom
