### ISSUE TITLE
Neh 6:7 redundant "also"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#616]
ULB Also you have also appointed prophets.

Having "also" twice is a little awkward. Suggest changing first "also" to "and" or just deleting it.

**Comment by TomWarren** [comment]
Yep. THe ULB of NEH 6:7 now reads: 

\v 7 You have also appointed prophets to make this proclamation about you in Jerusalem, saying, 'There is a king in Judah!' You can be sure the king will hear these reports. Therefore come, let us speak with one another."

Thanks John, 

Tom
