### ISSUE TITLE
Eze 29:18 ULB shaved or rubbed bald

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#617]
ULB: Every head was shaved
UDB: their heads were rubbed bare under their helmets,

Could ULB "was shaved" be changed to "was made bald" or "was rubbed bald" to fit with UDB and other versions?

**Comment by TomWarren** [comment]
The ULB of EXK 29:18 now reads: 

\v 18 "Son of man, Nebuchadnezzar the king of Babylon stationed his army to do hard work against Tyre. Every head was rubbed until it was made bald, and every shoulder was made raw. Yet he and his army received no payment from Tyre for the hard work that he carried out against it.

Thanks,
Tom
