### ISSUE TITLE
Ezek 37:24 "like king David" ?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#618]
ULB David my servant will be king over them

UDB Someone who will be like King David

Does this mean someone "like" David, or does it mean someone descend from David?

**Comment by TomWarren** [comment]
Like in ISA 55, where it speaks of "my steadfast, sure, love for David" it points to the Davidic promise, not merely to the historical figure, but also to the lasting throne and dynasty of David's kingdom (2 Sam 7). 

The UDB of EZK 37:24 now reads:
\v 24 The king who rules over them will always come from the family of King David. David was the one who served me well. There will be one shepherd to watch over them and to take care of all of them. They will carefully obey all my laws.

Thanks John, 
TW
