### ISSUE TITLE
EZK 24:21 SV agreement

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#619]
'Say to the house of Israel, the Lord Yahweh says this: Behold! The pride of your strength, the desire of your eyes, and your lusts are defiling my sanctuary! ..."

In this verse, it appears that the subject of "defile" should be Yahweh, not the people of Jerusalem.

**Comment by kim-putter** [comment]
Also, there third noun phrase referring to the the temple has been shortened to "your lusts." It should be "the lusts of your soul" or "the desire of your soul."

**Comment by TomWarren** [comment]
The ULB of EZK 24:21 now reads: 
\v 21 'Say to the house of Israel, the Lord Yahweh says this: Behold! I will descecrate my sanctuary—the pride of your power, the delight of your eyes, and the yearning of your soul; and your sons and your daughters whom you left behind will fall by the sword

Thanks Kim, 

Tom
