### ISSUE TITLE
Ezk 30:2 ULB Capital T needed.

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#621]
"Son of man, prophesy and say, '**the** Lord Yahweh says this:

The word "the" should be capitalized.

**Comment by TomWarren** [comment]
The ULB of EZK 30:20 now read:
\v 2 "Son of man, prophesy and say, 'The Lord Yahweh says this:
\q Wail, "Woe is the coming day."

Thanks,
Tom
