### ISSUE TITLE
Ezk 30:16  ULB or UDB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#622]
ULB: Memphis will **have enemies** every day.
UDB: the people in Memphis will constantly **be terrified**.

Some versions are like ULB and some like UDB. Would you want them to be the same?

**Comment by TomWarren** [comment]
The ULB of EZK 30:16 now reads: (for a starting place)
\v 16 Then I will set fire in Egypt; Pelusium will be in severe agony, Thebes will be broken up, and Memphis will face enemies every day.

The UDB of EZK 30:16 now reads: 
\v 16 I will burn Egypt with fire;
\q2 the people in Pelusium will suffer severe pain.
\q1 Enemies will conquer Thebes,
\q2 and the enemies of Memphis will attack the people who live there every day.

Thanks,
Tom
