### ISSUE TITLE
Ezk 34:31 "I am" or "I will be"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#627]
ULB I will be your God

UDB  I will be your God

Should this be in future tense? All other versions I checked say "I am your God."

**Comment by TomWarren** [comment]
The ULB of EZK 34:31 now reads:

\v 31 For you are my sheep, the flock of my pasture, and my people, and I am your God—this is the Lord Yahweh's declaration.'"

The UDB of EZK 34:31 now reads:
\v 31 It is as though you, my people, are my sheep whom I take care of, and I am your God. That is what I, Yahweh the Lord, declare.'"

Thanks,
TW
