### ISSUE TITLE
Jer 2:13 ULB Clarifying the two evils

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#629]
ULB: For my people have committed two evils against me: They have abandoned the springs of living waters **by digging out** cisterns for themselves,
broken cisterns that cannot hold water!

The ULB looks like it tells about only one evil: that they abandoned the sprigs of living waters. It looks like the rest of the sentence is just a manner clause telling how they committed that evil.

Could the ULB be changed to make it clear that the first evil was abandoning the springs of living water, and the second was digging cisterns for themselves?

For my people have committed two evils against me: They have abandoned the springs of living waters, and they have dug out  cisterns for themselves,
broken cisterns that cannot hold water!

**Comment by TomWarren** [comment]
Yep, the UDB of JER 2:13 now reads, as suggested:

\v 13 For my people have committed two evils against me: They have abandoned the springs of living waters,
\q and they have dug out cisterns for themselves,
\q broken cisterns that cannot hold water.

Thanks Susan,

TW
