### ISSUE TITLE
ISA 40:11 Odd line break in poetry

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#63]
There is a line break between "he will gather in his arm" and "the lambs". I'm not sure where it should be. Maybe this would be good:

\v 11 He will feed his flock like a shepherd,
\q1 he will gather in his arm the lambs, and carry them close to his heart,
\q1  and will gently lead the ewes nursing their young.

**Comment by hharrissWA** [comment]
Changed as noted by Susan.
