### ISSUE TITLE
Jer 2:14 Is Israel a slave? Was he not born at home?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#630]
ULB: Is Israel a slave? Was he **not** born at home?
UDB: You Israelite people, you were certainly not slaves when you were born

Hebrew does not have the word "not." The point is that Israel is not a slave and was not born (as a slave) in a slave owner's house. Someone who was sold into slavery, could possibly get out. But someone who was born as a slave could never become free.

Could ULB be changed to one of these?
Is Israel a slave? Was he born at home?
Is Israel a slave? Was he born in his master's house?
Is Israel a slave? Was he born into slavery?
Is Israel a slave? Is he a home-born slave?

**Comment by TomWarren** [comment]
Yep. The ULB of JER 2:14 now reads:

\v 14 Is Israel a slave? Was he born in his master's home? So why has he become plunder?

"master's" is added for clarity, "home-born" is a descriptor of a slave, who has a master, and was, therefore property of his master. 

Thanks Susan,

TW
