### ISSUE TITLE
Jer 2:21 ULB a disloyal one from a foreign vine

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#632]
ULB: Yet how you have changed toward me, **a disloyal one from a foreign vine**!
UDB: So now it is disgusting that you have become like a rotten worthless vine.

I find it hard to make any sense out of the second phrase in the ULB. (I'm not sure what "one" refers to and how "from" fits in here). 
Does the ULB mean something like this?
"You are disloyal to me, and so you are like a wild vine"

Perhaps "disloyal" would be better replaced with a word that describes the vine, and let the idea of disloyalty could be implied in "you have changed toward me."

Also the ULB and UDB seem quite different.

**Comment by TomWarren** [comment]
The ULB of JER 2:21 was changed to read:

\v 21 I planted you as a choice vine, completely from pure seed.
\q How then have you have changed yourself into a corrupt, worthless vine?

The UDB of JER 2:21 now reads: 
\v 21 It is as though you were the best grapevine that I could plant, 
\q2 and I planted you so you would grow from the very best seed.
\q1 So how could you change yourself from the best grapevine into becoming like a vine that is disgusting and rotten?

Thanks,

Tom

**Comment by SusanQuigley** [comment]
Looks great to me. Thanks for fixing both of them.
