### ISSUE TITLE
Jer 2:23 ULB  Misplaced question mark

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#633]
How can you say, 'I am not defiled! I have not walked after the Baals?'

The question mark should follow the quote mark.

**Comment by TomWarren** [comment]
Yep. The ULB of JER 2:23 now reads:

\v 23 How can you say, 'I am not defiled! I have not walked after **the Baals'?**
\q Look at your behavior in the valleys! Understand what you have done, you swift camel running its own way!

Thanks Susan, 

TW
