### ISSUE TITLE
Jer 41:9 Gedaliah incorrect info

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#635]
ULB The cistern where Ishmael threw all the dead bodies that he and Gedaliah had struck down

This is not correct. Ishmael killed Gedaliah and threw his body in a pit. (See: 41:1-5)

**Comment by TomWarren** [comment]
There was some confusion on this point among some older translations.
בור גדול ; "large cistern"  is close to "Gedaliah". 

The ULB of JER 41:9 now reads:
\v 9 The cistern where Ishmael threw all the dead bodies that he had killed, was a large cistern that King Asa dug to make a defense against King Baasha of Israel. Ishmael son of Nethaniah filled it in with the dead.

The UDB of JER 41:9 was not changed:
\v 9 The well where Ishmael's men had thrown the corpses of the men whom they had murdered was the deep well that King Asa's men had dug in order that they would have water in the city if the army of King Baasha of Israel would surround the city. Ishmael's men filled that well with corpses.

Thanks John, 

Tom
