### ISSUE TITLE
Jer 41:9 typo

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#636]
ULB Ishmael son of Nethaniah **filled it those** who were killed

Needs the word "with" added.

**Comment by TomWarren** [comment]
There may be a lag. 
The ULB of JER 41:9 now reads:

\v 9 The cistern where Ishmael threw all the dead bodies that he had killed, was a large cistern that King Asa dug to make a defense against King Baasha of Israel. Ishmael son of Nethaniah filled it in with the dead.

Sometimes I work the entire section and it has the effect of putting me ahead in time. 
Thanks

Tom
