### ISSUE TITLE
Jer 41:17 spelling variant

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#637]
ULB Geruth **Chimham**

UDB  Geruth **Kimham**

**Comment by TomWarren** [comment]
Looks like it should be Kimham in both (checking the NIV as our guide). 
The UDB of JER 41:17 now reads:
\v 17 They took them all to Geruth **Kimham** village near Bethlehem. And they all prepared to go to Egypt.

The ULB of JER 41:17 now reads:
\v 17 Then they went and stayed for a while in Geruth **Kimham**, which is near Bethlehem. They were going to go to Egypt

This would follow 2SA 19:37, 38, 40, where a person is named, Kimham, and spelled just like the place.

Thanks, 

Tom
