### ISSUE TITLE
Luk 8:24 - capitalization

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#64]
The UDB capitalized both occurrences of "Master" and the ULB does only the first. Seems like they should match.

**Comment by TomWarren** [comment]
"Master! Master! We are about to die!"  now in the ULB.
Taking the issue of capitalization is easier than explaining why one is caps and the other is not. In these cases, apart from the exclamation, master would be lc, except if it were used as a title, like the Master Jesus - but that would normally be "Lord Jesus."
