### ISSUE TITLE
Jer 2:35 ULB "Instead" to "But" or "Yet"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#640]
ULB:  **Instead,** in spite of all these things, you keep saying, 'I am blameless. Surely Yahweh's anger will turn from me.'
But look! You will be judged since you say, 'I have not sinned.'

The word "Instead" does not fit well here, because nothing was told before this about what they should do. Verses 32-35 tell about their sins.  So "Yet" or "But" would be better.

**Comment by TomWarren** [comment]
The ULB of JER 2:35 now reads:
\v 35 You say, 'I am innocent; surely his anger has turned away from me.'
\q But look! I will bring down judgment on you because you say, 'I have not sinned.'

Thanks,

TW
