### ISSUE TITLE
Jer 3:1 ULB That woman is this land!

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#641]
"They say, 'A man sends his wife away, so she goes from him and becomes another man's wife.
Should he return to her again? Is she not completely unclean?'
**That woman is this land!**
You have acted like a whore with many companions, and now do you want to return to me?—this is Yahweh's declaration.

It looks like the phrase "That woman is this land!" was added to make explicit the implicit information that the people of Israel were like that woman. But I don't think it is needed. In fact, the people of Israel were worse than this woman. She went off and married one other men; Israel was like "a whore with many companions."

 Maybe all that is needed is the word "But" as he transitions to the people of Israel.

"They say, 'A man sends his wife away, so she goes from him and becomes another man's wife.
Should he return to her again? Is she not completely unclean?'
**But you** have acted like a whore with many companions, and now do you want to return to me?—this is Yahweh's declaration.

**Comment by TomWarren** [comment]
I reworked JER 3:1 it was too far removed from the HEB text.
The ULB of JER 3:1 now reads:

\v 1 "If a man divorces his wife and she goes from him and becomes another man's wife,
\q will he return to her again? Would that land not be greatly polluted?
\q You have lived as a prostitute who has many lovers; and would you return to me?—this is Yahweh's declaration.

Try that. 

TW

**Comment by SusanQuigley** [comment]
This works nicely. Thank you.
