### ISSUE TITLE
Jer 42:1 and 43:2 name variant

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#642]
42:1
ULB Jezaniah

UDB Azariah

43:2
ULB Azariah

UDB Azariah

I'm assuming 42:1 ULB should have "Azariah"

**Comment by TomWarren** [comment]
For JER 42:1
ULB and UDB NOW both have Jezaniah son of Hoshaiah. 

the UDB was changed to read:

\v 1 Then Johanan son of Kereah and **Jezaniah** son of Hoshaiah, and all the other leaders of the Israelite soldiers who had not surrendered to the army of Babylonia, and many other people, including those who were important and those who were not important, came to me.

For JER 43:2 both ULB and UDB have "Azariah son of Hoshaiah" and this appears to me to be correct.

Azariah seems to be correct, as "son of Hoshaiah" in JER 43:2 (ULB and UDB). 
Perhaps another son of Hoshaiah.

Or just a mystery.
