### ISSUE TITLE
Jer 3:5 ULB  So continue to do it!

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#643]
Look! You have proclaimed you would commit evil, and you have committed it. **So continue to do it!**"

I don't see any versions that translate the last phrase as a command. I like the command, because it shows God's anger and implies that he will not stop being angry with them. But it would be introducing a figure of speech that is not in the original (The figure would be using a command ironically to show his anger.) I would  need to write a note for it so people can understand it, but my note would imply that this figure is in the original.

How about something like this?
Look! You have proclaimed you would commit evil, and you have committed it. And you will continue to do it!"

**Comment by TomWarren** [comment]
There is a difficult shift from third per to second person. The quotation helps to make sense of it. 
The ULB of JER 3:4-5 now reads: 

\v 4 Now will you not call out to me: 'My father! My closest friend even from my youth!
\q
\v 5 Will he always be angry? Will he always keep his wrath to the end?'
\q Look! This is what you have said, but you do all the evil you can!"

This is a re-write. 
Thanks,

Tom

**Comment by SusanQuigley** [comment]
Thank you. That works.
