### ISSUE TITLE
Jer 3:14a ULB "I have married you" to  "I am your husband"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#645]
Return, faithless people!—this is Yawheh's declaration—**for I have married you!**

Could "for I have married you" be changed to "for I am your husband"? That way it it keeps the focus on the relationship, not on something God has done as if this were some new thing.

**Comment by TomWarren** [comment]
Yep, בָּעַ֣לְתִּי is master, especially "husband" and so ...


The ULB of JER 3:14 now reads: 

\v 14 Return, faithless people!—this is Yawheh's declaration—I am your husband!
\q I will take you, one from a city and two from a family, and I will bring you to Zion!

מִשְׁפָּחָה was irregularly translated family or clan. With unfortunate overtones of "clan" I have rendered them all "family"ies ... 

Thanks Susan, 

Tom
