### ISSUE TITLE
Jer 3:16 ULB What won't be made?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#646]
ULB: This statement will no longer be made.'
UDB: and you will not want to make a new one.'

In the ULB, it is the statement that will not be made, and in the UDB, it is the ark of the covenant that will not be made (again).

**Comment by TomWarren** [comment]
The UDB catches the idea that the ark will not be made again. 
The UDB is unchanged.

The ULB of JER 3:16 was edited, and it now reads:
\v 16 Then it will happen that you will increase and bear fruit in the land in those days—this is Yahweh's declaration-they will no longer say, "The ark of the covenant of Yahweh!" This matter will no longer come up in their hearts or be remembered; it will not be missed, and another one will not be made.'

Thanks, 

Tom
