### ISSUE TITLE
JER 13:27 fragment

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#647]
Your adultery and neighing, the shamefulness of your promiscuous behavior on the hills and in the fields! I will cause them to be seen, these detestable things! 

The first sentence above is a fragment; not a complete sentence.

**Comment by pohlig** [comment]
Kim, Ezk. 13:27 can't be the right reference can it?

**Comment by kim-putter** [comment]
Oops I meant JER 13:27

**Comment by TomWarren** [comment]
Supplying the subject and verb (from context) 
the ULB of JER 13:27 now reads:

\v 27 I have seen your adultery and neighing, the shamefulness of your promiscuous behavior on the hills and in the fields! I will cause them to be seen,
\q these detestable things! Woe to you, Jerusalem! You have not been clean. How long will this continue?"

Thanks, 

Tom
