### ISSUE TITLE
Jer 45:4 missing phrase in UDB.

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#648]
ULB This is true over all the earth

This phrase is not reflected in the UDB.

**Comment by TomWarren** [comment]
ULB of JER 45:4 now reads: 
\v 4 This is what you must say to him: 'Yahweh says this: See, what I built, I am now tearing down. What I planted, I am now pulling up—I will do this throughout all the earth.

UDB of JER 45:4 now reads: 

\v 4 But Baruch, this is what Yahweh says: 'I will destroy this nation that I established. This nation is like a tree that I planted and that I will now pull up with its roots. I will do this everywhere in the world.

Thanks,

TW
