### ISSUE TITLE
Jer 3:23  "many" to "noise on"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#649]
ULB: Only lies come from the hills, from the **many** mountains
UDB: We did not get any help from the idols that we worshiped on the hilltops,
we did not get any help from **making all that noise** up there. 

Few versions translate hamown as "many." Most (including UDB) have something like these:
"the tumult, "noisy worship of false gods," "orgies," "commotion," "noise" 

Could ULB be changed to something like this?
Only lies come from the hills, from the **noise on the** mountains

**Comment by TomWarren** [comment]
The ULB of JER 3:23 now reads: 
\v 23 Surely lies come from the hills, a confusing noise from the mountains; 
\q surely Yahweh our God is the salvation of Israel.

Thanks,

Tom
