### ISSUE TITLE
EXO 34:15

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#65]
Exodus 34:15 ULB Do not make a covenant with the inhabitants of the land. They commit adultery and go after their gods and sacrifice to their gods, and they will invite you **and you ^ eat some of their sacrifices**. 

The last clause sounds strange. Should "will" or "might" be added between "you" and "eat"?

 Or could the idea of _pen_ "lest" be included?
Do not make a covenant with the inhabitants of the land. They commit adultery and go after their gods and sacrifice to their gods, and  when they will invite you, you might eat some of their sacrifices.

**Comment by TomWarren** [comment]
\v 15 Do not make a covenant with the inhabitants of the land. They commit adultery and go after their gods and sacrifice to their gods, and someone invites you, and you eat some of his sacrifice. 

The verse is a bit difficult because it shifts from "they" to "he" in the last phrase. 
This rendering seems regular.

**Comment by SusanQuigley** [comment]
"They commit adultery and go after their gods and sacrifice to their gods, and someone invites you and you eat some of his sacrifice." This sounds like God is asserting that the Israelites eat some of the pagan sacrifices. I don't think he's asserting it. I think he's saying "Be careful" (v. 12 _hishshamer_) **lest** (_pen_) you make a covenant with them and they sacrifice and invite you and you eat it. All of these are things that might/will happen **if** the Israelites are not careful.
Here are some ways of keeping the idea of "lest" in the text.

Be careful. Otherwise  you will make a covenant with the inhabitants of the land. Then they will commit adultery and go after their gods and sacrifice to their gods, and they/someone will invite you and you  will eat some of their/his sacrifices.
or
Do not make a covenant with the inhabitants of the land. If you do, they will commit adultery and go after their gods and sacrifice to their gods, and they/someone will invite you, and you will eat some of their/his sacrifice.

**Comment by TomWarren** [comment]
\v 15 Be careful not to make a covenant with the inhabitants of the land. They will prostitute themselves to their gods and sacrifice to their gods, and someone invites you and you eat some of his sacrifice. 
\v 16 If you do, you will even take some of their daughters for your sons, and their daughters will prostitute themselves to their gods, and they will make your sons will also prostitute themselves to their gods.
\v 17 Do not make for yourselves gods of molten metal.

**Comment by SusanQuigley** [comment]
**They will prostitute** themselves to their gods and sacrifice to their gods, and **someone invites you and you eat** some of his sacrifice. 
Tom, thanks for working on this. But I'm back. The first part of the sentence has future tense, and the second has present tense. It sounds odd in English. Are you ok with that in the ULB?

**Comment by TomWarren** [comment]
\v 15 Be careful not to make a covenant with the inhabitants of the land, when they prostitute themselves to their gods and sacrifice to their gods, and someone invites you and you eat some of his sacrifice. 
\v 16 You even take some of their daughters for your sons, and their daughters prostitute themselves to their gods, and they make your sons prostitute themselves to their gods.
\v 17 Do not make for yourselves gods of molten metal.

I will keep at it. I think the future would have worked, it is natural. But this is closer to the source (Heb). 
Thanks.
