### ISSUE TITLE
MRK 9:44, 46, 48 - footnote

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#650]
I wonder if the end-user will find the footnote on verse 44 very confusing. Since the quote is the entire verse of 44 and 46 and is present in verse 48 - I wonder if there could be more explanation of why the verses are empty. 
Here is what BibleGateway-ESV footnote states: Some manuscripts add verses 44 and 46 (which are identical with verse 48)

Is it possible to not have a footnote refer back to another footnote but rather repeat the information? Especially when they are not in the same chunk.
Also - note that the quote in the footnote is different than what is in verse 48.
Here is what is stated:

 43 If your hand causes you to stumble, cut it off. It is better for you to enter into life maimed than to have two hands and to go into hell, into the unquenchable fire.
\v 44 \f + \ft The best ancient copies omit this phrase from verses 44 and 46, \fqa "where their worm never dies and the fire is never quenched" \f*

\s5
\v 45 If your foot causes you to stumble, cut it off. It is better for you to enter into life lame than to have your two feet and be thrown into hell.
\v 46 \f + \ft See note on verse 44 \f*

\s5
\v 47 If your eye causes you to stumble, tear it out. It is better for you to enter into the kingdom of God with one eye than to have two eyes and to be thrown into hell,
\v 48 where their worm does not die, and the fire is not put out.

**Comment by TomWarren** [comment]
The text of the omitted verse is now consistent. 
The notes in vs 44 and 46 are exactly the same. 

The ULB of MRK 9:43-48 now reads:

\v 43 If your hand causes you to stumble, cut it off. It is better for you to enter into life maimed than to have two hands and to go into hell, into the unquenchable fire.
\v 44 \f + \ft The best ancient copies omit this phrase from verses 44 and 46, \fqa "where their worm does not die, and the fire is not put out" \f*

\s5
\v 45 If your foot causes you to stumble, cut it off. It is better for you to enter into life lame than to have your two feet and be thrown into hell.
\v 46 \f + \ft The best ancient copies omit this phrase from verses 44 and 46, \fqa "where their worm does not die, and the fire is not put out" \f*

\s5
\v 47 If your eye causes you to stumble, tear it out. It is better for you to enter into the kingdom of God with one eye than to have two eyes and to be thrown into hell,
\v 48 where their worm does not die, and the fire is not put out.


Thanks,

Tom
