### ISSUE TITLE
Jer 46:4 get in chariots or on horses

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#652]
ULB Harness the stallions and get on them, you riders

UDB Put harnesses on your horses, and get on their backs.

The commentaries I read say this is about strapping the horses to chariots and riders getting into the chariots rather than on the backs of the horses.

**Comment by TomWarren** [comment]
The commentaries seem to go beyond what is written. What is in the ULB leaves room for the chariots, but they are not mentioned by name. Best left in a note. 
The ULB of JER 46:4 now reads:

\v 4 Put the harness on the horses; mount up on the horses and take your stand with your helmets on;
\q polish the spears and put on your armor.

Thanks, 

TW
