### ISSUE TITLE
Jer 46:8-9 speaker?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#653]
ULB It says, 'I will go up; I will cover the earth. I will destroy cities and their inhabitants.
9Go up, horses. Be angry, you chariots.

UDB It is the army of Egypt
    that will be covering the land like a surging flood,
and they will boast that they will cover the earth
    and will destroy cities and the people who live in them.
9You riders of horses, charge into the battle!

I'm not sure who is speaking in verse 9. In the ULB it seems the Egyptians continue speaking. In the UDB it seems Yahweh is speaking.

**Comment by TomWarren** [comment]
Jeremiah seems to be giving the prophecy from Yahweh, see 46:1. Egypt is the apparent speaker in vs 8. 
For clarity, repeating "Egypt" 2x. 

The ULB of JER 46:8 now reads: 

\v 8 Egypt rises like the Nile, like rivers of water that rise and fall.
\q Egypt says, 'I will go up and I will cover the earth. I will destroy cities and their inhabitants.

The UDB of JER 46:8 

\v 8 The kingdom of Egypt rises and falls  
\q2 like the Nile that surges with a flood of water.
\q1 Egypt will boast that they will cover the earth
\q2 and that they will destroy the cities of their enemies,
\q1 and all  the people who live in them.

Thanks John,

TW
