### ISSUE TITLE
Jer 4:2 ULB  Misplaced quote marks?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#656]
Jer 4:2 ULB and if you swear, 'Yahweh lives in truth, justice, and righteousness,'
the nations will ask for my blessing, and they will praise me.

Most versions treat "in truth, justice, and righteousness" describing how the people swear, not how Yahweh lives.
Could ULB be changed to something like one of these?

and if you swear in truth, justice, and righteousness, 'Yahweh lives,'
the nations will ask for my blessing, and they will praise me.
or
and if in truth, justice, and righteousness you swear, 'Yahweh lives,'
the nations will ask for my blessing, and they will praise me.

**Comment by TomWarren** [comment]
Yep. The ULB of JER 4:2 now reads: 

\v 2 and if you swear, 'Yahweh lives,' in truth, justice, and righteousness,
\q then the nations will bless themselves in him, and in him they will glory. 

A bit different from what we had. 

Thanks,

TW

**Comment by TomWarren** [comment]
Quotations: 
\v 1 "If you return, Israel—this is Yahweh's declaration—then it should be to me that you return.
\q If you remove your detestable things from before me and do not wander from me again,
\q
\v 2 and if you swear, 'Yahweh lives,' in truth, justice, and righteousness,
\q then the nations will bless themselves in him, and in him they will glory."

Thanks, 

TW
