### ISSUE TITLE
Jer 4:20b ULB or UDB Whose tent(s)?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#658]
Jer 4:20b
ULB: They devastate my **tabernacle** and my **tent** abruptly.
UDB: Suddenly all our **tents** will be destroyed; even the **curtains** inside the tents will be ripped apart.

Is it God's tabernacle or the people's tents?
For the ULB, would you want to change "tent" to "curtains"?

I don't see any versions that use the word "tabernacle" here. It seems to make most sense for this to be Jeremiah speaking, not Yahweh.

**Comment by TomWarren** [comment]
The ULB of JER 4:20 now reads: 

\v 20 Disaster follows after disaster; for all the land lies in ruins. Suddenly my tents are destroyed, my curtains in a moment..

This is a redo. 
Thanks,

Tom
