### ISSUE TITLE
Jer 4:23 ULB "and see!" to "Behold"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#659]
Jer 4:23 ULB
23 I saw the land, **and see!** It was formless and empty. ...
24 I looked at the mountains. **Behold**, they were trembling, ...
25 I looked. **Behold**, there was no one, ... 
26I looked. **Behold,** the orchards were a wilderness ...

Could v 23 match the following verses?
I saw the land. **Behold, it** was formless and empty. ...

**Comment by TomWarren** [comment]
The ULB of JER 4:23 now reads: 

\v 23 I saw the land. Behold! It was formless and empty. For there was no light for the heavens.

I replaced the other "See!" with "Behold!" in Jer. 


Thanks,

Tom
