### ISSUE TITLE
EZK 32:27 ULB vs UDB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#66]
Ezekiel 32:27 ULB They **do not lie** with the fallen warriors of the uncircumcised who have gone down to sheol
Ezekiel 32:27 UDB They **will surely lie** there, along with other godless soldiers who have died.
These say opposite things. 

The ULB used to say "Do they not lie with the fallen warriors of the uncircumcised who have gone down to Sheol...?"

**Comment by TomWarren** [comment]
Following the ULB and the Hebrew text:
The UDB: \v 27 They will not lie there beside the mighty soldiers who have died. Their shields will be with their bodies, and their swords will lie under their heads. While they were alive, they terrified many people on the earth.

**Comment by SusanQuigley** [comment]
UDB They will **not lie** there beside the uncircumcised warriors who have died. 
ULB They do **not lie** with the fallen warriors of the uncircumcised
If it is negated, what does that mean? V 26 says that they were killed. If v 27 says they do not like with the fallen warriors, does it mean that they lie elsewhere? Sh
I think the point of the rhetorical question is to say that they **do** lie with the fallen warriors. They're dead just like the others. This whole chapter is about people who die/lie.

**Comment by TomWarren** [comment]
It is difficult. Seems like those who fought valiantly, were not honored in death, but were buried. This was in a series of warnings of defeat after defeat. The next to be warned appears to be Egypt. Vs 28, the NIV supplies "Pharaoh".

**Comment by TomWarren** [comment]
\v 27 Do they not lie with the fallen warriors of the uncircumcised who have gone down to sheol
\q with all their weapons of war, and with their swords placed under their heads?
\q Their shields were placed over their bones. For they were the terror of warriors in the land of the living!
 
\s5
\q
\v 28 So you, Egypt, will be destroyed in the midst of the uncircumcised! And you will lie with those who were killed by the sword! 

Reading the first phrase as a question helps some. This is difficult.

**Comment by TomWarren** [comment]
About my limit for the day. Pick this up tomorrow?

**Comment by SusanQuigley** [comment]
Tom, I see that most versions negate it. NIV has the rhetorical questions "Do they not lie ..." so I thought it meant that they do lie. I see now that what you had was good. "They do not lie ..."

**Comment by pohlig** [comment]
I followed the NIV interpretation, "Do they not lie...?" So I took the rhetorical question out from the UDB and changed it into a statement, "They lie..." That's about all I understand from this discussion, I'm afraid.
