### ISSUE TITLE
Jer 4:27 ULB "them" to "it"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#660]
This is what Yahweh says, "All the land will become a devastation, but I will not completely destroy **them**.

Could "them" be changed to "it" so it refers to the land? Other versions have "it" and Hebrew _wekala_ is singular.

**Comment by TomWarren** [comment]
Yep. The ULB of JER 4:27 now reads: 
\v 27 This is what Yahweh says, "All the land will become a devastation, but I will not completely destroy it.

The Choco seems to be arriving today. 

Thanks,

Tom

**Comment by SusanQuigley** [comment]
Hurray! Thank you!
