### ISSUE TITLE
Job 24:3 apostrophe

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#663]
UDB they take **widow's** oxen to guarantee that the widows

Since "widows" is plural later in the sentence, I think the apostrophe should be after the "s": widows'

**Comment by TomWarren** [comment]
Yes, 
THe UDB of JOB 24:3 now reads:
\v 3 Some take away the donkeys that belong to orphans,
\q2 and they take **widows'** oxen to guarantee that the widows will pay back the money that they loaned to those widows.
