### ISSUE TITLE
Jer 5:2 ULB  By the life of Yahweh

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#664]
Even if they are saying, **'By the life of Yahweh,'** they are making false oaths."

Could "By the life of Yahweh" be changed to "As Yahweh lives" so that it will be the same as 12:16 and 5 other verses?

**Comment by TomWarren** [comment]
The ULB of JER 5:2 now reads: 
\v 2 Although they say, 'As Yahweh lives,' yet they are swearing falsely."

Thanks, 

TW

**Comment by TomWarren** [comment]
I edited this a bit, for clarity (the universal reason), The ULB of JER 5:2 now reads: 
\v 2 You must be truthful, just, and righteous when you swear, 'As Yahweh lives.'
\q Then the nations will bless themselves in him, and in him they will glory."

Thanks,

TW

**Comment by TomWarren** [comment]
I removed the exclamation point for 12:16, and they all read, "As Yahweh lives".

TW
