### ISSUE TITLE
Jer 4:2 ULB  "Yahweh lives"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#665]
and if you swear, **'Yahweh lives,'** in truth, justice, and righteousness,

Could "Yahweh lives" be changed to "As Yahweh lives" so that it could be the same as 12:16 and other verses that word it that way?

**Comment by TomWarren** [comment]
The ULB of JER 4:2 now reads:
\v 2 You must be truthful, just, and righteous when you swear, 'As Yahweh lives.'
\q Then the nations will bless themselves in him, and in him they will glory."


I thought this was closed, but here are the other places where "As Yahweh lives" have been homologated:
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\24-JER\04.usfm (1 hit)
	Line 8: \v 2 You must be truthful, just, and righteous when you swear, '**As Yahweh lives**.'
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\24-JER\05.usfm (1 hit)
	Line 10: \v 2 Although they say, '**As Yahweh lives**,' yet they are swearing falsely."
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\24-JER\12.usfm (1 hit)
	Line 62: \v 16 It will come about that if those nations carefully learn the ways of my people, to swear by my name '**As Yahweh lives**' just as they have taught my people to swear by Baal, then they will be built up in the midst of my people.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\24-JER\16.usfm (2 hits)
	Line 33: \v 14 Therefore see! The days are coming—this is Yahweh's declaration—when it will no longer be said, '**As Yahweh lives**, the one who brought up the people of Israel from the land of Egypt.'
	Line 34: \v 15 For as Yahweh lives, the one who brought up the people of Israel from the land of the north and from the lands where he had scattered them, I will bring them back to the land that I gave to their ancestors.
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\24-JER\23.usfm (2 hits)
	Line 23: \v 7 Therefore see, days are coming—this is Yahweh's declaration—when they will no longer say, '**As Yahweh lives,** who brought the people of Israel up from the land of Egypt.'
	Line 24: \v 8 Instead they will say, '**As Yahweh lives**, who brought up and who led back the descendants of the house of Israel from the northern land and all the lands where they had been driven.' Then they will live in their own land."
  C:\Users\wthom_000\Desktop\GitHub\ulb-en\24-JER\38.usfm (1 hit)
	Line 34: \v 16 But King Zedekiah swore to Jeremiah in private and said, "**As Yahweh lives**, the one who made us, I will not kill you or give you into the hand of those men who are seeking your life."


Hope that covers it, 

Thanks,

TW

**Comment by SusanQuigley** [comment]
Thanks for the the fix and the list.
