### ISSUE TITLE
Jer 46:15 ULB and UDB disagreement?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#666]
ULB Why has your god Apis run away? Why is your bull-god not standing? Yahweh has thrown him down.

UDB Why do those whose strength you trust fall down?
        They cannot stand up,
            because Yahweh will knock them down.

I'm not sure if these mean the same thing. The god Apis was in the form of a bull which can symbolize strength. So is the UDB just translating the meaning of the form of Apis? Or does the UDB use "strength" to refer to "warriors" like most English versions translate it?

Right now, I'm not sure the best way to handle this in the notes.

**Comment by TomWarren** [comment]
The ULB of JER 46:15 now reads: 
\v 15 Why are your mighty ones face-down on the ground? They will not stand, because I, Yahweh, have pushed them to the ground.

Thanks,

Tom
