### ISSUE TITLE
Jer 2:19  ULB missing "of"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#667]
ULB: this is the declaration * Yahweh the Lord of hosts.

This needs "of" where I put the asterisk.

**Comment by TomWarren** [comment]
The ULB of JER 2:19 now reads: 

\v 19 Your wickedness rebukes you, and your faithlessness punishes you. So think about it; understand that it is wicked and bitter
\q for you to abandon me, Yahweh your God, and to dread me no more—this is the **declaration of Yahweh** the Lord of hosts.

Thank you, 

Tom

**Comment by TomWarren** [comment]
For continuity, 
JER 2:19b now reads: 
\q when you forsake Yahweh your God, and have no fear of me—this is the declaration pf Yahweh the Lord of hosts.
JER 49:5 now reads: 
\v 5 See, I am about to bring terror on you—this is the declaration of Yahweh the Lord of hosts—

The phrase "the Lord, Yahweh of hosts" was unnecessarily complex.: and Lord goes with hosts, not with Yahweh... 
The new renderings are closer to the HEB.

Thanks

Tom

**Comment by SusanQuigley** [comment]
Thanks for fixing the "of."

As for the other change, the Hebrew is adonay Yahweh səbaowt.
Wouldn't that be Lord Yahweh of hosts?

The phrase "Yahweh of hosts" occurs 75 times in Jeremiah, and we a tW page for it.

**Comment by TomWarren** [comment]
The phrase Lord of hosts seems clear.
Yahweh of hosts,
The HEB has, "Lord Yahweh of hosts." 
In Eng we would put the descriptive "Lord" next to what he is lord of, "hosts".  There are only 4 of these in Jer. 

Thanks,
Tom

**Comment by TomWarren** [comment]
Yahweh of hosts, is fine.
