### ISSUE TITLE
Jer 2:19 ULB Yahweh the Lord of hosts 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#668]
Jer 2:19 this is the declaration **Yahweh the Lord of hosts**.
Jer 49:5 this is the declaration of **Yahweh, the Lord of hosts**

Could these be changed to the following?
this is the declaration of **the Lord Yahweh of hosts**

"Yahweh of hosts" occurs 75 times in Jeremiah ULB.
"the Lord Yahweh of hosts" occurs 4 times. 

Or maybe a comma would be good in all 6 of these
the Lord, Yahweh of hosts

**Comment by TomWarren** [comment]
This caused a rather complex continuity issue to be revealed in the ULB. 

I rendered the phrases: 

Yahweh the Lord of hosts, and 
the Lord Yahweh of hosts, not using commas. 

 "the Lord Yahweh of hosts" ־אֲדֹנָ֥י יְהוִ֖ה צְבָאֽוֹת׃ 
and "Yahweh God of hosts:   יְהוָֽה־אֱלֹהִ֥ים_׀ צְבָא֡וֹת    --- should be distinguished in the text.

The phrase Yahweh of hosts , יְהוָ֣ה  צְבָא֗וֹת occurs 262x. (many of those would be included in these below)

**The Lord Yahweh of hosts**
ISA 1:24 "Lord Yahweh of hosts"
ISA 3:1 "Lord Yahweh of hosts"
ISA 3:15 "Lord Yahweh of hosts"
ISA 10:16 "Lord Yahweh of hosts"
ISA 10:23 "Lord Yahweh of hosts"
ISA 10:24 "Lord Yahweh of hosts"
ISA 10:33 "Lord Yahweh of hosts"
ISA 19:4 "Lord Yahweh of hosts"
ISA 22:5 "Lord Yahweh of hosts"
ISA 22:12 "Lord Yahweh of hosts"
ISA 22:14 "Lord Yahweh of hosts"
ISA 22:15 "Lord Yahweh of hosts"
ISA 28:22 "Lord Yahweh of hosts"
JER 2:19 "Lord Yahweh of hosts"
JER 46:10 "Lord Yahweh of hosts"
JER 46:10 "Lord Yahweh of hosts"
JER 49:5 "Lord Yahweh of hosts"
JER 50:25 "Lord Yahweh of hosts"
JER 50:31 "Lord Yahweh of hosts"
AMO 9:5 "Lord Yahweh of hosts"

**Yahweh God of hosts:**
PSA 59:5 "Yahweh God of hosts"
PSA 80:4 "Yahweh God of hosts"
PSA 80:19 "Yahweh God of hosts"
PSA 84:8 "Yahweh God of hosts"
PSA 89:8 "Yahweh God of hosts"
JER 44:7 "Yahweh God of hosts"

For 26 total of both expressions.
