### ISSUE TITLE
JER 15:12 mismatch

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#669]
ULB  ...Especially iron from the north that is mixed with bronze?

UDB ...But Judah's enemies, who are as strong as iron or bronze

The ULB has iron mixed with bronze whereas the UDB has iron/bronze.

**Comment by TomWarren** [comment]
The UDB of JER 15:12 was edited and now reads: 
\v 12 People of Judah, you know how strong iron is when it is mixed with bronze, 
\q2 it is very hard and good for weapons. 
\q1 That iron mixed with bronze metal is just like the strength of your enemies when they attack Judah from the north,
\q2 no one will be able to stop them.

Thanks Kim, 

TW
