### ISSUE TITLE
Jer 46:28 quotation marks (part 2)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#672]
Depending on what you do with the quotation marks from my previous comment on 46:14, you may need to adjust the quotation marks here as well. 

ULB 27"But you, my servant Jacob, do not fear. Do not be dismayed, Israel, for see, I am about to bring you back from far away, and your offspring from the land of their captivity. Then Jacob will return, find peace, and be secure, and there will be no one to terrify him. 28You, my servant Jacob, do not fear—this is Yahweh's declaration—for I am with you, so I will bring complete destruction against all the nations where I scattered you. But I will not destroy you completely. Yet I will discipline you justly and will certainly not leave **you unpunished."'"**

The way the text stands right now, this should close with just one set of double quotation marks. (I think)

**Comment by TomWarren** [comment]
Yep. This was done in a previous ISSUE. 
 The ULB of JER 46:28 now reads; 

\v 28 You, my servant Jacob, do not fear—this is Yahweh's declaration—for I am with you, so I will bring complete destruction against all the nations where I scattered you. But I will not destroy you completely. Yet I will discipline you justly and will certainly not leave you unpunished."

Thanks, 

TW
