### ISSUE TITLE
JER 9:12 what/who

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#673]
Who is the wise man that understands this? 
What does Yahweh's mouth proclaim to him so he might report it?
Why has the land perished?...

The second question above is translated differently than all other translations. Here the word "what" is usually translated with the sense "who."

**Comment by TomWarren** [comment]
The ULB of JER 9:12 now reads: 
\v 12 What man is wise enough to understand this? To whom has the mouth of Yahweh spoken, and he will declare it?
\q Why has the land perished and been destroyed like the wilderness that no one can pass through.

Thanks Kim,

Tom

**Comment by kim-putter** [comment]
The last question needs a question mark instead of a period.

**Comment by TomWarren** [comment]
The ULB of JER 9:12 now reads:
\v 12 What man is wise enough to understand this? To whom has the mouth of Yahweh spoken, and he will declare it?
\q Why has the land perished and been destroyed like the wilderness that no one can **pass through?**

Thanks,

Tom
