### ISSUE TITLE
Job 1:21 missing word

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#674]
ULB 21He said, "It was naked **that I out** of my mother's womb, and it

Need to add "came" after "I."  

"It was naked that I came out of my mother's womb"

**Comment by TomWarren** [comment]
The ULB of JOB 1:21 now reads: 
\v 21 He said, "I was naked when I came out of my mother's womb, and I will be naked  when I will return there. It is Yahweh who gave, and it is Yahweh who has taken away. May the name of Yahweh be blessed."

Thanks John,

Tom
