### ISSUE TITLE
Jer 48:39 add possessive

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#678]
ULB Moab turns **it** back in shame!

I believe this should be "Moab turns **its** back in shame."

**Comment by TomWarren** [comment]
The ULB of JER 48:39 now reads: 
\v 39 How it has been shattered! How they howl in their lamenting! **Moab turns its back** in shame! So Moab will become an object of derision and a terror to all those who are around him."

Thanks John,

Tom
