### ISSUE TITLE
Jer 7:1 ULB The word that came to Jeremiah from Yahweh, "..."

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#679]
7:1 The word that came to Jeremiah from Yahweh, "..."

I wonder if this should have "saying" since _lemor_ is there and the quote immediately follows it, or if it would be good to delete "saying" in the verses below.  If "saying" is not used, then maybe a colon should precede the quote.

11:1 The word that came to Jeremiah from Yahweh, **saying**, "..."
18:1  The word that came to Jeremiah from Yahweh, saying,  "..."
30:1 The word that came to Jeremiah from Yahweh, saying, "..."

**Comment by TomWarren** [comment]
This is a bit strange in English. I would be ok with taking out ", saying" for the purpose of clarity. 
The phrase occurs 10 x in Jer, but most are for the more complex sentences, like, 
JER 32:1 The word came to Jeremiah from Yahweh in the tenth year of Zedekiah king of Judah, the eighteenth year of Nebuchadnezzar.
JER 34:1 a complex sentence with great distance between "The word that came .... saying"
\v 1 The word that came to Jeremiah from Yahweh, when Nebuchadnezzar king of Babylon and all of his army, together with all the kingdoms of the earth, the domains under his power, and all their people were waging war against Jerusalem and all of her cities, saying: 

JER 34:8-9 now reads" 
\v 8 The word came to Jeremiah from Yahweh after King Zedekiah had made a covenant with all the people in Jerusalem, to proclaim freedom to them
\v 9 that each man must free his Hebrew slaves, both male and female, so one was to make a slave of a Jew, who was his brother.
See JER 35:1 \v 1 The word came to Jeremiah from Yahweh in the days of Jehoiakim son of Josiah king of Judah, saying,
See JER 40:1 \v 1 The word came to Jeremiah from Yahweh after Nebuzaradan the commander of the king's bodyguard had released him at Ramah. He had found Jeremiah bound with chains among all the captives of Jerusalem and Judah who were being carried into exile to Babylon.

Hope this is helpful. 

Thanks,

Tom
