### ISSUE TITLE
JER 23:37  Sentence Fragment starting with "Because"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#68]
Jeremiah 23:38  The string starting with "Because" is not a full sentence.  Suggestion: either delete the word "Because," or replace the period at the end of v 38 with a comma and delete the word "Therefore" in v 39. 

\v 38 You report a declaration from Yahweh, but Yahweh says this, "**Because you say, '...,' even though I sent a command to you and said, 'Do not say: This is a declaration from Yahweh.'**
\v 39 Therefore, see, I am about to pick you up and throw you away from me, along with the city that I gave you and your ancestors.

**Comment by hharrissWA** [comment]
Edited these verses in keeping with the structure noted.
