### ISSUE TITLE
JER 9"12

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#680]
The last question in this verse needs a question mark instead of a period.

**Comment by TomWarren** [comment]
The ULB of JER 9:12 now reads: 
\v 12 What man is wise enough to understand this? To whom has the mouth of Yahweh spoken, and he will declare it?
\q Why has the land perished and been destroyed like the wilderness **that no one can pass through?**

The question mark was added. 
Thank you.

Tom Warren
