### ISSUE TITLE
Jer 49:1 typo

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#681]
UDB the people who **decended** from Ammon

Should be "descended"

**Comment by TomWarren** [comment]
The UDB of JER 49:1 now reads:
\v 1 This message is about the people who descended from Ammon. This is what Yahweh says:
\q1 "There are plenty of Israelite people left
\q2 to occupy the land of the tribe of Gad.
\q1 So, why are the people who worship the god Milcom living in those towns?

Thanks John,

Tom
