### ISSUE TITLE
Jer 49:2 "daughters will light fires"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#682]
ULB its daughters will light fires

May want to change "daughters" to "villages" since that is what it means in the context. If not, I can explain it in the notes.

Also, it seems that the verb should be passive: "it daughters/villages will be lit on fire"

**Comment by TomWarren** [comment]
The ULB of JER 49:2 now reads:
\v 2 So look, the days are coming—this is Yahweh's declaration—when I will sound the signal for battle
\q against Rabbah among the people of Ammon, so it will become a deserted heap and its villages will be set on fire.
\q For Israel will possess those who possessed him," says Yahweh.

Note the edit on "will be set on fire." Will be "kindled" or lit. 

Thanks John,

Tom
