### ISSUE TITLE
Eph 5:18  Sentence-initial "And"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#683]
Eph 5:18  ULB **And** do not get drunk with wine,

I see that "And" was removed from the note, but it's still in the ULB.
**Do not get drunk with wine** - "You should not get drunk from drinking wine"

Would you want to delete "And" from the ULB?

**Comment by TomWarren** [comment]
Two against one. Sorry. 

There were some instructions (especially in Paul) when he picks up a theme of teaching, and the connective reminds the reader what he was doing. So here, the "and" can stand. 

The Greek is "And do not get drunk with wine." 
I think it can stand as is. The ENG can carry the load. Perhaps more loose in the UDB? We are trying to keep as close to the source as possible. Most modern versions are with us on this. 


Thanks, 
Tom

**Comment by SusanQuigley** [comment]
No problem. Someone had taken the "And" out of the note. I'll just put it back into the note.
