### ISSUE TITLE
Jer 49:4 ULB/UDB agreement?

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#684]
ULB Why are you proud of your **strength**? Your strength **will flow away**

UDB You are very proud of your **very fertile valleys**,
    but they **will soon be ruined.**

These seem to be taking two different interpretive paths.

**Comment by TomWarren** [comment]
This could be a place for a textual footnote, that could be either valley, treasure, or power/might. 
There is a high parallelism in these two sections: 

The UDB of JER 49:4 now reads:
\v 4 Why do you brag about your valleys, 
\q your valleys that are so fruitful, you faithless daughter?
\q You think that your wealth will bring you protection against your enemies
\q and so you dare to ask, "Who is there who can come against me?'

The ULB for JER 49:4 now reads: 
\v 4 Why do you boast of your valleys,
\q2 your valleys that are so fruitful, you unfaithful daughter? 
\q1 You trusted in your riches,
\q2 and you said, 'Who dares to come against us!'

Thanks, 

Tom
