### ISSUE TITLE
GEN 42:9

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#688]
The readers want to confirm that the double 'had' is correct.

\v 9 Joseph remembered the dreams that he had had about them. He said to them, "You are spies. You came to see the undefended parts of the land."

**Comment by TomWarren** [comment]
Removing an "had".

The ULB of GEN 42;9 now reads:

\v 9 Joseph remembered the dreams that he **had** about them. He said to them, "You are spies. You came to see the undefended parts of the land."

Thanks,

Tom

**Comment by pjoakes** [comment]
"had had" was grammatically correct, because the pluperfect was necessary to make the dreaming occur before the past-tense remembering. Why not follow the Hebrew and say, "Joseph remembered the dreams that he had dreamed about them."

**Comment by TomWarren** [comment]
OK. Perry's rendering is closer to the HEB, as well.
The ULB of GEN 42:9 now reads: 
\v 9 Then Joseph remembered the dreams he had dreamed about them, and he said to them, "You are spies! You have come to see the undefended parts of the land."

Thanks, 
Tom
