### ISSUE TITLE
JER 10:12 parallelism

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#689]
"The maker of earth in his power established dry land in his wisdom and spread the heavens in his understanding."

The ULB renders this verse in a confusing way. The three verbs "make, establish, and spread" are parallel here and this is lost by make the first into a noun "maker." Consider changing.

**Comment by TomWarren** [comment]
The ULB of JER 10:12 now read:
\v 12 But it was he who made the earth by his power, and he established the world by his wisdom, and by his understanding he stretched out the heavens.

Thanks Kim,

Tom
