### ISSUE TITLE
ULB John 20:16

### ISSUE THREAD

**Issue by pjoakes** [Door43/ulb-en#690]
Jesus said to her, "Mary." She turned, and said to him in Aramaic, "Rabboni" (which means "Teacher").

All other occurrences of Ἑβραϊστί in the ULB are translated as "Hebrew." For consistency, I suggest here:
 
Jesus said to her, "Mary." She turned, and said to him in Hebrew, "Rabboni" (which means "Teacher").

**Comment by TomWarren** [comment]
FYI, the UBS Handbook has: The expression "in Hebrew"  (5.2; 19.13,17,20) means “in Aramaic.  Perhaps we could add a note where "in Hebrew" appears saying that the dialect of Hebrew was Aramaic and that some versions identify it as such.

It is split about 50/50 for modern versions. Some read "in Aramaic" : ESV, NIV, NET, CEV, ; and some, namely: GNT, ASV, NLT, and REV52 have "in Hebrew", interesting that the KJVA omits the language name, and has simply, "saith unto him, Rabbon'ni; which is to say Master."

Aramaic only appears in the ESV NT in John, 5:2: 19:13, 17, 20; 20: 16.

Ἑβραϊστί appears in John 5:2; 19:13, 17, 20; 20:16; REV 9:11; 16:16

Only in 
The OT uses of "Aramaic" are reserved.

I will change the single occurrences of "Aramaic" in the ULB NT and checking that every other use of Ἑβραϊστί in the New Testament, will read "Hebrew". 

The ULB of JHN 20:16 now reads: 
\v 16 Jesus said to her, "Mary." She turned, and said to him in **Hebrew**, "Rabboni" (which means "Teacher").


Thanks, 

Tom Warren
