### ISSUE TITLE
Act 22:4 ULB Typo

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#692]
I persecuted this Way to the death, **binding up and deliver** to prison both men and women,

"deliver" should be "delivering"

We have a note involving this phrase.
**binding up and deliver to prison both men and women** - "tying up both men and women and putting them in prison"

**Comment by TomWarren** [comment]
The ULB of ACT 22:4 now reads:
\v 4 I persecuted this Way to the death, **binding up and delivering them** to prison both men and women,

Thanks,

Tom
