### ISSUE TITLE
Jer 5:5 ULB Missing end quote mark

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#694]
_4_ So I said, "Surely these are only poor people.
They are foolish, for they do not know Yahweh's ways, nor their God's decrees.
_5_ I will go to the important people and declare God's messages to them, for they at least know Yahweh's ways,
the decrees of their God.** But they all broke their yoke together; they all tore apart the chains that bound them to God.

It looks like there should be a final double quote mark where I put the asterisk in v.5. This will close the quote that started in v 4. 
Also it would be good to have a line break after the end quote mark.

**Comment by TomWarren** [comment]
The ULB of JER 5:4-5 is now a quotation block:
\v 4 So I said, "Surely these are only poor people.
\q They are foolish, for they do not know Yahweh's ways, nor their God's decrees.
\q
\v 5 I will go to the important people and declare God's messages to them, for they at least know Yahweh's ways,
\q the decrees of their God. But they all broke their yoke together; they all tore apart the chains that bound them to God."

Thanks,

Tom

**Comment by SusanQuigley** [comment]
Could the end quote mark be moved to a place earlier in v5 after "decrees of their God"? This would fit the UDB and other versions that use quote marks.

Jeremiah said that he would go talk to the people who knew Yahweh's ways, but after he said he would do that, he saw that they, too, were rebellious.

\v 4 So I said,
\q **"Surely these are only poor people.
\q They are foolish, for they do not know Yahweh's ways, nor their God's decrees.
\q
\v 5 I will go to the important people and declare God's messages to them, 
\q for they at least know Yahweh's ways, the decrees of their God."**
But they all broke their yoke together; they all tore apart the chains that bound them to God.

**Comment by TomWarren** [comment]
Yes. It needed reformatting for this. 
The ULB of JER 5:4-5 now reads:
\v 4 So I said, "Surely these are only poor people.
\q They are foolish, for they do not know Yahweh's ways, nor their God's decrees.
\q
\v 5 I will go to the important people and declare God's messages to them, for they at least know Yahweh's ways, the decrees of their God."
\q But they all broke their yoke together; they all tore apart the chains that bound them to God.

Thanks,

Tom
