### ISSUE TITLE
Jer 5:7 ULB took on the marks of

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#695]
Why should I pardon these people?
Your sons have abandoned me and have made oaths by what are not gods.
I fed them fully, but they committed adultery and **took on the marks of** a house of prostitution.

I don't know what "took on the marks of a house of prostitution" means. I don't see anything like it other versions. They say that the people "assembled in troops" or "thronged to" the prostitutes house.

**Comment by TomWarren** [comment]
The ULB of JER 5:7 was edited and now reads:
\v 7 Why should I pardon these people?
\q Your sons have abandoned me and have made oaths by what are not gods.
\q I fed them fully, but they committed adultery and walked in great numbers to the houses of prostitutes.

The last verb: יִתְגֹּדָֽדוּ׃ is rendered "cut themselves," but with referenced to Jer 5:7, also, "gather in troops, or bands, to throng" which is rendered here as "walked in great numbers" 

Thanks Susan, 

Tom
