### ISSUE TITLE
Jer 5:18 ULB  that then

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#699]
It will happen when you, Israel and Judah, say, 'Why has Yahweh our God done all these things to us?' **that then** you, Jeremiah, will say to them, 'Just as you abandoned Yahweh and worshiped foreign gods in your land, so you will also serve strangers in a land that is not your own.'

The words "that then" together sound awkward. Perhaps it was left over when "It will happen" and "that" were added to the ULB. Could it be changed to one of these?

It will happen when you, Israel and Judah, say, 'Why has Yahweh our God done all these things to us?' **that** you, Jeremiah, will say to them, 'Just as you abandoned Yahweh and worshiped foreign gods in your land, so you will also serve strangers in a land that is not your own.'
or
When you, Israel and Judah, say, 'Why has Yahweh our God done all these things to us?' **then** you, Jeremiah, will say to them, 'Just as you abandoned Yahweh and worshiped foreign gods in your land, so you will also serve strangers in a land that is not your own.'

**Comment by TomWarren** [comment]
The ULB of JER 5:18 now reads:
When you, Israel and Judah, say, 'Why has Yahweh our God done all these things to us?' then you, Jeremiah, will say to them, 'Just as you abandoned Yahweh and worshiped foreign gods in your land, so you will also serve strangers in a land that is not your own.'

Thanks Susan, 

Tom
