### ISSUE TITLE
Job 19:22 ULB sentence break

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#7]
\v 22 Why do you persecute me as if you were God;
\q Why are you not satisfied with consuming my flesh?

We either need to uncapitalize "Why" after the semi-colon, for put a question mark after "God". Since these are two separate rhetorical questions, it would be easier to write translation notes if we added the question mark to the first clause to make it a separate sentence.

**Comment by TomWarren** [comment]
Changed ; to ? 
Fixed.
