### ISSUE TITLE
Hab 2:16

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#700]
Text is trying to extend the rhetorical question from 2:15, but all other English versions end the extension at the first Hebrew word, as does ULB. All other versions continue the verse as declarative, not interrogative. (Note that the first "When" sentence ends with a period, as with other versions.)

When one came to a heap of grain expecting twenty **measures, but there** were only ten. When one came to the wine vat to draw out fifty **measures, but there were only twenty?**
When one came to a heap of grain expecting twenty **measures, there** were only ten. When one came to the wine vat to draw out fifty **measures, there were only twenty.**

**Comment by TomWarren** [comment]
The ULB of HAG 2:15-16 with some editing, now reads:
\v 15 So now, think in your minds about the past leading up to this very day. Before stone was placed upon stone in the temple of Yahweh,
\v 16 how was it then? When you came to a heap of twenty measures of grain, there were only ten; and when you came to the wine vat to draw out fifty measures, there were only twenty.

Thanks Henry, 

Tom
