### ISSUE TITLE
Jer 5:19 ULB  "worshiped" to "served

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#701]
ULB: Just as you abandoned Yahweh and **worshiped** foreign gods in your land, so you will also serve strangers in a land that is not your own

Could "worshiped" be changed to served to make the similarity to their sin and the consequences clearer?

Because the ULB says "worshiped" someone wrote this note. It seems to imply that some versions have not translated it correctly. 
**worshiped foreign gods** - Many versions translate, "served foreign gods," but here what is meant is worshiping them.

I would rather have a note like this:
 **Just as you ... served foreign gods in your land, so you will also serve strangers** -  Here "served foreign gods" represents worshiping foreign gods. God would punish them for serving foreign gods by making them serve foreigners. AT: "Because you ... worshiped foreign gods in your land, you will have to serve foreigners"  (See: Metaphor)

**Comment by TomWarren** [comment]
The ULB of JER 5:19 has been edited, and it now reads:
\v 19 When you, Israel and Judah, say, 'Why has Yahweh our God done all these things to us?' then you, Jeremiah, will say to them, 'Just as you abandoned Yahweh and **served foreign gods** in your land, so you must also serve strangers in a land that is not your own.'

Thanks Susan, 

Tom
