### ISSUE TITLE
Hag 2:23

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#702]
I will **set you like the seal on my ring**
The Heb seems to indicate the entire unit, not the seal separate from the ring, and whatever it is goes on the finger. There is no prepositional phrase for "on my." Most versions have
I will **make you like my signet ring**

**Comment by TomWarren** [comment]
\v 23 On that day—this is the declaration of Yahweh of hosts—I will take you, Zerubbabel son of Shealtiel, as my servant—this is Yahweh's declaration.
\q2 I will make you like the seal on my ring, for it is you that I have chosen!
\q2 —this is the declaration of Yahweh of hosts!'"


There it is.

Thanks,

Tom

**Comment by hmw3** [comment]
Except that the problem wasn't the verb, it was what he would be like. 

\q2 I will make you **like the seal on my ring,** for it is you that I have chosen!
should be
\q2 I will make you **like a signet ring,** for it is you that I have chosen!

**Comment by TomWarren** [comment]
\q2 I will make you like a signet ring, for I have chosen you!
\q2 —this is the declaration of Yahweh of hosts!'"
