### ISSUE TITLE
ECC 2:8 questions needed

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#704]
"... I got male and female singers for myself, and delights from the children of mankind, concubines and wives."

I had few questions. First why is the word "from" used above instead of "of?" Also, would "sons" be a better translation instead of "children?" Also, should "wives" be mentioned with "concubines?"

**Comment by TomWarren** [comment]
Question 1:  The ULB of ECC 2:8 now reads:
\v 8 I also accumulated for myself silver and gold, the treasures of kings and provinces. I got male and female singers for myself—the delights of the children of humanity—and many concubines.

The order of the text appears to be a list, with the description "the delights of the children of humanity" a parenthetical description. 

Question 2: the reference of "sons of" is referring to the concubines and wives, and for clarity for the MTT, is translated as "children" much the same as the "children of Israel."  Here it is the "children of humanity {הָאָדָ֖ם}."

Question 3: wives are not mentioned but the enigmatic expression  שִׁדָּ֥ה  וְשִׁדּֽוֹת׃, some render as "breast and breasts" a crudity, to be sure. The lexicons translate as: "unknown." So any suggestion would be problematic. 
The best appears to be simply, "concubines"  

From the UBS Handbook from ParaTExt: 

The concluding phrase and many concubines, man's delight raises many problems. The Hebrew text is literally “exquisite delights of the sons of man,” followed by a phrase that is difficult to understand (siddah we siddoth). RSV|prj:RSV52.ECC.2.8 places the last phrase first, rendering it many concubines (NIV|prj:NIV84.ECC.2.8 “harem”). As the root sdh does not occur anywhere else, it is difficult to fix its meaning absolutely, but the context almost demands that sexual pleasure is its sense here. This is quite appropriate when we recognize that Solomon is the model for much of this book (see 1 Kgs 11.3). The Hebrew phrase consists of a singular plus a plural form of the noun siddah; such a construction probably indicates a large number, hence the rendering many. If “concubine” is a term that is not known or used in the translator's language, then “women” can be used. Man's delight: though the Hebrew phrase is unusual, its general sense is clear, namely, “what delights any man.” Two possible models for translation are: • I amassed silver and gold; kings and foreign powers gave me their treasures. I organized groups of male and female singers, and as for women,* I enjoyed as many of them as any man could want. • I became extremely wealthy. I was entertained by men and women singers, and enjoyed many concubines,* the delight of any man. Possible footnote: *The Hebrew is obscure. Some versions translate “concubines,” while some refer to wealth. Most see a reference to sexual pleasures.
