### ISSUE TITLE
Ezk 18:7 awkward sentence (Maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#705]
ULB What can be said about a man **does not oppressed** anyone

I think it should "who does not oppress"

(This does not affect the notes)

**Comment by TomWarren** [comment]
Thanks, 
The ULB of EZK 18:7 now reads:
\v 7 What can be said about **a man who does not oppress anyone,** and he gives back to the debtor what was put up as security for a loan, and he does not commit theft but gives his food to the hungry and he covers the naked with clothes, is he a righteous man?
