### ISSUE TITLE
Ezk 18:29 Rhetorical question wording (maybe needed for notes)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#706]
ULB It is not your ways that are not fair?

If you keep as a rhetorical question it should be "Is it not your ways that are not fair?"

If you change to a statement it should be "It is your ways that are not fair."

If you keep as a question I will need to add a note. If you make it a statement, no change to notes is necessary.

**Comment by TomWarren** [comment]
The question was changed to a statement.
The ULB of EXK 18:29 has been changed to read:
\v 29 But the house of Israel says, 'The way of the Lord is not fair!' How is my way not fair, house of Israel? It is your ways that are not fair.
