### ISSUE TITLE
ECC 4:1 maintenance 

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#707]
...Look at the tears of oppressed people...

Here "look" should be 1st person Sing. referring to the author; it shouldn't be a command.

**Comment by TomWarren** [comment]
The ULB of ECC 4:1 now reads:
\v 1 Once again I thought about all the oppression that is done under the sun.
\q1 And behold, the tears of oppressed people,
\q2 and they had no one to comfort them!
\q1 Power was in the hand of their oppressors,
\q2 and there was no one to comfort them!

Thanks Kim, 

Tom
