### ISSUE TITLE
Jer 5:13 ULB there is no one else to declare Yahweh's messages to us

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#708]
11 For the houses of Israel and Judah have completely betrayed me—this is Yahweh's declaration—
12 and they have denied me. They say, 'He is not real.
Evil will not come on us, nor will we see sword or famine.
13 For the prophets have become as useless as the wind **and there is no one else to declare Yahweh's messages to us.** Let their threats come upon themselves.'

The phrase in bold gives the impression that the people really wanted prophets who would declare God's word. But verses 11 and 12 show that they did not want to hear God's word. 

Could that phrase be changed to something like one of these?
and his word is not in them. 
and what they say is not Yahweh's message.
and they do not declare Yahweh's message.

**Comment by TomWarren** [comment]
The ULB of JER 5:11-13 now reads:
\v 11 For the houses of Israel and Judah have completely betrayed me—this is Yahweh's declaration.
\q
\v 12 They have spoken falsely about Yahweh and said, 'He will do nothing;
\q no harm will not come upon us, and we will not see sword or famine.
\q
\v 13 The prophets will become wind, the word is not in them, so let what they say be done to them.'"

The was very UDBish. Hope this helps.

Tom

**Comment by SusanQuigley** [comment]
v12  ... **no** harm will **not** come upon us, 

Thanks for fixing the whole chunk.
Please delete either "no" or "not."
