### ISSUE TITLE
Jer 5:13 ULB  Closing quote mark

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#709]
7 Why should I pardon these people?
Your sons have abandoned me and have made oaths by what are not gods.
I fed them fully, but they committed adultery and walked in great numbers to the houses of prostitutes.
...
12 and they have denied me. They say, 'He is not real.
Evil will not come on us, nor will we see sword or famine.
13For the prophets have become as useless as the wind and there is no one else to declare Yahweh's messages to us. Let their threats come upon themselves.'"

There is a double quote mark closing what God says in 7-13. It would be good either to delete it or to add a double quote mark opening what God says at the beginning of v. 7.

**Comment by TomWarren** [comment]
Right. 
Added quote at the beginning of JER 5:7, to balance them out. 

Thanks,

Tom
