### ISSUE TITLE
1SA 16:5 And he And he

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#71]
1SA 16:5  **And he And he dedicated** Jesse and his sons to Yahweh, 
Delete one "And he"

**Comment by Hanker10** [comment]
Done.

**Comment by TomWarren** [comment]
\v 5 He said, "In peace; I have come to sacrifice to Yahweh. Dedicate yourselves to Yahweh for the sacrifice and come with me." And he dedicated Jesse and his sons to Yahweh, and then he called them to the sacrifice.
This was synced.
