### ISSUE TITLE
Jer 5:21 ULB vs UDB  Who is this talking about?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#711]
ULB: 'Hear this, foolish people! For **idols** have no will;
there are eyes in **them**, but **they** cannot see. There are ears on **them**, but **they** do not hear.

UDB: "Listen to this, **you** people who are foolish and who do not have any sense:
**You** have eyes, but it is as though **you** cannot see;
**you** have ears, but it is as though **you** cannot hear.

In the ULB it's about idols, and in the UDB it's about the people.

**Comment by TomWarren** [comment]
The UDB was edited to follow the ULB:
\v 21 "Listen to this, you people who so are foolish! 
\q2 The idols that you worship have no understanding that they can answer you. 
\q1 Yes, they have eyes, but they cannot see anything. 
\q2 Yes, they have ears, but they cannot hear anything.  

Thanks,

Tom

**Comment by TomWarren** [comment]
The ULB of HAG 2:23 has been changed to read:
\v 23 On that day—this is the declaration of Yahweh of hosts—I will take you, Zerubbabel son of Shealtiel, as my servant—this is Yahweh's declaration.
\q2 I will **make you like a signet ring,** for it is you that I have chosen!
\q2 —this is the declaration of Yahweh of hosts!'"

Thanks,

Tom
