### ISSUE TITLE
Rom 16:26 Missing phrase.

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#715]
but that now has been revealed and made known by the prophetic scriptures
according to the command of the eternal God, for the obedience of faith.

The phrase "to all the nations" is missing."  How about something like one of these?

but that now has been revealed and made known by the prophetic scriptures **to all the nations**
according to the command of the eternal God, for the obedience of faith.
or 
but that now, **by the prophetic scriptures**, has been revealed and made known **to all the nations**
according to the command of the eternal God, for the obedience of faith.

**Comment by TomWarren** [comment]
The ULB of ROM 16:26 now reads:
\v 26 but now has been revealed, and through the prophetic writings has been made known to all nations, according to the command of the eternal God, for the obedience of faith.

All phrases are there now.

Tom
