### ISSUE TITLE
Luk 10:21 ULB - O Father

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#72]
I thought we were removing the vocative forms.

**Comment by BramvandenHeuvel** [comment]
O Larry, though hast the right of it!

**Comment by lrsallee** [comment]
I did a rough search and found 71 occurrences of "O" in the ULB and UDB.

**Comment by SusanQuigley** [comment]
Yesterday Jim and I were looking at exclamations, and he noticed that the ”Oh” in Luke 24:25 was really a vocative and changed it to ”O.” I think he’ll need to be in on this discussion.

Susan

On May 26, 2016, at 9:47 AM, lrsallee <notifications@github.com<mailto:notifications@github.com>> wrote:


I did a rough search and found 71 occurrences of "O" in the ULB and UDB.

**Comment by lrsallee** [comment]
So...we are keeping "O" but not "Oh"???

**Comment by SusanQuigley** [comment]
No. We're keeping "Oh" for exclamations. Apparently we're keeping "O" for vocatives, but I don't know if it's because it just sort of happened by accident or because a decision was made to keep them.

**Comment by TomWarren** [comment]
O Father, is good. 
Thanks,
