### ISSUE TITLE
Jer 6: 7 ULB "plague" to "wounds"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#720]
Just as a well keeps giving water, so this city keeps producing wickedness.
Violence and disorder are heard in her.  Suffering and **plague** are continually before me.

The word "plague" strongly implies that it is judgment from God; people can't cause plagues.

But it's possible that makkah is something that people cause. Could makkah be translated as "wounds" to leave open that possibility? If it is understood as something that people cause, then this sentence would basically be telling about the wickedness of the people of Jerusalem.

Suggestion:
Just as a well keeps giving water, so this city keeps producing wickedness.
Violence and disorder are heard in her.  Suffering and **wounds** are continually before me.

**Comment by TomWarren** [comment]
The ULB of JER 6:7 now reads;
\v 7 As a well pours out fresh water, so this city keeps producing wickedness.
\q Violence and disorder are heard within her; sickness and wounds are continually before my face. 

Thanks Susan, 

Tom
