### ISSUE TITLE
Ecc 12:11 missing imagery? (Maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#722]
ULB 11The words of wise people are like goads. Like nails driven deeply are the words of the masters in collections of their proverbs, which are taught by one shepherd.

UDB 11The things that I and other wise people say teach people what they should do. They are like our shepherd.

The UDB leaves out a lot of imagery. I didn't know if this was on purpose or if you would want to add it in.

**Comment by TomWarren** [comment]
The UDB of ECC 12:11 now reads:
\v 11 The things that I and other wise people say give directions, and they are like nails that fix things together and last a long time. When people follow clear and understandable directions, they know what is right, and, so then they can do it. The sayings of the wise are like our shepherd who guides us where we need to go.
