### ISSUE TITLE
Jer 6:10 ULB Who reproaches?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#723]
Jer 6:10
ULB:  Look! The word of Yahweh has come to them **to correct them**, but they do not want it.
UDB: They **scorn** my messages;
they do not want to listen to them at all!"

Most versions that do not simply say "the word of the the LORD is a reproach to them" treat leherpah "reproach" as the UDB does -- the **people's** attitude toward God's word.

**Comment by TomWarren** [comment]
The UDB of JER 6:10 now reads:
\v 10 Who can I, Jeremiah, speak to? Who would listen to me, even if I spoke to them? 
\q2 The ears of the Israelite people are unable to hear what I have to tell them.
\q1 See! the message Yahweh gave me to tell them is offensive to them.  
\q2 When they hear the message of Yahweh, they hate what I tell them!"

Thanks Susan,

Tom
