### ISSUE TITLE
2 Sam 15:19

### ISSUE THREAD

**Issue by pjoakes** [Door43/ulb-en#724]
Then the king said to Ittai the Gittite, "Why did you go you with us, too? Return and stay with King Absalom, for you are a foreigner and an exile. Return to your own place.

This is too speculative for a literal version. The word "Absalom" is not in the text, and a strong case can be made that "the king" here refers to the king of Gath, Ittai's former king that David is telling him to return to, along with his "brothers" from that same kingdom. If we retain the last sentence, then we must delete "Absalom," because the two ideas are incompatible: either he is going to his own place, or he is going with Absalom.
I suggest:
Then the king said to Ittai the Gittite, "Why would you go you with us, too? Return and stay with the king, for you are a foreigner and an exile. Return to your own place.

**Comment by TomWarren** [comment]
The ULB for 2SA 15:19 now reads:

\v 19 Then the king said to Ittai the Gittite, "Why will you come with us? Return and stay with the king, for you are a foreigner and an exile. Return to your own place.

Thanks, 
Tom
