### ISSUE TITLE
Jol 2:25 - 3:13

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#725]
This is punctuated as one quotation from YHWH. This makes the line at 3:11 
Yahweh, bring down your mighty warriors
awkward because it has Yahweh telling people to proclaim that other people will say that.

I recommend following most versions and breaking the main quote at the end of 3:8 and having 3:9-13 be Joel's words. That way from "Prepare yourselves for war" to "gather yourselves together there" can be the direct quote of what is to be proclaimed to the nations. Then "Yahweh, bring down your mighty warriors" can be outside the quote. Then "Let the nations wake themselves up" to "for their wickedness is enormous" is another quote of what is to be proclaimed to the nations.

In other words ...

Instead of:

\c 2
...
\v 19 Yahweh answered his people,
...
\v 25 "I will restore to you the years of crops that the swarming locust has eaten
...
\c 3
...
\v 8 I will sell your sons and your daughters,
...
\q For Yahweh has spoken.
...
\v 9 Proclaim this among the nations,
\q 'Prepare yourselves for war,
...
\v 10 Beat your plowshares into swords
...
\q "I am strong."
...
\v 11 Hurry and come,
\q all you nearby nations,
\q gather yourselves together there.
\q Yahweh, bring down your mighty warriors.'
...
\v 12 Let the nations wake themselves up
...
\v 13 Put in the sickle,
...
\q for their wickedness is enormous."

This:
\c 2
...
\v 19 Yahweh answered his people,
...
\v 25 "I will restore to you the years of crops that the swarming locust has eaten
...
\c 3
...
\v 8 I will sell your sons and your daughters,
...
\q For Yahweh has spoken."
...
\v 9 Proclaim this among the nations,
\q "Prepare yourselves for war,
...
\v 10 Beat your plowshares into swords
...
\q 'I am strong.'
...
\v 11 "Hurry and come,                _(I'm assuming the quotes mark the beginning of a new paragraph)_
\q all you nearby nations,
\q gather yourselves together there."
\q Yahweh, bring down your mighty warriors.
...
\v 12 "Let the nations wake themselves up
...
\v 13 Put in the sickle,
...
\q for their wickedness is enormous."

**Comment by TomWarren** [comment]
I removed the open quote at  2:19.

Left the opening quote at beginning of 2:25

open through end of chapt.

Close the quote at the end of 3:8 (we use the convention of including 
"for Yahweh has spoken" as part of the quote.)

Open quote at beginning of 3:9

Change double to single quotations marks at end of 3:10 'I am strong.'

No quote at 3:11 (part of the extended quote).

End of 3:13 the quote is closed.

3:17 Yahweh speaks, so open double quotes

3:21 quote extended to include the phrase "for Yahweh lives in Zion." 
(following out convention).

Seems right to me.

Check it and see if you can live with it.

Tom

**Comment by hmw3** [comment]
Looks like I was overly concise again.

The opening quote in 2:19 belongs there. It's the beginning of Joel's quotation of Yahweh's words. My ellipsis was simply to say that nothing would change.

The opening quote at 2:25 is legit only if there is a paragraph break at the end of 2:24. I don't see one in the USFM file. In fact, I'm not sure how "paragraphs" in poetry (i.e., stanzas) would be divided in USFM, but that's not my problem -- I just hope _someone_ knows how it's done. So either there should be a stanza/paragraph break between 2:24 and 2:25 or the open quote needs to be deleted.

Your interpretation is that "Yahweh, bring down your mighty warriors" is part of what Joel is telling his addressee to proclaim among the nations. Correct? I would end the quote before it and start a new one after it, but the decision is yours.

Other than those things, looks good.

**Comment by TomWarren** [comment]
Added paragraph marker at the end of 2:24
Kept quotation at 2:25.
Set off the prophet cry to Yahweh with single quotes, and paragraph. It stands off by itself now.

Thanks

Tom

**Comment by hmw3** [comment]
That's fine.

There needs to be an opening double quote before

Look, I will send you grain, new wine, and oil. 

in 2:19.

**Comment by hmw3** [comment]
That's fine.

There needs to be an opening double quote before

Look, I will send you grain, new wine, and oil. 

in 2:19.

**Comment by TomWarren** [comment]
The ULB of JOL 2:19 now reads:
\v 19 Yahweh answered his people,
\q "Look, I will send you grain, new wine, and oil.
\q You will be satisfied with them,
\q and I will no longer make you a disgrace among the nations.
