### ISSUE TITLE
NUM 2:13 & 16 tR

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#726]
There is a change in how the 'numbering' is written. From 'The number in xxx is ###.' to 'Those numbered in xxx is ###.'
I think that the singular/plural verb tense should be changed.

\v 13 **Those numbered in his division is** 59,300.

\s5
\v 14 The tribe of Gad is next. The leader of the people of God is Eliasaph son of Deuel.
\v 15 **The number in his division is** 45,650.

\s5
\v 16 All **those numbered in the camp of Reuben, according to their divisions, is** 151,450.

**Comment by TomWarren** [comment]
The ULB of NUM 2:13 now reads:
\v 13 The number in his division is 59,300.
Vs 16 is different in the HEB and is a summary statement
The ULB of NUM 2:16 now reads:
\v 16 The number of all the men assigned to the camp of Reuben, according to their divisions, is 151,450. They will set out second.

I think that fixes the issue. 

Thanks, 

Tom
