### ISSUE TITLE
Num 9:11 & 12 tR

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#727]
What is the 'IT'? Passover? Or lamb? 

\v11 They must keep the Passover in the second month on the fourteenth day at evening. They must **eat it** with bread without yeast and with bitter herbs.
\v 12 They must not **leave it** until the morning, or break any of **its bones**. They must follow all the regulations for the Passover.

The ULB has the information about the lamb expressed explicitly. Perhaps the Hebrew was implicit here?

**Comment by TomWarren** [comment]
The ULB of NUM 9:11-12 has been edited to read:
\v 11 In the second month on the fourteenth day at evening, they will eat the Passover meal. They must eat the Passover lamb with bread that is made without yeast and with bitter herbs.
\v 12 They must not leave any of it until the morning, or break any of its bones. They must follow all the regulations for the Passover.

Thanks, 

Tom
