### ISSUE TITLE
MAT 12:1 grainfields or grain fields

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#73]
Mat 12:1 Grainfields is written as one word.
Mark 2:23 Grain fields is written as two words.
Luke 6:1 Grain fields is written as two words.
NIV has it as one word. The spell checker on this corrects it to two words.

**Comment by TomWarren** [comment]
Oddly, grainfield(s) is the correct spelling. 
I have changed the two "grain fields" to "grainfield.

**Comment by TomWarren** [comment]
Dear Susan,

The correct spelling (oddly) appears to be "grainfields" not "grain field."

I have corrected the two "grain fields" to "grainfields".

Thanks,

Tom

**Comment by SusanQuigley** [comment]
Thank you, Tom.

On May 31, 2016, at 2:07 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


Oddly, grainfield(s) is the correct spelling.
I have changed the two "grain fields" to "grainfield.
