### ISSUE TITLE
Jer 6:26  two funerals?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#732]
ULB: Daughter of my people, fasten on sackcloth and roll about in the dust of _**a funeral for an only child**_.
**_Perform a bitter funeral for yourself_**, for the destroyer will come suddenly upon us.

UDB: So I, Jeremiah, say say to you, "My dear people, put on rough clothes and sit in ashes to show that you are sorry for your sins.
**_Mourn and cry very much, as a woman would cry if her only son had died_**.
For your enemies are very near,
and they are going to destroy everything. **_Prepare for your own funerals_**."

In the ULB and UDB there appear to be two commands to mourn. In the UDB there are clearly two reasons for mourning. The first is to show sorrow for sins, and the second is preparing for their own funerals.  I wonder if both the ULB and UDB could be shortened. 

ULB Suggestion:
Daughter of my people, fasten on sackcloth and roll about in the dust of a funeral for an only child.
**_Mourn bitterly,_** for the destroyer will come suddenly upon us.

UDB Suggestion:
So I, Jeremiah, say say to you, "My dear people, put on rough clothes and sit in ashes to show **_your grief._**
Mourn and cry very much, as a woman would cry if her only son had died.
For your enemies are very near, and they are going to destroy everything.

**Comment by TomWarren** [comment]
The ULB of JER 6:26 was edited and now reads:
\v 26 Daughter of my people, put on sackcloth and roll in ashes; 
\q mourn with painful sobs as for an only son, 
\q for the destroyer will suddenly come upon us.

"roll in ashes" follows the HEB text, and a note may be added.

The UDB of JER 6:26 was edited and now reads:
\v 26 So I, Jeremiah, say to you, 
\q "My dear people, put on rough clothes and sit in ashes 
\q to show how much you are grieving.
\q1 Mourn loudly and cry very much,
\q2 as a mother would cry when her only son has died.
\q1 For your enemies are very near,
\q2 and they are going to destroy everything."

"as a mother" the text implies the mother

Thanks, hope that helps.

Tom
