### ISSUE TITLE
NUM 14:37-38

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#736]
There is a question on where **_This made all the community complain against Moses._** comes from. It is not seen in some English versions and does not seem to be in the Hebrew (interlinear).

\v 36-37 So the men whom Moses had sent to look at the land all died by the plague before Yahweh. These were the men who had returned and brought a bad report about the land. **_This made all the community complain against Moses._**
\v 38 Of those men who had gone to look at the land, only Joshua son of Nun and Caleb son of Jephunneh remained alive.

**Comment by TomWarren** [comment]
This was very much like the UDB, and therefore it was simplified here.
The ULB of NUM 14:37-38 was edited and now reads:
\v 36 The men Moses sent to spy out the land, when they returned, they made the entire community grumble against Moses by spreading a bad report about the land—
\v 37 the men who had brought out a bad report about the land—died of a plague before Yahweh.
\v 38 Of those men who had gone to spy out the land, only Joshua son of Nun and Caleb son of Jephunneh remained alive.

Thanks, 

Tom
