### ISSUE TITLE
LEV 21:20 tR

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#737]
shouldn't this verse ---
\v 20 a man who **_has hump_** in his back or is abnormally thin or short, or a man with a defect in his eyes, or with a disease, sore, scabs, or whose testicles have been crushed.

have the letter/word 'a' before hump?
\v 20 a man who **_has a hump_** in his back or is abnormally thin or short, or a man with a defect in his eyes, or with a disease, sore, scabs, or whose testicles have been crushed.

**Comment by TomWarren** [comment]
Yes, the ULB for LEV 21:20 now reads:

\v 20 a man who **has a hump** in his back or is abnormally thin or short, or a man with a defect in his eyes, or with a disease, sore, scabs, or whose testicles have been crushed.

Thanks,

Tom
