### ISSUE TITLE
Luk 11:2 - addition of "Jesus"

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#74]
Somehow in the past, we added "Jesus" (not in GK) into the opening of this verse in the ULB instead of into the UDB. Seems like these should be reversed.

**Comment by TomWarren** [comment]
Larry, 
Don't see what you are referring to in Lk 2:2 (ULB), checked the UDB and didn't find it. Reference?

**Comment by lrsallee** [comment]
Tom, sorry about that. The "1" got dropped.

12:2

**Comment by TomWarren** [comment]
Luke 11:1 ULB 
\v 1 It happened when Jesus was praying in a certain place, one of his disciples said to him, "Lord, teach us to pray just as John taught his disciples." 

It should be supplied for clarity, with the new chapter, the "he" is slightly obviated, so it is helpful to keep the reader on firm ground, and supply name of the one praying, "Jesus."
"Jesus" is supplied in both the ULB and the UDB for clarity.
Thanks.

**Comment by lrsallee** [comment]
That works. Thanks.
