### ISSUE TITLE
ECC 8:12 typo

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#740]
Even if a sinner does evil a hundred times and still lives for a long time, yet I know that it will be well with those who respect God, who honor his presence with them. 

Do the first two clause beginning with "even" and "yet" flow together. Perhaps only maintain "even" or "yet" to show the contrast.

**Comment by kim-putter** [comment]
Also the phrase "who honor his presence with them" is confusing.  This phrase should be parallel with "those who respect God."

**Comment by TomWarren** [comment]
With some revision, the ULB of ECC 8:12 now reads:
\v 12 Even though a sinner does evil a hundred times and still lives a long time, yet I know that it will be better for those who respect God, for those who stand before him and show him respect.

Hope that clears up a few matters, 
Thanks Kim,

Tom
