### ISSUE TITLE
Amo 4:14 ULB Earth

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#745]
ULB: and treads on the high places of the Earth.

The word "Earth" is capitalized. Is that intentional?

**Comment by TomWarren** [comment]
Yep. The ULB of AMO 4:14 now reads:
\v 13 For, look, he who forms the mountains
\q also creates the wind,
\q reveals his thoughts to mankind,
\q makes the morning darkness,
\q and treads on the high places of **the earth.**
\q Yahweh, God of hosts, is his name."

Thanks,

Tom
