### ISSUE TITLE
Mic 4:6, 5:9

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#746]
Please conform these occurrences of נְאֻם־יְהוָ֗ה to the form in Jeremiah, "this is Yahweh's declaration."

I think it would be a worthwhile project to conform all 267 occurrences of the phrase in the OT, but you may have better things to do with your time. Maybe it should be a maintenance mode thing for after the May 31 deadline.

**Comment by hmw3** [comment]
ACtually, there are 218 occurrences already of "this is Yahweh's declaration," so getting to the others isn't a mammoth task.

**Comment by TomWarren** [comment]
The ULB of MIC 4:6 now reads: 
\v 6 "On that day"—this is Yahweh's declaration—
\q "I will assemble the lame
\q and gather the outcast,
\q those whom I have afflicted.

The ULB of MIC 5:10 (HEB 9) now reads: 
\v 10 "It will happen in that day"—this is Yahweh's declaration—
\q "that I will destroy your horses from among you
\q and will demolish your chariots.

Tom
