### ISSUE TITLE
Amo 8:3 incomplete sentence (needed)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#747]
ULB 3
In that day—this is the declaration of the Lord Yahweh.
The corpses will be many, 

This is not a complete sentence. Probably should be dashes after "Lord Yahweh" and have lower case "the" in "The corpses."

I will wait to write the note until after you have had a chance to look at this.

**Comment by TomWarren** [comment]
The ULB of AMO 8:3, with some editing,  now reads:
\v 3 The songs of the temple will become wailings in that day
\q —this is the declaration of the Lord Yahweh—
\q many, many dead bodies are thrown everywhere!
\q Silence!"
Thanks John,

Tom
