### ISSUE TITLE
1Co 8:6 ULB "him" to "whom"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#749]
Yet for us, there is only one God the Father, from **him** are all things, and for whom we live, and one Lord Jesus Christ, through whom all things exist, and through whom we exist.

Should the phrase  "from **him** are all things" be " from **whom** are all things"?

**Comment by TomWarren** [comment]
The ULB of 1CO 8:6 now reads:
\v 6 Yet for us there is only one God the Father, **from whom are all things** and for whom we live; and one Lord Jesus Christ, through whom all things exist, and through whom we exist.

Thanks Susan, 

Tom
