### ISSUE TITLE
Luk 11:2 ULB - Passive "sanctify"

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#75]
The current rendering of "sanctify" in the ULB is active. This does not reflect the passive imperative of the original, so I am having a hard time writing a note to explain it. Can we render it active in the ULB, and retain the current active rendering in the UDB?

**Comment by TomWarren** [comment]
Again, not Luke 2:2 .... sorry.

**Comment by lrsallee** [comment]
11:2. Sorry about that.

**Comment by lrsallee** [comment]
11:2

**Comment by TomWarren** [comment]
Yes, the Greek has, "your name be sanctified." 
Luke 11:2-4 ULB
\v 2  Jesus said to them, "When you pray say, 
\q 'Father, holy be your name.  
\q2 Your kingdom come. 

\s5
\q
\v 3 Give us our daily bread each day.
\q 
\v 4  Forgive us our sins, 
\q2 as we forgive everyone 
\q2 who is in debt to us.
\q Do not lead us into temptation.'"

\v 2  Jesus said to them, "When you pray say, 
\q 'Father, holy be your name. 
\q2 Let your kingdom come.
