### ISSUE TITLE
Jer 19:3 remove "and" (Maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#750]
ULB See, and I am about to bring disaster 

Do not need the "and" after "See."

**Comment by TomWarren** [comment]
Yes, 
The ULB of JER 19:3 now reads:
\v 3 Say, 'Hear the word of Yahweh, kings of Judah and inhabitants of Jerusalem! Yahweh of hosts, God of Israel, says this, **"See, I am about to bring disaster** on this place, and the ears of everyone who hears of it will tingle.

Thanks John,

Tom
