### ISSUE TITLE
Jer 20:12 incomplete sentence (Maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#751]
ULB 12 But you, Yahweh of hosts, you who examine the righteous and who see the mind and the heart.
Let me see your vengeance

The first part is not a complete sentence. Could change period after "heart" to comma and make "Let" lowercase.

**Comment by TomWarren** [comment]
Yes, the ULB of JER 20:12, with some editing, now reads:
\v 12 But Yahweh of hosts, you examine the righteous and see the mind and the heart,
\q let me see your vengeance on them for I have committed my cause to you.
\q

Thanks John,

Tom

**Comment by pjoakes** [comment]
It looks like the comma after “heart” should be a period or semicolon.

Thanks,

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>





On Apr 4, 2017, at 8:53 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, the ULB of JER 20:12, with some editing, now reads:
\v 12 But Yahweh of hosts, you examine the righteous and see the mind and the heart,
\q let me see your vengeance on them for I have committed my cause to you.
\q

Thanks John,

Tom

**Comment by TomWarren** [comment]
A semicolon is better. 
The ULB of JER 20:12 now reads:
\v 12 But Yahweh of hosts, you examine the righteous and see the mind **and the heart;**
\q let me see your vengeance on them for I have committed my cause to you.

Thanks Perry, 

Tom
