### ISSUE TITLE
John 6:40

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#753]
Is the closing quote missing?

\s5
\v 35 Jesus said to **_them, "I am_** the bread of life; he who comes to me will not be hungry, and he who believes in me will never be thirsty.
\v 36 But I told you that indeed you have seen me, and you do not believe.
\v 37 Everyone whom the Father gives me will come to me, and he who comes to me I will certainly not throw out.

\s5
\v 38 For I have come down from heaven, not to do my own will, but the will of him who sent me.
\v 39 This is the will of him who sent me, that I would lose not one of all those whom he has given me, but will raise them up on the last day.
\v 40 For this is the will of my Father, that everyone who sees the Son and believes in him would have eternal life and I will raise him up on the **_last day._**

\s5
\p
\v 41 Then  the Jews grumbled about him because he had said, "I am the bread that has come down from heaven."

**Comment by TomWarren** [comment]
The ULB of JHN 6:40 now reads;
\v 40 For this is the will of my Father, that everyone who sees the Son and believes in him would have eternal life and I will raise him up **on the last day."**

Thanks,

Tom
