### ISSUE TITLE
Amo 5:26-27  Relationship of 27 to 26

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#755]
**ULB**:  
26 You will lift up Sikkuth as your king,
and Kaiwan, your star god
—idols that you have made for yourselves.
27 **Therefore** I will exile you beyond Damascus,"
says Yahweh,
whose name is the God of hosts.

**UDB**: 
26 **But now** you will carry the two idols that you have made—
Sikkuth, the god whom you call 'king,'
and Kaiwan, the image of the star that you worship. **You will carry them with you into exile.**
27 **For** I will now force you to go to a country that is far beyond Damascus!
That will surely happen because I, Yahweh, commander of the angel armies, have said it!"

In the ULB it sounds like going into exile is punishment for lifting up Sikkuth and Kaiwan. 
In the UDB it sounds like carrying their idols and going into exile is punishment for making their idols.
Could the ULB be more like the UDB?

26 You will lift up Sikkuth * your king,
and Kaiwan, your star god
—idols that you have made for yourselves.
27 **And** I will exile you beyond Damascus,"
says Yahweh,
whose name is the God of hosts.

**Comment by TomWarren** [comment]
The UDB was not touched. 
The ULB of AMO 5:26 now reads:
\v 26 You have lifted up the images of Sikkuth, your king,
\q and Kaiwan, your star god—
\q which you made for yourselves. 

Thanks Susan, 

Tom
