### ISSUE TITLE
Amo 3:1 ULB Punctuation - Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#756]
1Hear this word that Yahweh has spoken against you, people of Israel, against the whole family that I brought up out of **the land of Egypt,**
2"I have chosen only you
from all the families of the earth.
Therefore I will punish you
for all your sins."

It looks like the comma after "the land of Egypt" should be either a colon or period.

**Comment by TomWarren** [comment]
The colon would be best:
The ULB of AMO 3:1 now reads:
\v 1 Hear this word that Yahweh has spoken against you, people of Israel, against the whole family that I brought up out of the land of Egypt:
\q
\v 2 "I have chosen only you
\q from all the families of the earth.
\q Therefore I will punish you
\q for all your sins."
