### ISSUE TITLE
Amo 3:6b ULB  odd "and"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#757]
Will disaster come on a city
**and** Yahweh has not sent it?

The "and" sounds odd in English. Could it be changed to "if" or "when"?

Will disaster come on a city
**if** Yahweh has not sent it?
or 
Will disaster come on a city
**when** Yahweh has not sent it?

**Comment by TomWarren** [comment]
The ULB of AMO 3:6 was edited and now reads:

\v 6 If a trumpet sounds in a city,
\q will the people not tremble?
\q If disaster overtakes a city,
\q has Yahweh not sent it?

Thanks,

Tom
