### ISSUE TITLE
TIT 2:11

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#759]
The ULB has:
\v 11 For the grace of God has appeared to all people.

The MAST team leader asks:

Greek: has appeared indeed the grace of God, bringing salvation to all men;

Is this a case of the additional text in the Greek not being in the best manuscripts?

**Comment by TomWarren** [comment]
The ULB was missing the supplied connective "for the" 
The GRK text is: 11
    Ἐπεφάνη   γὰρ  ἡ  χάρις  τοῦ θεοῦ σωτήριος πᾶσιν ἀνθρώποις
as appeared  for  the grace   of  God     salvation to all   men (people) 

The ULB of TIT 2:11 now reads:
\v 11 For the grace of God has appeared for the salvation of all people.

An AT: For the grace of God that brings salvation has appeared to all people.

From the UBS Handbook:
There are two grammatically possible constructions: (1)_They go with the word translated salvation. This is the view of most English versions and commentators. So the meaning is: “God has revealed his kindness by providing a way to save all people.” (2)_They belong with the verb translated appeared. This is how the NIV and KJV understand this phrase, that is: God’s grace has appeared to all men. So the meaning is: “God has revealed to all people his kindness which gives them a way to be saved.” It is recommended that you follow the first interpretation. 

Further note:
The phrase "to all men" is not an inclusive "all" here is a "selective" all, meaning that "all men" is all sorts of men, all kinds of men, not every single man (or woman) who ever lived. The GRK text does not support the "universal" or "inclusive" all, or the suggestion that all people are saved, but that all kinds of people are saved.  The translator should check that the meaning of "all" in their translation means "all kinds" "every level of person" "all who believe."
