### ISSUE TITLE
Amo 3:11, 12 ULB  Replace commas with colon? Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#760]
11 Therefore, this is what the Lord Yahweh **says,**
"An enemy will surround the land.

12 This is that Yahweh **says,**
"As the shepherd rescues out of the mouth of the lion

I think the comma after "says" should be a colon.

**Comment by TomWarren** [comment]
With some editing, the ULB of AMO 3:11-12 now reads:
\v 11 Therefore, this is what the Lord Yahweh says,
\q "An enemy will surround the land,
\q and pull down your strongholds
\q and plunder your fortresses."
\q
\v 12 This is what Yahweh says,
\q "As the shepherd rescues out of the mouth of the lion
\q two legs only, or a piece of an ear, 
\q so will the people of Israel who live in Samaria be rescued;
\q they will be left with only the corner of a couch
\q or the corner of a bed."

Look this over, it appears to ok. 

Thanks,

Tom

**Comment by SusanQuigley** [comment]
The reason I asked for colons to replace the commas is because **Therefore, this is what the Lord Yahweh says** and **This is what Yahweh says** are complete independent clauses, so they would be followed by a colon.
If the quote margins simply said "Therefore the Lord Yahweh says" and "Yahweh says" then the word "says" would be followed by a comma.

**Comment by TomWarren** [comment]
I caught that, too. I think it is as you want.

**Comment by SusanQuigley** [comment]
Thanks. And I like the changes you made inside the quotes.
