### ISSUE TITLE
Jer 22:18 delete "with" (Maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#761]
ULB They will not lament for him **with**, saying

Do not need "with"

**Comment by TomWarren** [comment]
The ULB of JER 22:18 was edited (first line) and corrected (removed "with") and it now reads:

\v 18 Therefore this is what Yahweh says about Jehoiakim son of Josiah, king of Judah: 
\q They will not lament for him, saying, 
\q 'Woe, my brother!' or 'Woe, my sister!' 
\q They will not lament for him, saying,
\q 'Woe, master!' or 'Woe, majesty!'

Thanks John, 

Tom
