### ISSUE TITLE
Amo 3:13 ULB Change comma to colon - Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#762]
Hear and testify
against the house of Jacob
—this is the declaration of the Lord Yahweh, **the God of hosts,**
14"For in the day that I punish the sins of Israel,
I will also punish the altars of Bethel.

I think "the God of hosts" should be followed by a colon rather than a comma.

**Comment by TomWarren** [comment]
The ULB of AMO 3:13 now reads:
\v 13 Hear and testify
\q against the house of Jacob
\q —this is the declaration of the Lord Yahweh, the God of hosts:

Thanks Susan,

Tom
