### ISSUE TITLE
Jer 27:1 ULB/UDB disagreement (Needed)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#763]
ULB  "Make fetters and a yoke for yourself. Place them on your neck. 3**Then send them** out to the king of Edom

UDB Make a yoke and bonds, then fasten them around your own neck. 3**Then send messages** to the kings of Edom

The ULB (and the Hebrew) seem to suggest that Jeremiah is supposed to send the yoke and bonds. UDB and most English versions say he Jeremiah is supposed to send a message.

Do you want to change one or the other, or should I explain it in the notes?

**Comment by TomWarren** [comment]
The UDB and the ULB are now saying the same thing.
The UDB of JER 27:1 now reads:

\v 3 Then send them to the kings of Edom, Moab, Ammon, Tyre, and Sidon, by telling those messages to the ambassadors from those countries who have come to Jerusalem to talk to King Zedekiah.


Thanks John,

Tom

**Comment by jhutchins25** [comment]
UDB Make a yoke and bonds, then fasten them around your own neck. 3Then send them to the kings of Edom, Moab, Ammon, Tyre, and Sidon, **by telling those messages** to the ambassadors from those countries who have come to Jerusalem to talk to King Zedekiah

I think if you change the first part of the sentence from "Then send messages" to "Then send them" referring to the yoke and bonds, then you will need to change the next part of the sentence as well.

**Comment by TomWarren** [comment]
Sorry, so much going on. Need freeze program!

The UDB of JER 27:3 now reads:

\v 3 Then send them to the kings of Edom, Moab, Ammon, Tyre, and Sidon, and give them to the ambassadors from those countries who have come to Jerusalem to talk to King Zedekiah.

Thanks, 

Tom
