### ISSUE TITLE
Jer 27:7 change plural to singular (Maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#764]
ULB For all the nations will serve him, his **sons**, and his **grandsons**

Sons and grandsons should be singular.

**Comment by TomWarren** [comment]
The ULB of JER 27:7 now reads:
\v 7 For all the nations will serve him, his **son**, and his **grandson** until the time for his land comes. Then many nations and great kings will subdue him.

Thanks John,

Tom
