### ISSUE TITLE
Jer 30:2 Redundant phrase (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#765]
ULB Write for yourself **in a scroll** all the words that I have declared to you **in a scroll**

Please remove second "in a scroll"

**Comment by TomWarren** [comment]
THe ULB of JER 30:2 now reads, with some editing:

\v 2 "This is what Yahweh, God of Israel, says, 'Write in a scroll all the words that I have spoken to you.

I simplified the text a bit. 

Thanks John,

Tom
