### ISSUE TITLE
Jer 14:9 awkward phrase (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#767]
ULB Why will be you like a confused man

Should be "Why will you be"

**Comment by TomWarren** [comment]
The ULB of JER 14:9 was edited and it now reads:

\v 9 Why are you like someone who is astounded, or like a warrior who has no power to rescue?
\q2 You are in our midst, Yahweh, and your name is called over us. Do not leave us!

Thanks John, 

Tom

**Comment by TomWarren** [comment]
A note about "your name is called over us" follows the HEB, but may need a bit of explanation.
