### ISSUE TITLE
Lam 3:42, 47 ULB  Missing close quotation mark?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#770]
ULB:  41 Let us lift up our hearts and our hands to God in the **heavens:**
42 **"We** have transgressed and rebelled,

The ULB has a double quotation mark at the beginning of 42 after the colon in 41, and no close quotation mark.  I'm not sure if the mark should be deleted in 42, or if a close quotation mark is needed later.

The UDB has double quotation marks at the beginning of 42 and the end of 47.

**Comment by TomWarren** [comment]
I worked through the quotation marks in the UDB and ULB and they are they same in this chapter. 
There is a long quote from LAM 3:42-66  (which seems to be a prayer) with the quote closing at the end of the chapt. 

Thanks,

Tom 

Thanks, 

Tom
