### ISSUE TITLE
Lam 3:50 ULB  Awkward wording

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#772]
ULB:  until he will look down and Yahweh will see from heaven.

Could this be changed to something like one of these?
until Yahweh looks down and sees from heaven.
until Yahweh looks down from heaven and sees.

**Comment by TomWarren** [comment]
The ULB of LAM 3:49-50 now read:
\v 49 My eyes will shed tears without ceasing, without relief,
\q
\v 50 until Yahweh from heaven looks down and sees. 


Thanks Susan, 

Tom
