### ISSUE TITLE
Lam 3:52 ULB  Missing word

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#773]
Lam 3:52 ULB  I have been hunted like a bird * those who were my enemies;

The word "by" is missing before "those"

**Comment by TomWarren** [comment]
Yep. 
The missing word was replaced, the ULB of LAM 3:52 now reads:
\v 52 I have been hunted like a **bird by those** who were my enemies; they hunted me without a reason.

Thanks Susan, 

Tom
