### ISSUE TITLE
Jer 29:21 change "say" to "says" (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#774]
ULB Yahweh of hosts, God of Israel, **say** this about Ahab

"say" should be "says."

Also just noticed extra comma in UDB verse 21

the God whom Israel **worships,, says**

**Comment by TomWarren** [comment]
YEP,
The ULB of JER 29:21 now reads:
\v 21 'Yahweh of hosts, **God of Israel, says** this about Ahab son of Kolaiah and Zedekiah son of Maaseiah, who prophesy falsely to you in my name: See, I am about to put them into the hand of Nebuchadnezzar king of Babylon. He will kill them before your eyes.

Thanks,

Tom
