### ISSUE TITLE
Lam 3:54 ULB Direction of the water

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#775]
53 They cast me into a pit and they threw a stone on me,
54 and **waters poured over my head**. I said, 'I have been cut off!'

The ULB gives the impression that water came down from above.
UDB and UBS-TH indicate that the water inside the pit rose up over his head.
Could the ULB be changed?

**Comment by TomWarren** [comment]
The ULB of LAM 3:54 has been edited to read:
\v 53 They cast me into a pit and they threw a stone on me,
\q
\v 54 and they caused waters to overflow, covering my head. I said, 'I have been cut off!'

Thanks Susan,

Tom
