### ISSUE TITLE
Jer 44:1 Patros (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#778]
ULB **in the land of Patros**

Should this be Pathros like in 44:15?

**Comment by TomWarren** [comment]
We are aligning the spelling of proper names with those spellings in the NIV. 
The term Pathros, is the region of upper Egypt, and the NIV translates it with that in mind.

The ULB of JER 44:1 now reads: 
\v 1 The word that came to Jeremiah concerning all the Judeans who lived in the land of Egypt, the ones staying in Migdol, Tahpanhes, Memphis, and in Upper Egypt.

 Note may be needed that indicates that "upper Egypt" would be "southern Egypt".

**Comment by jhutchins25** [comment]
Do you want to change "Pathros" in ULB 44:15 to "upper Egypt" as well?

**Comment by TomWarren** [comment]
Yep, 
The ULB of JER 44:15 now reads:
\v 15 Then all the men who knew that their wives were burning incense to other gods, and all the women who were in the great assembly, and all the people who were living in Lower and Upper Egypt, answered Jeremiah.

Same note about Upper (means southern) and Lower (means northern). 
Thanks,

Tom
