### ISSUE TITLE
Jer 44:30 UDB addition (Maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#780]
UDB  And that is what happened several years later.

I'm not sure why this in the UDB. Is it supposed to be here?

**Comment by TomWarren** [comment]
That made the UDB read a bit like a Bible Story Book. 
The UDB of JER 44:30 now reads;
\v 30 I will cause Hophra, the king of Egypt, to be captured by his enemies who want to kill him, just like I caused King Zedekiah of Judah to be captured by the soldiers of King Nebuchadnezzar of Babylon.'" 

Thanks John,

Tom
