### ISSUE TITLE
LAM 1:16 a / the? (maintenance) 

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#782]
...since the comforter who should restore my life is far from me....

Should "the comforter" above be indefinite, "a comforter?"

**Comment by TomWarren** [comment]
With a bit of editing. The ULB of LAM 1:16 now reads:
\v 16 For these things I weep, my eyes overflow with tears;
\q for a comforter is far from me, one who restores my life.
\q My children are desolate because the enemy has conquered me.

Thanks Kim,

Tom
