### ISSUE TITLE
Hab 1:15-17 singular or plural pronouns (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#785]
For these verses, the Hebrew is third person singular throughout.

In the ULB verse 15 it is plural "They bring up ... they drag ... they rejoice.

In verse 16 they are singular "he offers ... his nets ... his dragnet ... his net he lives ... his food"

In verse 17 they switch back to plural "they therefore ... their fishing nets"

Do you want to make these consistent throughout the verses, either all singular or all plural?

**Comment by TomWarren** [comment]
The ULB of HAB 1:15-17 now reads:
\v 15 He brings all of them up with a fishhook; 
\q he drags men away in his fishnet;
\q he gathers them together in his dragnet;  
\q so he rejoices and he is glad. 
\q
\v 16 Therefore he sacrifices to his net 
\q and burns incense to his dragnet,
\q for by his net he lives in luxury, 
\q and his food is the richest kind.
\q
\v 17 Will he therefore keep emptying his net, 
\q and will he continually slaughter the nations without mercy?"

Thanks John. most versions have it as the HEB is. That is good with me. 

Tom
