### ISSUE TITLE
Jer 9:3 Add "one." (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#786]
ULB They go from wicked act to another

Need "one" between "from wicked"

**Comment by TomWarren** [comment]
The ULB of JER 9:3 is corrected to read:
\v 3 Yahweh declares, "They tread on their bows of lies with their tongues,
\q but it is not because of any faithfulness of theirs that they grow strong on the earth.
\q They go **from one wicked** act to another. They do not know me."

Thanks John,

Tom
