### ISSUE TITLE
Zec 12:3 remove extra "that" (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#787]
ULB On that day that

Remove second "that"

**Comment by TomWarren** [comment]
The ULB of ZEC 12:3 is fixed:
\v 3 **On that day,** I will make Jerusalem a heavy stone for all the peoples. Anyone trying to lift that stone will hurt himself very much, and all the nations of the earth will gather against that city.

Thanks,

Tom
