### ISSUE TITLE
Mrk 9:23 ULB - 'If you are able?' 

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#79]
This is a question about a previous statement, 'If you are able...' 

The question mark should follow the quotation mark:

'If you are able'?

**Comment by TomWarren** [comment]
The ULB now reads: 
\v 23 Jesus said to him, "'If you are able'? All things are possible for the one who believes."

The phrase "If you are able" is not a question, but Jesus questions the premise, "If you are able"?
So you are correct, the ? should be outside the quotation. 
Thanks.
