### ISSUE TITLE
LAM 2:16 verb tense

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#791]
"All your enemies open their mouths and mocked you."

Should the verb "mocked" be present tense?

**Comment by kim-putter** [comment]
Also,

"...This is the day we jave waited for! We have lived to see it!"

Change "jave" to "have." 

Jave a good time fixing it?

**Comment by TomWarren** [comment]
The ULB of LAM 2:16 now reads:
\v 16 All your enemies open their mouths against you.
\q They sneer and grind their teeth and say, "We have swallowed her up!
\q This is the day we have waited for! We have lived to see it!"

Thanks Kim. 

Tom
