### ISSUE TITLE
Lam 4:6 ULB odd  "and it"  -- Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#794]
Lam 4:6 ULB
The punishment of the daughter of my people is greater than that of Sodom,
**and it** was overthrown in a **moment**
and no one lifted a hand to help her.

If the word "it" refers to Sodom, could "and it" be changed to "which"?
Could a comma follow the word "moment"?

**Comment by TomWarren** [comment]
The ULB of LAM 4:6 was edited to read:
\v 6 The punishment of the daughter of my people is greater than that of Sodom,
\q which was overthrown in a moment and no hands were wrung for her.

Thanks Susan, 

Tom
