### ISSUE TITLE
Jer 50:43 verb tense (needed)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#795]
ULB  43The king of Babylon heard the reports about them and his hands fell limp in distress. Anguish **seizes** him like a woman giving birth.

Should read "Anguish seized him like a woman giving birth."

**Comment by TomWarren** [comment]
The ULB for JER 50:43 now  reads:
\v 43 The king of Babylon heard the reports about them and his hands fell limp in distress.
\q Anguish **seized** him like a woman giving birth.

Thanks John,

Tom
