### ISSUE TITLE
Heb 2:2 ULB  Typo  

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#796]
For if the message that was spoken through the angels is valid, and every **trespas** and disobedience receives just punishment,

"trespas" should be "trespass"

**Comment by TomWarren** [comment]
The ULB of HEB 2:2 now reads:
\v 2 For if the message that was spoken through the angels is valid, and every **trespass** and disobedience receives just punishment,

Thanks,

Tom
