### ISSUE TITLE
LAM 5:17 extra phrase

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#798]
For this our heart has become sick,
and our eyes have grown dim,
for these things our eyes grow dim

The idea of their "eyes being dim" is here twice. It should only be stated once.

**Comment by TomWarren** [comment]
The ULB of LAM 5:17 now reads:
\v 17 For this our heart has become sick,
**\q for these things our eyes grow dim
\q**
\v 18 for Mount Zion lies desolate, with jackals prowling over it.

Thanks Kim,

Tom
