### ISSUE TITLE
Nam 2:6 remove "q2" (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#799]
UDB by enemy soldiers, **q2** and her slave girls

Please take out "q2"

**Comment by TomWarren** [comment]
The UDB of NAM 2:6 added the formatting marker "\"
\v 7 The queen will have her clothes stripped off her by enemy soldiers,
\q2 and her slave girls will moan like doves
\q2 and beat their breasts to show that they are very sad.

Should be ok now.

Thanks,

Tom
