### ISSUE TITLE
2ch 15:1 Oded/Obed confusion

### ISSUE THREAD

**Issue by lrsallee** [Door43/ulb-en#8]
There are several places in 2ch where the ULB and UDB do not agree on whether the person is Oded or Obed. 

- 15:1
- 15:8
- 28:9

**Comment by pohlig** [comment]
You're right. Fixed the instances of "Obed" to "Oded" in ULB.

**Comment by TomWarren** [comment]
Added one more in 2 Ch15:8 (where UDB omitted, referring it back to vs1). The text had Oded, so I added it.
