### ISSUE TITLE
Ecc 5:10 redundant word (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#800]
ULB Anyone **one** who

Extra "one"

**Comment by TomWarren** [comment]
Yep. 
The ULB of ECC 5:10 now reads:
\v 10 **Anyone who** loves silver will not be satisfied with silver,
\q2 and anyone who loves wealth always wants more.
\q1 This, too, is vapor.

Thanks John, 

Tom
