### ISSUE TITLE
Lam 4:20 ULB Odd tense

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#801]
of whom it was said, "Under his shadow **we would live** among the nations."

Could the verb in the quote be changed to future tense?
This is a direct quote.  At the time the people were saying this, I think they would have been saying "Under his shadow we **will live** among the nations."

**Comment by TomWarren** [comment]
Yep.
The ULB of LAM 4:20 now reads:
\v 20 The breath in our nostrils—Yahweh's anointed one—he was the one who was captured in their pits;
\q of whom it was said, "Under his shadow **we will live** among the nations."

Thanks Susan, 

Tom
