### ISSUE TITLE
1CH 25:11 name mismatch 

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#802]
the fourth fell to Izri, his sons and his relatives, twelve persons in number; 

The name "Izri" is spelled Zeri" in 1 CH 25:3.

**Comment by TomWarren** [comment]
This name "Izri" in 1CH 25:11 is a variant in the MT for "Zeri" found in 1CH 25:3. A footnote in the text has been added.
 
The ULB of 1CH 25:11 was edited to add a footnote:
\v 11 the fourth fell to Izri, \f + \ft this is a variant of Zeri, found in 1CH 25:3, and refers to the same person \f* his sons and his relatives, twelve persons in number;

Another footnote was added at ULB 1CH 25:3 with the reverse information added for clarity:
The ULB of 1CH 25:3 now reads;
\v 3 From the sons of Jeduthun: Gedaliah, Zeri, \f + \ft this is a variant of Izri, found in 1CH 25:11, and refers to the same person \f* Jeshaiah, Shimei, Hashabiah, and Mattithiah, six in all, under the direction of their father Jeduthun, who played the harp for giving thanks and praising Yahweh.

Thanks Kim,

Tom
