### ISSUE TITLE
Lam 4:22 ULB Punctuation

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#803]
Daughter of Zion, your punishment will come **to an end,**
he will not extend **your exile**
But daughter of Edom, he will punish;
he will uncover your sins.

It looks like their should be a semicolon at the end of the first line
and a period at the end of the second.

**Comment by TomWarren** [comment]
Yep.
The ULB of LAM 4:22 now reads:
\v 22 Daughter of Zion, your punishment will come to an end;
\q he will not extend your exile.
\q But daughter of Edom, he will punish;
\q he will uncover your sins.

Thanks Susan, 

Tom
