### ISSUE TITLE
1CH 25:14 alt spelling

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#804]
the seventh fell to Jesharelah, his sons and his relatives, twelve persons in number;

This is an alternate for the name Asharelah in 1CH 25:2. Are we wanting to sync alternate spellings for names?

**Comment by kim-putter** [comment]
I'll list other alternates found here just in case:

25:18 Azarel is Uzziel in 25:4.

**Comment by kim-putter** [comment]
25:22 Jeremoth is Jerimoth in 25:4.

**Comment by TomWarren** [comment]
Asharelah/ Jesharelah
\v 2 From the sons of Asaph: Zaccur, Joseph, Nethaniah, and Asharelah, \f +\ft this is the same person referred to in 1CH 25:14 as Jesharelah \f* the sons of Asaph, under the direction of Asaph, who prophesied under the king's supervision.

and
\v 14 the seventh fell to Jesharelah, \f +\ft this is the same person referred to in 1CH 25:2 as Asharelah \f* his sons and his relatives, twelve persons in number;

Azarel / Uzziel 
\v 4 From the sons of Heman: Bukkiah, Mattaniah, Uzziel, \f +\ft this is the same person referred to in 1CH 25:18 as Azarel \f*  Shebuel, and Jerimoth, Hananiah, Hanani, Eliathah, Giddalti, Romamti Ezer, Joshbekashah, Mallothi, Hothir, and Mahazioth.

\v 18 the eleventh fell to Azarel, \f +\ft this is the same person referred to in 1CH 25:4 as Uzziel \f*  his sons and his relatives, twelve persons in number;

Jerimoth is the corrected name in both instances 25:4 and 25:22.
The ULB of 1CH 25:22 now reads:
\v 22 the fifteenth fell to **Jerimoth**, his sons and his relatives, twelve persons in number;


These are a wild difficulty.

Thanks,

Tom
