### ISSUE TITLE
1CH 26:1 alt spelling

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#806]
Here were the divisions of the gatekeepers: From the Korahites, Meshelemiah son of Kore, a descendant of Asaph.

This Asaph refers to Ebiasaph from 9:19.

**Comment by TomWarren** [comment]
I added two notes to the text.
The ULB of 1CH 9:19 now reads, with a footnote:
\v 19 Shallum son of Kore son of Ebiasaph \f +\ft Ebiasaph is the same person referred to as \fqa Asaph \fqa* in 1CH 26:1 \f*, who as son of Korah, and his relatives from the house of his father, the Korahites, were in charge of the work of the service, they guarded the door to the tent, as their ancestors had guarded the camp of Yahweh, and they also had guarded the entrance.

The ULB of 1CH 26:1 was edited by adding a footnote, it now reads:
\v 1 Here were the divisions of the gatekeepers: From the Korahites, Meshelemiah son of Kore, a descendant of Asaph \f +\ft Asaph is the same person referred to as \fqa Ebiasaph \fqa* in 1CH 9:19 \f*.

Thanks Kim, 

Tom
