### ISSUE TITLE
1ch 7:23-24

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#807]
I think the parenthesis should end after v. 23; the bit about Sheerah seems to go with "Zabad's son was Shuthelah" rather than with the birth of Beriah.

\s5
\p
\v 20 The descendants of Ephraim were as follows: Ephraim's son was Shuthelah. Shuthelah's son was Bered. Bered's son was Tahath. Tahath's son was Eleadah. Eleadah's son was Tahath.
\v 21 Tahath's son was Zabad. Zabad's son was Shuthelah. (Ezer and Elead were killed by men of Gath, natives in the land, when they went to steal their cattle.
\v 22 Ephraim their father mourned for them many days, and his brothers came to comfort him.

\s5
\v 23 He slept with his wife. She conceived and bore a son. Ephraim called him Beriah, because tragedy had come to his family.[[i.e., end it here]]
\v 24 His daughter was Sheerah, who built Lower and Upper Beth Horon and Uzzen Sheerah.)

**Comment by TomWarren** [comment]
The ULB of 1CH 7:23-24 now reads:
\v 23 He slept with his wife. She conceived and bore a son. Ephraim called him Beriah, because tragedy had come to his family.)
\v 24 His daughter was Sheerah, who built Lower and Upper Beth Horon and Uzzen Sheerah.

Thanks Henry, 

Tom
