### ISSUE TITLE
1CH 26:14 another alt.

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#808]
When the lot was thrown for the east gate, it fell to Shelemiah.

Shelemiah is Meshelemiah in 26:2.

**Comment by TomWarren** [comment]
The ULB of 1CH 26:2 added a footnote:
\v 2 Meshelemiah \f + \ft Meshelemiah is the same individual as \fqa Shelemiah \fqa* in 1CH 26:14 \f*  had sons: Zechariah the firstborn, Jediael the second, Zebadiah the third, Jathniel the fourth,

The ULB of 1CH 26 14 added a footnote:
\v 14 When the lot was thrown for the east gate, it fell to Shelemiah \f + \ft Shelemiah is the same individual as \fqa Meshelemiah \fqa* in 1CH 26:2 \f* . They then threw lots for Zechariah his son, a prudent advisor, and his lot came out for the north gate.

Thanks Kim, 

Tom
