### ISSUE TITLE
1CH 26:18 too many guards!

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#809]
At the court to the west there were four posted, four at the road, and two at the court. 

There are 4 extra guards here! There should be 4 guarding the road and 2 at the court.

**Comment by TomWarren** [comment]
The ULB of 1CH 26:18 now reads:
\v 18 At the court to the west there were four stationed at the road and two at the court.

A fragment was left in the text making too many guards.

Thanks Kim,

Tom
