### ISSUE TITLE
1ki 8:32 ULB  Odd "to"s  Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#811]
1ki 8:32 ULB: judge your servants, condemning the guilty and bring what he has done upon his own head, and **to** declare the righteous one to be innocent, and **to** reward him for his righteousness.

The word "to" doesn't fit in these places. Maybe it could be changed to something like this:
 judge your servants, condemning the guilty **to bring** what he has done upon his own head, and **declaring** the righteous one to be innocent, **to reward** him for his righteousness.
or 
 judge your servants. **Condemn** the guilty **to bring** what he has done upon his own head, and **declare** the righteous one to be innocent, **to reward** him for his righteousness.

**Comment by TomWarren** [comment]
The ULB of 1KI 8:31-32 was edited to read:
\v 31 If a man sins against his neighbor and is required to swear an oath, and if he comes and swears an oath before your altar in this house,
\v 32 listen from the heavens and act. Judge your servants, condemning the guilty and bringing what he has done upon his own head. Declare the innocent not guilty and give to him according to his righteousness.

See if that works. 

Thanks Susan,

Tom

**Comment by SusanQuigley** [comment]
Tom, that sounds much better. Thank you.
I wrote another maintenance issue for the parallel passage in 2Ch 6:23 concerning using parallel structures for parallel requests. If you want to apply that here, that would be great. If not, this is good.

**Comment by TomWarren** [comment]
Yep. 
I have paralleled 1KI 8:31-32 with 2CH 22-23, which now reads:
\v 22 If a man sins against his neighbor and is required to swear an oath, and if he comes and swears an oath before your altar in this house,
\v 23 listen from the heavens and act. Judge your servants, condemning the guilty and bringing what he has done upon his own head. Declare the innocent not guilty and give to him according to his righteousness.

They are now rendered in the same manner. 

Thanks Susan, 

Tom
