### ISSUE TITLE
2Ch 6:23 ULB Using parallel structures for parallel requests - Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#812]
then hear from the heavens and act and **judge** your servants, **repaying** the wicked, to bring his conduct on his own head. **Declare** the righteous innocent, to give him the reward for his righteousness.

This gives the impression that judging and repaying the guilty are one request, and then declaring the righteous innocent is another. But I think that dealing with the guilty and dealing with the righteous both explain what he means my "judge your servants". Maybe it could be changed to something like this.

then hear from the heavens and act and judge your servants. **Repay** the wicked, to bring his conduct on his own head, **and declare** the righteous innocent, to give him the reward for his righteousness.

**Comment by TomWarren** [comment]
The ULB of 2CH 6:23-23 now reads:
\v 22 If a man sins against his neighbor and is required to swear an oath, and if he comes and swears an oath before your altar in this house,
\v 23 listen from the heavens and act. Judge your servants, condemning the guilty and bringing what he has done upon his own head. Declare the innocent not guilty and give to him according to his righteousness.
