### ISSUE TITLE
2Ch 1:2 "of thousands and of hundred" (Maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#813]
ULB to the commanders of **thousands** and of **hundreds**

UDB the army commanders of **one thousand** soldiers and the commanders of **one hundred** soldiers

These give different amounts of soldiers that they were in charge of.

The same phrase is in Num 31:14. There the UDB says "those men who were commanders over thousands of men and those who were commanders over hundreds of men"

**Comment by TomWarren** [comment]
The UDB of 2CH 1:2 (in part) now reads:
\p Solomon called together the army commanders who directed thousands of soldiers, and the commanders who directed hundreds of soldiers, with the judges and all the other leaders in Israel. He told them to go with him to Gibeon. So they all went to the place on the hill where idols were worshiped at Gibeon. That was the same place where God had met with his people in the tent which Moses had made. There Solomon and all the others with him prayed to Yahweh.

Thanks John, 

Tom
