### ISSUE TITLE
1ch 1:51, 54

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#814]
The word translated "head" in these verses, _'ellup_, is better translated "chief." Chiefs are often "heads" (_ro'šim_) but present rendering necessitates a note explaining a metaphor that does not exist in the Hebrew.

**Comment by TomWarren** [comment]
Chief seems to be the choice for most versions.  Leaders of clans; heads of the families groups; 
The ULB of 1CH 1:51-54 now reads:
\s5
\v 51 Hadad died.
\p The **chiefs** of Edom were Timna, Alvah, Jetheth,
\v 52 Oholibamah, Elah, Pinon,
\v 53 Kenaz, Teman, Mibzar,
\v 54 Magdiel, and Iram. These were the **chiefs** of Edom.

That just walks the road that the HEB text has. Hope that gives you something to work with. 

Thanks Henry, 

Tom
