### ISSUE TITLE
Zec 8:19-23 quotation marks (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#815]
ULB 8:19 a double quotation opens. To me it looks like it closes at the end of verse 23. If so, the quotation in verse 21 should be a single quotation, and I think it should close at the end of 21.

**Comment by TomWarren** [comment]
The quotation marks for ULB ZEC 9:29-34 have been adjusted to read:
\v 19 "Yahweh of hosts says this: The fasts of the fourth month, 
\q the fifth month, the seventh month, and the tenth month 
\q will become times of joy, gladness, and happy festivals for the house of Judah! 
\q Therefore love truth and peace!

\s5
\q 
\v 20 Yahweh of hosts says this: People will come again, 
\q even those who are living in many different cities.
\q
\v 21 The inhabitants of one city will go to another city and say, 
\q 'Let us quickly go to beg before the face of Yahweh 
\q and to seek Yahweh of hosts! We ourselves are also going.'
\q 
\v 22 Many people and mighty nations will come to seek Yahweh of hosts in Jerusalem 
\q and beg for the favor of Yahweh!

\s5
\p 
\q
\v 23 Yahweh of hosts says this: In those days 
\q ten men from every language and nation 
\q will grasp the hem of your robe and say, 
\q 'Let us go with you, for we have heard that God is with you!"

Thanks John, they are mind-numbing, 

Tom

**Comment by jhutchins25** [comment]
I know it is mind-numbing. One more thing though, there needs to be a single quotation mark and a double quotation at the end of 23.

Thanks.

**Comment by TomWarren** [comment]
Ah. Just ran past it. 
Thanks. 
\v 19 "Yahweh of hosts says this: The fasts of the fourth month, 
\q the fifth month, the seventh month, and the tenth month 
\q will become times of joy, gladness, and happy festivals for the house of Judah! 
\q Therefore love truth and peace!

\s5
\q 
\v 20 Yahweh of hosts says this: People will come again, 
\q even those who are living in many different cities.
\q
\v 21 The inhabitants of one city will go to another city and say, 
\q 'Let us quickly go to beg before the face of Yahweh 
\q and to seek Yahweh of hosts! We ourselves are also going.'
\q 
\v 22 Many people and mighty nations will come to seek Yahweh of hosts in Jerusalem 
\q and beg for the favor of Yahweh!

\s5
\p 
\q
\v 23 Yahweh of hosts says this: In those days 
\q ten men from every language and nation 
\q will grasp the hem of your robe and say, 
\q 'Let us go with you, for we have heard that God is with you!'"

You are going to be the wisest man in Christendom. 

Thanks,

Tom
