### ISSUE TITLE
2 Ch 1:16 Turkey (Maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#816]
UDB from the region of Kue in Turkey

I can't remember seeing a reference to a modern country in the UDB. Do you want this here?

Also, here the ULB/UDB say "Kue." In 1 Kings 10:28 it says "Cilicia." Both are the same Hebrew word. Do you want them to be the same in both books?

**Comment by TomWarren** [comment]
2CH 1:16 appears to be correct, "Kue." 
The UDB of 2CH 1:16 now reads:
\v 16 Solomon's horses were imported from Egypt and from the region of Kue.

The proper names should be the same in the ULB and UDB, for consistency for the MTTs. 

The ULB of 1KI 10:28 was edited and now reads:
\v 28 Solomon owned horses that had been bought from Egypt and Kue. The king's merchants purchased them in herds, each herd at a price.

The UDB of 1KI 10:28 was edited and now reads:
\v 28 Solomon's agents bought horses and supervised the bringing of them into Israel from the areas of Egypt and Kue that were famous for breeding horses.


Thanks,

Tom
