### ISSUE TITLE
2ch 7:3a ULB "looked on" Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#817]
2ch 7:3a ULB  All the people of Israel **looked on** when the fire came down and the glory of Yahweh was on the house.

MTTs might look for an object to the preposition "on."
Could "looked on" be changed to "saw"? (I was going to say "watched" but they didn't stand there watching. They bowed down with their faces to the ground.)

**Comment by TomWarren** [comment]
With some editing, the ULB of 2CH 7:3 now reads:
\v 3 When all the people of Israel saw the fire come down and the glory of Yahweh over the house, they bowed down with their faces to the ground on the stone pavement and worshiped and gave thanks to Yahweh. They said, "For he is good, for his covenant loyalty endures forever."

Thanks Susan, 

Tom
