### ISSUE TITLE
1CH 28:14 phrasing

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#819]
"He gave him the weight of all the gold vessels for every kind of service and of all the silver vessels, for all the objects for every kind of service."

It seems ambiguous here whether the final phrase "for all the objects for every kind of service" corresponds to the silver or to both the gold and the silver.  In the Hebrew it is clearer, the final phrase corresponds to the silver.  Actually, the info about the gold and the info about the silver are written in parallel style.

**Comment by TomWarren** [comment]
The Current ULB now reads:
\v 14 He determined the weight of all the gold vessels for each service, the weight of silver vessels for each service,
\v 15 the weight of the gold for all the gold articles, to be lampstands and gold lamps, the weight of gold for each lampstand, the weight of silver for each silver lampstand, according to the use of each lampstand in the service. 

That seems to follow the HEB text more closely. 

Tom Warren
