### ISSUE TITLE
2 Ch 2:2 ULB/UDB disagreement

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#821]
ULB eighty thousand men as **woodcutters** in the mountains

UDB eighty thousand men **to cut stones** from quarries in the hills

One says they are woodcutters, the other says they are stone cutters.

**Comment by TomWarren** [comment]
The majority render חֹצֵ֣ב, as "stone-cutters."
The ULB of 2CH 2:2 now reads:
\v 2 Solomon assigned seventy thousand men to carry loads, and eighty thousand men as stonecutters in the mountains, and 3,600 men to supervise them.

This seems to fit. 
Thanks John, 

Tom

**Comment by jhutchins25** [comment]
Hello again, Tom.

I just found the same issue in 2:18 

eighty thousand to be woodcutters in the mountains

**Comment by TomWarren** [comment]
The ULB of 2CH 2:18 was changed to read:
\v 18 He assigned seventy thousand of them to carry loads, eighty thousand to be **stonecutters** in the mountains, and 3,600 to be supervisors to put the people to work.

Thanks John, 

Tom
