### ISSUE TITLE
2Ch 8:5 ULB   Delete comma

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#822]
Also he built **Bethhoron the Upper,** and Bethhoron the Lower, cities fortified with walls, gates, and bars.

I think the comma after Bethhoron the Upper" should be deleted. (I'm assuming that the final phrase describes the two cities.)

**Comment by TomWarren** [comment]
Yep. 
The ULB of 2CH 8:5 now reads:
\v 5 Also he built Bethhoron the Upper and Bethhoron the Lower, cities fortified with walls, gates, and bars.

Thanks Susan, 

Tom
