### ISSUE TITLE
2 Ch 3:8-9 talents and shekels (needed)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#824]
I'm having trouble getting all the numbers to add up, but I may be doing something wrong.

ULB 600 talents. 

According to the tA page a talent is 33 kilograms. This would equal 19,800 kilograms which is 19.8 metric tons. The UDB translates this as 21 metric tons. Should it be 20 metric tons?

ULB 50 shekels.

According to the tA page a shekel is 11 grams. This would equal 550 grams which is a little over a half a kilogram. The UDB translates it as 1 3/5 kilograms.

Do my calculations look correct to you?

**Comment by TomWarren** [comment]
The UDB of 2CH 3:8 was just changed in a project:
\v 8 They also built the very holy place inside the temple. It was nine meters long, the same as the temple's width. The width of the very holy place was the same. They covered its walls with sheets of pure gold that altogether weighed about **twenty** metric tons.

The UDB of 2CH 3:9 now reads:
\v 9 Each gold nails weighed about one-half a kilogram. They also covered the walls of the upper rooms with thin sheets of gold.
