### ISSUE TITLE
1ki 10:4 ULB "burnt offering" Maintenance

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#825]
the manner in which he offered **burnt offering**

The singular "burnt offering" sounds odd. Could it be plural?

**Comment by TomWarren** [comment]
Curious, this was already fixed:
The ULB of 1KI 10:4 currently reads:
\v 5 the food on his table, the seating of his servants, the work of his servants and their clothing, also his cupbearers, and the manner in which he offered burnt offerings in the house of Yahweh, there was no more breath in her.


Tom
