### ISSUE TITLE
Lam 1:13 typo (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#827]
UDB and has prevented me from **walking turning** back to our home. 

Need to remove either "walking" or "turning"

**Comment by TomWarren** [comment]
The UDB had "he prevented me from turning...
but the HEB had "he turned me back. The ULB correctly has: \q He has spread a net for my feet and turned me back.

The UDB of LAM 1:13 now reads:
\v 13 It is as though he sent a fire from heaven
\q2 that burned in my bones;
\q1 it is as though he has placed a trap to entangle my feet,
**\q2 and made me turn back.**
\q1 He has abandoned me;
\q2 I am weak and alone every day, all during the day.
