### ISSUE TITLE
Lam 1:18-19 2 typos (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#828]
1) UDB: 1:18 Look and see that that I am suffering greatly

Delete one "that"

2) UDB: 1:19 My priests and my leaders died with the walls of the city

"with" should be "within"

**Comment by TomWarren** [comment]
The UDB of LAM 1:18 now reads:
\v 18 But what Yahweh has done to me is fair,
\q2 for I had refused to obey what he told me to do.
\q1 You people everywhere, listen to me!
\q2 Look and see **that** I am suffering greatly.
\q1 My young daughters and brave sons
\q2 have been taken away to far off lands.

Thanks John, 

Tom
