### ISSUE TITLE
Lam 1:22 typo (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#829]
UDB  let those **evils** deeds

Should be "evil."

**Comment by TomWarren** [comment]
The UDB of LAM 1:22 now reads:
\v 22 Yahweh, let those **evil** deeds come near to you
\q2 so you may see them all!
\q1 Punish them as you have punished me
\q2 for all my sins!
\q1 I suffer and groan very much,
\q2 and I faint within my inner self.

Thanks, 

Tom
