### ISSUE TITLE
Lam 2:10 verb tense consistency (needed)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#831]
ULB  Jerusalem **bowed** their heads to the ground

This may need to be "have bowed" to match the tense of other verbs in verse.

**Comment by TomWarren** [comment]
Yep. 
The ULB of LAM 2:10 now reads:
\v 10 The elders of the daughter of Zion sit on the ground in silence.
\q They have thrown dust on their heads and put on sackcloth.
\q The virgins of Jerusalem **have bowed** their heads to the ground.

Thanks John,

Tom
