### ISSUE TITLE
2ch 9:12:ULB in addition to that which she had brought to the king

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#832]
King Solomon gave to the queen of Sheba everything she wished for, whatever she asked, **in addition to that which she had brought to the king**. 

This last phrase reads this way in the ESV (and apparently in the  Hebrew), but people could easily think that it means that Solomon gave back to her the gifts she had given him. Most modern English versions translate it differently: either "more than what she had brought to the king" or "in addition to what he gave her in exchange for what she had brought to the king."

What would you think of making the ULB like the other modern English versions?

**Comment by TomWarren** [comment]
The ULB of 2CH 9:12 now reads:
\v 12 King Solomon gave to the queen of Sheba everything she desired and whatever she asked for; **he gave her more than what she had brought to the king.** So she left and went back to her own land, she and her servants.

Thanks Susan, 

Tom
