### ISSUE TITLE
2 Ch 4:6 missing phrase in UDB

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#833]
ULB  he put five on the right hand, and five on the left

This is not reflected in the UDB.

**Comment by TomWarren** [comment]
ULB  of 2CH 4:6 was edited and now reads:
\v 6 He made also ten basins for washing things; he put five on the south side, and five on the north; items used in performing the burnt offering were to be washed in them. The large basin known as "The Sea" was used by the priests for them to wash.

UDB of 2CH 4:6 was edited and now reads:
\v 6 The craftsmen also made ten basins for washing the articles that were to be used in making offerings, and they set five on the south side, and five on the north side. In them the utensils used for the burnt offering were washed, and the priests washed themselves in the large bronze basin known as "The Sea."
