### ISSUE TITLE
2ch  9:12 ULB  "No wood like this" to "No things like these"?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#834]
ULB: **No wood like this** had been seen before in the land of Judah.
This looks like it was made to fit 1 Kings 10:12.

But for 2ch 9:12 Hebrew has kahem "like them," and other versions and UDB have "like them,"  apparently referring to the stairs and instruments rather than the wood.
ESV: There never was seen the like of them before in the land of Judah.

**Comment by TomWarren** [comment]
The UDB of 2CH 9:12 now reads:
\v 10-12 King Solomon gave to the queen from Sheba everything that she wanted. He gave her more than she had given to him. Then she and those who came with her returned to her own land.
\p The men of Hiram worked with the men of Solomon to bring gold from Ophir. They also brought a large amount of algum wood. The wood was used to make steps for the house of Yahweh, and they also used the wood to make harps and lyres for those who played music. No one in all the land of Judah had ever seen anything like the quality of the algum wood that was used to make the steps and the instruments. 

That is now consistent. 

Thanks,

Tom
