### ISSUE TITLE
2Ch 9:18 ULB round top or gold footstool?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#835]
2Ch 9:18 ULB the top of the throne was round behind.

Hebrew, UDB, and other versions tell about a gold footstool attached to the throne or its steps -

**Comment by TomWarren** [comment]
This is also on the other ISSUE.
The UDB of 2CH 9:18 now reads:
\v 18 There were six steps in front of the throne. There was a gold footstool that was attached to the throne. At each side of the throne there was an armrest, and alongside each armrest there was a statue of a lion.
