### ISSUE TITLE
2 Ch 4:18 ULB/UDB disagreement (needed)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#837]
ULB indeed, the weight of the bronze could not be known.

UDB  no one tried to weigh it all.

These don't seem to agree to me. One says they could not weigh the amount. The other says they did not bother weighing it because it was so much.

There is a similar issue in 1 Ki 7:47.

**Comment by TomWarren** [comment]
The UDB is better aligned with the ULB. 
The UDB of 2CH 4:18 now reads:
\v 18 All of those things that Solomon told them to make used a very large amount of bronze, so great was the amount they used that no one knew how much it all weighed.

Thanks,

Tom
