### ISSUE TITLE
2ch 9:23 ULB Missing words

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#838]
2ch 9:23 **All the earth** sought the presence of Solomon

This is missing "the kings of."
 **All the kings of the earth** sought the presence of Solomon

**Comment by TomWarren** [comment]
Yep. 
The ULB of 2CH 9:23 now reads:
\v 23 All the kings of the earth sought the presence of Solomon in order to hear his wisdom, which God had put in his heart.

Thanks Susan, 

Tom
