### ISSUE TITLE
REV 1:2 "burnished" to "polished"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#84]
Rev 1:2 has "burnished bronze"
Dan10:6 has "polished bronze"
MTTs are more likely to know "polished" than "burnished." Could "polished" be used instead?

Also Rev 2:18
1 Kings 7:16, 45, 
2 Chronicles 4:16

**Comment by pohlig** [comment]
I agree that "polished" is far more likely to be understood. I will make these changes to "polished." Thanks

**Comment by SusanQuigley** [comment]
Thank you. ☺
On Jun 16, 2016, at 8:46 AM, pohlig <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree that "polished" is far more likely to be understood. I will make these changes to "polished." Thanks

**Comment by TomWarren** [comment]
I will make the corrections. ... one moment
2 Ki 7:16
2 Ki 7:45
2 Ch 4:16
Rev 1:15
Rev 2:18
Completed changed  from burnished to polished. 
Thanks

**Comment by pohlig** [comment]
Just changed them.

**Comment by SusanQuigley** [comment]
Tom and Jim,

At 8:52 I got this message that Tom change them, and at 9:09 I got one saying that Jim changed them.
Could you two have been working on different documents?

Susan

On Jun 16, 2016, at 8:52 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


I will make the corrections. ... one moment
2 Ki 7:16
2 Ki 7:45
2 Ch 4:16
Rev 1:15
Rev 2:18
Completed changed from burnished to polished.
Thanks

**Comment by TomWarren** [comment]
We are talking about that now.


All is well.

Tom

**Comment by SusanQuigley** [comment]
Very good.

On Jun 16, 2016, at 9:19 AM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:

We are talking about that now.


All is well.

Tom
