### ISSUE TITLE
2CH 16:13 semi colon alert

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#840]
"Asa slept with his ancestors; he died in the forty-first year of his reign."

Just FYI. I've heard rumor that semi colons are evil.

**Comment by TomWarren** [comment]
The ULB of 2CH 16:13 now reads:
\v 13 So Asa slept with his ancestors, dying in the forty-first year of his reign.

Thanks, as in my email, thanks for your good eye.

Tom
