### ISSUE TITLE
2Ch 10:2 ULB Parentheses

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#841]
It happened that Jeroboam son of Nebat heard of this (for he was in Egypt, to where he had fled from the presence of King Solomon, **but Jeroboam returned from Egypt).**

Putting "but Jeroboam returned from Egypt" in the parenthesis seems to show that Jeroboam heard the news after he returned from Egypt.
Other versions have him hearing the news in Egypt and then returning. Would something like one of these work?

It happened that Jeroboam son of Nebat heard of this while he was in Egypt, to where he had fled from the presence of King Solomon. **So Jeroboam returned from Egypt.**
or
It happened that Jeroboam son of Nebat, who was in Egypt, heard of this. (For he had fled there  from the presence of King Solomon.) **So Jeroboam returned from Egypt.**

**Comment by TomWarren** [comment]
The ULB of 2CH 10:2 now reads:
\v 2 When Jeroboam the son of Nebat heard this (for he was in Egypt, where he had fled from King Solomon), he returned from Egypt.

Hope that covers it. 
Thanks,

Tom
