### ISSUE TITLE
1ki 12:18 ULB Adoram vs UDB  Adoniram 

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#843]
1ki 12:18 ULB has Adoram and UDB has Adoniram.
I don't know if you want these to be the same.

2ch:18 has Adoniram in both.

Note in NET Bible tells about differences in early versions.

**Comment by TomWarren** [comment]
The ULB of 1KI 12:18 now reads:
\v 18 Then King Rehoboam sent Adoniram , who was over the forced laborers, but all Israel stoned him to death with stones. King Rehoboam fled quickly in his chariot to Jerusalem.

Perhaps a Note about the possibility of the alternate spelling of the name of Adoniram would be helpful. 

Thanks, 

Tom
