### ISSUE TITLE
2CH 18:3 semi colon

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#844]
"...Jehoshaphat answered him, "I am like you, and my people are like your people; we will be with you in the war.""

Another evil semi colon above.

**Comment by TomWarren** [comment]
Perhaps a carry-over from the ASV. 
The ULB of 2CH 18:3 now reads:
\v 3 Ahab, king of Israel, said to Jehoshaphat, king of Judah, "Will you go with me to Ramoth Gilead?" Jehoshaphat answered him, "I am like you, and my people are like your people. We will be with you in the war."

Thanks Kim, 

Tom
