### ISSUE TITLE
2CH 20:21 verb tense

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#846]
When he had consulted with the people, he appointed those who should sing to Yahweh and give him praise for his holy glory, as they went out preceding the army, and say, "Give thanks to Yahweh, for his covenant faithfulness endures forever."

Verb tenses seem off in this verse.

**Comment by TomWarren** [comment]
The ULB of 2CH 20:21 now reads:
\v 21 After he consulted with the people, he appointed those who sang to Yahweh and who praised him for his majestic splendor as they went out before the army, saying, "Give thanks to Yahweh, for his covenant faithfulness endures forever."

Thanks Kim,

Tom
