### ISSUE TITLE
2Ch 26:16 Missing word

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#847]
for you have * unfaithful and you will not be honored by Yahweh God.

It looks like the word "been" is missing before "unfaithful."

**Comment by TomWarren** [comment]
Yep. 
The ULB of 2CH 26:16 now reads:
\v 18 They resisted Uzziah, the king, and said to him, "It is not for you, Uzziah, to burn incense to Yahweh, but for the priests, the sons of Aaron, who are consecrated to burn incense. Go out of the holy place, for **you have been unfaithful** and you will not be honored by Yahweh God."

Thanks Susan, 

Tom
