### ISSUE TITLE
2ch 26:22 ULB  Missing word?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#848]
As for the other matters concerning Uzziah, first and last, are in what Isaiah son of Amoz, the prophet, wrote.

This sentence does not have a subject. Should the word "they" be inserted before "are"?
Or maybe "as for" could be deleted.

**Comment by TomWarren** [comment]
The ULB of 2CH 26:22 was edited to read:
\v 22 The other matters concerning Uzziah, from first to last, were recorded by the prophet Isaiah son of Amoz.

Thanks, 

Tom
