### ISSUE TITLE
2ch 26:23  Capital K not  needed

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#849]
a burial ground that belonged to the Kings

Please change "Kings" to "kings"

**Comment by TomWarren** [comment]
The ULB of 2CH 26:23 now reads:
\v 23 So Uzziah slept with his ancestors; they buried him with his ancestors in a burial ground that belonged to the **kings**, for they said, "He is a leper." Jotham, his son, became king in his place.

Thanks Susan, 

Tom
