### ISSUE TITLE
DAN 10:16 like a human being

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#85]
Dan 10:16 "like a human being" (Hebrew: kismet bene adam)
Rev 1:13 "like a Son of Man"
Could these be translated the same way? 
I'm assuming that the phrase "Son of Man" in Rev was intended to make people think of this one in Daniel

**Comment by pohlig** [comment]
Not all references to the expression "son" or "sons of man" can be argued to have anything to do with the NT title Son of Man. Dan. 10:16 is doesn't seem to refer to the same being in Dan. 7 "son of man."

**Comment by SusanQuigley** [comment]
OK. Thank you, Jim.
On Jun 16, 2016, at 9:37 AM, pohlig <notifications@github.com<mailto:notifications@github.com>> wrote:


Not all references to the expression "son" or "sons of man" can be argued to have anything to do with the NT title Son of Man. Dan. 10:16 is doesn't seem to refer to the same being in Dan. 7 "son of man."
