### ISSUE TITLE
2Ch 30:3 ULB Extra word

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#851]
because there were not enough priests who had **not** consecrated themselves,

The word "not" before "consecrated" should be deleted.

**Comment by TomWarren** [comment]
The ULB of 2CH 30:3 now reads:
\v 3 They could not celebrate at the regular time, because not enough priests had consecrated themselves for the celebration and the people had not gathered together in Jerusalem.

A bit of a rework. hope that works,

Tom
