### ISSUE TITLE
2 Ch 32:32 capitalization of book title

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#854]
ULB written in The Vision of the Prophet Isaiah Son of Amoz

UDB written in the Vision of Isaiah the Prophet

If I understand correctly, we are following NIV 2011 format for book capitalization. If so, NIV has "written in the vision of the prophet Isaiah son of Amoz"

Also, while you are there, there needs to be a space between "of" and "Judah" in UDB verse 32.

**Comment by TomWarren** [comment]
The rules for capitalization have been changed on many occasions, and I did give this a brief scan.
The ULB of 2CH 32:32 now reads:
\v 32 As for the other matters concerning Hezekiah, including his actions of covenant loyalty, you can see that they are written in the **vision of the prophet Isaiah** Son of Amoz, and in the book of the kings of Judah and Israel.

The UDB of 2CH 32:32 now reads:
\v 32 A record of the other things that happened while Hezekiah was ruling, and the things that he did to please God, is on the scroll in which is written in the vision of Isaiah the prophet. It is also written in the book of the kings **of Judah** and Israel.

Thanks John, 

Tom

**Comment by pjoakes** [comment]
Thanks,

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>

ULB: “Son” doesn’t need capitalization, but maybe “Prophet" (Isaiah) does, like King David:

the vision of the prophet Isaiah Son of Amoz,

UDB: too many “in”s:

on the scroll in which is written in the vision of Isaiah the prophet.

On May 2, 2017, at 1:43 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


The rules for capitalization have been changed on many occasions, and I did give this a brief scan.
The ULB of 2CH 32:32 now reads:
\v 32 As for the other matters concerning Hezekiah, including his actions of covenant loyalty, you can see that they are written in the vision of the prophet Isaiah Son of Amoz, and in the book of the kings of Judah and Israel.

The UDB of 2CH 32:32 now reads:
\v 32 A record of the other things that happened while Hezekiah was ruling, and the things that he did to please God, is on the scroll in which is written in the vision of Isaiah the prophet. It is also written in the book of the kings of Judah and Israel.

Thanks John,

Tom

**Comment by TomWarren** [comment]
The case of looking at only one issue. 

The ULB of 2CH 32:32 was edited:
\v 32 As for the other matters concerning Hezekiah, including his actions of covenant loyalty, you can see that they are written in the vision of the prophet Isaiah son of Amoz, and in the book of the kings of Judah and Israel.

The UDB of 2CH 32:32 now reads:
\v 32 A record of the other things that happened while Hezekiah was ruling, and the things that he did to please God, is written on the scroll of the vision of Isaiah the prophet. It is also written in the book of the kings of Judah and Israel.

Thanks Perry, 

Tom
