### ISSUE TITLE
2Ch 30:5 ULB  implication of comma

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#855]
For they had not observed it with large numbers of people**, according to what was written.**

The comma before "according to what was written"  seems to imply that their not observing the passover with large numbers was according to what was written. That is,  it implies that it was written that they should not observe it in large numbers. 
Maybe the comma could be removed and the last phrase changed to "as it was written that they should do" or "as it was prescribed" to show that it was written that they should do it in large numbers, but they had not done in that way.

For they had not observed it with large numbers of people as it was written that they should do.
For they had not observed it with large numbers of people as it was prescribed.

**Comment by TomWarren** [comment]
The ULB of 2CH 30:5 now reads:
\v 5 So they agreed to make a proclamation throughout all Israel, from Beersheba to Dan, that the people should come to celebrate the Passover to Yahweh, the God of Israel, in Jerusalem. For they had not observed it with large numbers of people according to what was written.

Perhaps a note on "what was written" meaning "what was written in the Law of God."

Thanks, 
Tom
