### ISSUE TITLE
2ch 30:7 ULB  destruction vs horror

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#857]
30:7 ULB Do not be like your ancestors or your brothers, who trespassed against Yahweh, the God of their ancestors, so that **he gave them up to destruction**, as you see. 

Could "he gave them up to destruction" be changed to something like "he made them to be an object horror" as in 29:8.

29:8 wayyittənem lizwa'ah/ləza'awah ləshammah
30:7 wayyittənem ləshammah

Aaron explained wrote this.
Set apart for destrucion should render the Hebrew ḥrm (devote to destruction)
This word is šammâ

**Comment by TomWarren** [comment]
The ULB of 2CH 30:7 now reads:
\v 7 Do not be like your ancestors or your brothers, who trespassed against Yahweh, the God of their ancestors, so that **he made them an object of horror,** as you see.

Yes, 29:8 is accurate. 

Thanks,

Tom
