### ISSUE TITLE
1 Ch 16:19 pronoun issue.

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#858]
ULB 19 I said this when you were only few in number,

Since the quotation closes at the end of verse 18, it seems here "I" should be "He" as in the UDB.

**Comment by TomWarren** [comment]
The UDB of 1CH 16:19-20 was edited a bit and now reads:
\v 19 When Yahweh's people were only a few in number,
\q2 a tiny group of people who were living in that land like strangers,
\q1
\v 20 they continued to wander from one place to another,
\q2 from one kingdom to another.

The ULB of 1CH 16:19-20 was re-edited to read:
\v 19 When they were only few in number,
\q so very few, and they were strangers in the land,
\q
\v 20 they wandered from nation to nation,
\q from one kingdom to another.

The shift comes by simplifying the rendering, beginning with, "When Yahweh's people (They, them).
Hope that helps, 

Tom
