### ISSUE TITLE
2CH 34:7 semi colon

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#859]
He broke down the altars, beat the Asherah poles and the carved images into powder, and cut apart all the incense altars throughout all the land of Israel; then he returned to Jerusalem.

**Comment by TomWarren** [comment]
Two sentences from one. 
The ULB of 2CH 34:7 now reads:
\v 7 He broke down the altars, beat the Asherah poles and the carved images into powder, and cut apart all the incense altars throughout all the land of Israel. Then he returned to Jerusalem.

Thanks Kim, 

Tom
