### ISSUE TITLE
GEN 2:23-24  Indent needs to end before 24

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#86]
Gen 2:23 is indented. (This is what Adam said about Eve)
Gen 2:24 also shows up indented on https://door43.org/en/ulb/ep/ot. (This is narrator's comment.)
Does it need some kind of code so that 24 will not be indented?

**Comment by SusanQuigley** [comment]
I think I found the problem. Gen 4:25 has \p before the part that should no longer be indented. 

\s5
\v 23 Lamech said to his wives, 
\q "Adah and Zillah, listen to my voice; you wives of Lamech, listen to what I say.
\q For I have killed a man for wounding me, a young man for bruising me.
\q
\v 24 If Cain is avenged seven times as much, truly Lamech will be avenged seventy-seven times as much."

\s5
\p
\v 25 Adam slept with his wife again, and she bore another son. She called his name Seth and said, "God has given me another son in the place of Abel, for Cain killed him."
\v 26 A son was born to Seth and he called his name Enosh. Then people began to call on the name of Yahweh.

**Comment by TomWarren** [comment]
Gen 2 had indent removed: 
The USFM is better to show formatting, but the return to margin in after 23 and 24 starts at margin. 
22With the rib that Yahweh God had taken from the man, he made a woman and brought her to the man. 23The man said,
"This time, this one is bone of my bones, and flesh of my flesh.
She will be called 'woman,' because she was taken out of man."
24Therefore a man will leave his father and his mother, he will be united to his wife, and they will become one flesh. 25They were both naked, the man and his wife, but were not ashamed.

**Comment by TomWarren** [comment]
Gen 4 is also returned to margin after v24. The USFM is formatted better, but here is the change:
23Lamech said to his wives,
"Adah and Zillah, listen to my voice; you wives of Lamech, listen to what I say.
For I have killed a man for wounding me, a young man for bruising me.
24If Cain is avenged seven times as much, truly Lamech will be avenged seventy-seven times as much."
25Adam slept with his wife again, and she bore another son. She called his name Seth and said, "God has given me another son in the place of Abel, for Cain killed him."

**Comment by SusanQuigley** [comment]
Tom, thanks for working on this. I didn't see Gen 4:24 as a problem. I thought that the reason that 4:24 showed up right is that it had \p before it starting a new paragraph. So I was thinking that the way to fix Genesis 2:24 was to add \p before v. 24. 
It looks like there are two ways to stop the indenting. One is \m and one is  \p

**Comment by SusanQuigley** [comment]
Tom, thanks for working on this. I didn't see Gen 4:24 as a problem. I thought that the reason that 4:24 showed up right is that it had \p before it starting a new paragraph. So I was thinking that the way to fix Genesis 2:24 was to add \p before v. 24.

It looks like there are two ways to stop the indenting. One is \m and one is \p

Susan

On Jun 17, 2016, at 1:13 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


Gen 4 is also returned to margin after v24. The USFM is formatted better, but here is the change:
23Lamech said to his wives,
"Adah and Zillah, listen to my voice; you wives of Lamech, listen to what I say.
For I have killed a man for wounding me, a young man for bruising me.
24If Cain is avenged seven times as much, truly Lamech will be avenged seventy-seven times as much."
25Adam slept with his wife again, and she bore another son. She called his name Seth and said, "God has given me another son in the place of Abel, for Cain killed him."
