### ISSUE TITLE
Lam 4:7 verb tense issue in UDB

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#860]
UDB 7Our leaders **are** like pure snow or white milk,

Here "are" should be "were." Verse 7 states what the leaders were like. Verse 8 states what they are like now.

**Comment by TomWarren** [comment]
The UDB of Lam 4:7-8 was edited:
\v 7 Our leaders used to be like pure snow or white milk,
\q2 they were so clean and spotless.
\q1 Their bodies were healthy,
\q2 pink like coral and brilliant like sapphires.
\q1
\v 8 Now our leaders' faces are blacker than soot,
\q2 and no one recognizes them when they walk in the streets.
\q1 Their skin has shriveled and it hangs on their bones,
\q2 and it has become as dry as a stick of wood.

Thanks very much John, 

Tom
