### ISSUE TITLE
1Ch 5:26 Extra word

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#862]
ULB He **took brought** them to Halah

Need to remove "took" or "brought"

**Comment by TomWarren** [comment]
Yep. The ULB of 1CH 5:26 now reads:
\v 26 The God of Israel stirred up Pul king of Assyria (also called Tiglath-Pileser, king of Assyria). He took into exile the Reubenites, Gadites, and the half tribe of Manasseh. He **brought** them to Halah, Habor, Hara, and to the river of Gozan, where they remain to this day.

Thank you John, 

Tom
