### ISSUE TITLE
1Ch 6:25 genealogy problem

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#863]
ULB The sons of Elkanah were **Amasai, Ahimoth, and Elkanah.**

UDB 25Elkanah's other sons were **Amasai and Ahimoth**.
        26Ahimoth's son was **Elkanah**.

ULB says Elkanah had 3 sons. The UDB says he has two sons.

**Comment by TomWarren** [comment]
The ULB of 1CH 6:25-28 now reads:
\v 25 The sons of Elkanah were Amasai, Ahimoth,
\v 26 And a son named Elkanah, Zophai his son, Nahath his son, 
\v 27 Eliab his son, Jeroham his son, and Elkanah his son. \f + \ft The LXX adds to the list \fqa Samuel his son. \f*

\s5
\v 28 The sons of Samuel were the firstborn, Joel, and Abijah, the second-born.

The UDB of 1CH 6:25-28 now reads:
\v 25 Elkanah's sons were Amasai, Ahimoth,
\li2
\v 26 and a son also named Elkana.
\li2 Elkanah's son was Zophai.
\li2 Zophai's son was Nahath.
\li2
\v 27 Nahath's son was Eliab.
\li2 Eliab's son was Jeroham.
\li2 Jeroham's son was Elkanah.
\li2 Elkanah's son was Samuel.

Somewhat befuddling.

Thanks John, 

Tom
