### ISSUE TITLE
john 19:36  British spelling

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#866]
For these things happened in order to **fulfil** scripture,

**fulfil**  with one "l" at  the end is a British spelling. 
ULB has been using "fulfill."

**Comment by TomWarren** [comment]
The ULB of JHN 19:36 now reads:
\v 36 For these things happened in order to fulfill scripture, "Not one of his bones will be broken."

Thanks, 

Tom

**Comment by TomWarren** [comment]
That is all of them in the ULB. There were NONE in the UDB> 

Thanks
Tom
