### ISSUE TITLE
john 18:9 British spelling

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#867]
This was in order to **fulfil** the word that he said

**fulfil**  with one "l" at the end is a British spelling. 
ULB has been using "fulfill."

**Comment by TomWarren** [comment]
The ULB of JHN 18:9 has been fixed:
Also JHN 18:9 now reads:
\v 9 This was in order to fulfill the word that he said: "Of those whom you have given me, I lost no one."

This was include on the John 19:36 issue, as well.

Tom
