### ISSUE TITLE
Jos 8:14 ULB the place facing toward the Jordan River valley

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#868]
13They positioned all the soldiers, the main army on the north side of the city, and the rear guard on the west side of the city. Joshua spent that night in the valley. 14 It came about when the king of Ai saw it, he and his army got up early and rushed out to attack Israel at **the place facing toward the Jordan River valley**. He did not know that an ambush was waiting to attack from behind the city.

_lammow'ed lipne ha'arabah_ 

Joshua was in the valley north of Ai. It's hard to imagine what it would mean for that place to "face" the Jordan River valley. It's not like it was a high point from which one could easily see the JR valley.

Some versions translate _ha'arabah_  as "the Arabah." But that was far to the south. So it's hard to imagine what it would mean for that place to "face" the Arabah.

Could _ha'arabah_ be translated simply as "the valley" and refer to the valley that Joshua was in?
Could "the place facing toward the Jordan River valley" be changed to something like one of these?
"the place in the valley"
"the meeting place in/near the valley"

**Comment by SusanQuigley** [comment]
If the ULB is changed, the  UDB would also need to be changed.

**Comment by TomWarren** [comment]
The Arabah was translated throughout as "Jordan River Valley." We had a project to align that term with that rendering. 
The ULB of JOS 8:14 now reads:
\v 14 It came about when the king of Ai saw it, he and his army got up early and rushed out to attack Israel at a certain place that was overlooking the Jordan River valley. He did not know that an ambush was waiting to attack from behind the city.

The UDB of JOS 8:14 now reads:
\v 14 When the king of Ai saw the Israelite army, he and his soldiers got up early the next morning and quickly went out of the city to fight them. They went to a place east of the city that overlooked the plain of the Jordan River, but they did not know that some Israelite soldiers were hiding ready to attack them from behind the city.

I hope that covers the issues. 

Thanks Susan, 

Tom
