### ISSUE TITLE
Pro 28:12, 28

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#869]
28: 12 וּבְק֥וּם רְ֝שָׁעִ֗ים יְחֻפַּ֥שׂ‮b‬ אָדָֽם > when the wicked arise, people hide themselves

28:28 בְּק֣וּם רְ֭שָׁעִים יִסָּתֵ֣ר אָדָ֑ם > When wicked people rise, men hide themselves

 אָדָ֑ם is same in both places in Heb but rendered differently ULB, but the predication for אָדָ֑ם is different in Heb but rendered the same in ULB. "People" would probably be best in both places, but you may want to check the OT as a whole to make sure.

**Comment by TomWarren** [comment]
The verb at the end of Pro 28:12 is יְחֻפַּ֥שׂ, meaning 'he is searched for", 
The grammar of the two verses is no as close as what was in the ULB (before editing). 
Check this.

The ULB of PRO 28:12 now reads:
\v 12 When the righteous triumph, there is great glory;
\q but when the wicked arise, people are sought out.

in 28:28 the first verb is קום "he arises" (qal part)

The ULB of PRO 28:28 now reads:
\v 28 When the wicked arise, people hide themselves;
\q but when they perish, the righteous increase.
