### ISSUE TITLE
1Ch 27:27 (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#870]
ULB 27 Shimei from Ramathite

This should be "Shimei the Ramathite" or "Shimei from Ramath"

**Comment by TomWarren** [comment]
The ULB of 1CH 27:27 now reads:
\v 27 Shimei the Ramathite was over the vineyards, and Zabdi the Shiphmite was over the grapes and the wine cellars.

Thanks John, 

Tom
