### ISSUE TITLE
Gen 16:14 UDB  Extra space

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#871]
Therefore the well was called Beer Lahai Roi ; behold, it is between Kadesh and Bered.

There is a space before the semicolon.

**Comment by SusanQuigley** [comment]
Oops. This was a problem in the ULB, not the UDB.

**Comment by TomWarren** [comment]
The ULB of GEN 16:14 now reads:
\v 14 Therefore the well was called Beer Lahai Roi; behold, it is between Kadesh and Bered.

Thanks Susan, 

Tom
