### ISSUE TITLE
2ch4:3 wording issue

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#872]
UDB 3Below the outer rim there were two rows of small figures of bulls **that the craftsmen all had been cast together** with the metal basin that was called "The Sea.

This sounds like the craftsmen cast themselves to the basin. Maybe it should be "that the craftsmen cast together with the metal basin."

**Comment by TomWarren** [comment]
There was quite a bit of editing on this. I hope this helps.
The UDB of 2CH 4:3 now reads:
\v 3 Below the outer rim there were small figures of bulls that were set in a circle, the bulls were placed 45 centimeters apart around the whole circle. The bulls were cast together in two rows, and they were also cast together with the metal basin that was called "The Sea." (Each row had three hundred figures of bulls.)

Thanks John, 
Tom
