### ISSUE TITLE
2Ch 4:4-5 "The Sea"

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#873]
ULB 4 **The sea** was set on top of them
ULB 5 **The sea** held three thousand baths of water.

In the surrounding verses this is written as "The Sea." Should these be changed to match the others?

(Just found another instance at the beginning of 4:15)

**Comment by TomWarren** [comment]
Yep. The ULB of 2CH 4:4-5 now reads:
\v 4 The large basin known as "The Sea" was set upon twelve oxen, three looking toward the north, three looking toward the west, three looking toward the south, and three looking toward the east. "The Sea" was set on top of them, and all their hindquarters were toward the inside.
\v 5 "The Sea" was as thick as the width of a hand, and its brim was forged like the brim of a cup, like a lily blossom. "The Sea" held three thousand baths of water.

Thanks John,

Tom
