### ISSUE TITLE
2ch 4:10 ULB more dynamic than UDB

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#874]
ULB He placed the basin known as "The Sea" **on the southeast corner of the house.**

UDB They placed the large tank that was called "The Sea" **on the east side of the temple, facing toward the south.**

Could the end phrases be switched?
ULB ... on the east side of the temple, facing toward the south.
UDB ... at the southeast corner of the temple

**Comment by TomWarren** [comment]
The UDB of 2CH 4:10 now reads:
\v 10 They placed the large tank that was called "The Sea" at the southeast corner of the temple.

The ULB of 2CH 4:10 now reads:
\v 10 He placed the basin known as "The Sea" on the east side of the temple, facing toward the south.

The puts the UDB and ULB in their right places, 
Thanks Susan, 

Tom
