### ISSUE TITLE
2Ch 4:14-16--3 issues (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#875]
1. ULB 14He also made the stands and the basins to go **on the stand**

The last "stand" should be plural.

2. ULB 16 that Huram-Abi made **them**

Don't need "them."

3. ULB 16 and all the other implements that Huram-Abi made them for King Solomon, for the house of Yahweh, of polished bronze

The proofreader felt the sentence was awkward ending with "of polished bronze." I looked it up and this does follow the Hebrew structure. If you feel it should be reordered you could put "of polished bronze" after "Huram-Abi made."

**Comment by TomWarren** [comment]
The ULB of 2CH 4:14 now reads:
\v 14 He also made the stands and the basins to go on **the stands;**
The ULB of 2CH 4:16 now reads:
\v 16 also the pots, shovels, meat forks, and all the other implements that Huram-Abi **made of polished bronze** for King Solomon, for the house of Yahweh.

Vs 16 had two issues, which were added to the rendering. 
Thanks John, 

Tom
