### ISSUE TITLE
2Ch 5:9 add "in" (maintenance)

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#877]
UDB who were standing the entrance to the very holy place

Need to add "in" after "standing."

**Comment by TomWarren** [comment]
The UDB of 2CH 5:9 now reads:
\v 9 The poles were very long, with the result that they could be seen by people who **were standing in the** entrance to the very holy place, but they could not be seen by anyone standing outside the temple. Those poles are still there.

Thanks, 
Tom
