### ISSUE TITLE
2Ch 5:11 awkward wording in UDB

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#878]
UDB 11Then the priests left the holy place in the temple. All the priests who were there, without concern for which group they were from, **and they** set themselves apart from others and performed the cleansing rituals God required of them before they could serve him.

Is "and they" supposed to be here? 

And, many other English versions put "without concern for which group they were in" after "set themselves apart." I think this makes the sentence easier to follow.

NIV All the priests who were there had consecrated themselves, regardless of their divisions.
ESV for all the priests who were present had consecrated themselves, without regard to their divisions
NASB for all the priests who were present had sanctified themselves, without regard to divisions

But, if you don't reorder the sentence I think just taking the "and they" out will make it clearer.

**Comment by TomWarren** [comment]
The UDB of 2CH 5:11 now reads:
\v 11 Then the priests left the holy place in the temple. All the priests who were there set themselves apart to serve the priestly duties, without concern for which group they were from.

That is the way I did it, too (I didn't peek, but I did check). 
Thanks John, 

Tom
