### ISSUE TITLE
Ezk 40:44 ULB Hebrew text is clearer

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#879]
Near the inner gate, in the inner courtyard, were singers' chambers. One of these rooms was on the north side, and one on the south. 45Then the man said to me, "This room facing south is for the priests who are on duty in the temple.

The Hebrew in BibleHub of v 44 tells both the location of the rooms and what direction they were facing. Could the ULB of 44 be changed to this?
Near the inner gate, in the inner courtyard, were singers' chambers. One of these rooms was on the north side **and faced south**, and one **was** on the south side **and faced north.**

The reason I'm asking for this is that  we understand that a **gate** that faces east is on the east side of the courtyard, and a **gate** that faces north is on the the north side of the courtyard. Yet a **room** that faces south is on the north side. It helps to have it spelled out in v44, as the Hebrew apparently does.

**Comment by TomWarren** [comment]
VS 44 appears to be describing the "rooms" or "chambers" for the singers.
The ULB of EZK 40:44 now reads:
\v 44 On the outside of the inner gate, within the inner courtyard, were singers' chambers, one on the north side facing south, and the other on the south side facing north.

This could be difficult for the MTT with "who's on north facing south?" etc, but that follows the HEB. 

Thanks, 
Tom
