### ISSUE TITLE
Ezk 40:46 ULB Tense issue

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#881]
45 Then the man said to me, "This room facing south is for the priests who are on duty in the temple.
46 The room facing north **was** for the priests on duty at the altar. These are the sons of Zadok who come near to Yahweh to serve him; they are among the sons of Levi."

If the man is still speaking in 46, the "was" should probably be "is"

**Comment by TomWarren** [comment]
The ULB of EZK 40:46 now reads:
\v 46 The room facing north is for the priests on duty at the altar. These are the sons of Zadok who come near to Yahweh to serve him; they are among the sons of Levi."

Tense corrected. 

Tom
