### ISSUE TITLE
Ezk 42:4  ULB Typo in footnote

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#882]
[1]Some ancient versions and many modern versions read one hundred cubits . Ancient Hebrew copies and some modern versions **read read** one cubit .

One "read" can be deleted.

**Comment by TomWarren** [comment]
The ULB of EZK 42:4 now reads(with the double "READ" removed:
\v 4 A passage ten cubits in width and one hundred cubits in length ran in front of the rooms. The rooms' doors were toward the north.
\f + \ft Some ancient versions and many modern versions read \fqa one hundred cubits \fqa* . Ancient Hebrew copies and some modern versions read \fqa one cubit.\f*

Thanks Susan, 

Tom
