### ISSUE TITLE
Ezk 44:4 "faces the house" or "front of the house"

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#883]
ULB: Next he brought me by way of the northern gate **that faces the house**.
UDB: Then the man brought me through the north entrance **to the front of the temple**.

Could the ULB be like the UDB and other versions -- 
Other versions are like the UDB "to the  front of the temple"

Next he brought me by way of the northern gate **to the front of the house**.

**Comment by TomWarren** [comment]
The ULB of EZK 44:4 now reads:
\v 4 Then he brought me by way of the northern gate to the front of the temple, and I looked, and behold, the glory of Yahweh filled the house of Yahweh, and I fell on my face.

The UDB of EZK 44:4 was not changed, and it reads:
\v 4 Then the man brought me through the north entrance to the front of the temple. I looked and saw that the glory of Yahweh filled his temple, and I prostrated myself on the ground.

Thanks Susan, 

Tom
