### ISSUE TITLE
RMS 3:10-18

### ISSUE THREAD

**Issue by ChrisJarka** [Door43/ulb-en#885]
From the field (MAST facilitator)

The ULB for Romans 3 shows a continuous quote from verse 10 through verse 18. Should there be any additional close/open quotes between 10 and 18 when the Old Testament references change between various Psalms and also Isaiah? 

The Greek text I looked at gives no indication of a quote being repeated nor of the source of the quote; i.e., there are no quotes in the Greek. However, there are periods at the end of the various verses quoted.

NOTE: the UDB does not have any quote marks.

**Comment by TomWarren** [comment]
Following the NIV, this seems to break up the references. The Note should be checked that each individual quotation from the OT is identified (where possible). 
The ULB of ROM 3:10-18 now reads:
\v 10 This is as it is written:
\q "There is no one righteous, not one.

\s5
\q
\v 11 There is no one who understands.
\q There is no one who seeks after God.
\q
\v 12 They have all turned away. They together have become useless.
\q There is no one who does good, no, not even one."

\s5
\q
\v 13 "Their throat is an open grave.
\q Their tongues have deceived.
\q The poison of snakes is under their lips."
\q
\v 14 "Their mouths are full of cursing and bitterness."

\s5
\q
\v 15 "Their feet are swift to pour out blood.
\q
\v 16 Destruction and suffering are in their paths.
\q
\v 17 These people have not known a way of peace."
\q
\v 18 "There is no fear of God before their eyes."

Hope that helps, 

Tom Warren
