### ISSUE TITLE
2Ch 2:13 name mismatch

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#887]
ULB Huram-Abi
UDB Huram

Do you want these to be the same?

**Comment by TomWarren** [comment]
The ULB of 2CH 2:13 and 4:16-17 now read:
\v 13 I will send to you **Huram-Abi,** one of my skilled craftsmen.

\v 16 the pots, shovels, meat forks, and all the other things needed for the work at the altar.
\p All those things that **Huram-Abi** and his craftsmen made for King Solomon were of bronze that they polished for it to gleam brightly.

\s5
\v 17 They made them by pouring melted bronze into the clay molds that **Huram-Abi** had set up near the Jordan River between the cities of Succoth and Zarethan.

The extra was at no extra cost.

Thanks John, 

Tom
