### ISSUE TITLE
2Ch 16:8 Missing word

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#888]
UDB: Remember that the huge armies from Ethiopia very powerful

Should be "Remember that the huge armies from Ethiopia **were** very powerful"

**Comment by TomWarren** [comment]
The UDB of 2CH 16:8 now reads:
\v 8 Remember that the huge armies from Ethiopia were very powerful. But when you relied on Yahweh, he enabled your army to defeat them.

Thanks John, 

Tom
