### ISSUE TITLE
2 Ch 16:12 typo

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#889]
ULB  Asa was afflicted with **a diseased** in his feet

Should be "disease"

**Comment by TomWarren** [comment]
Yep. 
The ULB of 2CH 16:12 now reads:
\v 12 In the thirty-ninth year of his reign, Asa was afflicted with a **disease** in his feet. Though his disease was very severe, he did not seek help from Yahweh, but only from the physicians.

Thanks John, 

Tom
