### ISSUE TITLE
2Ch 16:13 ULB/UDB mismatch

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#890]
ULB dying in the forty-first year of his reign

UDB ruling for almost forty years, he died

I find this a little confusing. When I read "almost forty years" it sounds to me like almost, but not quite 40 years, i.e., 38-39 years.

If "forty-first year" is correct, I think "ruling for a little more than forty years"  or "ruling for around forty years" may work better.

**Comment by TomWarren** [comment]
The UDB of 2CH 16:13 now reads:
\v 13 Asa had been ruling for about forty-one years when he died. 

This rendering is close to 16:12a, which reads"
\v 12 When Asa had been ruling for almost thirty-nine years, he was afflicted with a disease in his feet.  

Thanks John, 

Tom
