### ISSUE TITLE
2ch 24:27 book title capitalization

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#892]
ULB in The Commentary on the book of the kings

UDB in The Commentary on The Book of the Kings of Judah and Israel

The capitalization is different in ULB and UDB.

Honestly, I get confused on what should and should not be capitalized in these titles. Hopefully you know what they should look like :)

**Comment by TomWarren** [comment]
THe ULB of 2CH 24:27 now reads:
\v 27 Now the accounts about his sons, the important prophecies that were spoken about him, and the rebuilding of the house of God, see, they are written in **the commentary on the book of the kings.** Amaziah his son, became king in his place.

The names of the books were more descriptive than a true name (as many versions make them). They may be more an "archive" of historical papers (like Ebla, or more accessible, Alexandria, before the fire). 

Thanks for keeping at it. 

Tom
