### ISSUE TITLE
2Ti 2:14 unclear wording

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#893]
ULB Warn them before God not to quarrel about words. **Because of this** there is nothing useful. **Because of this** there is destruction for those who listen

I don't think "Because of this" is clear in these sentences. Maybe something like this is clearer

"Because there is nothing useful in this and there is destruction for those who listen"

**Comment by TomWarren** [comment]
Yep.
The ULB of 2TI 2:14 now reads:
\v 14 Keep reminding them of these things. Warn them before God against quarreling about words; it is of no value, and only ruins those who listen. \f + \ft Some versions read, \fqa Warn them before the Lord \fqa* \f*

Thanks John,

Tom
