### ISSUE TITLE
act 7:45 ULB Typo

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#894]
This is the tent that our fathers took **possess** of

possess --> possession

**Comment by TomWarren** [comment]
This is the ULB reading like the UDB (taking away the passive and other issues). Let's go over this. 
The ULB of ACT 7:45-46 now reads:
\v 45 Later, our fathers, under Joshua, received the tabernacle and brought it with them when they took possession of the land from the nations that God forced to leave  before the face of our fathers. It remained in the land until the time of David, 
\v 46 who found favor in the sight of God, and he asked if he might find a dwelling place for the God of Jacob.

The figure, "before the face of our father" may need a note (as usual).

That is closer to the GRK text. 
Thanks Susan, 

Tom
