### ISSUE TITLE
Amo 2:14

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#895]
\v 14 The swift **person** will find no escape;
\q the strong will not add to his own strength;
\q neither will the mighty save himself.

Since there's no "person" for "strong" or "mighty," it would be more consistent to delete the "person" here as well.

**Comment by TomWarren** [comment]
Yep.
THe ULB of AMO 2:14 now reads:
\v 14 The swift will find no escape;
\q the strong will not add to his own strength;
\q neither will the mighty save himself.

Thanks Henry, 

Tom
