### ISSUE TITLE
2Ti 3:8 incomplete sentence in ULB

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#896]
ULB In the same way that Jannes and Jambres stood **against Moses. In this way** these false teachers also...

This is not a complete sentence. Maybe this:

 In the same way that Jannes and Jambres stood against Moses, these false teachers also...

**Comment by TomWarren** [comment]
RightO!
The ULB of 2TI 3:8 now reads:
\v 8 In the same way that Jannes and Jambres stood against Moses, these false teachers also stand against the truth. They are men destroyed in mind, unapproved regarding the faith.
Thanks John,

Tom
