### ISSUE TITLE
2 Th 3:10 

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#897]
ULB "If any one does not want to work, he should not eat"

A proofreader suggested that this may be misleading. First, there is a difference between "not wanting" and "not willing."

Second, it could be interpreted to mean "if you do not want to work then you should fast"

Do you think this needs rewording?

**Comment by TomWarren** [comment]
The ULB of 2TH 3:10 now reads:
\v 10 When we were with you, we commanded you, "The one who is unwilling to work must not eat."

Hope that gets the idea. 

Tom
