### ISSUE TITLE
Act 19:34 ULB Artemis -> Diana

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#898]
saying, "Great is Artemis of the Ephesians."

The earlier verses and the UDB all have Diana rather than Artemis.

**Comment by TomWarren** [comment]
We are following the NIV (in most cases) for proper names (for broader testing of our choices, no doubt). 
The Greek is Aρτεμις, Artemis.  Diana is the Latin (Roman) equivalent of the same goddess.
A note to that effect might be helpful. 

The name Ἄρτεμις occurs in ACT 10: 24,27 (2x), 28, and 35 (and nowhere else in the text).

The ULB of ACT 19:34 (and all ULB references to Ἄρτεμις) now reads:
\v 34 But when they became aware that he was a Jew, they all cried out for about two hours with one voice, saying, "Great is Artemis of the Ephesians."
The UDB of ACT 19:34 (and all UDB references to Ἄρτεμις) now reads: 
\v 34 But when they became aware that he was a Jew, they all cried out for about two hours with one voice, saying, "Great is Artemis of the Ephesians."

Hope that helps. 

Thanks, 

Tom

**Comment by SusanQuigley** [comment]
Acts 19:24 ULB. Also here, "Diana" will need to be changed to Artemis.

**Comment by TomWarren** [comment]
The ULB of ACT 19:24 now reads:
\v 24 A certain silversmith named Demetrius, who made silver statues of Artemis, brought in much business for the craftsmen.

Sorry, I missed that one.

Tom
