### ISSUE TITLE
MRK 6:52 lost FOG

### ISSUE THREAD

**Issue by kim-putter** [Door43/ulb-en#90]
Mrk 6:52 ULB
"For they had not understood what the loaves meant, but their minds were slow to understand."

The ULB has dropped a figure of speech that is in the Greek. The phrase about their minds is literally, "their hearts were hardened."

Just FYI in case you guys want to add it back in.

**Comment by kim-putter** [comment]
Also, in the previous verse 51 ULB 
"He got into the boat with them, and the wind ceased blowing, and they were completely amazed at him"

The phrase "they were completely amazed" does not have an object in the Greek, rather it is more general. The phrase "at him" or "about what he had done" (UDB) would be best dealt with in a trans. note, with a implicit info ta link.

**Comment by pohlig** [comment]
Yes, I think we do want to add it back in. And I take your point in v. 51 Will make adjustments in the ULB.

**Comment by TomWarren** [comment]
Thanks.
