### ISSUE TITLE
1Ti 5:21 typo

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#900]
ULB and **to** nothing out of favoritism

I believe it should be "and **do** nothing out of favoritism"

**Comment by TomWarren** [comment]
The ULB of 1TI 5:21 now reads:
\v 21 I solemnly command you before God and Christ Jesus and the chosen angels, that you keep these commands without partiality, and **to do nothing** out of favoritism.

Thanks,

Tom

**Comment by SusanQuigley** [comment]
Could the two things that Paul commands be worded similarly?

I solemnly command you before God and Christ Jesus and the chosen angels, **that you keep** these commands without partiality, and **that you do** nothing out of favoritism.
or 
I solemnly command you before God and Christ Jesus and the chosen angels, **to keep** these commands without partiality, and **to do** nothing out of favoritism.

**Comment by TomWarren** [comment]
That makes sense.
The ULB of 1TI 5:21 now reads:
\v 21 I solemnly command you before God and Christ Jesus and the chosen angels, to keep these commands without partiality, and to do nothing out of favoritism.

Thanks Susan, 

Tom
