### ISSUE TITLE
Acts 7:45 ULB —before the face of our fathers—

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#901]
Later, our fathers, under Joshua, received the tabernacle and brought it with them when they took possession of the land. God forced those nations—before the face of our fathers—to leave the land. 

I see that this was changed so that "before the face of our fathers" is surrounded by em-dashes. I'm writing a note and need help with the interpretation. 

Is the point of putting it between em-dashes to clarify that "before the face of our fathers" modifies the verb "forced" rather than "leave"? Sort of like "Before the face of our fathers, God forced those nations to leave the land" meaning that the ancestors saw God do this? 

(Rather than "God forced those nations to leave the land before the face of our fathers" meaning either that the ancestors saw the nations leave or that the nations left while the ancestors were there to take the land?)

Hmm. I just realized the ULB "those nations" is a bit odd. The nations had not been mentioned yet. If we want "those nations" in the second sentence, maybe the first sentence could end with "from the nations."

**Comment by SusanQuigley** [comment]
Later, our fathers, under Joshua, received the tabernacle and brought it with them when they took possession of the land. God forced those nations—before the face of our fathers—to leave the land.

It seems like separating this into two sentences skews the purpose of the second one. I think the whole paragraph is about the tabernacle, and the part about how the nations were forced to leave is somewhat parenthetical. What about something like one of these?

Later, our fathers, under Joshua, received the tabernacle and brought it with them when they took possession of the land from the nations, when God forced those nations to leave before the face of our fathers.

Later, our fathers, under Joshua, received the tabernacle and brought it with them when they took possession of the land. They took the land when, before the face of our fathers, God forced those nations to leave the land.

Later, our fathers, under Joshua, received the tabernacle and brought it with them when they took possession of the land. They took the land when God forced those nations to leave the land before the face of our fathers.

**Comment by TomWarren** [comment]
Thanks Susan, I went over this verse again. Try this:
The ULB of Act 7:25-26 now reads:
\v 45 Later, our fathers, under Joshua, received the tabernacle and brought it with them when they took possession of the land. God took the land from the nations and drove them out before the face of our fathers.  The tabernacle remained in the land until the time of David,
\v 46 who found favor in the sight of God, and he asked if he might find a dwelling place for the God of Jacob.

Keep after it.

**Comment by SusanQuigley** [comment]
This looks good. Thank you.
