### ISSUE TITLE
Tit 2:8 ULB  Typo

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#903]
so that anyone who **oppose** you

"oppose" should be "opposes"

**Comment by TomWarren** [comment]
The ULB of TIT 2:8 now reads;
\v 8 and words that are above criticism, so that anyone **who opposes you** may be ashamed because they had nothing bad to say about us.

Thanks Susan,

Tom

**Comment by SusanQuigley** [comment]
Thanks for fixing it. I just now noticed the mismatch in tense between "who opposes you" and "had nothing bad to say." Could "had" be changed to "have"?

and words that are above criticism, so that anyone who opposes you may be ashamed because they **have** nothing bad to say about us.

**Comment by TomWarren** [comment]
The ULB of TIT 2:8 now reads:
\v 8 and words that are above criticism, so that anyone who opposes you may be ashamed because they have nothing bad to say about us.

"because they have ..." is rendering the the participle, ἔχων "having".

Thanks, four eyes are better ...

Tom
