### ISSUE TITLE
Tit 3:1,2  lonely adjective

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#906]
Remind them to submit to rulers and authorities, to obey them, to be ready for every good work. 2Remind them to revile no one, not to be eager to fight, gentle, showing all humility toward everyone.

In verse 2, the adjective "gentle" in a list of things to do sounds odd. Could it have the verb "be" with it?

2 Remind them to revile no one **and** not to be eager to fight,  **but to be** gentle, showing all humility toward everyone.

**Comment by TomWarren** [comment]
Yep.
The ULB of TIT 3:1-2 now reads, with the Pauline list reconnected:
\v 1 Remind them to submit to rulers and authorities, to obey them, to be ready for every good work,
\v 2 to revile no one, to not be eager to fight, and to be gentle, showing all humility toward everyone.

Thanks Susan, 

Tom
