### ISSUE TITLE
Ezk 1:15 possible missing phrase in ULB

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#907]
ULB there was one wheel on the ground beside the living creatures

The Hebrew has a phrase at the end of this that says something like "with its four faces."

Most English versions have some form of this phrase in their translations. But, one commentary says this phrase may be a corruption of the text, so I didn't know if you left it out on purpose.

So, I'll put it here for you to review. Thanks.

**Comment by TomWarren** [comment]
There appears to be an omission of the text. Thanks for your careful read here, John.
The ULB of EZK 1:15 now reads, :
\v 15 Then I looked at the living creatures; and I saw one wheel on the ground beside each of living creature with its four faces.

Thanks,

Tom
