### ISSUE TITLE
Deu 18:10 ULB  any one

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#908]
Deu 18:10 ULB There must not be found among you **any one** who puts his son or his daughter into the fire, anyone who uses divination, anyone who practices augury, or any enchanter, or any sorcerer,

Luk 19:31 ULB If **any one** asks you, 'Why are you untying it?' say, 'The Lord has need of it.'"
Should be "anyone" here.

1co 16:22 If **any one** does not love the Lord, may he be accursed.

These should be "anyone"

(There are three cases of "any one of" in the ULB. They are fine.)

**Comment by TomWarren** [comment]
All of these were changed to "anyone."
Saved and Synced.

Thanks, 

Tom
