### ISSUE TITLE
Zech 2:9 spelling

### ISSUE THREAD

**Issue by jhutchins25** [Door43/ulb-en#909]
UDB is the one who sent me **,Zecariah**, as a prophet.

**Zechariah**

**Comment by TomWarren** [comment]
The UDB of ZEC 3:9 now reads:
\v 9 "Tell them that I, Yahweh, will attack them. Their own slaves will take back their possessions from them, the people who had taken them in the first place." When that happens, you Jewish people will know that Yahweh, commander of the angel armies, is the one who sent me, **Zechariah**, as a prophet.

Thanks John, 

Tom
