### ISSUE TITLE
δαιμονιζομέν-

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#910]
Sometimes this is translated "possessed" and sometimes "controlled." Consider making consistent.

**Comment by TomWarren** [comment]
The "bold" are those which were changed.
These are the current reading of the ULB at these references, translating δαιμονίζομαι.
Thanks Henry, 

Tom

MAT 4:24 those possessed by demons
MAT 8:16 many who were **possessed** by demons
MAT 8:28 who were **possessed** by demons
MAT 8:33 who had been **possessed** by demons
MAT 9:32 a mute man possessed by a demon
MAT 12:22 possessed by a demon
MAT 15:22 My daughter is severely **demon-possessed**
MRK 1:32 or possessed by demons
MRK 5:15 the demon-possessed man, the one who had been possessed by Legion
MRK 5:16 the demon-possessed man
MRK 5:18 the demon-possessed man
LUK 8:36 the man who had been **possessed by demons** had been healed
JHN 10:21 a demon-possessed man
