### ISSUE TITLE
Luk 13:11

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#911]
Behold, a woman was there who for eighteen years had an **evil spirit** of weakness, and she was bent over and not able to completely stand up.

The text is 

ἰδοὺ γυνὴ πνεῦμα ἔχουσα ἀσθενείας

so "evil" should be deleted.

**Comment by TomWarren** [comment]
Yep. With some editing of the verse, the ULB of LUK 13:11 now reads:
\v 11 Behold, a woman was there who for eighteen years had a spirit of weakness. She was bent over and was not able to straighten up completely.

Thanks Henry, 

Tom
