### ISSUE TITLE
Gen 30:6

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#912]
God has judged in my favor. He has listened to my prayer

This is a bit too UDB-ish for

דָּנַ֣נִּי אֱלֹהִ֔ים וְגַם֙ שָׁמַ֣ע בְּקֹלִ֔י

It introduces the idea of favor, which is a tW that doesn't track to this usage. Consider

He has vindicated me. He has heard my voice

**Comment by TomWarren** [comment]
The ULB of GEN 30:6 now reads:
\v 6 Then Rachel said, "God has vindicated me, and he has heard my voice and given me a son." For this reason she called his name Dan.

Thanks Henry, 

Tom
