### ISSUE TITLE
Jhn 6:69

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#916]
Consider adding a note to explain the difference between KJV "Christ" and otherwise common (and ULB) "Holy One."

**Comment by TomWarren** [comment]
The ULB FOOTNOTE was added to JHN 6:69, and it reads:
\v 69 and we have believed and come to know that you are the Holy One of God \f + \ft The phrase \fqa the Holy One of God \fqa* is in the best ancient copies. Some later copies add an additional description and they read: \fqa the Christ, the Holy One of God. \f*."
