### ISSUE TITLE
1jn 5:3 ULB  lower case on phrase after colon

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#918]
ULB:  For this is love for God: **That** we keep his commandments. And his commandments are not burdensome.

I think "That" should be "that"

**Comment by TomWarren** [comment]
Yep. 
The ULB of 1JN 5:3 now reads:
\v 3 For this is love for God: that we keep his commandments. And his commandments are not burdensome.

Some just put a comma and leave it. But the semicolon calls more attention to the phrase. 

Thanks Susan, 

Tom
