### ISSUE TITLE
Num 2:14

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#921]
The tribe of Gad is next. The leader of the people of **_God_** is Eliasaph son of Deuel.
should be
The tribe of Gad is next. The leader of the people of **_Gad_** is Eliasaph son of Deuel.

**Comment by TomWarren** [comment]
Typo.
The ULB of NUM 2:14 now reads:
\v 14 The tribe of Gad is next. The leader of the people of Gad is Eliasaph son of Deuel.

Thanks Henry,

Tom
