### ISSUE TITLE
Mat 15:6

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#930]
the word of God

This is a B reading in the UBS Greek. KJV has "commandment" (from εντολη). Perhaps a footnote is in order.

**Comment by TomWarren** [comment]
The ULB of MAT 15:6 reads from the USFM:

4 For God said, 'Honor your father and your mother,' and 'He who speaks evil of his father or mother, will surely die.' 5 But you say, 'Whoever says to his father or mother "Whatever help you would have received from me is now a gift given to God,"' 6 that person does not need to honor his father. In this way you have made void the word of God [1] for the sake of your traditions.
[1]The best ancient copies have _the word of God_ but some have _the commandment_.

Thanks Henry, 

Tom
