### ISSUE TITLE
Heb 7:19 ULB  "for the future" (extra meaning)

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#931]
ULB: For the former regulation is set aside because it is weak and useless, 19(for the law made nothing perfect), and a certain hope **for the future** is introduced, through which we come near to God.

I wonder if "for the future" should be deleted. It is not in the Hebrew or other versions. 
I think that the hope is more not for the future but for God's acceptance. 
The former regulations of the Levitical priesthood could not make people (permanently) acceptable to God.
But Christ is our hope. Through him, we come near to God.

**Comment by TomWarren** [comment]
The ULB of HEB 7:19 now reads:
\v 19 (for the law made nothing perfect), and a better hope is introduced, through which we come near to God.

Thanks Susan,

Tom
