### ISSUE TITLE
Heb 12:9 ULB  Exclamation

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#932]
9Furthermore, we had human fathers who disciplined us and we respected them. How much more should we submit to the Father of spirits and live?

I don't think the second sentence is a rhetorical question but an exclamation. Could it have an exclamation point?

**Comment by TomWarren** [comment]
Your suggestion follows the NIV. 
The ULB of HEB 12:9 now reads:
\v 9 Furthermore, we had human fathers who disciplined us and we respected them. How much more should we submit to the Father of spirits and live!

Thanks, 

Tom
