### ISSUE TITLE
Luk 19:22  Tenses not matching

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#936]
You knew that I am a man of exacting standards, that **I take up** what I did not put in, and that **I reaped** what I did not sow.

Could "reaped" be changed to "reap"?

**Comment by TomWarren** [comment]
Changed in other GItHub.
\v 22 The nobleman said to him, 'By your own words I will judge you, you wicked servant. You knew that I am a demanding person, that I **take** up what I did not put in, and that I **reap** what I did not sow.
