### ISSUE TITLE
Psa 7:3-4

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#937]
These verses are UDB'd. Consider restoring the "if" constructions. Preceding or subsequent verses may have the same problem.

**Comment by TomWarren** [comment]
The ULB of PSA 7:3-4 now reads:
\v 3 Yahweh my God, if I have done this, 
\q and there is guilt on my hands—
\q
\v 4 if I have done evil to him who was at peace with me,
\q or senselessly harmed my enemy without cause, then hear my words.

\s5
\q
\v 5 Then let my enemy pursue my life and overtake me;
\q let him trample my life to the ground
\q and lay my honor in the dust.
\qs Selah\qs*

Try that. 

Tom

**Comment by TomWarren** [comment]
The addition at the end of vs 4 is our little way of making a full sentence out of a frag. 
Just let it go.
