### ISSUE TITLE
Zec 9:8

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#940]
I will camp around my land against enemy armies so no one can pass through

Some versions read something like, e.g. (NET)

Then I will surround my temple to protect it like a guard from anyone crossing back and forth

Where the radical צבה is taken to mean "guard," what "I" will be, rather than "army," what is guarded against. Consider adding a footnote acknowledging the alternate reading.

**Comment by TomWarren** [comment]
The USFM now has a footnote at ZEC 9:8 as follows:
ULB of ZEC 9:8 now reads:

8 I will camp around my land against enemy armies,[1]so no one can pass through or return, for no oppressor will pass any more through it. For now I will watch over my land with my own eyes!

[1]Most interpreters translate the Hebrew words as _against enemy armies_ and some translate the Hebrew a_s a guard_, and so translate the phrase, _I will surround my temple as a guard._

Thanks Henry, 

Tom

**Comment by TomWarren** [comment]
I saw the typo and corrected it. Happens to me often when I am on a roll. 
Should be ok now.

Tom
