### ISSUE TITLE
Mat 15:6 ULB Footnote marker

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#947]
In this way you have made void the word of God[1]for the sake of your traditions.

This is showing up in Dave's searches for mismatches between ULB and snippets. 
I  think it is because of the footnote marker.
Does the marker usually go at the end of the verse?

**Comment by TomWarren** [comment]
The marker needs to be close to the issue that is there. In many other cases, the footnote is next to the issue (so there is no confusion to the reader about what is being footnoted). 

There may not be a good way to keep the footnote close to the issue and not have it show up as a mismatch. The problem would be when there is a change AND a footnote, then you'd need to search to decide where the mismatch is (is it the footnote, or is there another matter that was edited?).

It would be a monumental task to move the footnotes.

**Comment by SusanQuigley** [comment]
Well, that's good news. I like the marker next to the issue, but I thought thee was some formatting issue that required that it be at the end.

**Comment by TomWarren** [comment]
I will check on whether there is a need for the footnote to be at the end. I don't think so, but many "rules" get overrun in the press of the moment.

**Comment by TomWarren** [comment]
The ULB of ROM 4:19 now reads, supplying a verb for clarity:
\v 19 Without becoming weak in faith, he considered his own body as dead (because he was about a hundred years old)—and the he considered the deadness of Sarah's womb.

The Greek here is tough. 

Thanks Henry, 

Tom

**Comment by SusanQuigley** [comment]
Tom, your reply to Henry about Rom 4:19 came up on the thread for Mat 25:6.

**Comment by TomWarren** [comment]
Sorry, two at once. 

Thanks.

**Comment by TomWarren** [comment]
I caught it just as you did.
