### ISSUE TITLE
JER 4:3 ULB \q needed

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#95]
\v 3 For Yahweh says this to each person in Judah and Jerusalem: 'Plow your own ground,
\q and do not sow among thorns.

It looks like it needs \q before 'Plow your own ground.

**Comment by TomWarren** [comment]
\v 3 For Yahweh says this to each person in Judah and Jerusalem: 
\q 'Plow your own ground,
\q and do not sow among thorns.
  
Fixed. Thanks
