### ISSUE TITLE
1th 5:27  appeal

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#951]
I **appeal** to you earnestly by the Lord that this letter be read to all the brothers.

"Appeal" sounds like this is a request or something he is begging of them.
 Enorkizō is stronger than that. How about urge, direct, order, or command?

**Comment by TomWarren** [comment]
Many versions use the adverbial clause to give the verb the sense of demand. 
The GRK Lexicon has "appeal to earnestly" as we had it. 
The ULB of 1TH 5:27 now reads:
\v 27 I solemnly charge you by the Lord to have this letter read to all the brothers.

Hope that works, 

Tom
