### ISSUE TITLE
Dan 9:24, 26

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#954]
"of years" after "sevens" perhaps should be deleted and taken care of in the tNs.

**Comment by TomWarren** [comment]
The ULB of DAN 9:24 - 26 now read:
\v 24 **Seventy sevens** are decreed for your people and your holy city to end the guilt and put an end to sin, to atone for wickedness, to bring everlasting righteousness, to carry out the vision and the prophecy, and to consecrate the most holy place.
\v 25 Know and understand that from the issuing of the order to restore and rebuild Jerusalem to the coming of the anointed one (who will be a leader), there will be **seven sevens** and **sixty-two sevens.** Jerusalem will be rebuilt with streets and a moat, despite the times of distress.

\s5
\v 26 After the s**ixty-two sevens**, the anointed one will be destroyed and will have nothing. The army of a coming ruler will destroy the city and the holy place. Its end will come with a flood, and there will be war even to the end. Desolations have been decreed.

Thanks Henry, 

Tom
