### ISSUE TITLE
Jhn 9:7 ULB Siloam (which translated is: Sent)."

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#957]
He said to him, "Go, wash in the pool of Siloam (which translated is: Sent)." 

Since John, not Jesus, is explaining the meaning of the word "Siloam," would it be clearer to change the ULB to one of these?

He said to him, "Go, wash in the pool of Siloam," (which translated is: Sent).
He said to him, "Go, wash in the pool of Siloam," (which translated is 'Sent').

**Comment by TomWarren** [comment]
The ULB of JHN 9:7 now reads:
\v 7 He said to him, "Go, wash in the pool of Siloam," (which is translated "Sent"). So the man went away, washed, and came back seeing.

Thanks Susan, 

Tom
