### ISSUE TITLE
JER 46:25 \m or \p needed?

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#96]
Jer 46:25-26 The material preceding this is poetry. This is a paragraph, but it is also indented. 
The next paragraph continues this quote but it is not indented. 
I think \m or \p is needed before v.25

**Comment by TomWarren** [comment]
Fixed it:
\s5
\q
\v 23 They will cut down the forests—this is Yahweh's declaration—although it is very dense.
\q For the enemies will be more numerous than locusts, unable to be counted.
\q
\v 24 The daughter of Egypt will be made ashamed. She will be given into the hand of people from the north."
\m 
 
\s5
\p
\v 25 Yahweh of hosts, the God of Israel, says, "See, I am about to punish Amon of Thebes, Pharaoh, Egypt and her gods, her kings the Pharaohs, and those who trust in them.
\v 26 I am giving them into the hand of the ones seeking their lives, into the hand of Nebuchadnezzar king of Babylon and his servants. Then after this Egypt will be inhabited as in previous days—this is Yahweh's declaration."

**Comment by SusanQuigley** [comment]
Looks good on https://door43.org/en/ulb/ep/ot.

On Jun 17, 2016, at 4:42 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed it:
\s5
\q
\v 23 They will cut down the forests—this is Yahweh's declaration—although it is very dense.
\q For the enemies will be more numerous than locusts, unable to be counted.
\q
\v 24 The daughter of Egypt will be made ashamed. She will be given into the hand of people from the north."
\m

\s5
\p
\v 25 Yahweh of hosts, the God of Israel, says, "See, I am about to punish Amon of Thebes, Pharaoh, Egypt and her gods, her kings the Pharaohs, and those who trust in them.
\v 26 I am giving them into the hand of the ones seeking their lives, into the hand of Nebuchadnezzar king of Babylon and his servants. Then after this Egypt will be inhabited as in previous days—this is Yahweh's declaration."
