### ISSUE TITLE
clan

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#960]
I think this term needs to be revisited.

1ch 23:7 reads "From the clans descended from Gershon" for לַגֵּרְשֻׁנִּ֖י.

This is a bit UDB-ish. Other clans are described as the Whoeverites. By analogy this should be "from the Gershonites."

I don't have time to go through all occurrences of "clan," but as a service to you, I have attached a file with all occurrences of the word in ULB. Feel free to change "clans descended from X" to "X-ites" when warranted.

I think we've already had a go-'round about "house of the father" (e.g., 1ch 7:40, where the phrase בֵית־הָאָבֹ֤ות seems to be translated twice), but I'm not sure what was decided, and it looks like there are a bunch of instances of that phrase in this list; I've added a file of just these instances to the archive.

You may even decide to put this off until later maintenance. If you go to the clan tW page, 
https://git.door43.org/Door43/en_tw/src/master/bible/other/clan.md
you'll see a link to Gen 10:2, where the word doesn't even appear in the ULB. I'm not sure what who is planning to do with the tW pages apart from me putting Strong's numbers on them, but clearly there is concordance work to be done.

[Archive.zip](https://github.com/Door43/ulb-en/files/1071797/Archive.zip)

**Comment by TomWarren** [comment]
Reviewed about 400 references to "clans" and "family" and "tribes" etc, and corrected about 100 along the way. 

Thanks Henry, 

Tom

**Comment by pjoakes** [comment]
Henry,

Yes, we do have tW concordance work planned for July.

Thanks,

Perry Oakes
perry_oakes@wycliffeassociates.org<mailto:perry_oakes@wycliffeassociates.org>





On Jun 13, 2017, at 9:58 AM, Henry Whitney <notifications@github.com<mailto:notifications@github.com>> wrote:


I think this term needs to be revisited.

1ch 23:7 reads "From the clans descended from Gershon" for לַגֵּרְשֻׁנִּ֖י.

This is a bit UDB-ish. Other clans are described as the Whoeverites. By analogy this should be "from the Gershonites."

I don't have time to go through all occurrences of "clan," but as a service to you, I have attached a file with all occurrences of the word in ULB. Feel free to change "clans descended from X" to "X-ites" when warranted.

I think we've already had a go-'round about "house of the father" (e.g., 1ch 7:40, where the phrase בֵית־הָאָבֹ֤ות seems to be translated twice), but I'm not sure what was decided, and it looks like there are a bunch of instances of that phrase in this list; I've added a file of just these instances to the archive.

You may even decide to put this off until later maintenance. If you go to the clan tW page,
https://git.door43.org/Door43/en_tw/src/master/bible/other/clan.md
you'll see a link to Gen 10:2, where the word doesn't even appear in the ULB. I'm not sure what who is planning to do with the tW pages apart from me putting Strong's numbers on them, but clearly there is concordance work to be done.

Archive.zip<https://github.com/Door43/ulb-en/files/1071797/Archive.zip>

**Comment by hmw3** [comment]
Good to know. Thanks!

________________________________
