### ISSUE TITLE
Ezr 3:2

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#967]
as commanded in the law of Moses

More OED literal:

as written in the law of Moses

**Comment by TomWarren** [comment]
The ULB of EZR 3:2 now reads:
\v 2 Jeshua son of Jozadak and his brothers the priests, and Zerubbabel son of Shealtiel, and his brothers rose up and built the altar of the God of Israel to offer burnt offerings as it is written in the law of Moses the man of God.

Thanks Henry, 

Tom
