### ISSUE TITLE
Jdg 5:7

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#968]
until I, Deborah, took command—a mother took command in Israel!

The text was changed to "took command" from "arose" in Oct 2015. The BDB has an entry for "come to power," but that's not the same as "take command." "Come on the scene" or "begin acting" would work just as well. I recommend "arise" with explanation in the tNs.

Also v. 9.

**Comment by TomWarren** [comment]
The ULB of JDG 5:7 now reads:
\v 7 There were few rural people in Israel,
\q until I, Deborah, arose,
\q arose as a mother in Israel!

Some disparity on that. 
Thanks, 

Tom
