### ISSUE TITLE
JER 38:22-23 Indent

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#97]
I'm not sure how this should be indented. It looks a little odd.

**Comment by TomWarren** [comment]
Fixed the offset. Seems right. Checked on USFM and it seems clean.
\s5
\v 22 Look! All the women who are left in your house, king of Judah, will be brought out to the officials of the king of Babylon. These women will say to you,
\q 'You have been deceived by your friends; they have ruined you.
\q Your feet are now sunk into the mud, and your friends will run away.'
\m
\v 23 For all of your wives and children will be brought out to the Chaldeans, and you yourself will not escape from their hand. You will be captured by the hand of the king of Babylon, and this city will be burned."

**Comment by SusanQuigley** [comment]
Looks good. Thanks.

On Jun 17, 2016, at 4:49 PM, Tom Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed the offset. Seems right. Checked on USFM and it seems clean.
\s5
\v 22 Look! All the women who are left in your house, king of Judah, will be brought out to the officials of the king of Babylon. These women will say to you,
\q 'You have been deceived by your friends; they have ruined you.
\q Your feet are now sunk into the mud, and your friends will run away.'
\m
\v 23 For all of your wives and children will be brought out to the Chaldeans, and you yourself will not escape from their hand. You will be captured by the hand of the king of Babylon, and this city will be burned."
