### ISSUE TITLE
Rut 1:13

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#970]
the hand of Yahweh has turned against me

The verb is clearly to go forth: כִּֽי־יָצְאָ֥ה בִ֖י יַד־יְהוָֽה

the hand of Yahweh has gone out against me

**Comment by TomWarren** [comment]
The ULB of RUT 1:13 now reads with editing:
\v 13 would you therefore wait until they were grown? Would you choose not to marry a husband? No, my daughters! It is exceedingly bitter to me for your sake that the hand of Yahweh has gone out against me."

Closer. 
Tom
