### ISSUE TITLE
Heb 10:38-39

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#971]
If he turns back ... those who turn back

The verb is more like withdraw or be timid, as in many versions.

    ἐὰν ὑποστείληται, ...ὑποστολῆς

If he shrinks back ... those who shrinks back

**Comment by TomWarren** [comment]
Yep.
The ULB of HEB 10:38 now reads:
\v 38 My righteous one will live by faith.
\q If he shrinks back, I will not be pleased with him."

Thanks Henry, 

Tom
