### ISSUE TITLE
isa 19:7

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#973]
the sown fields of the Nile will dry up, turn to dust, and blow away

מִזְרַ֣ע יְאֹ֔ור יִיבַ֥שׁ נִדַּ֖ף וְאֵינֶֽנּוּ

"Turn to dust" is an interpolation.

**Comment by TomWarren** [comment]
The ULB of ISA 19:7 now reads:
\v 7 The reeds along the Nile,
\q1 at the mouth of the Nile, 
\q1 and every sown field beside the Nile will become parched, 
\q1 will be driven away, and will be no more. 

Thanks Henry, 

Tom
