### ISSUE TITLE
Pro 1:11

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#975]
let us lie in wait to commit murder

"Blood" is in the ULB for murder often enough that it can be put in here as well.

**Comment by TomWarren** [comment]
The ULB of PRO 1:11 now reads:
\v 10 My son, if sinners try to entice you into their sin,
\q refuse to follow them.
\q
\v 11 If they say, "Come with us,
\q let us lie in wait **for blood,**
\q let us hide and attack innocent people for no reason.

Thanks Henry, 

Tom
