### ISSUE TITLE
Num 14:9

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#976]
We will consume them as easily as food

This is UDB, though some versions (NIV) translate this way. I would suggest following NET and ESV and translating literally.

**Comment by TomWarren** [comment]
The ULB of NUM 14:9 now reads:
\v 9 But do not rebel against Yahweh, and do not fear the people in the land, **for they are bread to us.** Their protection will be removed from them, because Yahweh is with us. Do not fear them."

Thanks Henry, 

Tom
