### ISSUE TITLE
Jos 7:5

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#980]
The hearts of the people were afraid and their courage left them

Consider following most versions

The hearts of the people melted and became like water

**Comment by TomWarren** [comment]
The ULB of JOS 7:5 now reads:
\v 5 The men of Ai killed about thirty-six men as they pursued them from the city gate as far as to the stone quarries, and they killed them as they were going down a hill. The hearts of the people melted and became like water.

Thanks Henry, 

Tom
