### ISSUE TITLE
Heb 4:3

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#986]
his **created works** were finished

The sense seems to be more like "labor" or "business" than like "something created." The UBS Handbook has an interesting discussion; NICNT is no help. I'm tempted to say that the use of the plural "works" is insignificant, probably idiomatic. The Handbook's objection to "all his activities" is not that it is inaccurate but that it could be misunderstood. Anyway, it's summertime and the weather is hot, so pretend "her daddy's poor" (and "do as you feel").

**Comment by TomWarren** [comment]
The ULB of HEB 4:3-5 now reads with edits:
\v 3 For we who have believed enter that rest, just as he said,
\q "As I swore in my wrath,
\q They will never enter my rest."
\p Even so, his works were finished from the foundation of the world.
\v 4 For he has somewhere spoken about the seventh day:
\q "And God rested on the seventh day from all his works."
\v 5 And again in this same passage he said:
\q "They will never enter my rest."

Thanks Henry, 

Tom
