### ISSUE TITLE
Deuteronomy 4:16

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#989]
the likeness of any **creature**

סָ֑מֶל has nothing to do with creation; it's the word for carved figure or statue.

**Comment by TomWarren** [comment]
The ULB of DEU 4:15-18 now reads:
\v 15 So take great heed to yourselves—for you saw no kind of form on the day that Yahweh spoke to you at Horeb out of the middle of the fire—
\v 16 that you do not corrupt yourselves and by making a carved image in the form of any figure, in the likeness of male or female,
\v 17 the likeness of any animal on the earth, the likeness of any winged bird that flies in the heavens,
\v 18 the likeness of anything that creeps on the ground, or the likeness of any fish that is in the water under the earth.

Thanks Henry, 

Tom
