### ISSUE TITLE
JE 23:28b-32 Indents

### ISSUE THREAD

**Issue by SusanQuigley** [Door43/ulb-en#99]
Jer 23:28b-32 looks like odd on https://door43.org/en/ulb/ep/ot.
The whole paragraph is indented, but it seems to have a hanging indent for 29-30. I don't know if the \q before 28b is doing what was expected.

**Comment by TomWarren** [comment]
Made a bit simpler and consistent with context. 

\s5
\p 
\v 28 The prophet who has a dream, let him report the dream. But the one to whom I have declared something, let him declare my word truthfully. What does straw have to do with grain?—this is Yahweh's declaration—
\v 29 And is my word not like fire?—this is Yahweh's declaration—and like a hammer smashing rock?
\v 30 So see, I am against the prophets—this is Yahweh's declaration—anyone who steals words from another person and says they come from me.

**Comment by SusanQuigley** [comment]
Looks good.
