### ISSUE TITLE
Joshua 10:35

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#990]
they completely destroyed everyone in it

I like this rendition better than the one in vv 28, 30, 32, 37, 39, where nefesh is translated "creature." I think "everyone" would be better as "every living being," and the other verses changed, but that's your call.

**Comment by TomWarren** [comment]
The ULB of JOS 10:28-30 now reads with edits throughout:
\v 28 In this way, Joshua captured Makkedah on that day and killed everyone there with the sword, including its king. He completely destroyed everyone in it. He left no survivor in it. He did to the king of Makkedah just as he had done to the king of Jericho.

\s5
\p
\v 29 Joshua and all Israel passed on from Makkedah to Libnah. He went into battle against Libnah.
\v 30 Yahweh also gave it into the hand of Israel—along with their king. Joshua struck it with the edge of the sword and every person in it. He left no survivor in it. He did to its king just as he had done to the king of Jericho.

\s5
\p
\v 31 Then Joshua and all Israel with him passed on from Libnah to Lachish. He camped by it and waged war against it.
\v 32 Yahweh gave Lachish into the hand of Israel. Joshua captured it on the second day and struck it with the edge of the sword, and every person in it, just as he had done to Libnah.

\s5
\p
\v 33 Then Horam, king of Gezer, came up to help Lachish. Joshua attacked him and his army until there was not even one survivor left.
\s5
\p
\v 34 Then Joshua and all Israel passed on from Lachish to Eglon. They camped by it and waged war against it,
\v 35 and captured it that same day. They struck it with the sword and they completely destroyed everyone in it, as Joshua had done to Lachish.

\s5
\p
\v 36 Then Joshua and all Israel passed on from Eglon to Hebron. They waged war against it.
\v 37 They captured it and struck it with the edge of the sword, and its king and its villages, and everyone in it. They left no survivor it, as they had done to Eglon, they totally destroyed it and every person in it. 

\s5
\p
\v 38 Then Joshua turned, and all the army of Israel with him, and they passed on to Debir and waged war against it.
\v 39 They captured it, its king and all its nearby villages. They struck them with the edge of the sword and completely destroyed every person in it. They left no survivor. They did to Debir and its king as they had done to Libnah and its king and to Hebron. 

Thanks Henry, 

Tom
