### ISSUE TITLE
Joshua 11:14

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#991]
They left no living creature alive

The noun is derived from "breathe," not "create." Consider

They left alive nothing that breathed.

**Comment by TomWarren** [comment]
JOS 11:14 now reads:
\v 14 The army of Israel took all the plunder from these cities along with the livestock for themselves. They killed every human being with the sword until all were dead. They left alive no creature than breathed.

Thanks Henry, 

Tom

**Comment by hmw3** [comment]
creature than breathed

should be

creature that breathed

I still think "creature" is superfluous since anything derived from the verb "create" is absent, but if retaining that word was a conscious decision, it's your call.

**Comment by TomWarren** [comment]
The ULB of JOS 11 :14 misspelling is corrected:
\v 14 The army of Israel took all the plunder from these cities along with the livestock for themselves. They killed every human being with the sword until all were dead. They left alive no creature that breathed.

Thanks Henry, 

Tom
