### ISSUE TITLE
2 Timothy 2:9

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#993]
being chained as a criminal

"as a criminal" is UDB or tN.

**Comment by TomWarren** [comment]
The ULB of 2TI 2:9 now reads:
Trying to avoid the metonymy of "being bound"= "imprisonment" but the second use of desmos (at the end, "but the word of God is not bound" calls "bound" back into the sentence. 

\v 9 for which I am suffering to the point of being bound with chains as a criminal. But the word of God is not bound.

Thanks Henry, 

Tom
