### ISSUE TITLE
Judges 13:14

### ISSUE THREAD

**Issue by hmw3** [Door43/ulb-en#999]
any food that the law declares to be unclean

Consider:

anything unclean

Also v. 7.

**Comment by TomWarren** [comment]
The ULB of JDG 13:14 now reads, after editing:
\v 14 She may not eat anything that comes from the vines, and do not let her drink wine or strong drink or eat anything unclean. She must obey everything I have commanded her to do."

Almost to 1000, Henry, 

Tom
